consensus/src/chained_bft/network.rs
Closes #287.
Fix comment.
Yes
Re-read comment.
#287
=> Minor comment fix for BlockRetrievalResponse.

client/src/client_proxy.rs, client/src/dev_commands.rs
functionality should be covered by new set of commands
=> [cli] dev section: deprecate old submit command

common/crash_handler/src/lib.rs
Currently Tokio's default behavior is to catch panics and ignore them.
This lead to an issue where we observed a panic! that did not crash a Tokio
thread and led to a misbehaving process that wouldn't die.  Since
setup_panic_handler now always overrides sets the custom panic hook, this
won't happen again.
=> [general] setup_panic_handler ensures all thread panics lead to process exit

mempool/src/shared_mempool.rs
process_incoming_transactions handler is cpu bound
perform eager sequence number check before full vm validation to filter out old txns
=> [mempool] shared mempool: eagerly filter out stale transactions

consensus/src/chained_bft/safety/safety_rules.rs, consensus/src/chained_bft/safety/safety_rules_test.rs
Summary:
We're planning to refactor `SafetyRules` s.t. it becomes not dependent on `BlockStore` at all,
but meanwhile we just want to not panic in case the parent is not available.
Even thought we do not fully understand the specific scenarios, in which it can happen, but it makes more sense to
return an error rather than crashing the validator.
refs #300
Test Plan: extended the unit test for consensus
=> [Consensus][small] SafetyRules voting does not panic

language/stdlib/modules/libra_coin.mvir
=> [language] adjust mint size limit to 1B Libra

documentation/coding_guidelines.md
I only enabled syntax highlighting for better readability
=> enabled syntax highlighting

client/libra_wallet/src/error.rs, client/src/lib.rs, execution/executor/src/block_processor.rs
Fixed Typos in a few rs files to enhance readability of code
Yes
None Needed
NA
=> Fixed Typos in a few rs files

storage/libradb/src/test_helper.rs, types/src/account_config.rs, types/src/account_state_blob/account_state_blob_test.rs, types/src/account_state_blob/mod.rs, types/src/proptest_types.rs
With this it's easier for #347 to update and pass test.
yes
Existing unit test coverage.
#347
=> [Storage] make any::<AccountStateBlob>() more real in proptests

language/README.md
* Copyedits to language README to improve readability.
* Heading updates to ensure consistency with other READMEs.
Yes
Review updated content.
=> [doc] Copyedits to language README

.gitignore, terraform/terraform.tfvars, terraform/variables.tf
=> [terraform] Comment out example variables to keep syntax valid

common/canonical_serialization/src/lib.rs, network/netcore/src/negotiate/outbound.rs, types/src/validator_public_keys.rs
Fixed typos in rs files to improve readability of code
Yes
NA
=> Fixed minor typos in rs files

Cargo.toml, common/proptest_helpers/src/lib.rs, common/proptest_helpers/src/value_generator.rs, language/README.md, language/benchmarks/.gitignore, language/benchmarks/Cargo.toml, language/benchmarks/benches/transactions.rs, language/benchmarks/src/lib.rs, language/benchmarks/src/transactions.rs, testsuite/libra_fuzzer/Cargo.toml, testsuite/libra_fuzzer/src/commands.rs, testsuite/libra_fuzzer/src/fuzz_targets.rs, testsuite/libra_fuzzer/src/fuzz_targets/compiled_module.rs, testsuite/libra_fuzzer/src/fuzz_targets/vm_value.rs, testsuite/libra_fuzzer/src/lib.rs
Going to flesh this out in the future, but this should be enough to get started with.
=> [language] add a skeleton benchmark framework for VM execution

language/tools/cost_synthesis/src/bytecode_specifications/stack_transition_info.rs
Before the recent change to equality in the VM we were using Rust's version of
equality, which, in particular meant that it was "legal" to (or at least, we could get away with) pass in e.g.
`1 == true` to the VM. However, with the recent update this is no longer
the case so we need to update the typed call details for the bytecode
instructions to encode this new restriction.
This PR does this by introducing row-invariant types which encode that once we fix one type (i.e. a "row") all the other argument types (row) are fixed.
=> [language] Fix type signature definitions for Eq and Neq bytecode instructions in cost synthesis

Cargo.toml, execution/README.md, execution/execution_tests/Cargo.toml, execution/execution_tests/src/lib.rs, execution/execution_tests/src/tests/execution_service_test.rs, execution/execution_tests/src/tests/mod.rs, execution/execution_tests/src/tests/storage_integration_test.rs
I'm interested in using some of this code in language benchmarks.
=> [execution] factor out test helper code into separate crate

testsuite/cluster_test/src/health/log_tail.rs
Now cluster_test accepts EVENT_LOG env var and writes down events happened during test run.
This helps with debugging what is going on if test later fails.
=> [cluster_test] Write event log file

client/src/client_proxy.rs
diff adds following changes into compilation:
* address preprocessor (e.g. in smart contract `{{default}}` string will be replaced with sender address)
* runs langunage compiler to first fetch module dependencies
* fetches bytecode of those modules from storage
* passes down it back to language compiler
Create EarmarkedLibraCoin module listed in https://developers.libra.org/docs/move-overview.html#writing-modules
Create dependent script that uses it. Compile it and execute. Then verify balances
=> [cli] dev section: handle script dependencies

language/vm/vm_runtime/vm_runtime_types/Cargo.toml
Accidentally broke tests, no idea why it wasn't caught by CicleCI
=> [VM] Fix prop tests

config/generate_keypair/Cargo.toml, language/e2e_tests/Cargo.toml, language/stackless_bytecode_generator/Cargo.toml, language/vm/vm_runtime/Cargo.toml, testsuite/Cargo.toml, types/Cargo.toml
Completes the work started in #193 and #197 - now all files should follow the Cargo convention :)
=> Follow conventions for Cargo.toml files

common/proptest_helpers/src/repeat_vec.rs, common/proptest_helpers/src/unit_tests/repeat_vec_tests.rs
Found while trying to use this in a new location.
=> [proptest_helpers] fix bug with zero-length elements

mempool/src/core_mempool/transaction_store.rs, mempool/src/core_mempool/unit_tests/shared_mempool_test.rs
If gas price update is valid (i.e. no other values have also been changed), then delete the existing transaction, so that a new one with the updated gas price can be added
Unit test added
=> [mempool] Propagate updated transaction to shared mempool

types/src/proof/mod.rs
=> [proof] add comments in verify_sparse_merkle_element() for readability

benchmark/src/ruben_opt.rs, benchmark/src/txn_generator.rs
Improve readability of code
Yes
NA
=> Fixed typos

README.md
I want to contribute to the Blockchain community and get deep into the Libra project.
Yes
No tests required, only Markdown file updated.
No relation to other PRs
=> Update the line format in favour of Markdown syntax

docker/bench/bench.Dockerfile, docker/bench/bench_init.sh, docker/mint/mint.Dockerfile, docker/validator/validator.Dockerfile
Add docker files for benchmark binary, just like what have for validator, client, etc.
Yes
Deployed on my test cluster
=> [benchmark] add docker files for benchmark

testsuite/tests/libratest/dev_modules/module.mvir, testsuite/tests/libratest/dev_modules/script.mvir, testsuite/tests/libratest/smoke_test.rs, testsuite/tests/libratest/throughput_test.rs
Recently we made it possible for external developers to develop Move locally via CLI's dev section. To make sure this works well, adding end to end integration test that checks for successful compiling of modules and scripts, as well as execution. 
cargo test -- test_execute_custom_module_and_script
=> [testsuite] Integration test for local move development

Cargo.toml, config/config_builder/src/swarm_config.rs, config/src/config.rs, libra_node/Cargo.toml, libra_node/src/main_node.rs, state_synchronizer/Cargo.toml, state_synchronizer/build.rs, state_synchronizer/src/lib.rs, state_synchronizer/src/proto/mod.rs, state_synchronizer/src/proto/state_synchronizer.proto, state_synchronizer/src/runtime.rs, state_synchronizer/src/state_sync_service.rs
diff creates separate crate for state_synchronizer
and mock of grpc service(will be used by Consensus)
=> [state sync] initial crate + grpc service

storage/libradb/src/pruner/mod.rs, storage/libradb/src/pruner/test.rs, storage/libradb/src/state_store/state_store_test.rs, storage/sparse_merkle/src/mock_tree_store.rs, storage/sparse_merkle/src/sparse_merkle_test.rs
rename for consistency: purge -> prune
yes
=> [storage] rename for consistency: purge -> prune

consensus/src/chained_bft/chained_bft_consensus_provider.rs, consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/chained_bft_smr_test.rs, consensus/src/chained_bft/consensus_types/mod.rs, consensus/src/chained_bft/consensus_types/proposal_msg.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/proposer_election.rs, consensus/src/chained_bft/liveness/rotating_proposer_election.rs, consensus/src/chained_bft/liveness/rotating_proposer_test.rs, consensus/src/chained_bft/network.rs, consensus/src/chained_bft/network_tests.rs, consensus/src/chained_bft/proto_test.rs, network/benches/network_bench.rs, network/src/proto/consensus.proto
Replace the trait with concrete struct for better readability, we can still extend the struct to include more info in the future.
Yes.
=> [consensus] replace ProposerInfo with Author

storage/libradb/src/lib.rs
The annotation is no longer needed.
Yes.
`cargo test`
None.
=> [Storage] Remove unused dead_code annotation

.gitignore
Prevent `target/` directories from from showing up in git status`
Yes
=> Add cargo target/ directories to .gitignore

execution/executor/src/executor_test.rs
There was a conflict caused by https://github.com/libra/libra/commit/c75ba52beecc4530eb23f578e99fdbc9a543dc3d and https://github.com/libra/libra/commit/322494069810b21573b1b52c62ca68fe9f43b278
Yes.
CI
None.
=> [Executor] Fix build

common/logger/src/collector_serializer.rs, crypto/legacy_crypto/src/signing.rs, language/bytecode_verifier/src/control_flow_graph.rs, language/compiler/ir_to_bytecode/src/compiler.rs, language/e2e_tests/src/proptest_types.rs, language/vm/vm_runtime/vm_runtime_types/src/proptest_types.rs, storage/libradb/src/event_store/mod.rs, storage/sparse_merkle/src/nibble_path/mod.rs, storage/storage_service/src/lib.rs, types/src/account_state_blob/mod.rs, types/src/proptest_types.rs, types/src/validator_change.rs
It's a good practice, for better readability, to maintain the order of defined trait functions during implementation.
YES
-
=> Maintain trait functions ordering.

docker/mint/mint.Dockerfile, docker/mint/requirements.txt
To make it simple and clean to keep all python dependency packages in one place.
yes,
Execute run.sh then check if the python dependency packages was installed.
no
=> added requirements.txt for mint.Dockerfile

language/stackless_bytecode/bytecode_to_boogie/output.bpl, language/stackless_bytecode/bytecode_to_boogie/src/bytecode_function_generator.rs, language/stackless_bytecode/bytecode_to_boogie/src/bytecode_instrs.bpl, language/stackless_bytecode/bytecode_to_boogie/src/translator.rs, language/stackless_bytecode/bytecode_to_boogie/test_mvir/test-arithmetic.mvir
As the title suggests, I added implementation for integer overflow/underflow/division-by-zero and `CreateAccount` to bytecode-to-boogie translator. Test cases are also added to test the implementation.
Yes.
```
cargo run FILENAME
```
#434
#461
=> [language] add integer overflow/underflow/division-by-zero and implementation for CreateAccount

storage/jellyfish_merkle/src/jellyfish_merkle_test.rs, storage/jellyfish_merkle/src/nibble/mod.rs, storage/jellyfish_merkle/src/nibble/nibble_path_test.rs, storage/jellyfish_merkle/src/node_type/mod.rs, storage/jellyfish_merkle/src/node_type/node_type_test.rs
Create a wrapper of `u8` to represent a nibble (u4).
Y
cargo test
=> [storage] create Nibble to represent u4

types/src/proof/position.rs
Add comment for `FrozenSubtreeSiblingIterator::new`.
Yes.
CI.
None.
=> [Proof] Add comment for FrozenSubtreeSiblingIterator::new

crypto/nextgen_crypto/src/bls12381.rs, crypto/nextgen_crypto/src/unit_tests/bls12381_test.rs
Addressing various TODOs in BLS implementation related to serialization and key validation.
YES
`bls12381_test::test_keys_custom_serialisation()`
=> [crypto] Fix serialization/validation TODOs in bls12381

execution/executor/src/block_processor.rs, execution/executor/src/lib.rs, storage/scratchpad/src/accumulator/accumulator_test.rs, storage/scratchpad/src/accumulator/mod.rs
Make the names more consistent with the rest of the codebase.
Yes.
CI.
None.
=> [Storage] Rename element to leaf

consensus/src/chained_bft/event_processor.rs
Summary:
We recently introduced NIL blocks, which can now commit even if the execution of a block takes more time than the round duration.
Unfortunately it might lead to a situation in which the round duration is consistently smaller than the execution time but it doesn't grow because of the NIL blocks.
This diff does not notify the Pacemaker about the commits of the NIL blocks, this way the highest commit round kept by Pacemaker is the highest commit round of the non NIL blocks.
Test: current unit test coverage
Tasks: ref #371
=> [Consensus][small] Pacemaker timeout calculations ignore nil blocks

crypto/nextgen_crypto/src/bls12381.rs
Fixing doc comments and add a TODO for Fr size checking.
Yes
-
=> [crypto] Fix BLS comments

docker/mint/mint.Dockerfile, docker/mint/requirements.txt
Tested libra:master and found error related with requirements.txt
Since I introduced requirements.txt, I think I'm responsible to fix it.
Yes,
Build and run docker on my working environment.
-
=> [Docker] fixed error related with requirements.txt

common/proto_conv/proto_conv_derive/Cargo.toml, common/proto_conv/proto_conv_derive/src/lib.rs, crypto/legacy_crypto/src/macros/Cargo.toml
Upgrade `syn`, `quote` and `proc-macro2` to 1.0.
Yes.
CI
None.
=> Upgrade syn, quote and proc-macro2 to 1.0

terraform/templates/dashboards/storage.json
adding these:
1. latest and pruned till versions
2. number of accounts/internal nodes
3. acccount updates per transaction
4. event emits per transaction
5. state tree depth
yes
imported to dev env
=> [dashboard] storage: add a few panels

libra_swarm/src/swarm.rs
When user specifies a persistent config dir, `launch_swarm_attemp()` doesn't cleanup previously created dirs. The next attempt fails due to "File already exists".
Delete previous config directory created by failed `launch_swarm_attempt()`.
```
./target/release/libra_swarm -n 4 -c temp_config -f faucet_for_ruben
```
```
./target/release/libra_swarm -n 4 -c temp_config -f faucet_for_ruben_err
Faucet account created in (loaded from) file "faucet_for_ruben_err"
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: …
```
=> [libra_swarm] Fix path error when launch attempt fails

crypto/nextgen_crypto/src/bls12381.rs
This pull request fixes the non-uniformly random bls secret key generation by doing rejection sampling. Another potential but slower solution is to sample a much larger number and reduce it mod r, but reductions are expensive and being constant time does not bring more security in this case.
A better way to fix this is to make external pairing crate update to the more recent version of rand crate (they use 0.4.0, we use 0.6.5), in which case we can simply do:
let mut fr = Fr::rand(&mut rng);
but technically they also do rejection sampling, so we are not different.
The modulus r constant is hard coded here, because it is not public within pairing::bls12_381.
=> [crypto] Fixing random BLS key generation for testing

storage/jellyfish_merkle/src/lib.rs
The crate doc that was missing.
Yes
CI
=> [storage][doc] Jellyfish merkle

language/bytecode_verifier/src/abstract_state.rs, language/bytecode_verifier/src/partition.rs, language/bytecode_verifier/src/type_memory_safety.rs
This commit renames poorly named variables in bytecode verifier.
Yes
Existing tests
=> [language] This commit renames poorly named variables in bytecode verifier

terraform/auth.tf
This is nice than handwritten JSON.
`terraform plan` on dev workspace, only change is document version 2008-10-17 -> 2012-10-17.
=> [terraform] Use aws_iam_policy_document

language/e2e_tests/src/account.rs, language/e2e_tests/src/executor.rs, language/e2e_tests/src/tests/account_universe.rs, language/e2e_tests/src/tests/create_account.rs, language/e2e_tests/src/tests/mint.rs, language/e2e_tests/src/tests/peer_to_peer.rs, language/e2e_tests/src/tests/rotate_key.rs, language/functional_tests/src/evaluator.rs, language/tools/repl/src/main.rs
Clean up the duplicated code in language e2e tests.
Yes
=> [vm] Clean up account resource

storage/libradb/src/ledger_counters/mod.rs, storage/libradb/src/state_store/mod.rs, storage/libradb/src/state_store/state_store_test.rs
The counter I modified here is for all the nodes instead of only internals. Fix it to avoid confusion.
Y
CI
=> [storage] fix counter name

language/vm/src/foreign_contracts.rs, language/vm/src/serializer.rs, language/vm/vm_runtime/Cargo.toml, language/vm/vm_runtime/src/foreign_contracts.rs, language/vm/vm_runtime/src/gas_meter.rs, language/vm/vm_runtime/src/lib.rs, language/vm/vm_runtime/src/txn_executor.rs
Add checks for safety of `calculate_transaction_gas` in `gas_meter.rs`.
Yes.
Testing via `cargo test`. Passes existing tests. To reproduce the analysis performed by MIRAI, please run `RUSTC_WRAPPER=mirai MIRAI_LOG=warn cargo build --features "mirai-contracts"` from the VM directory.
N/A
=> [VM] Check for Gas Meter Safety

terraform/templates/dashboards/overview_dashboard.json
We change the name in #567 
Y
CI
=> [dashboard] update total_accounts formula

language/stackless_bytecode/bytecode_to_boogie/src/bytecode_instrs.bpl, language/stackless_bytecode/bytecode_to_boogie/src/translator.rs
This pull request
- Adds implementation for `LdAddr`,
- Modifies translation of `Abort` so `abort_flag` is set to true instead of doing `assert false`,
- Adds type checking to more places including after `Unpack`, after `Call`, etc,
- (Biggest change) Modifies the memory model so that there is only one constructor for `Reference` and parameters specific to global or local references are stored in newly added `RefType`. This way the Boogie code will be much cleaner. This change was proposed by @kkmc. We couldn't think of any bad implications this change might have but please comment if you spot one. 
Yes.
```
cargo run FILENAME
```
=> [language] modify Boogie memory model and implementations for instructions

state_synchronizer/src/coordinator.rs
diff provides new debug logs for better tracing of prod issues
=> [state sync] add logging

terraform/templates/dashboards/storage.json
Fix counter name in Storage dashboard
Y
CI
=> [dashboard] fix storage dashboard

state_synchronizer/src/coordinator.rs, state_synchronizer/src/peer_manager.rs
add logs to network discovery events and public methods of peer_manager
=> [state sync] peer manager logs

testsuite/libra_fuzzer/Cargo.toml, testsuite/libra_fuzzer/src/commands.rs, testsuite/libra_fuzzer/src/main.rs
A couple of simple improvements to libra_fuzzer.
=> some libra_fuzzer improvements

testsuite/cluster_test/src/deployment.rs, testsuite/cluster_test/src/main.rs
* This adds better support for running with ALLOW_DEPLOY env not set. Previously running without this flag would result in not so obvious behaviour. Now this works in more obvious way - no messages will be sent to slack and no actions on ECR/ECS will be taken if ALLOW_DEPLOY is not set
* It also reduces number of slack messages sent during deploy from 4 to 2. Previously we would tell when we starting deploy, finished deployed, passed test and tagged image. Now it condensed to just 2 messages - `deployed new version` and `test passed and image tagged`.
=> [cluster_test] Better UX for deployment lifecycle

types/src/account_config.rs
Remove the redundant account struct tag in `account_config.rs`
Yes, and have sent the CLA.
`cargo test`
N/A
=> Nit: remove redundant structure tag

consensus/src/chained_bft/chained_bft_smr.rs
Starting network message receiver in consensus before SMR initialization
blocks on state synchronization has the benefit of allowing
state synchronizer to sync from any number of connected peers because NewPeer
event delivery is not blocked on consensus being fully initialized.
Yes
#764
=> [consensus] Start network receivers before blocking on state sync during initialization

libra_node/src/main_node.rs
This diff fixes #749.
The order in which network provider, consensus and state synchronizer were initialized was creating a deadlock. We were initializing network provider after consensus, which was getting blocked on state synchronizer to catch up to root ledger info. The state synchronizer was in turn blocked because network provider had not delivered any NewPeer messages for it to know who to sync from -- network provider could not deliver these messages because it was not even initialized, hence creating a deadlock.
We fix the deadlock by starting network provider before consensus.
Yes
=> [libra node] Initialize network module after consensus

storage/libradb/src/schema/jellyfish_merkle_node/mod.rs
fix a broken link.
Yes
`cargo doc`
=> [storage] trivial: doc fix

storage/libradb/src/system_store/mod.rs
=> [storage] trivial: remove a unnecessary `#[allow(dead_code)]`

storage/jellyfish_merkle/src/iterator/mod.rs
- Rename `visited` to `parent_stack`.
- Replace `unreachable` with returning an error.
Y.
CI.
None.
=> [Storage] Small improvements to Jellyfish Merkle Iterator

network/src/protocols/discovery/mod.rs, network/src/protocols/discovery/test.rs
+ In this change, we _append_ our configured seed peer addrs to
whatever addrs we learn through discovery for that seed peer. This
prevents a stale discovery note from clobbering a fresh seed peer
configuration, which lead to the parition identified in #587.
=> [network][discovery] Fix #587. Incl seed addrs in connmgr update

testsuite/cluster_test/src/log_prune.rs
* Print last deleted stream age, to get sense of progress [seems like it deletes about 1 day worth of streams in about an hour]:
`Deleted 300 streams, last age: 21 days`
* Add maximum retry count for log stream deletion. This allows to run safely this with nohup
=> [cluster_test] Minor improvements to --prune-logs

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/block_store_test.rs, consensus/src/chained_bft/block_storage/block_tree.rs
=> [consensus] beautify block tree figures

scripts/changed-files.sh
Show a diff of any changes if CI detects that files were changed after build and test.
=> [ci] show diff of changed files

execution/executor/src/block_processor.rs, execution/executor/src/transaction_block.rs, storage/scratchpad/src/lib.rs, types/src/proof/accumulator/accumulator_test.rs, types/src/proof/accumulator/mod.rs, types/src/proof/mod.rs
Since we will use this implementation for both accumulator consistency proof and scratchpad purposes, move the code so it can be shared.
Yes.
CI.
None.
=> [Proof] Move in-memory accumulator implementation to types/proof

common/canonical_serialization/README.md
Fix errors in libra canonical serialization (LCS) documentation. (https://github.com/libra/libra/issues/805)
No. Pull-requests section does not exist in `CONTRIBUTING.md`.
No code change. Just documentation.
None.
=> [common] fix LCS documentation errors

language/bytecode_verifier/src/abstract_state.rs, language/bytecode_verifier/src/nonce.rs, language/bytecode_verifier/src/partition.rs, language/bytecode_verifier/src/type_memory_safety.rs
- Nonce is just a newtype around a `usize`
- The struct does impose any additional overhead at runtime
- As such, it can implement `Copy` without much worry
cargo check; cargo test
=> [language][Bytecode Verifier] Made Nonce copy

language/compiler/README.md
Some of the compiler flags and options have changed, and the
README file needs to be updated to match.
Yes
=> [language] Update usage info in the compiler README file

language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/src/context.rs
This fixes some spelling and punctuation problems that I happened
to notice.
Yes
=> [language] Tidy up some comments

crypto/crypto/src/ed25519.rs
With regards to malleability, we want to defend against a third party (other than the signer) trying to modify the signature payload. Briefly, an EdDSA signature is a tuple `(s, R)`, so there are three ways to modify the signature, either by altering `s` or `R` or both. However, **the `R` part is hashed during signing and verification** (to compute `h = H(ENC(R) || ENC(A) || M)`), and **thus a third party cannot modify R** without being detected.
This PR removes the check that `R` lies on a small group.
Ensuring that `s < order of the EC group` is important and remains as part of our malleability guarantees.
Note that the signer could always pick a small order R, but actually she will harm herself if she does so. We are currently interested about malleability issues in which a third party …
=> [crypto] EdDSA remove small group R check

testsuite/cluster_test/src/deployment.rs
If cluster test fails after deploy and then re-started, it immediately fails to tag image with `ImageAlreadyExists`, if image has not changed since previous start
We going to ignore this error making `tag_image` function idempotent
=> [cluster_test] Ignore ImageExists error when tagging image

state_synchronizer/src/coordinator.rs, state_synchronizer/src/peer_manager.rs
When we choose a peer to receive a chunk for synchronization, we use a scoring system that rewards good actors and punishes bad actors. Peer scoring currently only checks for the peer sending invalid chunk (#837), and this diff adds timeout logic. If a peer fails to respond and is causing a delay in the node making progress, we reduce the peer's score. However, the timed-out peer is not penalized as heavily as sending an invalid chunk error.
**Data structure**: `requests: HashMap<u64, (PeerId, SystemTime)>` in `PeerManager` struct
**Logic**:
1. Whenever a new request for a block is made, its <version, (peer_id, request_time)> is added to a requests hashmap
2. Whenever a response is received, the response for the version is removed from the hashmap
3. During `check_progress` in …
=> [state-sync] Adding timeout logic to peer scoring

state_synchronizer/src/peer_manager.rs
WeightedIndex library can be O(log(n)) if the weighted index vector does not need to be updated when choosing a peer. This diff adds logic to only update the weighted index vector when score changes, and store that vector to be used when picking peer, rather than calculating the distribution dynamically when picking.
unit test
=> [state-sync] Optimize weight distribution calculation for peer scoring

client/src/account_commands.rs
bugfix: client continue to mint when there are mint params error.
yes
=> [client] fix mint params error not return

client/src/client_proxy.rs
=> make clippy happy

.circleci/config.yml, .github/workflows/land-blocking.yml
Test bors libra landing on non-master branch, with enough to satisfy it's checks.
CI
None
=> [circle] ignore gh-pages

Cargo.lock, execution/db-bootstrapper/src/bin/db-bootstrapper.rs, storage/storage-interface/src/lib.rs, testsuite/Cargo.toml, testsuite/tests/libratest/smoke_test.rs
Useful information printed so that it's easy to identify problems like opening DB at a wrong folder (getting empty DB)
Y
eyes
=> [db-bootstrapper] print more information

language/libra-vm/src/libra_vm.rs
Add a hypothetical feature that gets activated if version gets incremented. Used for premainnet testing only!
Yes
We'll see :)
=> [vm] Build a hypothetical feature used for versioning testing.

common/logger/src/struct_log.rs
Previous writing system would write X number of bytes, and not guarantee
that the whole message is written.  This now guarantees that the whole
message is written by using the write_all function.
https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all
=> [logging] ensure TCP structured logging writes all data

execution/db-bootstrapper/src/bin/db-bootstrapper.rs
=> [db-bootstrapper] use read-only for waypoint generation

language/move-prover/src/cli.rs
This PR adds two command line options `eager-threshold` and `lazy-threshold` representing the thresholds the SMT solver uses during quantifier instantiation(`smt.QI.EAGER_THRESHOLD` and `smt.QI.LAZY_THRESHOLD`). 
Yes.
cargo test
=> [move prover] add smt.QI threshold options

.github/CODEOWNERS
@kchalkias @valerini and I (for now)
=> Add reviewers for crypto code

crypto/crypto/src/unit_tests/ed25519_test.rs
Strengthens the crypto tests a tad more.
=> [crypto, test-only] Point decompression checks + test output

testsuite/cluster-test/src/cluster_swarm/cluster_swarm_kube.rs
=> [cluster-test] revert change for delete job immdiately once it is done

types/src/account_config/resources/currency_info.rs
=> Expose preburn/total values of CurrencyInfoResource

types/src/proof/position/mod.rs
fix https://github.com/libra/libra/pull/5800
=> [fix] fix shift error when fuzzing accumulator schema

json-rpc/docs/type_transaction.md
=> Typo fixes in type_transaction.md

libra-node/src/main_node.rs, state-synchronizer/src/executor_proxy.rs, storage/backup/backup-cli/src/backup_types/epoch_ending/backup.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/backup.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/backup.rs, storage/backup/backup-cli/src/backup_types/transaction/restore.rs, storage/backup/backup-cli/src/coordinators/restore.rs, storage/backup/backup-cli/src/storage/command_adapter/command.rs, storage/backup/backup-cli/src/storage/command_adapter/config.rs, storage/backup/backup-cli/src/storage/command_adapter/mod.rs, storage/backup/backup-cli/src/storage/command_adapter/tests.rs, storage/backup/backup-cli/src/storage/local_fs/tests.rs, storage/backup/backup-cli/src/storage/test_util.rs, storage/libradb/src/lib.rs, storage/storage-interface/src/lib.rs, types/src/move_resource.rs
For the db restore drill.
#5797
#5824 
#5826 
#5821 
#5838
=> cherry-pick backup related fixes to release-0.20 

terraform/templates/dashboards/storage.json
add a panel track restore status.
=> [storage][dashboard] add restore status panel

docker/build-aws.sh, docker/tools/buildspec.yaml
to utilize build-aws.sh for building the tools container.
Y
build myself on codebuild.
=> add tools buildspec

storage/libradb/src/metrics.rs, storage/libradb/src/pruner/mod.rs, terraform/templates/dashboards/storage.json
compare the theoretic size of jellyfish merkle and the data from rocksdb.
=> [storage][dashboard] add estimated tree size with prune window counter

testsuite/cli/src/main.rs
ensure init once.
* manual test with libra-swarm
=> [cli] fix cli logger

docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/init/Dockerfile, docker/mint/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile
Make those docker stage identical with validator to save some build time.
=> [dkr] add ENABLE_FAILPOINTS to all Dockerfile

network/src/logging.rs, network/src/noise/handshake.rs, network/src/transport.rs
Removes StructuredLogEntry, and replaces it with the new schema'd
structured logs to remove a bunch of the related constants.
=> [network] remove StructuredLogEntry

client/json-rpc/src/client.rs
Separating out HTTP Errors from InvalidServerResponse error since some HTTP Errors are retriable.
We saw these errors in AOS logs
```
[2020-09-18T10:11:01Z ERROR aos::errors] Received non-retryable error: JsonRpcAsyncClientError: InvalidServerResponse Http error code 502 Bad Gateway
```
This error should be retried.
=> Add HTTPError to JsonRpcAsyncClientError and update is_retriable logic

Cargo.lock, common/libradoc/Cargo.toml, language/transaction-builder/generator/Cargo.toml, language/transaction-builder/generator/tests/generation.rs
* update serde-generate to include many recent improvements
* fix (ignored) python test
CI + manually run `--ignored` tests
https://github.com/novifinancial/serde-reflection/pull/60
https://github.com/novifinancial/serde-reflection/pull/61
=> [transaction builder generator] update serde-generate

docker/validator/build.sh, docker/validator/buildspec.yaml, testsuite/cluster-test/src/cluster_swarm/templates/libra_node_spec_template.yaml
Add support for Docker images clean up and transition.
Canaried in LBT
=> [dkr] add validator buildspec and rename e2e

.github/actions/land-blocking/find-lbt-images.sh
Propagate validator image rename. 
Canary
=> [LBT][compat] propogate validator image rename

config/management/operational/src/command.rs, config/management/operational/src/lib.rs, config/management/operational/src/owner.rs, config/management/operational/src/validator_config.rs
I cannot directly write into release-0.21 so I need to do this... sigh.
We need this for Wednesday.
=> [management] allow owner/operator support for adding new validator

common/logger/src/libra_logger.rs
This will include the current thread name when sending via JSON. We can also include it when we print out to stderr but we'd need to think a bit more about the human-readable output format.
=> logger: capture thread name if available

testsuite/smoke-test/src/key_manager.rs
This PR  updates the key manager smoke test and cleans up a few old pieces of code/articles that are no longer relevant.
Yes.
Running the test locally passes.
None.
=> [Smoke Tests] Update and clean up key manager smoke test.

language/move-prover/doc/user/install.md
=> [move-prover] Update installation instructions.

language/stdlib/modules/doc/overview.md, language/stdlib/modules/overview_template.md, language/stdlib/transaction_scripts/doc/spec_documentation.md, language/stdlib/transaction_scripts/doc/transaction_script_documentation.md, language/stdlib/transaction_scripts/spec_documentation_template.md, language/stdlib/transaction_scripts/transaction_script_documentation_template.md
See [here](https://github.com/wrwg/libra/blob/framework_spec_doc/language/stdlib/transaction_scripts/doc/spec_documentation.md) for the rendered form.
Finalize documentation for release.
Yes
NA
NA
=> [move-prover][documentation] Framework specification overview.

libra-node/src/lib.rs
This cherry-pick was triggerd by a request on #6542
> this should be made public so that docker can expose it
> 
> 
> 
> 
> (Write your motivation for proposed changes here.)
> 
> 
> (Write your answer here.)
> 
> ## Test Plan
> 
> (Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)
> 
> 
> (If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)
cc …
=> Cherry-pick PR #6542 into release-1.0: [libra-node] fix test json-rpc service

language/move-prover/doc/user/spec-lang.md
=> [move-prover][doc] Fixing broken link.

devtools/x/src/utils.rs
Deal with my shame :/
Fix a simple logic bug preventing sccache from writing when running in the auto branch.
Yes
CI build times should drop.
None
=> [sccache] fixing shameful logic bug

network/src/peer/mod.rs
This small cherrypicked diff removes stream-ratelimiter from network, which contained a memory leak. Every time a peer connected, sent at least one message, and then disconnected, we would leak a `tokio::sync::Semaphore`. We will be introducing a more robust token-bucket filter in the near future to replace stream-ratelimiter; for now, the stream-ratelimiter is causing more problems than it fixes.
The memory leak will eventually cause a node (validator, VFN, PFN) to OOM after too many peers connect, send at least one message, and then disconnect.
=> [cherry-pick][network] fix memory leak, remove stream-ratelimiter from network

json-rpc/src/runtime.rs, json-rpc/src/tests/unit_tests.rs
=> Cherry pick [json-rpc] fix cors validation to allow cross domain call in browser for release 1.0

common/metrics/src/op_counters.rs, mempool/src/counters.rs, mempool/src/shared_mempool/coordinator.rs, state-synchronizer/src/coordinator.rs, state-synchronizer/src/counters.rs
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)
=> [load test] add main loop metrics

developers.libra.org/website/siteConfig.js, developers.libra.org/website/static/js/new-site-redirects.js
redirect users from v1 docs site to v2
=> add new site redirects

docker/ci/alpine/Dockerfile, docker/ci/arch/Dockerfile, docker/ci/circleci/Dockerfile, docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/init/Dockerfile, docker/mint/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
Handle a bunch of dependabot prs for docker images in one go now that we've seen them work.
Yes
CI all the way
All the current open dependabot prs for docker images.
=> [docker] update base docker images.

common/logger/src/diem_logger.rs
This reverts commit 0e67edd3bdfdf6c2f2397d817d50e10c4c98bcc9.
=> Revert "logger: change default remote log level to info"

.github/workflows/post-land.yml
Fix the typo in conditional check in post-land test. 
Canary
=> [ci] fix typo in post-land test

.github/workflows/post-land.yml
Propagate name changes to post-land test. 
Canary https://github.com/diem/diem/actions/runs/421413195
=> [post-land] propagate diem name change

scripts/cti
Cluster test template has been updated.
Yes
http://grafana.ct-0-k8s-testnet.aws.hlw3truzy4ls.com/d/performance/performance?orgId=1
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/developers.libra.org, and link to your PR here.)
=> [cluster-test] Update grafana link

.github/actions/changes/action.yml, .github/actions/changes/get_pr_info.sh, .github/actions/matches/action.yml, .github/workflows/ci-test.yml
Testing gha workflow.
Yes
Github Actions Jobs
=> [gha] uses changes to determine which jobs to run

developers.diem.com/docs/node/config-deploy-fn.md, docker/compose/public_full_node/public_full_node.yaml
these were updated when the consensus key was made unexportable
=> point to the new pfn testnet config

.circleci/get_pr_info.sh
Figure out why we sometime don't have the target_branch set in bors auto branch builds.
Yes
CI
None
=> [circleci] log about the state of looked up pr info

.circleci/config.yml, .circleci/get_pr_info.sh
Switch CI to use vm executor class. 
This PR comprises of the following cherry-picks:
#6990 
#7000 
#7109 
CI
=> Cherry-pick PR #6990 into release-1.1: [ci] try vm class

secure/json-rpc/src/lib.rs, testsuite/smoke-test/src/operational_tooling.rs
The `VMStatusView` in the `secure-json-rpc` client was dropping the Move abort explanation when deserializing from the json-rpc server response. This adds these fields in so that we now get them. One of the smoke tests for the operational tooling has been updated to make sure that these abort code explanations are being created and returned back out. In the updated test we now get the following back as the MoveAbort status:
```
MoveAbort { 
location: "00000000000000000000000000000001::DiemSystem",
abort_code: 519,
explanation: Some(MoveAbortExplanationView {
category: "INVALID_ARGUMENT",
category_description: " An argument provided to an operation is invalid. Example: a signing key has the wrong format.", 
reason: "EALREADY_A_VALIDATOR", 
reason_description: " Tried to add a validator to …
```
=> [secure] Include Move abort code explanation in the VMStatusView

.github/actions/changes/get_pr_info.sh, .github/workflows/cargo-audit.yml
Add audit workflow and fix target branch on push events
=> gha: add audit workflow

language/diem-tools/writeset-transaction-generator/src/lib.rs, language/diem-tools/writeset-transaction-generator/src/main.rs, language/diem-tools/writeset-transaction-generator/src/release.rs, language/diem-tools/writeset-transaction-generator/src/unit_tests/mod.rs, language/diem-tools/writeset-transaction-generator/src/unit_tests/release_tests.rs
Create a command to create the writeset needed for release in `writeset-generator`. This command will take a json-rpc endpoint and a blockchain height as an input, comparing the diem framework over there with the local version, and generate a WriteSet. This will be a critical step in our release process as we need to check-in this generated binary for AOS to deploy the modified Diem Framework into production.
Yes
Added a test suite to make sure the diff logic is correct.
=> [writeset-generator] Implement a command to generate a release patch.

json-rpc/tests/integration_test.rs, mempool/Cargo.toml, mempool/src/core_mempool/transaction_store.rs, mempool/src/tests/core_mempool_test.rs
See #7169
Yes
Unit test
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/developers.libra.org, and link to your PR here.)
=> [mempool] return accepted for submitting same transaction in mempool

.circleci/config.yml, .github/actions/build-setup/action.yml, .github/actions/docker-checks/action.yml, .github/workflows/ci-test.yml, docker/ci/alpine/Dockerfile, docker/ci/arch/Dockerfile, docker/ci/centos/Dockerfile, docker/ci/circleci/Dockerfile, docker/ci/github/Dockerfile, x.toml
* get caching parity with circleci build.
* sccache needed volume map/symlink trickery.
* enable e2e test retries.
No mechanism to post e2e failures anywhere....
y
My bloodshot eyes.
=> [gha] caches: gha and sccache

json-rpc/tests/integration_test.rs, mempool/Cargo.toml, mempool/src/core_mempool/transaction_store.rs, mempool/src/tests/core_mempool_test.rs
This cherry-pick was triggerd by a request on #7174
> 
> See #7169
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?
> 
> Yes
> 
> ## Test Plan
> 
> Unit test
> 
> 
> (If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/developers.libra.org, and link to your PR here.)
cc @xli
=> Cherry-pick PR #7174 into release-1.1: [mempool] return accepted for submitting same transaction in mempool

consensus/src/liveness/proposal_generator.rs
This ensures that if we are using consensus slow downs, that transactions are committed to all validators and vfns as fast as possible. Previously all validators would move quickly through the execution phase but the committing validator wouldn't broadcast a QC until the timeout had occurred. This was due to the block having been committed locally and there were no pending transactions. This change incorporates the most recent committed block into "pending transactions", which is a no-op for every case except for the one just mentioned. And enables all validators and vfns to commit as fast as possible.
This will enable us to deploy a testnet that doesn't grow too fast, which will be critical in letting the public make practical use of our PFN entry point. Currently it takes several hours …
=> Cherry-pick PR #7182 into release-1.1: [consensus] avoid mempool long poll if root block has user txns

.github/actions/matches/action.yml, .github/workflows/ci-test.yml, language/move-lang/src/lib.rs
Cherry pick of two gha fixes landing on master.   One is to fix the short circuit logic for non-rust jobs (allowing them to be skipped).   The other is to provide bors a single job to check for success or failure of all run jobs.
Ah, and a third fix from master for move lang tests that had not yet been merged in.   Due to file system mount locations.
Yes
Master - tested already with several prs against gha-test-1 branch I setup over the weekend.
https://github.com/diem/diem/pull/7265
=> [gha] Release 1.1 fixes.

.circleci/config.yml, .github/actions/matches/action.yml, .github/workflows/ci-test.yml
Cherrypick relevant PRs to sync up release-1.1 and master branches.
Removes circleci rust jobs, and fixes match action for gha.
Y
CI in master
https://github.com/diem/diem/pull/7286
https://github.com/diem/diem/pull/7183
=> [release-1.1] Remove circleci rust jobs and touch up gha match action (cherrypick)

docker/ci/alpine/Dockerfile, docker/ci/github/Dockerfile, docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/init/Dockerfile, docker/mint/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
Update all docker base images.
Add tests docker layers to client and init docker images (as they have debian-slim bases and if not in sync could break binaries).
Updated alpine's pinned bash version.
Yes
CI (circleci that is)
All open dependabot docker prs.
=> [docker] updates and tests

language/diem-tools/writeset-transaction-generator/src/main.rs
Currently `Genesis` will be included in the `stdlib_modules`. We will need to manually filter those modules out from the release process so that they won't be published on-chain during the new release process.
Yes
Manually tested the binary and make sure genesis module isn't included.
=> [writeset-generator] Filter out Genesis module from release process.

SECURITY.md
Corrects link to security policy reference.
=> Updates security url

developers.diem.com/docs/sdks/overview.md
=> [website] fix SDK docs link

storage/backup/backup-cli/src/metadata/cache.rs, storage/backup/backup-cli/src/storage/command_adapter/command.rs, storage/backup/backup-cli/src/storage/command_adapter/config.rs, storage/backup/backup-cli/src/storage/command_adapter/mod.rs, storage/backup/backup-cli/src/storage/local_fs/mod.rs, storage/backup/backup-cli/src/storage/mod.rs, storage/backup/backup-cli/src/utils/backup_service_client.rs, storage/backup/backup-cli/src/utils/error_notes.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/backup/backup-cli/src/utils/read_record_bytes.rs
shortcut to log some context info and the stack trace when error happens.
Y
existing coverage.
tried some bad commands to observe the error log.
=> [backup] trait ErrorNotes 

testsuite/cluster-test/src/cluster_swarm/templates/vault_spec_template.yaml
revert an accidentally change for vault image pull template: https://github.com/diem/diem/pull/7080/files#diff-490f616124685028b5a9c674b01cee0485bc33219137b8245d7b3cdcc9129d1bL28.
=> [cluster-test] revert vault image pulling location

storage/diemdb/src/lib.rs
=> update diemdb rocksdb property map names

network/src/connectivity_manager/test.rs
There was a ton of differing and repeated code for setup and other things
in the conn mgr.  This attempts to rid the code of some of the old
paradigms prior to the `Peer` object.
Just some work I did trying to understand why the tests were failing for a different PR (and then found out that my changes were definitely a problem).  Additionally, these tests actually failed more on my changes, which could be some side effects of me removing the `eligible` peer part.  However, all of these tests run successfully, and should have less randomness in them.
=> [network] Consolidate repeated code in ConnMgr tests

.github/workflows/ci-test.yml, docker/ci/arch/Dockerfile, docker/ci/github/Dockerfile, docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/init/Dockerfile, docker/mint/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
All the debian docker updates in one go, on top of the disabling of arch pr that I'm waiting to land.   https://github.com/diem/diem/pull/7553
Yes
CI
https://github.com/diem/diem/pull/7553
=> Docker update

sdk/client/src/blocking.rs, sdk/client/src/client.rs, sdk/client/src/lib.rs
Add User-Agent HTTP header to requests made by the sdk client.
Fixes: #7484
yes
run tests
=> Add User-Agent HTTP header to requests made by the sdk client

.github/actions/build-setup/action.yml, .github/workflows/osx-sccache.yml
When landing on master produce osx object files per crate and store in s3
Yes
CI and local pulls.
https://github.com/diem/diem/runs/1864797013?check_suite_focus=true
None
=> [gha] sccache publish osx object files.

docker/client/Dockerfile, docker/tools/Dockerfile
Prevent future sha/version mismatches by allowing automation to handle the upgrade (no split base images).
Yes
CI
None
=> [docker] work well with automation

developers.diem.com/docs/core/run-local-network.md
=> fix doc links

language/diem-framework/modules/DiemTransactionPublishingOption.move
This PR fixes a spec bug.
Yes.
=> [diem-framework] fix spec bug

language/bytecode-verifier/src/lib.rs, language/bytecode-verifier/src/script_signature.rs, language/bytecode-verifier/src/verifier.rs, language/move-core/types/src/vm_status.rs, language/move-vm/runtime/src/loader.rs, language/move-vm/runtime/src/runtime.rs, language/move-vm/runtime/src/session.rs, language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
- Added execute_script_function entry point to the move-vm
- Added verification of the script function call
- Necessary for #7580
- New tests
=> [vm] Add execute_script_function and verification

storage/diemdb-benchmark/src/lib.rs, storage/diemdb-benchmark/src/main.rs
=> [diemdb_bench] add prune window

.github/workflows/daily.yml
Remove unneeded audit job
Yes
CI
None
=> [gha] remove canary from daily audit checks.

.github/actions/build-setup/action.yml, .github/actions/dockerhub_login/action.yml, .github/workflows/ci-publish-base-image.yml, .github/workflows/ci-test.yml, docker/ci/github/Dockerfile, scripts/dev_setup.sh
A cherry-pick of https://github.com/diem/diem/pull/7649
Y
This CI
https://github.com/diem/diem/pull/7649
=> [gha/docker] use a docker image per branch

common/trace/src/trace.rs
The previous behavior of this function, before #7654, was to error out on being called
more than once. Restore that behavior while not introducing unsafe code.
There's a separate function `diem_trace_set` whose behavior didn't
change -- it would return true if in INITIALIZED status, which is what
the current function does as well.
=> [diem-trace] restore previous behavior of set_diem_trace

.github/actions/changes/get_pr_info.sh, .github/workflows/ci-test.yml, .github/workflows/ci-update-sccache.yml
Linux sccache hasn't been updating - and I decided to move it to the same cache as sccache.
Needed to use the new base image location.
Also renamed the sccache file.
Yes
CI -- https://github.com/diem/diem/actions/runs/580275218
None
=> [sccache] linux builds and a little cleanup

mempool/src/shared_mempool/peer_manager.rs, mempool/src/tests/shared_mempool_test.rs
Currently, we only use broadcast to all failovers, rather than logic to
choose a single failover.  So, I'm cutting out that failover logic in
addition to a test that is specific only to it.
=> [mempool] Remove legacy failover logic

language/move-prover/boogie-backend/src/bytecode_translator.rs, language/move-prover/src/prelude.bpl
Differentiate between weak and strong borrows to (hopefully) improve performance of verifier.
Yes
Current coverage is sufficient (current verification pipeline does not yet make use of these functions).
=> [move-prover] add weak and strong borrow boogie instructions

language/compiler/ir-to-bytecode/src/compiler.rs, language/compiler/ir-to-bytecode/src/context.rs, language/compiler/ir-to-bytecode/syntax/src/lexer.rs, language/compiler/ir-to-bytecode/syntax/src/syntax.rs, language/ir-testsuite/tests/move/modules/access_friend_function_invalid.mvir, language/ir-testsuite/tests/move/modules/access_friend_function_valid.mvir, language/ir-testsuite/tests/move/modules/friend_decl_cyclic.mvir, language/ir-testsuite/tests/move/modules/friend_decl_cyclic_transitive.mvir, language/ir-testsuite/tests/move/modules/friend_decl_deps.mvir, language/ir-testsuite/tests/move/modules/friend_decl_deps_transitive.mvir, language/ir-testsuite/tests/move/modules/friend_decl_different_address.mvir, language/ir-testsuite/tests/move/modules/friend_decl_duplicated.mvir, language/ir-testsuite/tests/move/modules/friend_decl_non_existing.mvir, language/ir-testsuite/tests/move/modules/friend_decl_self.mvir, language/ir-testsuite/tests/move/publish/republish_module_compatible_add_friend.mvir, language/ir-testsuite/tests/move/publish/republish_module_compatible_friend_fn_to_public.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_change_friend_fn.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_change_unused_friend_fn.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_delete_friend_fn.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_delete_unused_friend_fn.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_drop_friend.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_drop_unlinked_friend.mvir, language/ir-testsuite/tests/move/publish/republish_module_incompatible_friend_fn_to_private.mvir, language/move-ir/types/src/ast.rs, language/move-lang/src/to_bytecode/translate.rs, language/testing-infra/module-generation/src/generator.rs
- allow `public(friend)` to be a function visibility modifier
- parse and compile friend declarations in modules
Yes
IR test cases added (although the compatibility tests might not be passing as it depends on #7750)
=> [ir-compiler] add support for friend visibility

mempool/src/shared_mempool/peer_manager.rs
Previously, mempool would keep all state of all peers ever connected for
the lifetime of the service.  Non-validators would immediately have
their state restarted from the beginning if reconnected, so there's no
point to keep that data around.
There are now slight behavioral changes in the code:
1. Instead of asserting and crashing when a mempool peer isn't found, it's skipped
2. If a mempool peer isn't found when checking for backoff, it's considered disabled
=> [mempool] Add SharedMempool GCing for non-validator peers

docker/compose/test_docker_compose.sh
Currently there is a race condition which intermittently breaks CI- this is due to nodetereministic output in combined docker-compose logs. By starting the containers and then looking at each containers' logs independently, the race condition is avoided.
yes
run `./docker/compose/validator-testnet/test_docker_compose.sh`
=> [docker-compose] Check docker logs separately to prevent race condition

storage/backup/backup-cli/src/storage/command_adapter/azure.sample.toml, storage/backup/backup-cli/src/storage/command_adapter/gcp.sample.toml, storage/backup/backup-cli/src/storage/command_adapter/s3.sample.toml
1. use relative paths so backups are interchangeable among platforms
2. add gzip filters
Y
=> [backup] update sample configs

.github/workflows/ci-test.yml, helm/fullnode/templates/tests/test-fullnode-connection.yaml
Add a small helm test and GHA that spins up a fullnode (from https://github.com/diem/diem/pull/7733) and checks that state sync is able to make progress. Test runs on `ubuntu-latest-xl` and uses the default requested resources 2 CPU and 4Gi for the fullnode.
For now, minikube is installed during the job, but ideally we can bake this in to the base image in `scripts/dev_setup.sh` (had some issue with the alpine build that I need to investigate)
Stacked on https://github.com/diem/diem/pull/7733, only review https://github.com/diem/diem/pull/7745/commits/d9864127591305de11ca78a1629db22e4624d414
Yes
Helm install and test locally. Also CI https://github.com/diem/diem/pull/7745/checks?check_run_id=1983882562
```
$ helm upgrade fullnode --set storage.class=standard --set storage.size=100Gi …
```
=> [helm][gha] pfn helm chart test

helm/fullnode/files/backup/azure.toml, helm/fullnode/templates/_helpers.tpl, helm/fullnode/templates/backup-verify.yaml, helm/fullnode/templates/backup.yaml, helm/fullnode/templates/restore.yaml
Sync recent changes from partners chart:
* https://github.com/diem/partners/pull/784
* https://github.com/diem/partners/pull/811
=> [helm] sync STRUCT_LOG_TCP_ADDR and azure config for backup

storage/backup/backup-cli/src/metadata/cache.rs
so that if error happens we don't end up with a stale (probably empty) file cached.
Y
locally
=> [backup] metadata cache: download to tmp file then rename

developers.diem.com/docs/move/creating-coins.md
There is an address typo in the documentation
Yes
N/A
N/A
N/A
=> Fixes inadvertent change in Coin address

specifications/trusted_computing_base/safety_rules/README.md
=> [tcb][safety_rules] added state machine specification

Cargo.lock, common/logger/Cargo.toml, common/metrics-core/Cargo.toml, common/metrics/Cargo.toml, common/workspace-hack/Cargo.toml
Update transitive deps, not handled by dependabot.
Yes
CI
None
=> [deps] update transitive deps

CHANGELOG.md, x.toml
Start changelog for next and future releases.
Also add an ignore rule in x for documentation changes.
No test other than CI
=> [changelog] start changelog for releases

developers.diem.com/docs/core/my-first-client.md
Help people getting started with Diem not get confused by examples in the 'my-first-client' guide that use Libra.
Requires PR https://github.com/diem/my-first-client/pull/26 to be merged first.
=> [doc] update my-first-client doc to rename libra to diem

.github/workflows/land-blocking.yml
There is a typo in LBT's  trigger condition.  
Canary + CI
=> [gha][lbt] fix typo in trigger condition

Cargo.lock, devtools/x-core/Cargo.toml, devtools/x-lint/Cargo.toml, devtools/x/Cargo.toml, devtools/x/src/lint/guppy.rs, devtools/x/src/lint/workspace_classify.rs
Prepare for nextest integration, and also introduce the `PackagePublish` enum per @bmwill's feedback.
=> [x] upgrade to guppy 0.9.0

execution/executor-benchmark/src/lib.rs
Print accumulative tps, easier for comparison between PRs.
Y
local run
=> executor-benchmark: print accumulative tps

language/diem-framework/modules/DiemAccount.move, language/diem-framework/modules/doc/DiemAccount.md, language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md, language/diem-framework/transaction_scripts/preburn.move
This PR fixes specs in DiemAccount module and preburn.move transaction script, and fixes timeouts in relevant functions.
=> [move prover][diem framework] fix timeouts in DiemAccount and preburn script

storage/backup/backup-cli/src/storage/command_adapter/local_folder.sample.toml
To add the gzip filter, so a downloaded backup from the Diem testnet can be interpreted via this sample file directly (with updated FOLDER variable)
y
locally.
=> [backup] update local_folder.sample.toml

specifications/move_adapter/README.md
Nothing substantive here, but I recently noticed a few small glitches...
Polish the docs!
Yes
=> [specifications] minor fixes to the move_adapter spec

state-synchronizer/src/executor_proxy.rs, state-synchronizer/src/tests/helpers.rs
This cherry-pick was triggerd by a request on #7060
cc @mickayz
=> Cherry-pick PR #7060 into release-1.1: [state-sync][bug-fix] removing integer overflow

language/diem-framework/modules/DesignatedDealer.move, language/diem-framework/modules/DiemAccount.move, language/diem-framework/modules/doc/DesignatedDealer.md, language/diem-framework/modules/doc/DiemAccount.md
Some specs were broken in an earlier PR.  The break was detected by @mengxu-fb.  This PR fixes the specs.
Yes.
Only specs are updated.  No changes to executable Diem Framework code.
=> [diem-framework] fix some broken specs

execution/executor-benchmark/src/lib.rs, execution/executor/src/lib.rs
To highlight cost in and outside of the VM.
Y
used locally to evaluate performance gain from some optimizations I'm doing.
=> executor benchmark: report total vm/executor/commit time

language/move-model/src/lib.rs, language/move-prover/bytecode/tests/from_move/regression_generic_and_native_type.exp
=> [move-prover] Remove now obsolete hack to work around deps problem.

testsuite/cluster-test/src/experiments/compatibility_test.rs
Update the compatibility test to test the compatibility between full nodes and validators. The cluster test will now test following:
1. Upgrade one full node and send it some transactions to make sure it can talk to old validator node's mempool and state sync correctly.
2. Upgrade half validator nodes and send transactions to their corresponding full nodes to make sure old full node image can talk to new validator nodes' mempool and state sync. This will also guarantee that the old validator node can reach consensus with new validator nodes
3. Upgrade the rest half of validator nodes and send transactions to these upgraded nodes. This will make sure mempool is working correctly for all new validator nodes.
4. Upgrade the rest half of full nodes and send transactions to these nodes. This …
=> [cluster-test] Update compatibility tests for full nodes.

Cargo.lock, client/json-rpc/Cargo.toml, client/json-rpc/src/broadcast_client.rs, client/json-rpc/src/lib.rs, sdk/client/src/client.rs, sdk/client/src/request.rs
=> Create Broadcast Client 2

network/src/peer_manager/mod.rs
In my investigation of how to check that a node is up on its own, I found this fun nugget.  We're basically hoping that we accidentally don't dial ourselves which would crash the node.  That or, for some reason two nodes have the same peer id.
In the event of a self dial, send a disconnect and drop the connection, rather than crash the node with an assert.
=> [network] Drop incoming self dials

.github/workflows/daily.yml
- Updated the `daily.yml` github workflow to daily perform the inconsistency check for Prover
To regularly preform the inconsistency check for Prover
Yes
cargo test
=> [move-prover] Add the Prover inconsistency test to the daily test routine

language/move-prover/tests/sources/functional/strong_edges.exp, language/move-prover/tests/sources/functional/strong_edges.move
Add functional tests for strong edges
Yes
=> [move-prover] functional tests for strong edges

client/assets-proof/src/README.md
Proof of Assets functionality
YES
Not required
=> AssetsProof readme

specifications/transactions/README.md
pulling and revising content from here https://docs.google.com/document/d/1YepqEoQUKMgB2HKS24VPCaf74Qa-u1aseqivhKn43Go/edit#
first step in #8045 
[Rendered](https://github.com/davidiw/libra/blob/spec/specifications/transactions/README.md)
=> initial transfer transaction spec

developers.diem.com/docs/move/structs-and-resources.md
=> [Docs] Typo fix in move docs

specifications/transactions/README.md, specifications/transactions/onchain/README.md
Defines the onchain portion for all the sufficiently well-defined DIPs and frameworks
next step in this https://github.com/diem/diem/issues/8045
=> onchain spec

.github/workflows/ci-test.yml
Add the missing step to fetch past refs so that LBT can look up base_ref.
Canary https://github.com/diem/diem/runs/2240245638?check_suite_focus=true
=> [lbt] add missing checkout step in image lookup

.github/workflows/daily.yml
More cargo-toolchain cleanup.
Yes
CI
None
=> [gha] use standard cargo

specifications/transactions/README.md, specifications/transactions/offchain-identity/README.md
well there's only one off-chain identity for now and that's subaddresses
so this is a tidied down version of DIP-5 --- considering that DIP-5
isn't finalized, I may push this back into DIP-5.
#8059
=> describes off-chain identity for transactions

.github/actions/build-setup/action.yml, .github/workflows/ci-publish-base-image.yml, x.toml
The last? of the cargo/rustc version cleanup.
Yes
CI
None.
=> [gha] more cargo/rustc version cleanup

language/tools/disassembler/src/disassembler.rs
Abilities syntax is ready, update disassembler accordingly. Originally disassembler panic-ed at DiemAccount.move with "unsupported ability set", found by @wrwg in #8127.
Yes
`cargo xtest`
#8127
=> [disassembler] format abilities, deprecate kind

testsuite/cli/src/client_proxy.rs
This PR aims to fix the issue mentioned [here](https://community.diem.com/t/how-to-compile-publish-modules-using-diem-cli-client-connected-to-a-local-test-validator-network/3534). The current cli can't get the account for diem_root account or tc account, causing functionalities like module publishing to fail.
Yes
Tested the module publishing flow via following command:
```
diem% dev c 0000000000000000000000000a550c18 <PATH_TO_MODULE>
diem% dev publish 0000000000000000000000000a550c18   <PATH_TO_COMPILED_MV>
```
=> [cli] Fix the logic for fetching diem_root account in the cli.

storage/scratchpad/src/sparse_merkle/node.rs
=> correct typo in node.rs

.github/workflows/docker-publish.yml
=> [gha] fix typo in env

.github/workflows/ci-test.yml
=> [cluster-test] disable debug log in LBT test

docker/ci/github/Dockerfile, docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/faucet/Dockerfile, docker/init/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
Upgrade debian base image across all debian based docker containers.
yes
CI
All dependabot docker prs open now.
=> [docker] debian base image update

Cargo.lock, storage/scratchpad/Cargo.toml, storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
further parallelize batch_update api in smt with another 4x speedup.
Y
current coverage.
=> [smt] Parallelize smt batch update with rayon::join

storage/scratchpad-benchmark/src/main.rs, storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
fix a missed rayon::join and a test.
without this rayon we get 4x slow down.
Y
=> [smt] added missed rayon::join() and some fixes

CHANGELOG/CHANGELOG-1.2.md, language/RELEASES.md
I plan to update this later with links to the descriptions of new language features, and we might also add more detailed notes on changes to the Prover, but this is a good start to describe what is new in version 1.2.
Documenting what's new for Move in version 1.2
Yes
=> [language] add Move release notes for version 1.2

language/move-lang/src/expansion/dependency_ordering.rs
The code for building a dependency graph does not add nodes for modules with no dependencies. Such modules will be each assigned a `dependency_order` of 0. Each module with dependencies has a unique `dependency_order`, so it's probably good to enforce this invariant for all modules.
This PR achieves this by adding a node to the dep graph for modules with no dependencies.
=> [move-lang] ensure that `dependency_order`  is unique for each module

language/move-lang/src/parser/ast.rs, language/move-lang/src/parser/syntax.rs, language/move-model/src/ast.rs, language/move-model/src/builder/exp_translator.rs, language/move-model/src/spec_translator.rs, language/move-model/src/ty.rs, language/move-model/tests/sources/quantifiers_ok.move, language/move-prover/boogie-backend-exp/src/boogie_helpers.rs, language/move-prover/boogie-backend-exp/src/bytecode_translator.rs, language/move-prover/boogie-backend-exp/src/spec_translator.rs, language/move-prover/boogie-backend/src/spec_translator.rs, language/move-prover/bytecode/src/livevar_analysis.rs, language/move-prover/bytecode/src/mono_analysis.rs, language/move-prover/tests/sources/functional/choice.exp, language/move-prover/tests/sources/functional/choice.move
Often times in the Diem specs we need to choose a value from a collection of values (typically a vector) which satisfies a certain predicate. Sometimes we also need to choose the smallest index into a vector s.t. a predicate is fullfilled. This PR introduces two choice operators which supports this.
For example, to choose a value in a vector we use this syntax:
```
choose v in vec where v.addr == validator_addr
```
To choose the smallest index we use:
```
choose min  i in 0..len(vec) where vec[i].addr == validator_addr
```
In general, the some/min keyword is followed by a single variable declaration which supports the same features as in quantifiers (`x in v` or `x: T`), followed by a `where` and a predicate.
Choices can use memory and refer to aribtrary variables in the context, …
=> [move-prover] Introduce choice operator for spec language.

storage/diemdb/src/pruner/mod.rs
After a DB restore, least_readable_version was initialized as 0 since there's no stale indices in the DB, while the target_least_readable_version is non zero, which result in the current code thinking there's still deletions to do and it keeps recv()ing comamnds in non-blocking mode, which results in a busy loop, showing as the pruner using 100% CPU of its thread on the dashboard.
Y
On testnet.
=> [pruner] fix busy looping after db-restore

json-rpc/types/src/views.rs
1. To keep consistent behavior when output null value field.
2. Current Rust jsonrpc types generated from protobuf definition does not accept field value == null case for a string type; this change avoids the problem for the client.
Yes
Unit Test
=> [json-rpc]: remove the json field metadata if the value is null

.github/workflows/transaction-replay.toml, storage/backup/backup-cli/src/storage/command_adapter/azure.sample.toml
replicating https://github.com/diem/partners/pull/878
Y
in prod. (verified in prod already)
https://github.com/diem/partners/pull/878
=> [backup] update azure config to filter out azcopy garbage outputs

config/management/operational/src/keys.rs
Embarrassingly enough, I spent a half hour trying to figure out why my copied key didn't work, and it was because there was a new line at the end.
Yes
Manual testing
=> [operational-tool] Make Key file reads trim whitespace

testsuite/cli/src/client_proxy.rs, testsuite/cli/src/dev_commands.rs
Create a command in cli to submit a writeset reading from a path.
Yes
Executed following command in cli:
`dev ws <GIT_ROOT>/language/diem-tools/writeset-transaction-generator/release/release-1.2.0-rc0.blob`
=> [cli] Create a command to submit writeset reading from path for cli.

docker/tools/Dockerfile
Add `curl` to support backup/restore on Oracle cloud.
=> [docker] Add curl to tools image

language/move-prover/tests/sources/regression/mono_after_global_invariant.move
Kindly refer to the test case and the comments inside for details.
Yes
CI (although the case should not verify)
=> [move-prover] test case on a potential issue with type quantifier elimination

json-rpc/Cargo.toml, json-rpc/src/fuzzing.rs, json-rpc/src/lib.rs, json-rpc/src/tests/mod.rs, json-rpc/src/tests/unit_tests.rs, json-rpc/src/tests/utils.rs
Breaking out changes from https://github.com/diem/diem/pull/8307 . Refactor of testing helper methods in order to use them in tests in https://github.com/diem/diem/pull/8307 .
yes
No functional changes- all existing tests should pass 
https://github.com/diem/diem/pull/8307
=> [RPC] Break out testing utils from unit tests

language/move-model/src/lib.rs
- Changed logic to rely on the 'move_continue_up_to' API and parse only once
- Changed filtering logic as a result
- Fixing a bug exposed on #8394. The filtering logic does not work quite right if there are modules defined over multiple files. 
- Just an implementation detail change. Relying on CI
=> [move-model] Only parse once

.github/workflows/ci-test.yml, .github/workflows/weekly.yml, scripts/weekly-dep-report.sh
A cron job to generate weekly report on dependency changes in this project and post to Slack channel.
Yes
1. making an assumption this repo contains at least two commits and commits span across at least two weeks.
2. There can be zero, one, or more than one commits in the last seven days from the time of running the script. The dependency change analysis needs to be tested in all the three cases.
3. Dependency can change, increase, or decrease. The dependency change analysis needs to be tested for all the three cases. 
4. CI workflow need to be tested - i) running each Monday at 14:14, ii) generating guppy report on latest commit and last commit from last week, iii) posting to Slack channel
=> [dependencies] [ci] Add a CI action to post weekly dependency report to Slack

docker/compose/README.md, docker/compose/monitoring/docker-compose.yaml, docker/compose/public_full_node/docker-compose.yaml
David likes his consistency.
So rename the docker compose file, and people using it will have to rename the file.
Also update the readme instruction with a bit more details.
=> [docker-compose] rename file name for consistency

common/time-service/src/lib.rs
Sleep doesn't do anything, unless you use it.
Yes
=> [time-service] Ensure sleep outputs are being used

config/management/operational/src/test_helper.rs, network/src/peer_manager/mod.rs, testsuite/diem-swarm/src/swarm.rs, testsuite/smoke-test/src/full_nodes.rs
I needed similar functionality in a different test, so I fixed this bug while I'm at it.
yes
E2E test now properly tests that no public connections can be made
Resolves https://github.com/diem/diem/issues/8409
=> Fix inbound connection limit

language/changes/4-unit-testing.md
Adds a language changelog entry for unit testing in Move
=> [language/changelog] Add changelog entry for Move unit tests

.github/workflows/weekly.yml
The CI action on posting dependency change report on Slack needs to be run on Friday morning. 
Yes
Wait for Friday.
=> [ci] changing CI action time for weekly dependency report

consensus/src/metrics_safety_rules.rs
Previously we perform initialize on NotInitialized error in https://github.com/diem/diem/pull/5033
but there's edge case that IncorrectEpoch could result in the same pattern (unable to vote until next epoch).
This PR extends it to handle IncorrectEpoch as well (and has a small refactor to make code more readable).
* Comprehensive test results that demonstrate the …
=> [safety rules] support retry on incorrect epoch

language/changes/3-abilities.md
=> [changelog] Add another name considered for abilities: kinds

docker/compose/README.md, docker/compose/data-restore/docker-compose.yaml, docker/compose/data-restore/s3-public.toml
Add docker-compose to do data restore
Yes
- run `docker-compose up -d` (used association mainnet S3 bucket for testing)
- check the log of the restore job, make sure it's making progress
- After restore, start a fullnode to use the data volume
=> [docker-compose] add data restore docker compose

language/move-prover/boogie-backend/src/boogie_wrapper.rs
Currently the prover collects three types of errors from Boogie:
- verification errors
- inconclusive errors
- inconsistency errors
In addition, in the collector for verification errors, there is a check
that if an error message does not belong to other known categories of
errors, it will mark the error message as an unknown boogie error.
Unfortunately the filter is not working now (maybe because Boogie has
changed the output format), leading to error messages being marked as
unknown (while they should be marked as inconclusive).
This commit re-organized the error parsing logic and uses the REGEX
patterns consistently for both early filtering as well as actual error
parsing.
Fix the daily CI
Yes
```
cd language/move-prover
mvp --dependency=../move-stdlib/modules …
```
=> [move-prover] fix error filtering in boogie-wrapper

devtools/x/src/test.rs
Fix this broken fuzzing coverage (ignores some crates which isn't allowed in builds like it is in cargo test).
Yes
CI
None
=> [circleci] fix fuzzing tests.

docker/forge/Dockerfile, scripts/dev_setup.sh
Install `helm` in the `forge` docker image. Helm is installed in the same way as in `dev_setup.sh`: https://github.com/diem/diem/blob/main/scripts/dev_setup.sh#L25
Yes
Codebuild
=> [docker] install helm in forge docker build

language/move-prover/boogie-backend/src/boogie_helpers.rs, language/move-prover/boogie-backend/src/prelude/native.bpl, language/move-prover/boogie-backend/src/prelude/prelude.bpl
=> [move-prover] Qualify module names by address in Boogie output

specifications/network/README.md, specifications/network/handshake-v1.md, specifications/network/messaging-v1.md, specifications/network/network-address.md, specifications/network/noise.md, specifications/network/onchain-discovery.md
Network spec fix more broken links.  Reviewed TODOs
=> Network spec fix more broken links, add line breaks for ease of future updates

.github/workflows/post-land.yml
Fix git rev-parse issue in the post-land workflow (ex https://github.com/diem/diem/actions/runs/962412599). 
Yes
Canary https://github.com/diem/diem/actions/runs/963513282
=> [gha] increase fetch depth in checkout

.github/workflows/ci-test.yml
Fix cluster test?
Yes
CI
None, or all of them?
=> [gha] fix cluster test.

.github/workflows/ci-publish-base-image.yml, .github/workflows/ci-test-complete.yml, .github/workflows/ci-test.yml, .github/workflows/ci-update-sccache.yml, .github/workflows/docker-publish.yml, scripts/dev_setup.sh
Allure2 had issues displaying flaky tests -- fixed by using a fork with an open pr applied to the current head revision of allure.
Need an updated action further tweak nextest output for allure2 consumption.   
Yes
Local tests comparing test results, and examining final reports by running the recent allure version over transformed output.
None
=> [gha] allure2 tests will now report flaky test results.

.github/workflows/ci-publish-base-image.yml, .github/workflows/ci-test-complete.yml, .github/workflows/ci-test.yml, .github/workflows/ci-update-sccache.yml, .github/workflows/daily.yml, .github/workflows/docker-publish.yml, .github/workflows/post-land.yml
This cherry-pick includes #8614, #8594, #8572, #8633
> Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
This affects only CI workflow.
> Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
CI + Canary https://github.com/diem/diem-private/actions/runs/966116986
> Why we must have it for V1 launch.
Be able to run perf test in release branch after cherry pick lands. Be able to run same workflow in private clone. 
> What workarounds and alternative we have if we do not push the PR.
Run tests manually.
=> Cherry-pick PR #8614 into release-1.3: [gha] increase fetch depth in checkout

Cargo.lock, language/move-prover/interpreter/crypto/Cargo.toml
This was a blind copy of the diem-cryto crate but many deps are not
actually needed here. This is a clean up.
clean-up for maintainability. See comments from @bmwill on #8598
Yes
CI
=> [stackless-vm] clean-up unused deps in the crypto lib

language/move-binary-format/src/check_bounds.rs
Address review comments left when these `unwrap_or(&[])` were introduced. Replace them with something that more closely resembles idiomatic Rust code.
Yes.
The existing test suite covers the code here.
Responds to review comments left on #8536.
=> [move] Clean up `unwrap_or(&[])` in bounds checker

language/documentation/book/src/SUMMARY.md, language/documentation/book/src/friends.md, language/documentation/book/src/functions.md, language/documentation/book/src/modules-and-scripts.md
- Added a new `friends.md` section for the syntax of friend declarations
- Extended the visibility subsection in `functions.md`
Update docs
Yes
mdbook build + eyes
=> [move documentation] update Move book for visibilities

language/move-vm/runtime/src/loader.rs
Remove usages of deprecated method `CompiledScript::into_module` from the Move VM loader, instead using `BinaryIndexedView` where necessary to access either module or script.
=> [move] Remove `into_module` from loader

devtools/x/src/installer.rs
Devs reporting problems with cargo install of sccache.
Yes
Meh
None
=> [x] force install cargo tools

language/move-vm/runtime/src/loader.rs
- Current error makes deserialization bugs hard to debug
- cargo x test
- Just logging change. The message is never stored
=> [move-vm-runtime] Improve logging around deserialization of modules

consensus/safety-rules/src/fuzzing_utils.rs, consensus/safety-rules/src/local_client.rs, consensus/safety-rules/src/safety_rules.rs, consensus/safety-rules/src/serializer.rs, consensus/safety-rules/src/t_safety_rules.rs, consensus/safety-rules/src/tests/suite.rs, consensus/src/metrics_safety_rules.rs, consensus/src/round_manager.rs, testsuite/diem-fuzzer/src/fuzz_targets/safety_rules.rs
1. return signature instead of full block
2. avoid updating preferred round (it's not related to safety)
=> [safety-rules] latency optimization

scripts/dev_setup.sh
Don't waste time on all jobs re-installing dotnet/golang if we don't have to.
Yes
CI
None
=> [dev_setup.sh] checks around golang/dotnet install

consensus/src/state_computer.rs
=> [execution] remove mutex after interior mutability

consensus/src/experimental/ordering_state_computer.rs, consensus/src/experimental/tests/execution_phase_tests.rs, consensus/src/experimental/tests/mod.rs, consensus/src/experimental/tests/ordering_state_computer_tests.rs, consensus/src/test_utils/mock_state_computer.rs, consensus/src/test_utils/mod.rs, execution/executor-types/src/lib.rs
Add unit tests for ordering_state_computer and execution_phase.
=> [decoupled-execution] Integration Part 4 - More tests

docker/ci/github/Dockerfile, docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/faucet/Dockerfile, docker/forge/Dockerfile, docker/init/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
Keep debian base images up to date.
Yes
CI
Open dependabot docker prs.
=> [docker] debian baseimage update

language/move-binary-format/src/normalized.rs
- Address minor issue with From<TypeTag>
- cargo test/cargo check. Doesn't seem to be used?
#8789
=> [move] Nits from #8789

.github/workflows/daily.yml, .github/workflows/weekly.yml
As discussed in #8644, the transaction-replay job is moved to weekly.
CI
=> [gha] run transaction-replay test on weekly

language/move-vm/runtime/src/loader.rs, language/move-vm/runtime/src/runtime.rs, language/move-vm/runtime/src/session.rs
Implement a type resolver public api for `Session` to help the `read-write-set` tooling. Removed a number of unneeded `mut` operations.
Yes
`cargo check`
=> [move-vm] Implement an external api for Loader.

language/move-vm/runtime/src/loader.rs
This commit is the first step towards refactoring the module loading
logic in the Move VM loader.
We model the dependency relations of the modules in the storage as a
directed graph G:
- each module is a node
- There are two types of edges G:
- Dep edge: A -d-> B, means that module A depends on B (by calling a
function in B or using a type defined in B)
- Friend edge: A -f-> B, means that module A declares that B is a
friend of A
We further define some notion about G:
- A dep closure of module A, denoted as D(A), is the set of modules in
G that are reachable from A by following **only** the dep edge -d->
- A complete closure of module A, denoted as C(A), is the set of modules
in G that are reachable from A by following both the dep edge and the
friend edge.
- Additionally, we define that …
=> [move-vm] refactor the module loading logic

language/move-symbol-pool/src/pool.rs, language/move-symbol-pool/src/symbol.rs
- Added str deref
- Added Cow optimization for owned strings
- Fixed ser/de
- deref improves the usability of symbols, with things like `sym.starts_with('_')` now being possible without an explicit `as_str()`
- `Cow` removes a useless clone in the `String`/`owned` case 
- ser/de was incorrect 
- Ran tests
=> [move-symbol-pool] Minor improvements

language/changes/6-phantom-type-params.md
Adds language changelog entry for phantom types
=> [language] Add changelog for phantom types

language/move-lang/functional-tests/tests/move/dependencies/pack_unpack_private.exp, language/move-lang/tests/move_check/typing/pack_unpack_private.exp, language/move-lang/tests/move_check/typing/pack_unpack_private.move
- Moved a functional test to a move-check test
- Test was flaky as a functional test
Ran tests
=> [move-lang] Quick test fix

execution/executor/src/lib.rs, state-sync/src/executor_proxy.rs
Reconfig events were the only ones coming out of execution, let's make it so we can access other events, and just filter later
Yes.
Run the current tests, as no functionality really should have changed
=> [execution] Output all events not just reconfig events

Cargo.lock, Cargo.toml, language/bytecode-verifier/transactional-tests/Cargo.toml, language/bytecode-verifier/transactional-tests/src/lib.rs, language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_bad.exp, language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_bad.mvir, language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_ok.exp, language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_ok.mvir, language/bytecode-verifier/transactional-tests/tests/tests.rs, language/testing-infra/transactional-test-runner/src/vm_test_harness.rs, language/testing-infra/transactional-test-runner/tests/vm_test_harness/example.exp, x.toml
- Added two tests to start (small example for this PR)
- Improved VM error printing
- Just a small initial API to show others how we might use this thing (cc @modocache)
- Ran the tests
- Waiting on #8766
=> [transactional tests][bytecode verifier] Start bytecode verifier test migration     

language/RELEASES.md
I reviewed the Move changes in the 1.4 release and produced this set of release notes.
Yes
Viewed formatted Markdown
=> [language] add Move release notes for version 1.4

.github/workflows/dep-update-review.yml
Specify `depdive=0.1.0` in `dep-update-review.yml`
Yes
=> [ci] use depdive=0.1.0

language/move-prover/doc/user/spec-lang.md
Update docs for changes made in #8890 
Keep our docs updated
Yes
CI
=> [move-prover] update spec lang doc on loop invariants

.github/workflows/daily.yml
=> [ci] update active branches

docker/ci/github/Dockerfile, docker/client/Dockerfile, docker/cluster-test/Dockerfile, docker/faucet/Dockerfile, docker/forge/Dockerfile, docker/init/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
Upgrade all debian base images to the latest release.
Yes
CI
All open debian dependabot issues.
=> [docker] new debian base image

.github/workflows/ci-post-land.yml, .github/workflows/ci-test.yml
Clean up straggling issues in the ci/cd pipeline.   get rust docs running again.
Yes
CI
None
=> [gha] fix up rustdoc for consistence & correct trigger.  Fix up lint to not rerun on bors land.

testsuite/forge/src/backend/k8s/swarm.rs
Implements `K8sSwarm::logs_location`. We don't have a logging setup yet to collect logs from all forge clusters, so for now return a `kubectl logs` command to retrieve the cluster logs before the pod is cleaned up.
This prevents forge k8s tests from panicking at the end 🙂 
Yes
Run forge and avoid panic for not implemented
```
$ ./scripts/fgi/run --pr 9004 -W rustietest
```
=> [forge] implement logs_location for k8s swarm

json-rpc/types/src/views.rs
1. protobuf generated Rust client code expects no null values for string types.
2. consistent with other view fields, remove the null values in JSON output.
Unit test
#8319
=> [json-rpc]: remove null values when serializing Views to JSON

Cargo.lock, common/workspace-hack/Cargo.toml
https://github.com/diem/diem/issues/9010
https://rustsec.org/advisories/RUSTSEC-2021-0093
y
dependency update
existing tests
Vulnerability seems real.
Wait for 1.5 roll.
=> [RUSTSEC-2021-0093][rel-1.4] crossbeam-deque 0.8.0 -> 0.8.1

Cargo.lock, common/workspace-hack/Cargo.toml
https://github.com/diem/diem/issues/9009
https://rustsec.org/advisories/RUSTSEC-2021-0093
y
dependency update
existing tests
Vulnerability seems real.
Wait for 1.5 roll.
=> [RUSTSEC-2021-0093][rel-1.3] crossbeam-deque 0.8.0 -> 0.8.1

consensus/src/experimental/linkedlist.rs, consensus/src/experimental/mod.rs
=> [decoupled-execution] add linked list for the buffer manager.

developers.diem.com/docs/governance.mdx, developers.diem.com/docs/welcome-to-diem.mdx
=> incorporate christy's comments

consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/commit_phase.rs, consensus/src/experimental/ordering_state_computer.rs, consensus/src/experimental/tests/commit_phase_tests.rs, consensus/src/experimental/tests/ordering_state_computer_tests.rs, consensus/src/experimental/tests/test_utils.rs
=> [decoupled-execution] process incoming ordered blocks and sync requests

developers.diem.com/docs/technical-papers/publication-archive.mdx, developers.diem.com/docs/technical-papers/state-machine-replication-paper.md
=> Fix broken doc link

state-sync/inter-component/consensus-notifications/src/lib.rs, state-sync/inter-component/mempool-notifications/src/lib.rs
This (small) PR offers some simple cleanups to the notification listener tests. Specifically, we're removing usage of the `notification_receiver` in the tests so that the `notifiers` are tested in a way that is consistent with production. Not a significant change, but it makes things cleaner.
Yes.
The existing unit tests cover these changes.
=> [State Sync] Small cleanups to notification listener tests.

consensus/src/experimental/buffer_item.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/execution_phase.rs, consensus/src/experimental/linkedlist.rs, consensus/src/experimental/mod.rs, consensus/src/experimental/persisting_phase.rs, consensus/src/experimental/pipeline_phase.rs, consensus/src/experimental/signing_phase.rs, consensus/src/experimental/tests/execution_phase_tests.rs
1. refactor buffer items.
2. execution phase logic.
3. remove the buffer diagram as the current design is extremely simple.
* What workarounds and alternative we have if …
=> [decoupled-execution] buffer manager execution phase logic

consensus/src/round_manager.rs
=> [consensus] make the optionally compiled code more obvious

.github/workflows/ci-test.yml, docker/build_push.sh, scripts/fgi/kube.py, scripts/fgi/run, testsuite/forge/src/txn_emitter/mod.rs
=> [Forge] Add forge LBT in ci-test

common/logger/src/diem_logger.rs, common/logger/tests/remote.rs
Allow configuring what logs get sent to the remote logging service by respecting the `RUST_LOG_REMOTE` environment variable. If `RUST_LOG_REMOTE` is not set then fall back to look at the normal `RUST_LOG` environment variable.
=> logger: allow configuring what logs get sent to the remote logging service

storage/diemdb/src/lib.rs, storage/diemdb/src/schema/mod.rs, storage/diemdb/src/schema/transaction_by_hash/mod.rs, storage/diemdb/src/schema/transaction_by_hash/test.rs
add a new cf for indexing txn by hash
Y
run diemdb-benchmark to open db.
=> [diemdb] add transaction_by_hash cf

common/logger/src/diem_logger.rs, common/logger/tests/remote.rs
This cherry-pick was triggerd by a request on #9181
> Allow configuring what logs get sent to the remote logging service by respecting the `RUST_LOG_REMOTE` environment variable. If `RUST_LOG_REMOTE` is not set then fall back to look at the normal `RUST_LOG` environment variable.
cc @bmwill
Intended to be 1 part of the longer term fix for this [SEV4](https://libra.pagerduty.com/incidents/P8VQYAA)
This enables configuring the logging filter, at start up, that should be applied to logs generated to be sent to the Associations central logging service. Today this can only be configured manually at runtime and …
=> Cherry-pick PR #9181 into release-1.4: logger: allow configuring what logs get sent to the remote logging service

consensus/src/experimental/buffer_item.rs, consensus/src/experimental/buffer_manager.rs
`process_sync_request` now tries to advance a buffer item to aggregated
Pop a prefix of buffer items if found an aggregated item.
* What workarounds and alternative we …
=> [decoupled-execution] process_sync_req now tries to advance a buffer item to aggregated

consensus/src/experimental/buffer_item.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/execution_phase.rs, consensus/src/experimental/persisting_phase.rs, consensus/src/experimental/pipeline_phase.rs, consensus/src/experimental/signing_phase.rs, consensus/src/experimental/tests/execution_phase_tests.rs
=> [decoupled-execution] more cleanups

language/move-prover/docgen/src/docgen.rs
- Extended `docgen` to generate the backward call graph diagrams of the functions in the DiemFramework
- Hopefully, these graphs should be useful when refactoring the code/spec of the Diem Framework.
- Demo
- unfold "Show all the functions that call "restore_withdraw_capability"" in the following link:
- https://github.com/junkil-park/diem/blob/diagram-demo/language/diem-framework/DPN/releases/artifacts/current/docs/modules/DiemAccount.md#function-restore_withdraw_capability
To generate the backward call graph diagrams for the Diem Framework documentation
Yes
cargo test
=> [move-prover] Generate the backward call graphs for the Diem Framework documentation

api/src/accounts.rs, api/src/test_utils.rs, api/types/Cargo.toml, api/types/src/address.rs, api/types/src/error.rs, api/types/src/lib.rs, api/types/src/move_types.rs
#9193 get account modules API.
Endpoint URL path: `/accounts/<address>/modules`
Returns a list of MoveModule JSON object.
The MoveModule object includes module exposed functions (including friend functions), structs and and friend modules.
Example module JSON:
```JavaScript
{
"address": "0x1",
"name": "DiemConfig",
"friends": [
{
"address": "0x1",
"name": "DiemConsensusConfig"
},
{
"address": "0x1",
"name": "DiemSystem"
},
{
"address": "0x1",
"name": "DiemTransactionPublishingOption"
},
{
"address": "0x1",
"name": "DiemVMConfig"
},
{
"address": "0x1",
"name": "DiemVersion"
},
{
"address": "0x1",
"name": "RegisteredCurrencies"
}
],
"exposed_functions": [
{
"name": "get",
"visibility": "public",
"generic_type_params": [
{
"constraints": [
"copy",
"drop",
"store"
]
}
],
"params": [], …
```
=> [api] get account modules

language/move-binary-format/src/layout.rs, language/move-binary-format/src/normalized.rs
Fixes a few bugs in the move-binary-format resolver.
Yes
Those bugs were exposed in future read-write-set tests. Not sure how we should test them as unit tests for now..
=> [move-binary-format] A few bugfixes

testsuite/forge/src/backend/k8s/mod.rs
=> [forge] make genesis always uses pr tag image

docker/ci/arch/Dockerfile, docker/ci/github/Dockerfile, docker/client/Dockerfile, docker/faucet/Dockerfile, docker/forge/Dockerfile, docker/init/Dockerfile, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/validator/Dockerfile
lump all docker base image updates (#9284~#9292) in one.
CI + canary
=> [docker] update base image

consensus/src/epoch_manager.rs, consensus/src/experimental/buffer.rs, consensus/src/experimental/buffer_item.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/hashable.rs, consensus/src/experimental/linkedlist.rs, consensus/src/experimental/mod.rs, consensus/src/round_manager.rs
Replace the underlying data structure from double-linkedlist to an ordered dictionary
=> [decoupled-execution] change linkedlist to ordered dictionary

language/move-prover/doc/paper21/corrected_example-apx.tex
=> [move-prover][paper] Adding missing source

scripts/fgi/run
=> [forge] change test result rely on report instead of pod state

language/documentation/book/src/generics.md
I noticed a typo in #9263 and decided to do some minor editing of the surrounding text while I was fixing it. I don't think there are any substantive changes here.
Yes
I opened the doc in a MarkDown editor to make sure it renders correctly.
=> [move][doc] some editing of the new section on phantom types

Cargo.lock, common/id-generator/src/lib.rs, state-sync/diem-data-client/Cargo.toml, state-sync/diem-data-client/src/diemnet/mod.rs
Cleanup to use Id generator in last `AtomicU64` location.
Yes
Current unit tests
=> [state-sync-data-client] Use id generator

scripts/dev_setup.sh
This adds support for cvc5 to dev_setup, in preparation for a future move from cvc4 to cvc5
=> [move-prover] Add support for cvc5

.github/workflows/ci-test.yml, api/doc/openapi.yaml, api/src/index.rs, api/src/tests/index_test.rs, scripts/api_lint.sh
#9193 
1. support CORS for cross domain request
2. improve openapi docs
3. add a simple lint job to land build
=> [api] support CORS and improve docs

shuffle/cli/src/transactions.rs
After I rebased, transactions was failing due to this PR: #9571. I was using a key that didn't exist in the updated json. This PR fixes transactions 
=> [shuffle] shuffle transactions fixed bug

shuffle/move/examples/main/helpers.ts, shuffle/move/examples/main/mod.ts
Using the /transactions/signing_message in https://github.com/diem/diem/pull/9381, this PR adds the ability to invoke arbitrary script functions on chain without having the local codegen.
Yes
1. Inability to test TS against running node atm. Epic to be done un subsequent PR.
1. Manual QA
Potentially eliminates https://github.com/diem/diem/pull/9572.
=> [shuffle] console invokes script functions via dev api:

execution/executor/src/lib.rs
Task: #9629 
Clarify errors in state sync when syncing a transaction that should be discarded. I have added more metadata about the failure such as transaction, transaction output, whether or not they were reexecuted in [`replay_transactions_impl`](https://github.com/diem/diem/blob/662bfeba024bf6de5798f57ffd8a062e25cdf08a/execution/executor/src/lib.rs#L506), and I have updated the bail message so that it includes the transaction version, status code, and now has a message that reads "Syncing transactions that have already been committed."
We recently encountered an error (due to an old bug in the VM) where state sync tried to execute a transaction but the resulting transaction output indicated that the transaction should be discarded. Given that state sync only synchronizes committed …
=> [State Sync] Update the error message returned by the executor for failed transactions

.github/workflows/ci-test.yml
=> [forge] turn on Forge in ci-test

crates/transaction-emitter/Cargo.toml
=> Changed cargo edition of new emitter back to 2018

shuffle/cli/src/console.rs, shuffle/cli/src/shared.rs, shuffle/cli/src/test.rs
Shuffle console and shuffle test have repetitive code. This PR fixes that. 
=> [shuffle] DRY up shuffle console and shuffle test

testsuite/diem-fuzzer/README.md
=> [fuzzer] update command for generate coverage report

.github/workflows/ci-test.yml
=> [GHA] bump up timeout to 40mins

shuffle/cli/README.md
README is outdated and does not include a section for Genesis DevX. Update `shuffle/cli/readme.md`
Yes
=> [shuffle] update readme.md

shuffle/move/examples/main/devapi.ts
Matching the [Dev API v1](https://docs.google.com/document/d/1KEPnGGU3zg_RmN8V4r2ms_MFPwsTMNyK7jCUFygviDg/edit#heading=h.1d0eslj78a0p), add the ability to get a txn by a version number to the TS api.
Yes.
Manual QA
=> [shuffle] txn devapi can take version|hash

storage/jellyfish-merkle/src/node_type/mod.rs
The fuzzer expects schema decoding never panics, while it's no longer the case because #9304 called InternalNode constructor in decoding.
Y
Using corpus that failed the coverage test for branch 1.5, the failure was reproduced on main and not reproducable on this fix.
=> [storage] fix fuzzer for schema decoding

api/Makefile, api/README.md, api/doc/openapi.yaml
#9193 
Add task to test openapi specification using [schemathesis](https://github.com/schemathesis/schemathesis), which runs fuzzing test to all APIs based on openapi spec.
=> [api] test api specification

consensus/src/consensusdb/schema/block/test.rs, consensus/src/consensusdb/schema/quorum_certificate/test.rs, consensus/src/consensusdb/schema/single_entry/test.rs, storage/diemdb/Cargo.toml, storage/diemdb/src/schema/epoch_by_version/test.rs, storage/diemdb/src/schema/event/test.rs, storage/diemdb/src/schema/event_accumulator/test.rs, storage/diemdb/src/schema/event_by_key/test.rs, storage/diemdb/src/schema/event_by_version/test.rs, storage/diemdb/src/schema/jellyfish_merkle_node/test.rs, storage/diemdb/src/schema/ledger_counters/test.rs, storage/diemdb/src/schema/ledger_info/test.rs, storage/diemdb/src/schema/mod.rs, storage/diemdb/src/schema/stale_node_index/test.rs, storage/diemdb/src/schema/transaction/test.rs, storage/diemdb/src/schema/transaction_accumulator/test.rs, storage/diemdb/src/schema/transaction_by_account/test.rs, storage/diemdb/src/schema/transaction_by_hash/test.rs, storage/diemdb/src/schema/transaction_info/test.rs, storage/diemdb/src/schema/write_set/test.rs, storage/schemadb/Cargo.toml, storage/schemadb/src/schema.rs
In unit tests, test the same thing with the fuzzer but with smaller input.
This is sent separately so that the fix itself can be picked as a small change.
Y
adding test.
#9668
=> [storage] test_no_panic_decoding

crates/transaction-emitter/src/lib.rs
```
====json-report-begin===
{
"metrics": [
{
"experiment": "all up, gas price 1",
"metric": "submitted_txn",
"value": 286470.0
},
{
"experiment": "all up, gas price 1",
"metric": "expired_txn",
"value": 0.0
},
{
"experiment": "all up, gas price 1",
"metric": "avg_tps",
"value": 1193.0
},
{
"experiment": "all up, gas price 1",
"metric": "avg_latency",
"value": 3784.0
},
{
"experiment": "all up, gas price 1",
"metric": "p99_latency",
"value": 4550.0
}
],
"text": "Test runner setup time spent 251 secs\nall up, gas price 1 : 1193 TPS, 3784 ms latency, 4550 ms p99 latency, no expired txns"
}
====json-report-end===
2021-11-10T00:23:19.145819Z [main] INFO testsuite/cluster-test/src/main.rs:227 Experiment Result: Test …
```
=> [forge] fix gas price test with extra coins per account

.github/workflows/ci-post-land.yml, docker/docker_republish.sh, scripts/dockerhub_prune.sh
=> [GHA] Add forge repo for docker republish in ci-post-land

shuffle/cli/src/shared.rs
As we're ramping up to connect to Trove Testnet, I've refactored the Networks struct in shared.rs and added Trove Testnet information to the Networks.toml. 
=> [shuffle] updated Network struct to support Trove Testnet

diem-node/src/lib.rs
=> [shuffle] reduce the mempool poll_count in lazy mode

Cargo.lock, Cargo.toml, shuffle/cli/Cargo.toml, shuffle/cli/src/account.rs, shuffle/cli/src/console.rs, shuffle/cli/src/lib.rs, shuffle/cli/src/main.rs, shuffle/cli/src/shared.rs, shuffle/cli/src/test.rs, shuffle/integration-tests/Cargo.toml, shuffle/integration-tests/src/helper.rs, shuffle/integration-tests/src/lib.rs, shuffle/integration-tests/tests/shuffle-forge.rs, shuffle/move/examples/e2e/message.test.ts, testsuite/forge/src/interface/chain_info.rs, testsuite/smoke-test/src/scripts_and_modules.rs, testsuite/smoke-test/src/state_sync.rs, x.toml
Add shuffle forge integration tests to have end to end testing of shuffle's interaction with an actual node. Start with the happy path scenario:
1. project creation
1. account creation
2. project deployment
4. typescript end to end testing
Yes
`cargo xtest -p shuffle-integration-test`
=> [shuffle] forge test of happy path hello blockchain

shuffle/cli/src/test.rs
`shuffle test e2e` was using the wrong private key. This fixes that.
Yes
`shuffle test e2e`
=> [shuffle] test cmd loads correct key

state-sync/state-sync-v1/src/coordinator.rs
After we added the cache in mempool (https://github.com/diem/diem/pull/9722 ), there'd be a short period between db knows about the commit but mempool is not notified.
Ideally we could have a lightweight notification instead of this (notify all txns could take up to 100ms), but I'll leave that for later.
* Comprehensive test results that demonstrate the …
=> [mempool] revert the asynchronously mempool notification

consensus/src/epoch_manager.rs, consensus/src/round_manager.rs
Start to see the safety rules client not dropped and wait until timeout after https://github.com/diem/diem/pull/9732 since it only implicitly drops when the sender is dropped.
This commit adds oneshot ack so that the epoch manager waits the round manager to exit before start new one.
* Comprehensive test results that demonstrate the fix working and not …
=> [consensus] blocking on RoundManager shutdown

diem-move/diem-transaction-benchmarks/src/transactions.rs
Updated the benchmark suite to invoke the diem_vm api straight to avoid the extra logging&comparison overhead in the FakeExecutor. The api used previously would did lots of extra things and caused the perf numbers to regress. This PR will make sure the numbers are back to normal.
Yes
Did a `cargo bench`. Make sure the perf numbers aligns with our previous benchmark results:
```
peer_to_peer            time:   [265.94 ms 269.53 ms 274.04 ms]                       
change: [-57.065% -56.083% -54.997%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
Benchmarking peer_to_peer_parallel: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.7s.
peer_to_peer_parallel …
```
=> [transaction-benchmark] Change benchmark logic to use DiemVM api

api/Operation.md
=> [api] update metrics operation doc

Cargo.lock, crates/transaction-emitter/src/lib.rs, testsuite/forge-cli/src/main.rs, testsuite/testcases/Cargo.toml, testsuite/testcases/src/lib.rs, testsuite/testcases/src/reconfiguration_test.rs
```
Test Statistics: 
fixed-tps-test : 9 TPS, 1385 ms latency, 2500 ms p99 latency,no expired txns
performance::performance-benchmark : 1710 TPS, 2613 ms latency, 5550 ms p99 latency,no expired txns
gas-price-unit-1 : 1509 TPS, 2975 ms latency, 12100 ms p99 latency,no expired txns
partialNodesDown::10%-down : 1652 TPS, 2445 ms latency, 5000 ms p99 latency,no expired txns
Reconfiguration: total epoch: 101 finished in 1680 seconds
```
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link …
=> [forge] Add reconfiguration test in forge

language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
Not sure how it passed build, but when I build shuffle today, got compile error related to the changes in this PR.
cargo build
=> [move-cli] fix a compile error

shuffle/cli/src/account.rs, shuffle/cli/src/deploy.rs, shuffle/cli/src/dev_api_client.rs, shuffle/cli/src/lib.rs, shuffle/cli/src/main.rs, shuffle/cli/src/shared.rs, shuffle/cli/src/test.rs, shuffle/cli/src/transactions.rs, shuffle/integration-tests/src/helper.rs, shuffle/integration-tests/src/lib.rs
We want to replace all the hard coded json rpc invocations with dev api calls in accounts.rs. This pr achieves this. 
1. Run `cargo run -p shuffle -- new <project_path>` and `cargo run -p shuffle -- node`.
2. Run `cargo run -p shuffle -- console <project_path>`. You should get this output:
3. Run `cargo run -p shuffle -- account`.  You should get an output similar to this:
4. Rerun `cargo run -p shuffle -- console <project_path>`. You should get this output. Notice that the account address matches the one from the picture in 3. 
5. To check if we can deploy modules from the account,  run `cargo run -p shuffle -- deploy -p <project_path>`.
6. In your console repl, run `await.devapi.modules()`. You should get an output similar to this:
(If this PR adds or changes functionality, please take …
=> [shuffle] replace json rpc with api in account.rs

config/src/config/state_sync_config.rs
This (simple) PR adds a new config for the state sync driver. It also enables the existing configs required by state sync v2. Note: none of these configs are currently used. We're paving the way for testing!
Yes.
The existing unit tests will cover basic config functionality. Once we actually use these configs, they'll be tested.
=> [State Sync] Add simple config for state sync driver.

Cargo.lock, common/workspace-hack/Cargo.toml, language/tools/move-cli/src/package/cli.rs, language/tools/move-cli/tests/testsuite/package_basics/args.exp, language/tools/move-cli/tests/testsuite/package_basics/args.txt, language/tools/move-package/Cargo.toml, language/tools/move-package/src/resolution/resolution_graph.rs
=> Add support for printing in-scope named addresses and values from Move packages

Cargo.lock, execution/executor-benchmark/Cargo.toml, execution/executor-benchmark/src/main.rs, execution/executor/Cargo.toml, execution/executor/src/lib.rs, json-rpc/src/tests/genesis.rs, storage/diemdb/src/transaction_store/mod.rs, types/src/account_state.rs, types/src/account_state_blob.rs
=> [execution] misc perf improvements

shuffle/move/examples/main/repl_help.ts
CI missed deno lint errors on `repl_help.ts`
Yes
`deno lint shuffle/move/examples/main`
=> easy: [shuffle] Fix repl_help.ts deno lint errors

shuffle/move/examples/main/repl_help.ts
Updated the help messages to match the output of `await help.main()` and `await help.helpers()`.
1. Run `cargo run -p shuffle -- console -p <project_path>`
2. Run help in repl
=> [shuffle] updated repl_help

developers.diem.com/docs/basics/basics-txns-states.md
=> Fix a typo

Cargo.lock, common/workspace-hack/Cargo.toml, testsuite/cli/diem-wallet/Cargo.toml, testsuite/cli/diem-wallet/src/lib.rs
ChildNumber is not exposed so that new_address_at_child_number can't be used.
=> [diem-wallet] cleanup dependencies and interface

shuffle/move/examples/integration/devapi.test.ts, shuffle/move/examples/main/client.ts, shuffle/move/examples/main/context.ts, shuffle/move/examples/main/devapi.ts, shuffle/move/examples/main/mod.ts
Extracted out a diem client for shuffle use cases.
Kept devapi interface same to reduce changes for this PR.
=> [shuffle] extract out deno diem client from devapi

shuffle/cli/src/account.rs, shuffle/cli/src/console.rs, shuffle/cli/src/deploy.rs, shuffle/cli/src/main.rs, shuffle/cli/src/shared.rs, shuffle/cli/src/test.rs
This PR cleans up files where we hard code many latest and test paths.
=> [shuffle] clean up latest/test methods

.github/workflows/ci-test.yml, shuffle/move/examples/main/mod.ts
Comply with deno lint on the .ts files.
=> [shuffle] fix deno lint errors on main/mod.ts

shuffle/cli/tutorials/HelloBlockchain.md
=> fix formatting in hello blockchain tutorial

shuffle/move/examples/e2e/message.test.ts, shuffle/move/examples/main/helpers.ts, shuffle/move/examples/main/mod.ts, shuffle/move/examples/main/sources/nft/NFTTests.move
Add E2E test for transferring NFT between accounts. 
shuffle test unit
shuffle test e2e
=> [shuffle] Transfer NFT

api/src/index.rs, api/src/tests/index_test.rs
Unit tests, 
Manual test result:
=> [api] fix cors for accepting POST request with content-type header

testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/cluster_helper.rs, testsuite/forge/src/backend/k8s/mod.rs, testsuite/forge/src/backend/k8s/swarm.rs
```
./scripts/fgi/run -T dev_czh_pull_9897 -W forge-2 --suite land_blocking
```
```
test all up ... ok
Test Statistics: 
all up : 2181 TPS, 2030 ms latency, 3150 ms p99 latency,no expired txns
====json-report-begin===
{
"metrics": [
{
"test_name": "all up",
"metric": "submitted_txn",
"value": 523485.0
},
{
"test_name": "all up",
"metric": "expired_txn",
"value": 0.0
},
{
"test_name": "all up",
"metric": "avg_tps",
"value": 2181.0
},
{
"test_name": "all up",
"metric": "avg_latency",
"value": 2030.0
},
{
"test_name": "all up",
"metric": "p99_latency",
"value": 3150.0
}
],
"text": "all up : 2181 TPS, 2030 ms latency, 3150 ms p99 latency,no expired txns"
}
```
(If this PR adds or changes functionality, please take …
=> [forge] Add ability to commit txn through validators

shuffle/cli/README.md, shuffle/cli/src/console.rs, shuffle/cli/tutorials/HelloBlockchain.md, shuffle/cli/tutorials/HelloNFT.md, shuffle/move/examples/e2e/message.test.ts, shuffle/move/examples/integration/devapi.test.ts, shuffle/move/examples/integration/helpers.test.ts, shuffle/move/examples/main/devapi.ts, shuffle/move/examples/main/mod.ts
1) Added transfer e2e test tutorial for hello NFT
2) waitfortransfercompletion -> waitfortransfer 
3) Added nft type parameter to helper functions
4) Added move.ts access to console
=> [shuffle] Polish transfer NFT tutorial

language/documentation/tutorial/README.md, language/documentation/tutorial/step_1/BasicCoin/Move.toml, language/documentation/tutorial/step_1/BasicCoin/sources/FirstModule.move, language/documentation/tutorial/step_2/BasicCoin/Move.toml, language/documentation/tutorial/step_2/BasicCoin/sources/FirstModule.move, language/documentation/tutorial/step_2_sol/BasicCoin/Move.toml, language/documentation/tutorial/step_2_sol/BasicCoin/sources/FirstModule.move, language/documentation/tutorial/step_2_sol/solution_commands, language/documentation/tutorial/step_4/BasicCoin/Move.toml, language/documentation/tutorial/step_4_sol/BasicCoin/Move.toml, language/documentation/tutorial/step_5/BasicCoin/Move.toml, language/documentation/tutorial/step_5_sol/BasicCoin/Move.toml, language/documentation/tutorial/step_6/BasicCoin/Move.toml, language/documentation/tutorial/step_7/BasicCoin/Move.toml, language/documentation/tutorial/step_7_sol/BasicCoin/Move.toml
Refactors sections 1, 2, and 5 and updates to the code.
It also updates the address from `0xdeadbeef` to `0xcafe`.
Once #9934 lands this will need to be rebased on that.
=> [move-docs] Update step 1, step 2, and step 5

shuffle/cli/tutorials/HelloBlockchain.md
=> [shuffle] better account description in Hello Blockchain tutorial

json-rpc/Cargo.toml
Running individual tests like `cargo xtest -p diem-key-manager` doesn't build.
Y
=> [scratchpad] trivial: fix build

language/move-lang/src/command_line/compiler.rs, language/move-lang/src/diagnostics/codes.rs, language/move-lang/src/expansion/translate.rs, language/move-lang/src/to_bytecode/translate.rs, language/move-lang/src/unit_test/filter_test_members.rs, language/move-lang/tests/move_check/naming/assert_one_arg.exp, language/move-lang/tests/move_check/naming/assert_one_arg.move, language/move-lang/tests/move_check/naming/other_builtins_invalid.exp, language/move-lang/tests/move_check/naming/other_builtins_invalid.move, language/move-lang/tests/move_check/typing/pack_unpack_private_script.exp, language/move-lang/tests/move_check/typing/pack_unpack_private_script.move, language/move-lang/tests/move_check/unit_test/attribute_location_invalid.exp, language/move-lang/tests/move_check/unit_test/expected_failure_not_test.move, language/move-lang/tests/move_check/unit_test/expected_failure_not_test.unit_test.exp, language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.exp, language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.move, language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.unit_test.exp, language/move-lang/tests/move_check/unit_test/multiple_errors.unit_test.exp, language/move-lang/tests/move_check/unit_test/multiple_test_annotations.unit_test.exp, language/move-lang/tests/move_check_testsuite.rs
- Fixed move_check tests to do code generation even with warnings
- Fixed so code generation does not happen if there are any errors
- Fixed some bugs resulting from this change
#9987
#9907 
- Fixed tests 
- Added tests
=> [move-lang] Bug fixes associated with incorrect error gating

helm/fullnode/Chart.yaml, helm/fullnode/README.md, helm/fullnode/files/backup/azure.toml, helm/fullnode/files/backup/oci.toml, helm/fullnode/files/fullnode.yaml, helm/fullnode/templates/_backup.tpl, helm/fullnode/templates/fullnode.yaml, helm/fullnode/templates/restore.yaml, helm/fullnode/templates/service.yaml, helm/fullnode/values.yaml
Update fullnode helm chart
Yes
=> [helm] update fullnode helm chart

shuffle/cli/src/shared.rs, shuffle/cli/src/test.rs
Previously, a shuffle project's named address had to be Sender. Now it can be anything as long as the value is "_".
Before:
```
[addresses]
Sender = "_"
```
After:
```
[addresses]
ArbitraryOne = "_"
ArbitraryTwo = "_"
```
Yes
`cargo test -p shuffle`
=> [shuffle] Named Address no longer needs to be Sender

terraform/vault-init/.terraform.lock.hcl, terraform/vault-init/README.md, terraform/vault-init/backend.tf, terraform/vault-init/backend.tf.example, terraform/vault-init/backend.tfvars, terraform/vault-init/diem-root.tf.example, terraform/vault-init/kubernetes.tf, terraform/vault-init/main.tf, terraform/vault-init/policy.tf, terraform/vault-init/versions.tf
Open source the vault initialization terraform. 
Removed network keys for original setup.
Yes
Will validate with local node deployment
=> [tf][vault-init] add terraform for vault initialization

terraform/validator/azure/.terraform.lock.hcl, terraform/validator/azure/aad/aks-aad.tf, terraform/validator/azure/aad/aks-aad_override.tf, terraform/validator/azure/auth.tf, terraform/validator/azure/backend.tfvars, terraform/validator/azure/backup.tf, terraform/validator/azure/cluster.tf, terraform/validator/azure/cost_override.tf.example, terraform/validator/azure/dns.tf, terraform/validator/azure/kubernetes.tf, terraform/validator/azure/main.tf, terraform/validator/azure/network.tf, terraform/validator/azure/templates/bastion_user_data.cloud, terraform/validator/azure/templates/vault_user_data.sh, terraform/validator/azure/terraform.tfvars, terraform/validator/azure/variables.tf, terraform/validator/azure/vault.tf, terraform/validator/azure/vault_override.tf, terraform/validator/azure/versions.tf
Open source Azure terraform files for validator deployment
Yes
validate locally
=> [tf][azure] add terraform files for validator deployment in Azure

state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-v2/state-sync-driver/src/driver.rs, testsuite/smoke-test/src/state_sync_v2.rs
When a validator starts up, consensus waits to be notified by state sync that the node has bootstrapped. In order for state sync to bootstrap the validator, it relies on peers to make syncing progress. However, in a single validator deployment (e.g., for test environments), there are no peers, and thus state sync blocks indefinitely. To prevent this, this PR updates state sync to use a timeout. If no peers are identified within 10 seconds, and the validator has a genesis waypoint, state sync will automatically hand execution over to consensus.
1. First, we add a simple smoke test that tests a single validator deployment with a genesis waypoint. This test currently fails.
2. Next, we update state sync v2 to use a timeout when no peers are found. With …
=> [State Sync] Support single validator deployments with genesis waypoints.

language/evm/examples/Move.toml, language/evm/examples/README.md, language/evm/examples/sources/Evm.move, language/evm/examples/sources/Faucet.move, language/evm/examples/sources/Token.move, x.toml
This PR contains some rough experiments for a possible programming model for EVM in Move. Check the README.md for details.
This assumes some basic knowledge of EVM and Solidity (see e.g. the [Ethereum book](https://github.com/ethereumbook/ethereumbook)).
Move-on-EVM
Yes
NA
NA
=> [move][evm] Experiments for EVM Move Programming Model

execution/executor/src/tests/mod.rs
This function used in tests used to rely on the block executor interfaces which I'm gonna impose more restrictions about the input blocks, namely existence of a state checkpoint at the end of a block, so I'm steering away from it.
Y
=> [executor] run_transactions_naive more naive

execution/executor/src/tests/mod.rs
1. The constructor takes in a size, instead of a range (which is never useful)
2. expect that the resulting block size being different from the number of user transactions (because we are gonna append the state checkpoint txn)
Y
=> [executor] trivial: refactor TestBlock

execution/executor/src/components/chunk_output.rs, storage/storage-interface/src/state_view.rs
Love it being more explicit.
Y
=> [executor] refactor state_view.into() -> state_view.into_state_cache()

Cargo.lock, diem-move/diem-vm/src/diem_vm.rs, diem-move/diem-vm/src/parallel_executor/mod.rs, diem-move/diem-vm/src/parallel_executor/storage_wrapper.rs, diem-move/diem-vm/src/parallel_executor/vm_wrapper.rs, diem-move/e2e-tests/src/executor.rs, diem-move/e2e-testsuite/src/tests/parallel_execution.rs, diem-move/mvhashmap/Cargo.toml, diem-move/mvhashmap/src/lib.rs, diem-move/mvhashmap/src/unit_tests/mod.rs, diem-move/mvhashmap/src/unit_tests/proptest_types.rs, diem-move/parallel-executor/Cargo.toml, diem-move/parallel-executor/src/executor.rs, diem-move/parallel-executor/src/lib.rs, diem-move/parallel-executor/src/proptest_types/bencher.rs, diem-move/parallel-executor/src/proptest_types/tests.rs, diem-move/parallel-executor/src/proptest_types/types.rs, diem-move/parallel-executor/src/scheduler.rs, diem-move/parallel-executor/src/task.rs, diem-move/parallel-executor/src/txn_last_input_output.rs, diem-move/parallel-executor/src/unit_tests/mod.rs
Parallelize smart contract execution without pre-estimates.
Passes fake executor and unit tests.
TODO:
Create and bind tasks for future extensions.
Improve fake executor integration tests to write different access paths based on reads. 
* Comprehensive test results that demonstrate the fix working and not …
=> Move in parallel

.github/workflows/ci-post-land.yml, .github/workflows/ci-test.yml
Repoints CI to new cloud. Tested extensively in draft PR #10165
Removed unused client image reference in ci-post-land as it will always cause the workflow to fail.
Also closes #10170
=> [ci] repoint forge and ECR to new cloud
