diem/diem

mempool/src/shared_mempool.rs
right now SMP doesn't utilize multiple cores
this diff reverts to previous behavior when each sync request used to be a separate task
to prevent unbound concerns and potential OOMing semaphore is added
=> [mempool] shared mempool: spawn separate task for each sync request

config/config_builder/src/bin/libra-config.rs
Using `unwrap` makes things hard to debug.
Yes.
cargo test
=> [ConfigBuilder] Replace unwrap with expect and better error message

language/stdlib/modules/libra_account.mvir
Why is one `0x00` and the other `0x0`? Looks weird.
=> Consistent naming of `0x0`

benchmark/Cargo.toml, benchmark/src/bin/ruben.rs, benchmark/src/grpc_helpers.rs, benchmark/src/lib.rs, benchmark/src/ruben_opt.rs
With some randomly injected sleep, TXN submissions from multiple AC clients will be smoothed a bit.
User can control the upper bound of sleep duration by specifying `-g` or `--stagger_range_ms`.
The larger the value, the slower the request rate since TXNs are much spreading out.
Staggering is disabled for mint operations.
E2E test with two different `stagger_range_ms` cases
Case 1. no stagger at all
```
./target/release/ruben -f faucet_for_ruben -s temp_config -n 32 -c 64 -g 1
......
Dispatch a chunk of 16 requests to client and start to submit after staggered 0 ms.
Dispatch a chunk of 16 requests to client and start to submit after staggered 0 ms.
......
10 epoch(s) of TXN throughput = [(972.4596391263058, 311.5302707636142), (1057.8512396694214, 307.8773301262778), (870.0084961767204, …
```
=> [benchamrk] Let AC clients submit TXNs with slight time difference.

language/bytecode_verifier/src/absint.rs, language/bytecode_verifier/src/type_memory_safety.rs, language/functional_tests/tests/testsuite/commands/join_failure.mvir
If the bytecode verifier encounters a join failure, it should flag the module or script as unverified. It used to do this correctly, but a bug was introduced when switching over to the generic abstract interpreter. This diff fixes the bug by:
- Introducing an enum for `BlockPrecondition` that includes join failures 
- Changing the type/memory safety analysis to flag any join failures encountered during analysis.
In the future, we may want to get rid of the idea of a "join failure" altogether and report all errors at the instruction level instead.
New functional test that exhibits a join failure.
=> [language] report join failures in type and memory safety analysis

benchmark/src/bin/ruben.rs, benchmark/src/grpc_helpers.rs, benchmark/src/lib.rs
Implement the following wait TXNs mechanism: when an account's persisted sequence number on validator
equals its local sequence number manipulated in `Benchmarker`, all its TXNs are committed.
Therefore waiting for all TXNs is equivalent to waiting on all senders' sequence numbers to meet this condition.
Advantage over waiting on storage's committed_txns counter:
1. robustness: we can have test liveness from multiple `Benchenmarker`s, assuming mint operations from them are not overlapped.
2. finer granularity: we can extend easily to report per account throughput.
* E2E test with `libra_swarm`. Normal case everything is fine. Notice we divided accounts into 4 chunks and wait:
```
./target/release/ruben -f faucet_for_ruben -s temp_config -n 40 -c 4
......
Dispatch a chunk of 400 requests …
```
=> [benchmark] Implement per-account waiting mechanism.

language/functional_tests/tests/testsuite/natives/signature_ed25519.mvir, language/functional_tests/tests/testsuite/natives/signature_ed25519_bad_msg.mvir, language/functional_tests/tests/testsuite/natives/signature_ed25519_bad_pk.mvir, language/functional_tests/tests/testsuite/natives/signature_ed25519_bad_sig.mvir, language/stdlib/natives/src/signature.rs
Fixing native single signature verification as it used to parse the inputs in reverse order than expected. Also functional tests were silently failing, so the above fixed the LinkerError as well. 
Fixes in the following functional tests:
```
signature_ed25519.mvir
signature_ed25519_bad_msg.mvir
signature_ed25519_bad_pk.mvir
signature_ed25519_bad_sig.mvir
```
=> [crypto] Fix LinkerError in native signature verification

terraform/templates/dashboards/analytics.json, terraform/templates/dashboards/overview_dashboard.json, terraform/templates/dashboards/usage_stats.json
By utilizing "state_blobs_created" and "state_blobs_retired" gauges in
storage module.
These counters are written as absolute values upon storage commit while the old one is bumpped by relative value when the executor executes a block (a restart and resync makes it inaccurrate).
yes
query is verified to work in testnet prometheus:
http://prometheus.stable.aws.hlw3truzy4ls.com:9091/explore?left=%5B%22now-6h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22max(storage_gauge%7Bop%3D%5C%22state_blobs_created%5C%22%7D)%20-%20max(storage_gauge%7Bop%3D%5C%22state_blobs_retired%5C%22%7D)%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D
=> [dashboard] Overview: make "Total Accounts" panel accurate

client/src/client_proxy.rs
Summary: This changes state, it should be POST.
Test Plan: Tested minting against production testnet.
Depends on a7a8c50.
=> [client] Send faucet requests as POST

testsuite/cluster_test/Cargo.toml, testsuite/cluster_test/src/cluster.rs, testsuite/cluster_test/src/experiments/mod.rs, testsuite/cluster_test/src/experiments/reboot_random_validator.rs, testsuite/cluster_test/src/health/commit_check.rs, testsuite/cluster_test/src/health/liveness_check.rs, testsuite/cluster_test/src/health/log_tail.rs, testsuite/cluster_test/src/health/mod.rs, testsuite/cluster_test/src/instance.rs, testsuite/cluster_test/src/main.rs
This diff introduces health checks for cluster test:
- Commit check verifies invariants on history of committed blocks:
* Commit sequence is increasing for each validator
* Validators commit same blocks on same rounds
- Liveness check verifies that system is still working
* Commits are produced by validators, with upper bound on delay
* Validators don't restart during test
Those checks are not ideal yet, but that's a start.
[for example commit check can be enforced to make sure sequence of commits is exactly same, versus weaker check that we have right now.]
When we run experiment, we verify, in parallel thread, that health checks are passed:
- Verify that cluster is healthy before experiment
- Verify that during experiment only affected validators don't pass health checks
- Verify that …
=> [cluster_test] Health checks for cluster test

mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/unit_tests/common.rs, mempool/src/core_mempool/unit_tests/core_mempool_test.rs, mempool/src/core_mempool/unit_tests/shared_mempool_test.rs
Current *e2e_latency* measured by mempool includes both *local* TXNs (from local AC) and *shared* TXNs (from shared mempool).
As a result, a TXN has `num_validators` e2e_latency values and the shared latency values will be less than, and noisy to, the one measured locally.
When adding shared TXNs from mempool, `Mempool::add_txn()` simply ignores inserting it into the `metrics_cache`, so that there will be only local latency for a TXN.
Extended unittest.
E2E test with 4-node `libra_swarm`. On the left side, only 1 client is submitting TXNs to a fixed validator. On the other side, 4 clients have connected one-to-one to 4 validators and are submitting TXNs to corresponding connected validator.
Signed-off-by: Jiaqi Yan <yjq@calibra.com>
=> [mempool] Only record local TXN's e2e latency.

common/logger/Cargo.toml, common/logger/src/lib.rs, common/proptest_helpers/Cargo.toml, language/vm/vm_runtime/vm_cache_map/Cargo.toml
* This modifies the following behavior:
- updates `crossbeam` in `proptest_helpers` & `vm_runtime` to 0.7.2 (which was [just released](https://github.com/crossbeam-rs/crossbeam/issues/401#issuecomment-514829720))
- removes usage of `crossbeam` in `common::logger` as:
+ `ArcCell` was [removed](https://github.com/crossbeam-rs/crossbeam/pull/301) in more recent versions of crossbeam,
+ it was [spin-locking](https://github.com/crossbeam-rs/crossbeam/issues/160) anyway
* Why this is better
- closes #279
- [`arc-swap`](https://docs.rs/arc-swap/) is ([mostly](https://github.com/crossbeam-rs/crossbeam/issues/160#issuecomment-378281816)) lock-free
* Why this is worse
- [`arc-swap`](https://github.com/vorner/arc-swap) is young
* Tests
- `cargo audit` + CI
=> [common, easy] Update crossbeam

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/consensus_types/mod.rs, consensus/src/chained_bft/consensus_types/sync_info.rs, consensus/src/chained_bft/consensus_types/timeout_msg.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/local_pacemaker.rs, consensus/src/chained_bft/liveness/local_pacemaker_test.rs, consensus/src/chained_bft/liveness/mod.rs, consensus/src/chained_bft/liveness/pacemaker.rs, consensus/src/chained_bft/liveness/pacemaker_timeout_manager.rs, consensus/src/chained_bft/liveness/pacemaker_timeout_manager_test.rs, consensus/src/chained_bft/liveness/proposer_election.rs, consensus/src/chained_bft/network.rs, consensus/src/chained_bft/sync_manager.rs, network/src/proto/consensus.proto, network/src/proto/mod.rs
Summary:
This commit doesn't change anything in the logic: it's the first preparation for the changes required for being able to send the missing pieces of information upon receiving of outdated timeout messages.
Today sync info is scattered across several fields both in the `TimeoutMsg` and in `Proposal`. This commit introduces a new struct `SyncInfo`, which is going to be included in both `TimeoutMsg`, `Proposal`, and could be sent as a standalone message.
Test: existing unit test coverage
Issue: #311
=> [Consensus] Introduce SyncInfo struct for accumulating sync information

language/tools/cost_synthesis/Cargo.toml, language/tools/cost_synthesis/src/bin/main.rs
The constants for determining stack size and number of iterations were
manually set variables within the main file. This commit makes these
settable from the command line using the `structopt` package.
=> [language] Add command-line arguments to cost synthesis

common/channel/src/lib.rs, common/channel/src/test.rs, network/src/protocols/direct_send/mod.rs
Fix #328 that slow peers can block the whole network module from processing.
When the message queue for a specific peer is full, drop the messages on the floor, so that it doesn't block other peers. Because direct send protocol is a fire-and-forget service, there is no delivery guarantee, and no feedback needs to be propagate up.
Yes
cargo test
=> [network] drop messages when message queue is full

language/e2e_tests/src/account_universe.rs, language/e2e_tests/src/tests/account_universe.rs, language/e2e_tests/src/tests/account_universe/create_account.rs, language/e2e_tests/src/tests/account_universe/peer_to_peer.rs, language/e2e_tests/src/tests/account_universe/rotate_key.rs
Add a `default_` prefix to `num_accounts` and `num_transactions`.
I kept getting confused at what these meant.
=> [language/e2e_tests] rename some account_universe default methods

types/src/proof/position.rs
The prefix for these numbers should be `0b`.
Yes.
CI
=> [Proof] Replace incorrect 0x with 0b in FrozenSubTreeIterator

testsuite/cluster_test/Cargo.toml, testsuite/cluster_test/src/aws.rs, testsuite/cluster_test/src/cluster.rs, testsuite/cluster_test/src/health/log_tail.rs, testsuite/cluster_test/src/health/mod.rs, testsuite/cluster_test/src/main.rs
Instead of reading instances.txt cluster test now queries instances from AWS.
This PR also have couple of nits:
* Instead of waiting for 10 seconds during startup, we query logs from past and wait for AWS thread startup
* More colors in output :)
* Health check runs less frequently, once every 5 seconds
* Experiment deadline - if experiment does not complete in 2 minutes it's considered failed
=> [cluster_test] Discovery for cluster test

.circleci/config.yml, terraform/faucet_variables.tf
Summary: Add a job to run `terraform validate` to prevent blatant
breakages. Also restore missing faucet variables which broke TF.
Test Plan: https://circleci.com/gh/libra/libra/152
=> [circleci] Validate Terraform configuration

docker/client/client.Dockerfile, docker/mint/mint.Dockerfile, docker/validator/validator.Dockerfile
Summary: Run the same build command (building both e2e and client) in
all docker images. This allows the docker cache from after the build to
be reused for all images, because all the rules up to this point are the
same. This will significantly speed up building all three images.
Test Plan: Built all three images; rust build was not repeated for the
second and third.
=> [docker] Improve build cache usage

client/src/commands.rs
Parse cmd error when there are multi blank here, for example:
```
t    0 1 100
```
between "t" and "0", there are two blankspace here and caused parse error. error info:    
```
[ERROR] Failed to perform transaction: Unable to parse input for account_reference_id/account_address - please enter an Usize.  Input was: , error: ParseIntError { kind: Empty }
```
Y
execute "t  0 1 100" again.
https://github.com/libra/libra/pull/323
=> [Client]Fixed multiple whitespace error

config/Cargo.toml, config/config_builder/src/swarm_config.rs, config/config_builder/src/util.rs, config/src/config.rs, config/src/trusted_peers.rs, consensus/src/chained_bft/chained_bft_consensus_provider.rs, consensus/src/consensus_provider.rs, crypto/secret_service/Cargo.toml, libra_node/Cargo.toml, libra_node/src/main.rs, libra_node/src/main_node.rs, libra_swarm/src/swarm.rs
- `config::KeyPairs` now contains `nextgen_crypto:ed5519::Ed25519PrivateKey` instances where `signing::PrivateKey` was used,
- `NodeConfig`, `BaseConfig` et al, only allow Clone under conditional compilations,
- The n copies of private key material per node (where n = # of peers) in `KeyPairs::load_config` are eliminated using the [mem::replace](https://github.com/rust-unofficial/patterns/blob/master/idioms/mem-replace.md) pattern
- elimination of `n` copies in `libra_swarm::LibraSwarm::add_node` through better mutability scoping
- The 2 copies of private key material per node (in `chained_bft_consensus_provider::initialize_setup` and `main_node::setup_network`) are eliminated through `mem::replace`.
- pursues the conversion to nextgen_crypto API
- the number of memory copies of private …
=> [crypto] Converts the config module to use the nextgen_crypto API

terraform/templates/dashboards/network.json
1. Fix the `pending_direct_send_outbound_messages` chart by adding `remote_peer_id` field.
2. Only display the lines with non-empty queues to reduce noise.
Yes
Tested on my own cluster.
=> [network] display pairwise direct send queue counters

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/event_processor.rs
When a validator receives a proposal, it is processed and a `ProcessProposalResult` enum is returned as a result. 
This enum either indicates that there is more work to be done to process the block, or that there is nothing to be done (the proposal was processed). 
In the latter case, the enum does not distinguish a failure to process the proposal versus a proposal fully validated and voted on.
The reason is that even though the proposal is then called `winning_proposal`, we still cannot fully know if we will eventually vote on the proposal as [there is more logic](https://github.com/libra/libra/blob/master/consensus/src/chained_bft/event_processor.rs#L468) that could still prevent the validator to vote on the proposal.
Yet, this PR adds a boolean inside the enum, with `true` indicating a …
=> [consensus] ProcessProposalResult now contains a better signal for success

language/vm/src/file_format.rs, language/vm/src/gas_schedule.rs
Currently there are no checks that ensure that every bytecode instruction is included in the `CostTable`.
This diff adds a check that will be run in debug builds to ensure that exactly `53` instructions (without duplicates) are present in the `memory_table` and `compute_table`.
This check is run during invocation of `cargo test` and thus can prevent a situation where a new instruction is added to the bytecode but is not added to the `CostTable`.
Yes.
Local testing via `cargo test`. Ensured that the `debug_assert` fails on values other than `53`.
N/A
=> [language] Add check for coverage of instructions in gas schedule

benchmark/src/bin/ruben.rs, benchmark/src/lib.rs, benchmark/src/ruben_opt.rs
Based on discussion on #348 , we decide the information provided by NodeDebugClient is useless in Benchmarker now.
However, `-d` option is kept for now in order to in sync with the AWS environment.
Local test with RuBen.
=> [benchmark] Remove NodeDebugClient from Benchmarker

storage/sparse_merkle/src/nibble_path/mod.rs, storage/sparse_merkle/src/nibble_path/nibble_path_test.rs
1. Changed some structs' visibility for migrating to JellyfishMerkleTree temporarily.
2. Add a method pop(), which is useful in JellyfishMerkleTree. 
Yes
`cargo test` in `sparse_merkle` crate
=> [storage] Add pop() method and related tests to NibblePath

terraform/templates/prometheus.json
Enabled an option to embed Grafana graphs & widgets in other pages.
This is useful for dashboards/external dashboard displays.
yes
Tested locally by setting Grafana in an `iframe`
=> [grafana] enable embedding Grafana dashboards (e.g., in iframes)

mempool/src/core_mempool/transaction_store.rs, mempool/src/core_mempool/unit_tests/common.rs, mempool/src/core_mempool/unit_tests/core_mempool_test.rs
We allow increases in gas price to speed up a transaction if needed. When updating, we need to make sure other values such as max gas amount, payload and expiration time have not been changed as well. Adding checks for consistency on those fields.
Added unit test in core_mempool_test.rs
=> [mempool] Check only gas price is updated when we allow increase in gas price to speed up a transaction

consensus/src/chained_bft/block_storage/block_tree.rs, consensus/src/chained_bft/safety/vote_msg.rs, consensus/src/state_synchronizer/sync_test.rs, crypto/nextgen_crypto/src/ed25519.rs, types/src/ledger_info.rs, types/src/proptest_types.rs
- Switches LedgerInfo to use Ed25519Signature
- Progress of conversion to the nextgen-crypto API
- this includes QuorumCertificate, VoteMsg, and transfers the whole of Consensus to nextgen
- breaking change, as LedgerInfo (etc) are serialized
- existing unit tests (type-only modifications)
- more conversion, esp. `transaction.rs`
=> [crypto] Switches LedgerInfo to nextgen_crypto

testsuite/cluster_test/src/cluster.rs, testsuite/cluster_test/src/instance.rs
Cluster test in previous version was not able to handle re-creation of workplace.
This change fixes two problems
- In discovery we should only account for running instances
* When re-creating workplace, we have bunch of terminated instances that confused discovery
- Disable StrictHostKeyChecking when connecting to validators via ssh
* Otherwise host key change breaks cluster_test
* Since we are in private VPC this should be pretty safe
=> [cluster_test] Fix cluster_test not working after re-creating workplace

language/compiler/src/main.rs
Added an extra flag in the compiler to pass in the downloaded on chain modules. We do need to sort out the stdlib stories in the compiler side(say whether they should be treated differently from the other modules)
We will test the publishing flow after we implemented the module fetcher in client.
=> [compiler] Add a flag to pass in on chain module dependencies

.gitignore
Per @huitseeker 
> These fragments, which make an assumption on the editor installed where this code is edited, seem to belong in a [local .gitignore](https://help.github.com/en/articles/ignoring-files) rather than the one of the project, no?
Yes
N/A
=> [gitignore] remove IDE-related lines

client/src/client_proxy.rs, client/src/commands.rs, client/src/dev_commands.rs, client/src/main.rs, libra_swarm/src/client.rs
diffs adds following changes to developer flow:
* address preprocessor will use {{sender}} template instead of {{default}} to substitute sender address
* is_module compilation flag changed to explicit module|script choice
* dev section shouldn't be displayed during connection to production testnet. It will only be displayed if mint key is provided (e.g. developer owns given network)
=> [cli] dev section: polishing

config/data/configs/node.config.toml, config/src/config.rs
Instead of defining defaults in the config file, this approach defines
defaults in code. This will allow the config file to be smaller because
it only needs to set non-default values, and reduce incompatibility
because new settings with a default won't need changes to configs.
Test Plan: Ran libra_swarm and checked generated config file with:
* `metrics` section completely missing
* `metrics` section present but `dir` not present
* `collection_interval_ms` set to non-default
=> [config] Use #[serde(default)] to define defaults in code

common/logger/src/security.rs, consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/chained_bft_smr_test.rs, consensus/src/chained_bft/consensus_types/sync_info.rs, consensus/src/chained_bft/consensus_types/timeout_msg.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/liveness/local_pacemaker.rs, consensus/src/chained_bft/liveness/pacemaker.rs, consensus/src/chained_bft/network.rs, consensus/src/chained_bft/network_tests.rs, consensus/src/chained_bft/sync_manager.rs, consensus/src/counters.rs
Summary:
In this diff we add a proper handling of `SyncInfoMsg`. We're sending this message when detecting that a remote peer is lagging:
* the check is executed upon receiving either a timeout message or a proposal
* the lagging criterion is determined by the round of the message and a round of the carried HQC
Test: in addition to the existing test coverage added a unit test that verifies proper sync info when receiving a timeout message from a lagging peer.
Issue: #311
=> [Consensus] Send sync info to help lagging remote peers

client/src/main.rs
The client cli crashes if no commands were provided e.g., newline or whitespaces
yes
Started client, clicked a few `<RET>` nothing crashed
```
$ target/debug/client -a ac.testnet.libra.org -p 80 -s scripts/cli/trusted_peers.config.toml
Connected to validator at: ac.testnet.libra.org:80
usage: <command> <args>
Use the following commands:
account | a
Account operations
query | q
Query operations
transfer | transferb | t | tb
<sender_account_address>|<sender_account_ref_id> <receiver_account_address>|<receiver_account_ref_id> <number_of_coins> [gas_unit_price_in_micro_libras (default=0)] [max_gas_amount_in_micro_libras (default 100000)] Suffix 'b' is for blocking.
Transfer coins (in libra) from account to another.
dev
Local move development
help | h
Prints this help
quit | q!
Exit this …
```
=> [client] do not panic on empty lines

config/data/configs/node.config.toml, config/src/config.rs
Sets remaining defaults in code instead of the config file. This sets
the default VMPublishingOption to "Open", but keeps it as "Locked" in
the default config file.
Test Plan: Ran libra_swarm
=> [config] Set BaseConfig and VMConfig defaults in code

crypto/nextgen_crypto/src/ed25519.rs, testsuite/libra_fuzzer/Cargo.toml
*What this changes*
- make `libra_fuzzer` call into the `"testing"` feature of `vm_runtime_types`
- mask a strategy introduced in #373 that could not be masked until #356 was introduced
*Test*
- to make sure this doesn't break, I ran `find ./ -iname Cargo.toml -execdir cargo check --all-targets \;` (but it costs CPU)
- another option is `cargo check --all-targets --bins -p libra-node -p libra_swarm -p libra_fuzzer` but it requires keeping in mind an up-to-date list of relevant binaries
=> Follow-up to #401 #356 #373

execution/execution_tests/src/tests/mod.rs, language/benchmarks/src/transactions.rs
After discussing this with @sblackshear, we've come to the conclusion that the
real executor is a bit too much work for now and not very high priority. But
I did spend some time exploring what work needs to be done and wanted to ensure
I don't forget it :)
Also address an unresolved issue from #380.
=> [language/benchmarks] add notes on how to implement against real executor

crypto/nextgen_crypto/src/lib.rs, crypto/nextgen_crypto/src/traits.rs, crypto/nextgen_crypto/src/unit_tests/mod.rs, crypto/nextgen_crypto/src/unit_tests/x25519_test.rs, crypto/nextgen_crypto/src/x25519.rs
This PR provides extends the key traits of the nextgen_crypto API with traits for Diffie-Hellman key exchange, and provides an X25519 DH implementation for the key traits. In particular:
- A new Diffie-Hellman ephemeral secret trait (named ExchangeKey) in traits.rs, that inherits from Private key and in addition defines the associated types for Public and Shared keys and provides a method for DH key exchange
- X255519 implementation in X25519.rs that uses the X25519-dalek library to implement the key APIs for the keys involved in DH exchange (Ephemeral, Public, Shared)
- Compact Serialization for the Public and Exchange DH keys (by François Garillot)
- Unit tests (incomplete)
Co-authored-by: François Garillot <fga@calibra.com>
Yes
Manual build and (incomplete) unit tests provided by this …
=> [crypto] Adds traits for DH key exchange + X25519 implementation  for nextgen_crypto

storage/libradb/src/lib.rs, storage/libradb/src/pruner/mod.rs, storage/libradb/src/pruner/test.rs, storage/libradb/src/state_store/mod.rs, storage/libradb/src/state_store/state_store_test.rs
Based on previous work that added and started maintaining the state retire records, this introduces a background thread to recollect db space. The length of history to keep is currently a constant, which needs to be converted to a config once we are clear about different behavior to expect on different types of nodes.
yes
Unit tests.
=> [storage] pruner

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/chained_bft_smr_test.rs, consensus/src/chained_bft/consensus_types/timeout_msg.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/local_pacemaker_test.rs, consensus/src/chained_bft/liveness/pacemaker_timeout_manager_test.rs, consensus/src/counters.rs, network/src/proto/consensus.proto
[Consensus] Attach votes to timeout messages.
Summary:
In this diff we're extending timeout message to include an optional Vote field:
* the votes are cached in `EventProcessor` to include the last vote msg of a validator
* upon timeout the cached vote message is attached to the timeout message
* upon receiving timeout message, the votes are added to the block store and new QCs can be generated
This PR appears as two commits, but the first one belongs to another PR #367 (they're touching similar pieces of code, so it's now rebased on top of it). Please review the second commit only.
Test: added a unit test that verifies vote aggregation via timeout messages
Task: ref #371
=> Vote in timeout msg

config/src/config.rs, execution/execution_tests/src/lib.rs, execution/executor/src/executor_test.rs, libra_node/src/main_node.rs, storage/storage_client/src/lib.rs, storage/storage_service/src/storage_service_test.rs, terraform/validator-sets/dev/node.config.toml, vm_validator/src/unit_tests/vm_validator_test.rs
When transactions are executed, these signed transactions along with
account states and events are passed to storage through a gRPC call.
Though the total size of the signed transactions is smaller than the 4MB
gRPC message length limit, the additional account states and events can
make the request exceeds the 4MB limit.
Given that the gRPC service between executor and storage is used within
a validator, I think it makes sense to increase the limit to 100MB.
Yes
Tested on benchmark cluster, get one node offline and online again, didn't observe the crash anymore during state sync
=> [storage] increase storage gRPC receiving message length

config/data/configs/node.config.toml, config/src/config.rs, terraform/validator-sets/dev/node.config.toml
With #393 and #400 we can remove most of these values. Change defaults
for referenced config files so those can be removed as well, and set
default listen address for admission control to 0.0.0.0.
Test Plan: libra_swarm, built docker and ran locally.
=> [config] Remove defaults from prod config

common/channel/Cargo.toml, common/channel/src/lib.rs, common/channel/src/test.rs, consensus/src/chained_bft/network.rs, network/src/connectivity_manager/test.rs, network/src/peer_manager/mod.rs, network/src/validator_network/network_builder.rs
In general, consensus/mempool would not like to process stale network messages. Specifically, one issue we've observed is that if one node gets stuck on processing consensus messages due to some issue, and then gets back to full speed after a while, stale messages get accumulated in the message queue. Consensus processes stale proposals slowly because it needs to request for missing blocks from other peers, and if the blocks are pretty old, they're pruned from consensus DB already.
The fix is to add a timeout for the messages waiting in queues. If the wait time exceeds the timeout, those messages will be simply dropped to save capacity for new messages.
More specifically, this PR does:
1. Add a timeout field in the Receiver of the channel wrapper, and drop the messages when pulling the …
=> [network] add timeout for inbound consensus/mempool events

consensus/src/chained_bft/liveness/local_pacemaker.rs, consensus/src/chained_bft/liveness/rotating_proposer_election.rs
The winning_proposals_sender.send can fail silently and leave the pacemaker
in an unproductive state.  If this occurs, it would be better to panic and
restart and recover.
Yes
Unittests
=> process_proposal local channel send should not fail silently

language/stackless_bytecode_generator/src/stackless_bytecode_generator.rs, language/stackless_bytecode_generator/tests/stack_elim_tests.rs
Get rid of unnecessary `work_list` and `cfg` from `StacklessBytecodeGenerator`.
Yes.
`cargo test`
=> [language] remove work_list and cfg from stackless bytecode generator

benchmark/src/bin/ruben.rs, benchmark/src/lib.rs, benchmark/src/ruben_opt.rs, benchmark/src/txn_generator.rs
Summary:
* Abstract account and request/TXN load generation into `LibraRequestGenerator` trait.
* Replace ring/pairwise TXN generation helper functions with corresponding generators.
* Add `-t` for the choice of TXN generator. Remove `-x` option since the `-t` option has make it no significant difference between `testliveness` and `measure throughput`.
Test Plan:
Tested with local libra_swarm.
=> [benchmark] Introduce LoadGenerator with two example TXN generators

Cargo.toml, storage/jellyfish_merkle/Cargo.toml, storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/node_type/mod.rs, storage/jellyfish_merkle/src/node_type/node_type_test.rs, storage/sparse_merkle/src/lib.rs, types/src/account_state_blob/mod.rs
We are going to change curent sparse merkle tree to jellyfish merkle
tree, which is more efficent than current merkle in the aspects of IOPS,
compaction overhead and space. This diff will first introduce the data
structures of two kinds of nodes in the tree and corresponding unit tests.
Yes
cargo test
=> [storage][jellyfish_merkle][1/3] Define node_type in jellyfish merkle tree

common/proptest_helpers/proptest-regressions/unit_tests/repeat_vec_tests.txt, common/proptest_helpers/src/repeat_vec.rs, common/proptest_helpers/src/unit_tests/repeat_vec_tests.rs
This will be useful for proptesting account universes, such that the probability of an account being selected can be reduced as the account is picked.
Included are both example-based and property-based tests.
=> [proptest_helpers] add a remove method to repeat_vec

terraform/monitoring.tf, terraform/templates/prometheus.json
Occasionally the files in /tmp disappear and monitoring/TF breaks. Put
them in /opt instead, and prefer to mount directories instead of files.
Deployed mgorven workspace, checked Prometheus consoles and
Grafana dashboards.
=> [terraform] Provision monitoring configs in /opt

language/bytecode_verifier/Cargo.toml, language/bytecode_verifier/src/verifier.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop, language/compiler/src/main.rs, language/functional_tests/tests/testsuite/natives/clever_non_existant_native_function.mvir, language/functional_tests/tests/testsuite/natives/non_existant_native_function.mvir, language/stdlib/src/lib.rs, language/vm/src/views.rs, language/vm/vm_runtime/src/txn_executor.rs, language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, types/src/account_address.rs
- To prevent programmers from publishing code with fake native functions. The bytecode verifier will now check that 
(a) the native function exists 
(b) the native function has the signature expected by the VM runtime 
- Any other properties of the native function (such as it being public or not) will still be left up to the declaration of the native function in move code
- Found bug with natives where the address was not checked. Added that field to the dispatch map to fix this
- Manually tested that the type checking works for native functions. Cannot yet mock out the std lib for functional tests, so this one off test will have to do for now
- Added tests for trying to add a fake native function 
- cargo test
=> [VM] Verify native functions

testsuite/cluster_test/src/cluster.rs, testsuite/cluster_test/src/health/commit_check.rs, testsuite/cluster_test/src/health/liveness_check.rs, testsuite/cluster_test/src/health/log_tail.rs, testsuite/cluster_test/src/health/mod.rs, testsuite/cluster_test/src/lib.rs, testsuite/cluster_test/src/main.rs
This change mostly add various debug information that helps to debug spurious failures in cluster_test.
- Measure and log how much time health check run takes when HEALTH_CHECK_DEBUG env is set
- Collect received timestamps on events from kinesis
- Measure number of pending messages between log tail thread and health check to see if one of threads is lagging behind
Also there are couple of improvements in logic in order to support larger clusters:
- Support for paging read of EC2 instances when discovering cluster
- Rework how log tail thread ramp up works - instead of waiting for fixed delay, we now wait (with timeout) until at least one event from each validator was received
- Protect from rare cases when kinesis events arrive out of order - we track last timestamp of event received …
=> [cluster_test] Support larger clusters and add debugging information

common/proptest_helpers/src/repeat_vec.rs, language/e2e_tests/src/account_universe.rs, language/e2e_tests/src/account_universe/create_account.rs, language/e2e_tests/src/account_universe/peer_to_peer.rs, language/e2e_tests/src/account_universe/rotate_key.rs, language/e2e_tests/src/account_universe/universe.rs, language/e2e_tests/src/tests/account_universe.rs
The main purpose here is to allow for accounts to only be picked a limited number of times. This will be useful for benchmarking parallel execution.
=> [language/e2e_tests] add alternate picking styles for account universes

benchmark/src/bin/ruben.rs, benchmark/src/grpc_helpers.rs, benchmark/src/lib.rs, benchmark/src/ruben_opt.rs, benchmark/src/submit_rate.rs
Add the ability to control how each client sends TXNs to AC. User can use `-k X` argument to send TXNs to AC at the speed of `X` TXNs per second per client.
Unittest in `submit_rate.rs`:
```
cargo test --release -p benchmark test_submit_rate -- --nocapture
```
E2E test:
For aggregated constant submission rate of 400 requests per second, run
```
./target/release/ruben -m localhost:45345 -f faucet_for_ruben -s temp_config \
-g 1 -n 64 -c 4 -e 3 -t pairwise
-k 100
3 epoch(s) of REQ/TXN throughput = [
(381.0941570524749, 220.07307113690092),
(392.5627755414989, 219.08429610611896),
(393.69473279507883, 350.0256366433088)
]
```
We have 4 clients, each sending at constant rate 100. Log shows that request throughput is roughly 390 requests/s. Figure shows Benchmarker is submitting at constant …
=> [benchmark] Submit TXNs in constant rate.

consensus/src/chained_bft/chained_bft_consensus_provider.rs
The comment is to pick the smallest ID but the implementation picks the max ID. Let's change the comment instead of changing the implementation.
Understanding and contributing to libra.
Yes
It should pass.
No related PRs
=> [consensus] Correct the comment

terraform/validators.tf
Validator instances can startup before the policy allowing access to
trusted_peers in S3 is installed.
=> [terraform] Fix startup race condition breaking trusted_peers

common/canonical_serialization/src/lib.rs
fix typo error from  little endian to little-endian
Y
N/A
=> fix typo  from little endian to little-endian

language/bytecode_verifier/src/verifier.rs, language/vm/src/views.rs, language/vm/vm_runtime/vm_runtime_types/src/lib.rs, language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, language/vm/vm_runtime/vm_runtime_types/src/native_structs/dispatch.rs, language/vm/vm_runtime/vm_runtime_types/src/native_structs/mod.rs
- Added similar dispatch for native structs as exists for native functions
- Utilized the native struct dispatch for builiding the signature of native functions
- Added a check for verifying the linking of native structs
- Cannot yet test easily without IR support (coming shortly)
cargo check; cargo test
Cannot test the core functionality yet
Depends on #405
=> [VM] Verify native struct

benchmark/src/bin/ruben.rs, libra_node/src/main_node.rs, storage/storage_client/Cargo.toml, storage/storage_client/src/lib.rs
This PR introduces a few small changes to improve our gRPC use.
The gRPC library we use (pingcap/grpc-rs) is a Rust wrapper around the C gRPC implementation. The C implementation is targeted towards a common use case of many clients -> few servers. There are specific optimizations there to support this use case, but they're not suitable for our in-process use case. 
Changes:
1) Increase the AdmissionControl executor pool size. This increases the availability of our system to clients. Mempool provides the queuing, and we can stop accepting requests when Mempool is full.
2) Change the clients generated by benchmarker to report different user-agents. We want the benchmarker to appear like many different clients, to utilize multiple AC threads, and this is how we achieve it.
3) Use the same …
=> gRPC Hackery

language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop, language/functional_tests/tests/testsuite/natives/non_existant_native_struct.mvir, language/stdlib/modules/vector.mvir
- Added native struct syntax to the IR. It is a modifier followed by no fi\
elds
- Added native struct support to the compiler
- Added tests for both the syntax and missing dependencies
- new test
- cargo  check; cargo test
Depends on #405 and #413
=> [MoveIR] Added Native Structs to the IR

admission_control/admission_control_service/src/admission_control_node.rs, admission_control/admission_control_service/src/admission_control_service.rs, admission_control/admission_control_service/src/unit_tests/admission_control_service_test.rs, benchmark/src/bin/ruben.rs, config/config_builder/src/swarm_config.rs, config/data/configs/full_node.config.toml, config/src/config.rs, libra_node/src/main_node.rs, libra_swarm/src/main.rs, libra_swarm/src/swarm.rs, testsuite/tests/libratest/smoke_test.rs
Diff adds role parameter to node's base config
Current options: Validator/FullNode
After this change `Validator` nodes will behave as usual
For FullNode type:
* Mempool is disabled
* Consensus is disabled
* p2p network is disabled
* AC doesn't have active connection to Mempool
* AC can only serve read queries
added `test_full_node` to integration tests. So far it just checks that AC can serve reads, but no writes
=> [full_node] configuration: add role

crypto/legacy_crypto/Cargo.toml, crypto/legacy_crypto/src/x25519.rs, crypto/nextgen_crypto/Cargo.toml, crypto/nextgen_crypto/src/bls12381.rs, crypto/nextgen_crypto/src/vrf/ecvrf.rs, crypto/nextgen_crypto/src/x25519.rs, crypto/secret_service/Cargo.toml, crypto/secret_service/src/crypto_wrappers.rs
This change removes `derive_deref` from the crypto crate, reducing dependent crates from 288 to 283.
Yes
Unit tests.
=> [crypto] remove derive_deref dependency from crypto crate

common/grpc_helpers/src/lib.rs, storage/storage_service/src/lib.rs
PR #403 set max receive message len on the gRPC client of the storage
channel. It turns out the gRPC server side needs to be configured as
well to make it work.
Tested locally with a simple gRPC client/server project, will double check on benchmark cluster.
#403
=> [storage] set max receive message len on gRPC storage server

Cargo.toml, language/tools/cost_synthesis/src/common.rs, language/tools/cost_synthesis/src/module_generator.rs, language/tools/test_generation/Cargo.toml, language/tools/test_generation/src/abstract_state.rs, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/lib.rs, language/tools/test_generation/src/main.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/arithmetic_instructions.rs, language/tools/test_generation/tests/bitwise_instructions.rs, language/tools/test_generation/tests/boolean_instructions.rs, language/tools/test_generation/tests/common.rs, language/tools/test_generation/tests/comparison_instructions.rs, language/tools/test_generation/tests/load_instructions.rs, language/tools/test_generation/tests/local_instructions.rs, language/tools/test_generation/tests/special_instructions.rs, language/tools/test_generation/tests/transaction_instructions.rs
Initial framework for automated generation of valid Move bytecode programs. These generated programs will be used as tests for the Move bytecode verifier and the Move VM transaction execution pipeline.
Yes.
A set of tests have been added `tests/` folder and will be run when `cargo test` is executed.
N/A
=> [VM] Automated Move bytecode test generation tool

benchmark/src/bin/ruben.rs, benchmark/src/bin_utils.rs, benchmark/src/lib.rs, benchmark/src/ruben_opt.rs, testsuite/Cargo.toml, testsuite/tests/libratest/main.rs, testsuite/tests/libratest/throughput_test.rs
The first step to run throughput measurement as regression test.
In future, CI could run throughput tests on both submitted PR and master, then compare the observed throughput.
Commit 1. Move helpers out of ruben.rs to be shared.
Commit 2. Add the end-to-end throughput test with `libra_swarm` and `Benchmarker`. Request speed is set to **constant 200 TXNs per seconds**, so the expected throughput should be around 150~190 TPS.
Run
```
cargo test --release -p testsuite test_throughput -- --nocapture
......
{"REQ_throughput_mean": 197.83, "REQ_throughput_stdev": 0.17}
{"TXN_throughput_mean": 173.62, "TXN_throughput_stdev": 2.28}
test throughput_test::test_throughput ... ok
```
Note output is print out in JSON format.
=> Introduce Throughput Test

language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, language/vm/vm_runtime/vm_runtime_types/src/native_structs/dispatch.rs
- Small change to use account_config::core_code_address() isntead of a 0x0 for native function/struct address
cargo check
cargo test
=> [VM] Use account_config::core_code_address() in natives

client/src/client_proxy.rs
few output changes:
* `waiting` instead of `[waiting`
* `no events emitted` is displayed in case of absence of events
=> [cli] improve output of wait_for_transaction

storage/jellyfish_merkle/Cargo.toml
#429 introduces the new API and somehow we have to enable `testing` feature of `types` whenever we depend on it.
Yes
Cargo test
=> [storage][jellyfish] fix building error

testsuite/tests/libratest/throughput_test.rs
Summary:
Add the missed template_path argument because of silent merge.
Test Plan:
cargo test --release -p testsuite -- --nocapture
=> [libratest] Fix launch_swarm in throughput test.

storage/jellyfish_merkle/src/jellyfish_merkle_test.rs, storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/mock_tree_store.rs, storage/jellyfish_merkle/src/node_type/mod.rs, storage/jellyfish_merkle/src/tree_cache/mod.rs, storage/jellyfish_merkle/src/tree_cache/tree_cache_test.rs, storage/sparse_merkle/src/nibble_path/mod.rs
This is the main implementation and tests of JellyfishMerkleTree. Which is essentially is a sparse merkle tree as our current implementation but with a few major optimizations.
1. We use NodeKey(version | nibble path) as key to uniquely identify a node instead of hash. The prefix - version - will help reducing compaction overhead since each commit of nodes will not overlap with any preceding commit thanks to monotonically increasing version.
2. We remove the `Extension` node to simplify code. It can be proved that the number of extension nodes will decrease as time goes and tree gets denser, so we choose to get rid of it to make the code easier to understand and maintain.
3. Merge blob node with leaf node for now for simplicity.
Yes
cargo test 
#378 #427
=> [storage][jellyfish][3/3] Jellyfish Sparse Merkle Tree implementation

config/config_builder/src/util.rs, config/src/config.rs, config/src/trusted_peers.rs, consensus/src/state_synchronizer/sync_test.rs, crypto/nextgen_crypto/src/ed25519.rs, crypto/nextgen_crypto/src/unit_tests/x25519_test.rs, crypto/nextgen_crypto/src/x25519.rs, network/benches/network_bench.rs, network/noise/Cargo.toml, network/noise/src/lib.rs, network/src/common.rs, network/src/connectivity_manager/test.rs, network/src/protocols/discovery/test.rs, network/src/transport.rs, network/src/validator_network/consensus.rs, network/src/validator_network/network_builder.rs, network/src/validator_network/test.rs, types/src/validator_public_keys.rs
Convert usages of `legacy_crypto::X25519PrivateKey` to `nextgen_crypto::x25519`.
The purpose of this task is to use the `nextgen_crypto API` (i.e. make the network identity key an x25519 key using the new crypto API) and convert the corresponding network code (which makes a few uses of it).
YES
existing
=> [crypto] apply nextgen_crypto x25519 across Libra

docker/mint/server.py
The client now sends these as POST.
Ran validators and faucet locally, tested minting. Tested
with `curl` that GET returns 405.
=> [faucet] Only accept POST requests

Cargo.toml, common/bounded-executor/Cargo.toml, common/bounded-executor/src/lib.rs, common/futures-semaphore/Cargo.toml, common/futures-semaphore/src/lib.rs, mempool/Cargo.toml, mempool/src/shared_mempool.rs, network/Cargo.toml, network/src/protocols/rpc/mod.rs, network/src/protocols/rpc/test.rs, network/src/validator_network/network_builder.rs
In the beginning, we used to `executor.spawn(_)` tasks without limit, but this provided no backpressure and would eventually crash to OOM. Next we used `stream.buffer_unordered(limit)` for task-level concurrency with backpressure, but it is not actually task parallel. Now, with the newly implemented `BoundedExecutor`, you can `executor.spawn(_).await` to get task-level parallelism+concurrency with still providing backpressure, since `BoundedExecutor` only allows a user-defined number of tasks to be executing at any point in time.
Then, we use `BoundedExecutor` in both shared_mempool and rpc protocol.
=> [mempool+network] Add and use BoundedExecutor to spawn tasks with backpressure

language/stackless_bytecode/bytecode_to_boogie/Cargo.toml, language/stackless_bytecode/bytecode_to_boogie/output.bpl, language/stackless_bytecode/bytecode_to_boogie/src/bytecode_function_generator.rs, language/stackless_bytecode/bytecode_to_boogie/src/bytecode_instrs.bpl, language/stackless_bytecode/bytecode_to_boogie/src/main.rs, language/stackless_bytecode/bytecode_to_boogie/src/translator.rs, language/stackless_bytecode/bytecode_to_boogie/test_mvir/test-arithmetic.mvir, language/stackless_bytecode/bytecode_to_boogie/test_mvir/test-func-call.mvir, language/stackless_bytecode/bytecode_to_boogie/test_mvir/test-reference.mvir, language/stackless_bytecode/bytecode_to_boogie/test_mvir/test-struct.mvir
I added some of the missing pieces mentioned in my last PR(#434) and fixed some bugs. 
- Mutable references passed in as arguments to function calls are returned as well because they might have been updated in the callee.
- Deep update functions are called after function calls that take in mutable references as arguments.
- Type checking for arguments. For example, in logic operations like `And` we assert `is#Boolean(op1)` and `is#Boolean(op2)`. And in the main function which we want to verify, I added `assume is#TYPE_CONS(arg)`.
- Eq and Neq functions for structs.
- Instructions related to gas/transactions/account.
- Abort/assert.
- LdAddr, LdByteArray and LdStr.
Yes.
```
cargo run FILE_NAME
```
I added assert statements in some of the test cases and all of the test cases in `test_mvir/` …
=> [language] add missing pieces to bytecode-to-boogie translator

terraform/templates/dashboards/system.json, terraform/templates/ec2_user_data.sh, terraform/validators.tf, terraform/variables.tf
We don't need remote EBS storage, and local storage is probably faster.
Deployed to mgorven workspace.
=> [terraform] Support and default to local storage instance types

benchmark/src/grpc_helpers.rs, benchmark/src/lib.rs
One of many preparing steps for a new binary that linear search the max throughput.
Reduce the amount of print out error msgs if they have already caught by counters.
Existing tests in benchmark package.
=> [benchmark] Suppress errors reported by counters.

storage/jellyfish_merkle/Cargo.toml, storage/jellyfish_merkle/src/node_type/mod.rs, storage/libradb/src/schema/jellyfish_merkle_node/mod.rs
We need to use it at different places but not only in schema.
Yes.
cargo test
https://github.com/libra/libra/pull/424#discussion_r310820978
=> [storage] move codec for NodeKey from schema to jellyfish merkle

storage/libradb/src/pruner/mod.rs, storage/libradb/src/schema/retired_state_record/mod.rs, storage/libradb/src/state_store/state_store_test.rs
With records being deleted on the smaller version side of the retire record log, seeking to
the first not-yet-deleted one gets slower and slower. While we can have more sophisticated implementation for this FIFO type data structure, remembering the current version being processed between pruning sessions is a straightforward optimization.
yes
=> [storage] Pruner optimiaztion: seek to first unpruned record faster

benchmark/src/bin/ruben.rs, benchmark/src/bin_utils.rs, benchmark/src/ruben_opt.rs
One of many preparing steps for a new binary that linear search the max throughput.
* Rename Opt to RuBenOpt. The future new binary will reuse all the arguments in RuBenOpt.
* Remove free lunch as it is never used.
Existing tests related to Benchmark package.
=> [benchmark] Adjust RuBen's StructOpt

benchmark/src/grpc_helpers.rs, benchmark/src/txn_generator.rs
One of the preparing steps for the new binary that linear searches max throughput.
After submitting all TXNs, wait for them to become committed until the last TXN expires.
Existing tests for benchmark package and throughput_test
=> [benchmark] Wait TXNs committed until the last expired

language/tools/cost_synthesis/src/module_generator.rs, language/tools/test_generation/Cargo.toml, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/common.rs, language/tools/test_generation/src/lib.rs, language/tools/test_generation/src/main.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/bitwise_instructions.rs, language/tools/test_generation/tests/boolean_instructions.rs
This PR makes it more likely that a valid bytecode sequence will be found during test generation.
Instructions can broadly be split into those that add to the stack and those that remove from the stack. This adds a probability measure to discourage adding to the stack when it its height is large, and encourage adding when the height is small. 
Yes.
Tested with tests in `tests/`
N/A
=> [VM] Consider stack size change during bytecode generation

config/src/config.rs, terraform/validator-sets/dev/node.config.toml
`grpc_max_receive_len` defaults to the same value in code. Change new
port number for consistency with new scheme.
Ran docker locally.
=> [config] Remove unnecessary default, change new port number

storage/libradb/src/pruner/mod.rs
I used to `Release` the atomic in the worker thread and `Acquire` it in the main thread (for test only), and now have realized `Relaxed` is good enough in this case since the atomic itself is the only thing that's communicated across the threads, relative ordering of other memory accesses is irrelevant.
yes
=> [storage] use Ordering::Relaxed everywhere for Prunner::worker_progress

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/proposer_election.rs, consensus/src/chained_bft/liveness/rotating_proposer_election.rs, consensus/src/chained_bft/liveness/rotating_proposer_test.rs
This change releases lock in sync_and_process_proposer before sending to `winning_proposal` channel.
This fixes deadlock between `sync_and_process_proposal` trying to send to `winning_proposal` channel while holding `event_processor` lock, and `winning_proposal_processor` trying to acquire lock to process `winning_proposal`, to unlock `winning_proposal` channel.
=> [consensus] Resolve deadlock between sync_and_process_proposal and process_winning_proposal

language/bytecode_verifier/src/abstract_state.rs, language/bytecode_verifier/src/type_memory_safety.rs, language/functional_tests/tests/testsuite/borrow_tests/borrow_global_bad0.mvir, language/functional_tests/tests/testsuite/borrow_tests/borrow_global_bad1.mvir, language/functional_tests/tests/testsuite/borrow_tests/borrow_global_bad2.mvir, language/functional_tests/tests/testsuite/borrow_tests/borrow_global_bad4.mvir, language/functional_tests/tests/testsuite/borrow_tests/borrow_global_bad5.mvir, language/functional_tests/tests/testsuite/borrow_tests/borrow_global_good.mvir, language/vm/src/errors.rs, types/src/proto/vm_errors.proto, types/src/vm_error.rs
This commit enforces that only references that are borrowed from input reference parameters
are returned by a procedure. This goal is achieved by tracking references derived from
global values (those obtained by borrow_global) for each resource type in a module.  At procedure
return, all of these references (and borrows from them) are checked to be released.
As a side effect of this enhancement, we can now also check when borrow_global<T>, exists<T>,
move_from<T>, and move_to_sender<T> are done there are no existing borrows on resource type T.
This is the first step towards elimination of dynamic reference counting on global references 
from the runtime.
I want to strengthen the borrow checker so that dynamic reference counting on global references may be eliminated.
Yes
Existing tests …
=> [language] Strengthen borrow checker

common/canonical_serialization/src/canonical_serialization_test.rs, common/canonical_serialization/src/lib.rs, consensus/src/chained_bft/block_storage/block_store_test.rs, consensus/src/chained_bft/block_storage/block_tree.rs, consensus/src/chained_bft/consensus_types/block.rs, consensus/src/chained_bft/consensus_types/block_test.rs, consensus/src/chained_bft/consensus_types/proposal_info.rs, consensus/src/chained_bft/event_processor.rs
Summary:
This diff doesn't modify the existing behavior but introduces preparations for the NIL block voting upon timeouts.
The basic idea of the NIL block voting is that different validators could vote for a special NIL block upon timeout in case they have not voted for anything else in the same round.
This way we can avoid gaps in the QC chains because the NIL QCs would be generated.
NIL blocks are special in the following way:
* timestamp: timestamps generated by different voters must be identical in order for the QC to be formed, hence it should be deterministically generated by every voter. The easiest solution today seems to determine timestamp equal to parent's timestamp + 1 us.
* author & signature: we could reuse the author and the signature we're using today for genesis.
I …
=> [Consensus] Introduce NIL Blocks

storage/jellyfish_merkle/src/jellyfish_merkle_test.rs, storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/node_type/mod.rs, storage/jellyfish_merkle/src/tree_cache/mod.rs, storage/jellyfish_merkle/src/tree_cache/tree_cache_test.rs
After #441, we can use `version` to index root node instead of hash. But there is a corner case, empty tree, which doesn't have any node to begin with for tree insertion. So we introduce a `Null` node type here for root node only as a sentinel value. Then each version will definitely has a corresponding root node with node_key {version, empty_nibble_path} existing in db. We enforce in the code that only root node can be null node.
cargo test
=> [storage][jellyfish] create null node to deal with empty tree case

network/netcore/src/multiplexing/yamux.rs, network/src/peer_manager/mod.rs, network/src/protocols/rpc/error.rs
Our yamux implementation can actually error when opening a substream,
specifically when we hit the configured `max_num_streams` limit. This
also means the implementation doesn't provide backpressure when opening
substreams, which will have to be solved eventually.
This change now converts `PeerManagerError::IoError` into
`RpcError::IoError` so we don't panic on an unrecognized error case
when the `PeerManager` returns `Err` on `open_substream`.
=> [network] Fix panic when opening too many substreams

testsuite/cluster_test/src/cluster.rs, testsuite/cluster_test/src/effects/reboot.rs, testsuite/cluster_test/src/health/liveness_check.rs, testsuite/cluster_test/src/health/mod.rs, testsuite/cluster_test/src/instance.rs, testsuite/cluster_test/src/main.rs
liveness check is still too flacky and can't be used for continuous testing.
This change improves it by increasing tolerance for commit delay.
One caveat of increased tolerance is that test passes before node even recovers from reboot, because liveness check sees commit that happened before reboot adn accepts it (reboot takes less then new accepted commit delay).
This is fixed with new `HealthCheck::invalidate` method. For liveness health check it removes information about last seen commit, making check fail for validator. This allows us to wait until validator comes back after reboot before completing experiment.
This change also removes dependency on ac port number:
Reboot effect now completes once instance starting reboot.
Previously it would wait until reboot is completed by checking …
=> [cluster_test] Improve liveness check

terraform/templates/dashboards/overview_dashboard.json
Our revision version is now 7 characters, because that's the default length you get in github, so displaying only 7 makes it easier to copy paste/search in github.
Also, we generate images with short rev now (might change in the future).
This was generated with Emacs replace-string.
yes
Tested on dev
=> 🖥 [dashboard][tiny] Update revision parsing for new rev format

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/block_store_test.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/proposal_generator_test.rs, consensus/src/chained_bft/sync_manager.rs
This is very mechanical diff - some block store functions are marked as `async` while they don't have any async code in them, this diff removes those `async` modifiers.
=> [consensus] Make some block store functions non-async

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/local_pacemaker.rs, consensus/src/chained_bft/liveness/pacemaker.rs, consensus/src/chained_bft/safety/safety_rules.rs, consensus/src/chained_bft/safety/safety_rules_test.rs
Safety doesn't depend on last_committed_round, remove it for simplicity.
Yes
=> [consensus] remove last_committed_round from safety_rules

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/mod.rs, consensus/src/chained_bft/chained_bft_smr_test.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/proposal_generator.rs, consensus/src/chained_bft/safety/safety_rules.rs
[Consensus] Vote for NIL blocks upon timeout
Summary:
In this PR we introduce a possibility to vote for an artificially generated NIL block in case the validator has not voted for anything in this round yet.
This way, the QC chains are not broken during the timeout rounds and things can get committed faster.
Note that today we check the newly received QCs when receiving proposals only, so we still don't have the commits upon timeout messages, will add it in the next commit.
Test:
* Added a test to the event processor.
* Extended the network playground to support "drop messages after X successful deliveries" and verified the HQC upon timeout messages with NIL blocks.
Task: ref #371
=> [Consensus] Vote for NIL blocks upon timeout

consensus/src/chained_bft/event_processor.rs
This field is missing before and could help peer to jump to correct round faster.
Yes
=> [consensus][fix] send highest timeout certificate with TimeoutMsg

client/Cargo.toml, config/config_builder/Cargo.toml, config/generate_keypair/Cargo.toml, crypto/nextgen_crypto/src/ed25519.rs, language/e2e_tests/Cargo.toml, language/e2e_tests/src/gas_costs.rs, language/functional_tests/_old_move_ir_tests/src/tests/key_rotation.rs, language/tools/cost_synthesis/Cargo.toml, language/tools/cost_synthesis/src/global_state/account.rs, language/vm/Cargo.toml, language/vm/src/transaction_metadata.rs, language/vm/vm_genesis/src/lib.rs, language/vm/vm_runtime/Cargo.toml, language/vm/vm_runtime/src/txn_executor.rs, language/vm/vm_runtime/src/unit_tests/runtime_tests.rs, storage/libradb/Cargo.toml, storage/libradb/src/event_store/test.rs, storage/libradb/src/mock_genesis/mod.rs, storage/libradb/src/schema/validator/mod.rs, storage/libradb/src/schema/validator/test.rs, storage/storage_service/Cargo.toml, storage/storage_service/src/mocks/mock_storage_client.rs
Removing the remaining usages of the legacy crypto signing API from the code base, most notably the functions in tests generating keypairs based on the old random generation.
YES
existing
=> [crypto] Use nextgen-crypto signing across Libra

consensus/src/chained_bft/chained_bft_smr.rs
future_locks::RwLock is already an Arc internally. This removes the extra,
unnecessary wrapper. See the docs at
https://docs.rs/futures-locks/0.3.3/futures_locks/struct.RwLock.html
I discovered this while reviewing some code in another context.
yes
This should not change any functionality, only reduce memory size of the type. Standard tests should not notice.
none
=> [consensus] Remove unnecessary Arc wrapper on futures_locks::RwLock

execution/executor/src/executor_test.rs, execution/executor/src/lib.rs
If the node restarts in the middle of syncing, the latest version from
startup info might be larger than the version in the latest ledger info.
In this case we should initialize the in-memory accumulator using the
latest transaction version, not the version from latest ledger info.
Yes.
Added a test that fails without the fix.
None.
=> [Executor] Initialize in-memory accumulator correctly after restart

types/src/proof/position.rs, types/src/proof/unit_tests/position_test.rs
This change introduces FrozenSubtreeSiblingIterator: an iterator that
generates the siblings of given frozen subtrees. This can be used to
show retrive the nodes in an accumulator that shows this accumulator can
be derived from a smaller accumulator.
Y.
CI
None.
=> [Proof] FrozenSubtreeSiblingIterator

language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop, language/functional_tests/tests/testsuite/examples/multiple_transactions.mvir, language/functional_tests/tests/testsuite/modules/modules_not_a_type.mvir
This simplifies the parser AST by getting rid of some legacy constructs. 
It also removes the need for kind annotations (V#/R#). So now you can write `x: LibraCoin.T` instead of `x: R#LibraCoin.T`. The compiler will determine the kind by resolving the name.
Note: currently annotations are still accepted by the parser. In other words "R#LibraCoin.T" is still valid syntax. However annotations are completely ignored by parser and does not make it to the AST. There will be followup codemods that will remove annotations from existing move ir code. 
cargo test
=> [language/move ir] simplify parser AST & remove kind annotations

network/build.rs, network/src/proto/mod.rs, network/src/proto/state_synchronizer.proto, network/src/validator_network/mod.rs, network/src/validator_network/state_synchronizer.rs
Add network client for state synchronization. This module will be used by the state synchronizer module to send and receive chunk request RPCs.
Added unit tests
#475 
#484 
Yes
=> [network][state sync] Add network client for state synchronizer

language/bytecode_verifier/src/abstract_state.rs, language/bytecode_verifier/src/resources.rs, language/bytecode_verifier/src/signature.rs, language/bytecode_verifier/src/type_memory_safety.rs, language/bytecode_verifier/src/verifier.rs, language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop, language/tools/cost_synthesis/src/global_state/account.rs, language/tools/cost_synthesis/src/module_generator.rs, language/tools/cost_synthesis/src/stack_generator.rs, language/vm/src/deserializer.rs, language/vm/src/file_format.rs, language/vm/src/file_format_common.rs, language/vm/src/printers.rs, language/vm/src/proptest_types.rs, language/vm/src/proptest_types/signature.rs, language/vm/src/resolver.rs, language/vm/src/serializer.rs, language/vm/src/views.rs, language/vm/vm_runtime/src/unit_tests/module_cache_tests.rs, language/vm/vm_runtime/src/unit_tests/runtime_tests.rs, language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, language/vm/vm_runtime/vm_runtime_types/src/native_structs/dispatch.rs
- Kinds are a in weird spot currently where Kind's are used for multiple purposes
- Struct Defintions no longer have a a kind. Instead they now have a `is_nominal_resource` flag. Only types should have kinds
- Nominal resources are the "root" resources. At some point, a type NEEDS to be declared a resource (instead of just being inferred as a resource from it's type arguments)
- Types can now be in two kinds `Resource` or `Unrestricted`. There is a kind `All` to represent the union of the two, which is used when the type is existential
- I chose `Unrestrictred` over `Copyable` since they can also be popped and dereferenced and mutate. None of those things are conveyed via `Copyable`. I still think `T: copyable` is a good UX choice for the language, but it feels off for an internal name 
- …
=> [VM] Restructure Kinds

language/stdlib/modules/libra_account.mvir, language/stdlib/modules/libra_coin.mvir, language/stdlib/modules/validator_set.mvir, language/stdlib/modules/vector.mvir
Followup of #472. This removes the kind annotations in stdlib modules.
cargo test
=> [language/stdlib] remove kind annotations

config/src/utils.rs, language/bytecode_verifier/bytecode_verifier_tests/src/unit_tests/code_unit_tests.rs, language/bytecode_verifier/src/control_flow_graph.rs, language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/src/unit_tests/cfg_tests.rs, language/compiler/src/unit_tests/expression_tests.rs, language/functional_tests/src/evaluator.rs, language/functional_tests/src/tests/global_config_tests.rs, language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, network/src/peer_manager/mod.rs, network/src/protocols/peer_id_exchange.rs, storage/jellyfish_merkle/src/node_type/node_type_test.rs, storage/sparse_merkle/src/node_type/mod.rs
##Motivation
We should prefer `assert_eq` when possible as it's more declarative and it allows for more detailed assertion failed messages.
YES
existing tests
=> Use `assert_eq` when possible

consensus/src/chained_bft/chained_bft_smr_test.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/local_pacemaker.rs, consensus/src/chained_bft/liveness/local_pacemaker_test.rs, consensus/src/chained_bft/liveness/pacemaker.rs
Summary:
A validator can receive QCs via multiple ways: proposals, timeout certificates, QCs that are aggregated by the validator itself.
We used to send these QCs to SafetyRules and process the corresponding commits only if the QC is received via proposal.
However, once we introduce the NIL block voting we want to be able to commit blocks via the QCs that are generated during the timeouts: in this change we're adding QC processing to some several other places.
Tests: Extended the NIL block voting test to verify that a commit happens upon timeout.
Task: ref #371
=> [Consensus] Process QCs not only from proposals

testsuite/cluster_test/src/experiments/mod.rs, testsuite/cluster_test/src/experiments/reboot_random_validator.rs, testsuite/cluster_test/src/health/log_tail.rs, testsuite/cluster_test/src/main.rs
Rename RebootRandomValidator -> RebootRandomValidators and support simultaneous multiple validators reboot as experiment.
This PR also contains retry for rare kinesis failures(as separate commit)
=> [cluster_test] Reboot multiple validators

storage/libradb/src/event_store/mod.rs
#532 removed this line and consensus tests are broken.
Y
cargo test -p consensus
#532
=> [storage] add back one missing line in event_store

docker/bench/bench_init.sh
Remove unused option in benchmark image entry script.
This option was required, but got removed from code and left as optional argument to make sure deployment scripts do not break after the code is committed.
Now it's time to cleanup.
Y
None. This argument is unused, and stayed there for flexibility in updating deploy scripts and code.
=> [docker][tiny] Remove unused debug interface option from benchmark script

terraform/templates/dashboards/execution.json
Update the time spend in storage to save txns chart as the counter
`block_execute_time_us` has been updated to `block_execute_time_s`
Yes
Updated on the dashboard and exported from there.
=> [execution] fix time spend in storage to save txns chart

consensus/src/chained_bft/event_processor.rs, consensus/src/util/time_service.rs
Summary:
In one of the recent changes I accidentally dropped the check on whether the wait before vote has succeeded (happens in case a block timestamp is slightly ahead of validator's local clock).
Fixing it in this PR.
Tests: consensus existing unit tests
=> [Consensus][small] Fix `wait_before_vote` function

network/src/protocols/rpc/mod.rs, network/src/protocols/rpc/utils.rs, network/src/validator_network/consensus.rs
Any client needing to implement RPC would end up re-implement this logic. So good to centralize in a `util` library.
Yes
=> [network] Create RPC util library for unary_rpc

libra_node/src/main_node.rs, network/benches/network_bench.rs, network/src/counters.rs, network/src/validator_network/network_builder.rs, network/src/validator_network/test.rs, state_synchronizer/src/tests.rs
Dedicated network sender and network event stream for State Synchronizer will allow splitting State Synchronizer from Consensus.
Yes
#512
=> [network][state sync] Integrate state sync sender and event stream into network builder

storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/node_type/mod.rs, storage/jellyfish_merkle/src/node_type/node_type_test.rs
An internal node can only be valid if it has:
1. 1 child, must be non-leaf
2. 2+ children, any type
We enforce this rule in this PR to prevent any bug in the future.
Y
Cargo test
=> [storage] assert the validity of an internal node at the creation

storage/libradb/Cargo.toml, storage/libradb/src/ledger_store/mod.rs, storage/libradb/src/lib.rs
Right now we read latest ledger info from DB every time we need it, but deserializing the signatures seems expensive.
Yes.
CI
=> [Storage] Cache latest ledger info in memory

testsuite/cluster_test/Cargo.toml, testsuite/cluster_test/src/aws.rs, testsuite/cluster_test/src/deployment.rs, testsuite/cluster_test/src/health/log_tail.rs, testsuite/cluster_test/src/lib.rs, testsuite/cluster_test/src/main.rs
This diff introduces auto-update into cluster test.
To achieve this, cluster test periodically queries ECR and gets hash of docker image corresponding to some predefined tag.
If hash of image changes, cluster test redeploys validators, and wait for them to become healthy before running experiment.
This diff also adds `--wipe-all-db` command to quickly wipe db of all validator in cluster.
=> [cluster_test] Re-deploy validators when image hash changes

storage/scratchpad/Cargo.toml, storage/scratchpad/src/accumulator/accumulator_test.rs, storage/scratchpad/src/accumulator/mod.rs, types/src/proof/position.rs
This functionality will be used when we need to verify the proof showing
that two accumulators are consistent -- one of them can be obtained by
appending certain items to the other.
Here `append_siblings` will compute the new root hash of the accumulator
with newly appended items.
Yes.
CI.
None.
=> Implement Accumulator::append_siblings

benchmark/Cargo.toml, benchmark/src/bin/ruben.rs, config/config_builder/src/bin/libra-config.rs, config/config_builder/src/swarm_config.rs, libra_swarm/src/main.rs, libra_swarm/src/swarm.rs, testsuite/Cargo.toml, testsuite/tests/libratest/smoke_test.rs, testsuite/tests/libratest/throughput_test.rs
Currently when launching Libraswarm, we can only configure the number of validator nodes to spin up. Once we have full nodes, we want to test having full nodes as part of Libra swarm. This diff changes the "num_nodes" param to a struct LibraSwarmTopology, which has a vector of sizes in this order: vec['num_nodes', 'num_full_nodes']. Passing in vec[2, 2] will create 2 validators, each with 2 full node.
Full node is in development, so launch_swarm only takes the first value (num_nodes).
cargo test ran successfully
=> Libra swarm to take parameter topology instead of single number of validators

storage/accumulator/src/lib.rs, types/src/proof/position.rs, types/src/proof/unit_tests/position_test.rs
Exposing both position and treebits modules is a bit confusing. This
change makes sure the codebase uses only position so we can change
treebits to be a private module inside position next.
Yes.
CI.
None.
=> [Proof] Stop using treebits module outside position

execution/executor/src/block_processor.rs, storage/scratchpad/src/accumulator/mod.rs
To verify accumulator consistency proof, we will need to construct the small accumulator using the frozen subtree roots in the proof. Since the proof may not be valid, we change `Accumulator::new` to return a `Result`.
Yes.
CI.
None.
=> [Proof] Change Accumulator::new to return Result

benchmark/Cargo.toml, benchmark/src/bin/max_throughput.rs, benchmark/src/bin/ruben.rs, benchmark/src/bin_utils.rs, benchmark/src/cli_opt.rs, benchmark/src/lib.rs, testsuite/tests/libratest/throughput_test.rs
* By submitting TXNs at constant rates and keeping increasing the rate by `inc_step`, search the maximum throughput within `[lower_bound, upper_bound]`. Search can end earlier when commit to submit ratio is less than a predefined threshold.
* Transaction volume is increasing by adding more new accounts into the network during search.
* For each submission rate, average throughput value over several epochs are calculated and used in comparing. The maximum of these moving-window-average values is reported when search end.
Search the max throughput of my own server. The shortest one takes around 30 mins
```
./target/release/lisar -f faucet_for_ruben -s temp_config \
-e 1 -m localhost:45345 -l 50 -i 5 -b 1
......
Commit ratio at submit rate 155 per client is 0.6416
Search ends ealier as …
```
=> [benchmark] Search max throughput by linearly increasing submission speed and TXN volume.

types/src/proof/mod.rs, types/src/proof/position/mod.rs, types/src/proof/position/position_test.rs, types/src/proof/position/treebits/mod.rs, types/src/proof/position/treebits/treebits_test.rs, types/src/proof/unit_tests/mod.rs
Exposing both `position` and `treebits` modules seems a bit confusing. Instead make `treebits` a private module inside `position`.
Yes.
CI.
None.
=> [Proof] Make treebits a private module inside position

consensus/src/chained_bft/liveness/local_pacemaker.rs, consensus/src/chained_bft/test_utils/mock_state_computer.rs, consensus/src/chained_bft/test_utils/mock_txn_manager.rs, consensus/src/state_computer.rs, consensus/src/txn_manager.rs
It's more idiomatic to use the util functions than creating a closure when we don't need await.
Y
=> [consensus][nit] use future::ready/ok/err

testsuite/libra_fuzzer/Cargo.toml
https://github.com/libra/libra/pull/582 breaks the fuzzer (spec. `libra_fuzzer/fuzz`). I [noticed the issue](https://github.com/libra/libra/pull/582#issuecomment-521506806) before merging, but my fat fingeers missed inserting the fix in the [new version of the PR](https://github.com/libra/libra/compare/8b5bc542505c6bf8d03f71c2080d1a556ed75236..dd3eb647b638ebee7b8e6205d66d558eb48e6900).
The fix is hereby attached.
=> [easy] Fix Post 582

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/mod.rs, consensus/src/chained_bft/consensus_types/block.rs, consensus/src/chained_bft/consensus_types/block_test.rs
Summary: We used to have nil block timestamps equal to their parents timestamps. However, execution uses LedgerInfo timestamps for verifying that the state synchronization requests are moving the system forward.
There are several alternative options we could take: 1) remove the check from execution, 2) add a round field to LedgerInfo, and 3) have NIL blocks incrementing timestamps.
The simplest one for now is to just have a NIL block timestamp = parent timestamp + 1 us
Tests: unit tests
Issue: ref #371
=> [Consensus][small] Nil block timestamp

crypto/legacy_crypto/src/hash.rs, crypto/nextgen_crypto/src/bls12381.rs, crypto/nextgen_crypto/src/ed25519.rs, crypto/nextgen_crypto/src/traits.rs, crypto/nextgen_crypto/src/unit_tests/cross_test.rs, crypto/nextgen_crypto/src/x25519.rs, crypto/secret_service/src/crypto_wrappers.rs, storage/libradb/src/schema/validator/mod.rs
*What this does*
Makes us rely on constants in the individual signing scheme's declarations for length information rather than on a (mostly unused) generic method.
Removes dead code.
(see individual commit messages)
*Why this is better*
Makes union types (in cross_test, secret_service) more regular.
*Why this is worse*
n/a
*Tests & TODO*
Technically augments code coverage (red diff)
=> [crypto] Removes public key lengths from API + cleanup

language/README.md
A previous commit moved files around:
https://github.com/libra/libra/commit/dba7a61e6b4d84b416c96c25e057a9f2e9ee9996
This rendered these 2 links invalid. Updated paths to new locations for these files.
Fixes broken links.
yes
view rendered md and open links, validate they no longer return 404
n/a
=> Update README.md after compiler split

client/libra_wallet/src/wallet_library.rs, client/src/client_proxy.rs, client/src/lib.rs, testsuite/Cargo.toml, testsuite/tests/libratest/smoke_test.rs, types/src/transaction_helpers.rs
This enhancement separates the construction and the submission of a transfer transaction into 2 separate routines:
* `prepare_transfer_coins` - construct and return a transfer (unsigned) RawTransaction.
* `submit_signed_transaction` - construct and submit a signed transaction from an unsigned raw transaction, a signature, and the respective public key.
This is useful for plugging in an external transaction signer, e.g., a hardware wallet or a threshold signature scheme.
Yes.
Yes, Corporate CLA. Confirmed with Kostas and Eric.
Added `test_external_transaction_signer` in testsuite/tests/libratest/smoke_test.rs. 
https://github.com/libra/libra/pull/438
=> [crypto] Support external transaction signer

testsuite/libra_fuzzer/README.md, testsuite/libra_fuzzer/src/commands.rs, testsuite/libra_fuzzer/src/fuzz_targets.rs, testsuite/libra_fuzzer/src/fuzz_targets/compiled_module.rs, testsuite/libra_fuzzer/src/fuzz_targets/vm_value.rs, testsuite/libra_fuzzer/src/lib.rs, testsuite/libra_fuzzer/src/main.rs
Some fuzz targets will only be able to generate 1 corpus value or even none at all.
(Also tacked on a readme update)
=> [libra_fuzzer] add a way for a fuzz target to skip generation

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/consensus_types/sync_info.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/proposer_election.rs, consensus/src/chained_bft/liveness/rotating_proposer_election.rs, consensus/src/chained_bft/liveness/rotating_proposer_test.rs, consensus/src/chained_bft/sync_manager.rs
We think the current design is over-complicated because of the concurrent message processing. It results in error-prone and hard-to-debug/understand code.
And the nature of hotstuff protocol is sequential progressing(propose -> vote -> QC and propose), we think a simpler solution might work too.
This is the first PR to switch to sequential processing by removing concurrent proposals.
Yes
=> [consensus] remove concurrent proposal processing

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/mod.rs
Continued from last PR https://github.com/libra/libra/pull/515, this PR merges how we process ProposalMsg into a single function and also rename process_proposal -> pre_process_proposal, process_winning_proposal -> process_proposed_block.
It also reorganized the impl struct so that private functions stay in a separate block.
Y
=> [consensus] merge process_winning_proposal and process_proposal and re-naming/organize

language/stackless_bytecode/bytecode_to_boogie/output.bpl, language/stackless_bytecode/bytecode_to_boogie/src/translator.rs
As the title of this PR suggests, I
- Refactored translator code so that generation of different parts of the code now happen in different functions. For example, now there are separate `generate_function_sig` and `generate_function_body` for generating signature and body of a function. This is useful for specification generation which I'm also working on. 
- Added support for variable mapping. If argument names are provided in the form of `Option<Vec<String>>`, generated Boogie will refer to the actual names of the arguments instead of temporaries like `t1`. This is also useful for specification generation since specs are written on IR level and refer to actual variable names.
Yes.
```
cargo run FILENAME
```
#434
#461 
#524
=> [languages] refactor code and add support for variable naming

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/lib.rs
Continued from https://github.com/libra/libra/pull/579, this PR we switch from multiple concurrent tasks to one single task polling new events.
Y
=> [consensus] switch from concurrent event processor to sequential

client/src/client_proxy.rs
Association address was modified in some previous PR, but the client is still listening to the old address.
Yes
Checked minting locally against testnet
=> [client] Fix bug in client minting

language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop
- Added Acquires list to Move IR AST
- It is parsed after the return type before the body of the function
- It is passed onto the bytecode, but not yet verified
- Not yet added to core contracts or tests, thats the next PR
cargo check; cargo test
Continuation of #575
=> [language][MoveIR] Added Parsing and Compiler Support for Acquires List

.circleci/config.yml, docker/circleci/build.sh, docker/circleci/circleci.Dockerfile
This installs and uses sccache for builds. The resulting cache file is stored
between CircleCI runs using CicleCI's caching system. While not perfectly
cacheable yet, this saves about 30% of build time.
See blog post about this at https://medium.com/@edouard.oger/rust-caching-on-circleci-using-sccache-c996344f0115
Builds times can always be faster.
yes
Current build times are ~15-20m on CI. This should reduce builds to ~10-15m. You can check in the [CircleCI jobs page](https://circleci.com/gh/libra)
none
=> [ci] Enable sccache to speed up build times

storage/libradb/src/ledger_counters/mod.rs, storage/libradb/src/ledger_counters/test.rs, storage/libradb/src/state_store/mod.rs, storage/libradb/src/state_store/state_store_test.rs
I think we are gonna use `Bell` and `Tentacle` to replace `Internal` and `Leaf`. More PRs are coming.
Y
Cargo test
=> [storage] change ledger_counter name related to jellyfish merkle

benchmark/src/cli_opt.rs
Final cleanup step to get rid of debug interface in benchmark.
Existing tests
```
$ ./target/release/ruben -f faucet_for_ruben -s temp_config -d localhost:9000
error: Found argument '-d' which wasn't expected, or isn't valid in this context
```
```
$ ./target/release/ruben -f faucet_for_ruben -s temp_config --debug_address localhost:9000
error: Found argument '--debug_address' which wasn't expected, or isn't valid in this context
```
Run `rg debug benchmark` and check no debug interface related code.
=> [benchmark] Remove debug_address option.

common/canonical_serialization/src/canonical_serialization_test.rs, common/canonical_serialization/src/lib.rs, types/src/transaction.rs, types/src/transaction/program.rs, types/src/transaction/unit_tests/mod.rs, types/src/transaction/unit_tests/program_test.rs, types/src/unit_tests/transaction_test.rs, types/src/unit_tests/write_set_test.rs, types/src/write_set.rs
This tackles the serialization subtasks from refs #454
- CanonicalSerialization support for TransactionPayload(Program, WriteSet)
- WriteSet contains AccessPath, which already supports CS, and WriteOp, which needs it
- WriteOp consists of a vec and primitves
- Program contains vec, primitives, and TransactionArguments
- Transaction arguments are a type field (i32) and a primitive (string, byte u64)
- Add serialization unit tests
=> [common,type] Add more CanonicalSerialiazation support

language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop
Summary:
- The parser and AST currently supports prototype verification constructs `requires <string>`, `ensures <string>`, `verify <string>` and `assume <string>`. These are not used by any tooling downstream.
- We decided that ordinary procedures (or perhaps a special native module) would be a better way to implement `verify`/`assume` because we can also have optional runtime checking.
- We will likely want `requires`/`ensures` in the IR in the future, but they will be implemented using something more structured than a string (e.g., so we can match formals to variables used in the IR).
Test Plan:
`cargo test`, there actually weren't any tests for this parser functionality.
=> [language] remove unused verification annotations from parser/AST

storage/libradb/src/lib.rs
Summary:
There is no need to create vectors and zip them all together
at the end; just zip directly with the transactions.
There is no need to create vectors and zip them all together
at the end; just zip directly with the transactions.
This is cleanup prep before I make some changes to transaction commit.
I can't read.
cargo test; CI
=> [storage] Improve iterators during TXN Commit

types/src/proof/definition.rs
This change introduces `AccumulatorConsistencyProof` that shows one accumulator can be obtained by appending leaves to the other accumulator.
Yes.
Proof generation, verification and tests will be in another change.
None.
=> [Proof] Introduce AccumulatorConsistencyProof

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/block_tree.rs, consensus/src/chained_bft/block_storage/mod.rs
*What this does*:
- remove `is_ancestor` from block storage,
- remove `print_all_blocks`.
*Why this is better*:
- no code or test is using this,
*Why this is worse*:
- it's not
=> [consensus] Cleanup unused, untested helper methods in consensus

libra_node/Cargo.toml, libra_node/src/main_node.rs, network/benches/network_bench.rs, network/src/interface/mod.rs, network/src/validator_network/mod.rs, network/src/validator_network/network_builder.rs, network/src/validator_network/test.rs, state_synchronizer/src/tests.rs
`NetworkBuilder` currently constructs the consensus and mempool network handles by default. In the case of full nodes, if these handles are constructed but the corresponding modules are not initialized, we observe `panic!` in network code attempting to send events (such as `NewPeer`) to all upstream handlers.
With this PR, the goal is to modularize the construction of upstream handlers over the vanilla network stack. To accomplish this, we split construction of upstream senders and event handlers from `NetworkBuilder` and move it to `NetworkProvider`. Users now follow the following steps when setting up the network:
```
let (listen_addr, mut network_provider) = NetworkBuilder::new(...)
.foo()
.bar()
.build();
let (upstream_sender, upstream_events) = network_provider.add_mempool([..mempool …
```
=> [network] Refactor NetworkBuilder to enable modularized construction

types/src/account_config.rs
```
Compiling types v0.1.0 (/Users/wqfish/github/libra/types)
warning: unused import: `crypto::HashValue`
--> types/src/account_config.rs:19:5
|
19 | use crypto::HashValue;
|     ^^^^^^^^^^^^^^^^^
|
= note: #[warn(unused_imports)] on by default
```
Yes.
CI.
None.
=> [Types] Fix warning

language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop
=> [language][MoveIR] remove unused get_height construct

state_synchronizer/src/coordinator.rs, state_synchronizer/src/executor_proxy.rs, state_synchronizer/src/lib.rs, state_synchronizer/src/synchronizer.rs, state_synchronizer/src/tests.rs
adds support for normal full node workload
`autosync` parameter is added
In `autosync` mode, state synchronizer tries to fetch new data from upstream nodes even if no target version was set
notes:
* for Full Nodes peers will be discovered through networking stack. For Validator from relevant QC
* it's basic implementation. Works closer to rpc model than long polling. For latter we need request queue and async notification. Will be added in separate diff
* added API to state sync client to query/debug internal state. So far it includes known version only
* executor_proxy was moved to separate file
`test_full_node` is added
=> [state sync] full node support

storage/jellyfish_merkle/src/lib.rs, storage/storage_client/src/state_view.rs, storage/storage_proto/src/lib.rs, storage/storage_service/src/mocks/mock_storage_client.rs, types/src/proof/mod.rs
There is some minor inconsistency that some code uses `types::proof:xxx` but other code uses `types::proof::definition::xxx`. This change makes `definition` private.
Y.
CI.
None.
=> [Proof] Make definition module private

.circleci/config.yml
This fixes the audit workflow, which is incorrectly trying to use sccache currently.
This was broken by #507, as it applied RUSTC_WRAPPER even on the audit workflow which did not have sccache installed, which caused failures like https://circleci.com/gh/libra/libra/2383.
Noticed audit workflow errors.
yes
If the normal CI workflows run successfully on this PR and still use caching, this should be good to go.
=> Split out sccache environment as not all workflows use it.

config/config_builder/src/swarm_config.rs, libra_swarm/src/main.rs, libra_swarm/src/swarm.rs, testsuite/Cargo.toml, testsuite/tests/libratest/smoke_test.rs
To test the behavior of full nodes and validators, we need to add the ability to spawn full nodes in the swarm environment. This commit adds logic to launch full nodes by setting necessary node config values with the correct role (Validator or Full Node). Alias has been introduced for creating unique filepaths and directories for validators and its connecting full nodes.
test_full_node() in smoke_test.rs tests that full nodes spawned in swarm can fulfill read requests, but not write requests. Note that the case where there are multiple validators are broken, because we do not have proper networking setup for fullnodes to connect to validators yet.
=> [swarm] Add ability to spawn full nodes in swarm

common/executable_helpers/Cargo.toml, language/vm/vm_genesis/src/lib.rs, types/src/lib.rs
*The behavior this modifies*:
- don't import config in a "testing" context in executable_helpers' [dependencies]
- remove uneeded private key cloning in vm_genesis
*Why this is better*:
- fixes a subtle transitive import of crypto under [test]
- removes uneeded private key cloning
*Why this is worse*:
- n/a
*Test*:
`find ./ -iname "Cargo.toml" -execdir cargo check --all-targets \;`
to check there's no more bad version of the testing import:
` ag '\[dependencies\](\n|[^\[])*testing'`
*TODO*:
linter for Cargo.toml files (#627)
=> [language, types] Remove erroneous masking import, last non-test private key clone

documentation/coding_guidelines.md, execution/execution_tests/Cargo.toml, network/Cargo.toml
*What this does*:
- document profiles are not a good way out of conditional test compilation and why,
- adds a "testing" flag to network, execution_tests imports, uncaught by CI
*Why this is better*:
- You'll know to avoid trying to re-do feature activation through profiles,
- Can compile network /execution independently
*Why this is worse*:
- n/a
*Testing*:
```
find ./ -iname Cargo.toml -execdir cargo check --all-targets \;
```
=> [doc, network] Document profiles in conditional compilation

language/bytecode_verifier/src/type_memory_safety.rs, language/functional_tests/tests/testsuite/dereference_tests/deref_eq_bad.mvir, language/functional_tests/tests/testsuite/dereference_tests/deref_eq_good.mvir
Eq and Neq can be applied to references.  The meaning is that
values obtained by dererencing are compared.  Therefore, checks
applied at ReadRef must be applied here also.  This diff adds
these extra checks.
Yes
Existing tests + two new tests
=> [language] bug fix in type checking of Eq and Neq

testsuite/libra_fuzzer/fuzz/Cargo.toml
Testing for fuzz targets is covered by `cargo test` in `testsuite/libra_fuzzer`.
Closes #624.
=> [libra_fuzzer] disable test target for fuzz_runner

consensus/Cargo.toml, consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/consensus_types/block.rs, consensus/src/chained_bft/consensus_types/timeout_msg.rs, consensus/src/chained_bft/liveness/pacemaker.rs, language/bytecode_verifier/Cargo.toml, language/vm/Cargo.toml
Updated mirai-annotations to latest version (1.3.1) which supports post-conditions.
Added preconditions to handle addition overflow errors reported by MIRAI.
Yes
`cd consensus; RUSTC_WRAPPER=mirai cargo check`
=> [consensus] Libra mirai

execution/execution_tests/src/tests/storage_integration_test.rs, network/src/validator_network/test.rs, types/src/test_helpers/transaction_test_helpers.rs, types/src/transaction.rs, types/src/validator_set.rs, types/src/validator_signer.rs, types/src/validator_verifier.rs
- remove `verify_message` from `validator_signer` (SoC)
- remove, `new_empty` from `validator_verifier` (pedantic w/ good alternatives)
- remove `make_from` from `ValidatorSet` (unused, weird code path to deserialize from)
- remove `as_inner` from `transaction` (unused, good alternative nearby)
- remove `create_signed_transactions_block` from `transaction_test_helpers` (unused, pedantic, test helper)
=> [types] Removes unused code from some crypto-related data structures

language/vm/vm_runtime/Cargo.toml, language/vm/vm_runtime/src/block_processor.rs, language/vm/vm_runtime/src/code_cache/module_cache.rs, language/vm/vm_runtime/src/data_cache.rs, language/vm/vm_runtime/src/lib.rs, language/vm/vm_runtime/src/loaded_data/loaded_module.rs, language/vm/vm_runtime/src/process_txn/execute.rs, language/vm/vm_runtime/src/process_txn/validate.rs, language/vm/vm_runtime/src/process_txn/verify.rs
This commit addresses potential vector overflows in the VM runtime. These overflows are addressed by two methods:
- Showing that the overflow will not actually occur.
- Using Rust's checked add to detect the presence of an overflow and raise an appropriate error.
Yes.
Passes existing tests. To reproduce the analysis performed by MIRAI, please run `RUSTC_WRAPPER=mirai MIRAI_LOG=warn cargo build --features "mirai-contracts"` from the VM directory.
#503
=> [VM] Audit potential vector overflows

language/vm/vm_runtime/src/lib.rs
Remove the duplicate MIRAI annotations import in `vm_runtime/src/lib.rs`.
Yes.
Local testing with `cargo test`.
N/A
=> [VM] Remove duplicate MIRAI annotations import

terraform/templates/validator.json, terraform/validators.tf, terraform/variables.tf
To run some experiments, we may need to add additional capabilities to the
ecs task. For example, to inject network delay using the `netem` tool,
`net_admin` capability is needed.
This PR adds the parameter for adding capabilities, but the default value
is empty which doesn't affect production. In the experiments we run,
just set this parameter explicitly to add the special capabilities.
Yes
Deployed with 100 nodes with `net_admin` capability, was able to inject network delay using `netem`
=> [terraform] add a variable for adding capabilities as linux parameter

language/vm/vm_genesis/src/main.rs
It's easy to commit code that would change the genesis blob without regenerating it. This PR adds a test that will flag such changes.
Added code that changed the genesis blob without updating it, checked that the test failed
=> [language] test that flags genesis blob changes

execution/executor/src/block_processor.rs, execution/executor/src/mock_vm/mod.rs, language/e2e_tests/src/account.rs, language/e2e_tests/src/tests.rs, language/e2e_tests/src/tests/bad_txn.rs, language/functional_tests/_old_move_ir_tests/src/tests/transactions.rs, language/functional_tests/_old_move_ir_tests/src/tests/verify_transaction.rs, language/vm/vm_runtime/src/process_txn/execute.rs, language/vm/vm_runtime/src/process_txn/validate.rs, language/vm/vm_runtime/src/process_txn/verify.rs, types/src/proptest_types.rs, types/src/proto/transaction.proto, types/src/transaction.rs, types/src/transaction/module.rs, types/src/transaction/script.rs, types/src/transaction/transaction_argument.rs, types/src/transaction/unit_tests/program_test.rs
We want to move away from Program transactions where execution and
publishing are in a single transaction.
There are several problems and complications with that model.
The plan is to have 2 kind of transactions:
- Script which are execution only transactions (CompiledScript)
- Module which are publishing only transactions (CompiledModule)
This diff defines the 2 type of transactions without removing Program yet.
This diff should be backward compatible and it should change nothing in the way
transactions are submitted and executed.
We are only defining the transaction type (Script/Module) and enabling
ser/deser tests for them. However the transactions are not supported yet by the VM
and they report an error if they are submitted to AC or the Executor.
The sequence of diffs and PRs is …
=> [execution][vm] Introduce Script and Module transactions.

docker/bench/bench.Dockerfile, docker/bench/bench_init.sh
I'm currently following the docker for libra project and realized that bench docker was commit with older port number 14297 (metrics_server_port). 
Ref https://github.com/libra/libra/commit/283e17f5a687f003deb100674979598cec385a99
To avoid mistake in near future, I propose update port as the same.
Yes,
Test Plan: Built docker images, ran locally. Deployed to my workspace.
=> [Network] Fixed wrongly port assigned from old metrics port 14297 to new metrics port 9101

config/src/config.rs, network/src/validator_network/state_synchronizer.rs, state_synchronizer/src/coordinator.rs, state_synchronizer/src/tests.rs
If upstream synchronizer doesn't have required data and requested timeout > 0, we'll add it to subscription queue. Entry will be removed from queue once either new chunk is ready or request is expired
modified full_node sync test
=> [state sync] long polling support

consensus/src/chained_bft/chained_bft_smr.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/pacemaker.rs, consensus/src/chained_bft/liveness/pacemaker_test.rs
This PR simplifies pacemaker further:
- new_round_event is returned as function result instead of sending through channels
- remove await/async from pacemaker
- jump start is now more unified with existing certificates.
Y
=> [consensus] cleanup after sequential event processor - part 4

types/src/proof/definition.rs, types/src/proof/proptest_proof.rs
These traits implementations can be derived.
Y
CI
=> [Proof] Derive Arbitrary instead of manually implementing it for a few types

config/src/config.rs, state_synchronizer/src/coordinator.rs
Sanity check for chunk limit and timeout parameters for chunk request. If the parameters are above certain value as passed in through state synchronizer config, abandon request and log an error message.
=> [state-sync] Validate request chunk parameters

types/src/proof/definition.rs, types/src/proof/proptest_proof.rs, types/src/proof/unit_tests/proof_proto_conversion_test.rs, types/src/proto/proof.proto
For the frozen subtree roots, they should not contain any default hashes, so we simply write these hashes. For the siblings, note that they always start with some non-default hashes, followed by some default hashes, so we just need to write the non-default ones as well as the total number of siblings.
Yes.
CI.
=> [Proof] Implement FromProto and IntoProto for AccumulatorConsistencyProof

execution/executor/src/lib.rs, storage/libradb/src/lib.rs, storage/storage_client/src/lib.rs, storage/storage_proto/src/lib.rs, storage/storage_proto/src/proto/storage.proto, storage/storage_proto/src/tests.rs, storage/storage_service/src/lib.rs, storage/storage_service/src/mocks/mock_storage_client.rs
Currently state synchronizer has no way to get the latest `transaction_info`. So we rename `startup_info` to make it general since it can be used by both `executor` and `state_synchronizer`.
Y
CI
=> [storage] rename executor_startup_info to startup_info

execution/executor/src/block_processor.rs, execution/executor/src/executor_test.rs
Currently, if a transaction chunk is not the last chunk corresponding to the ledger info, and it is empty (or it is not empty but all the transactions in the chunk have been committed, for example this could happen if a chunk is sent to executor twice), storage would return an error since it expects either new transaction or new ledger info.
Fix this by not calling `save_transactions` in this case.
Yes.
Added a few test cases.
None.
=> [Executor] Handle empty chunks during state synchronization

state_synchronizer/src/coordinator.rs, state_synchronizer/src/executor_proxy.rs, state_synchronizer/src/tests.rs
right now known_version in StateSyncrhonizer is derived from latest_ledger_info
it's not always correct. During cathing up phase, storage version will make progress, while latest ledger info will be the same until last chunk
=> [state sync] use new API to fetch latest version

testsuite/cluster_test/src/health/commit_check.rs
We maintain map from round to commit to check safety, this PR makes sure this map does not grow too large.
We verify separately, that committed rounds for each validator always go up.
This means we can pick lowest committed round across all validators and remove all entries from this map for rounds below lowest committed round.
Because we allow progress to happen between experiments, this technique should keep map relatively small.
=> [cluster_test] Fix commit_check OOMing cluster_test

consensus/Cargo.toml
We no longer use it after simplifying concurrency in event_processor
Hopefully we not going to need it in future as well.
=> [consensus] Remove future_lock dependency

storage/jellyfish_merkle/src/jellyfish_merkle_test.rs, storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/tree_cache/mod.rs
unsorted node cache may result in overlapping L0 files in rocksdb.
Y
CI
=> [storage] make node_cache sorted

common/futures-semaphore/Cargo.toml, common/grpc_helpers/Cargo.toml, execution/execution_service/Cargo.toml, execution/execution_tests/Cargo.toml, network/netcore/Cargo.toml, network/socket_bench_server/Cargo.toml, storage/storage_client/Cargo.toml, storage/storage_service/Cargo.toml, testsuite/libra_fuzzer/fuzz/Cargo.toml
After this, the only versions in use in the code base are 0.1.28 (old style) and 0.3.0-alpha.17 (new style).
(minimal impact expected)
```
find ./ -iname Cargo.toml -execdir cargo check --all-targets \; 
```
=> [easy] Updates futures dependency to binary-compatible versions

common/metrics/src/lib.rs, common/metrics/src/op_counters.rs, consensus/src/chained_bft/block_storage/block_tree.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/liveness/proposal_generator.rs, consensus/src/chained_bft/network.rs, consensus/src/chained_bft/sync_manager.rs, consensus/src/counters.rs, consensus/src/state_computer.rs, execution/executor/src/block_processor.rs, mempool/src/core_mempool/mempool.rs
This PR makes our histograms for time duration usable by matching the values we log to the buckets we use. This enables us viewing percentile values (p50, p99, etc) and not just averages for duration. 
It also adds a small helper struct to log `Duration` struct directly, so code that tries to use it doesn't have to deal with unit conversions.
I'd want to squash it before merging
(y)
I ran it locally and checked that new buckets look good, values are distributed to many buckets (and not just the last one as previously).
=> Time historgram buckets

language/bytecode_verifier/src/absint.rs, language/bytecode_verifier/src/code_unit_verifier.rs, language/bytecode_verifier/src/control_flow_graph.rs, language/compiler/src/unit_tests/cfg_tests.rs
The abstract interpreter relies on a specific implementation of the CFG. This commit makes it rely on a CFG trait instead. Making the CFG more abstract will make it easier to support useful features like backward analysis without changing the interpreter.
Existing tests, Should be pure refactoring.
=> [language] Cfg trait

storage/jellyfish_merkle/src/node_type/mod.rs
Let's go back to our old-school encoding to alleviate the ordering issue of `version | nibble_path`.
Y
CI
=> [storage] change jellyfish node_key encoding

storage/libradb/src/ledger_store/ledger_info_test.rs, storage/libradb/src/ledger_store/mod.rs, storage/libradb/src/schema/ledger_info/mod.rs
we will use mostly epoch number to query `ledger_info`, needed by consensus reconfig.
Y
CI
=> [storage] change ledger_info key from Verison to epoch_num

language/bytecode_verifier/src/absint.rs, language/bytecode_verifier/src/control_flow_graph.rs, language/bytecode_verifier/src/stack_usage_verifier.rs, language/compiler/src/unit_tests/cfg_tests.rs
Another step toward making CFGs more abstract so we can implement backward iteration. Exposing blocks forces forward iteration over instructions. I thought of making blocks abstract instead, but this seemed easier (actually simplifies a lot of client code that needed to deal with `Option<BasicBlock>`).
Existing tests, should be pure refactoring
=> [language][bytecode verifer] hide blocks from clients of CFG

language/bytecode_verifier/src/verifier.rs, language/compiler/ir_to_bytecode/src/compiler.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop, language/functional_tests/src/evaluator.rs, language/functional_tests/tests/testsuite/generics/builtins.mvir, language/functional_tests/tests/testsuite/generics/call.mvir, language/functional_tests/tests/testsuite/generics/function_def.mvir, language/functional_tests/tests/testsuite/generics/pack.mvir, language/functional_tests/tests/testsuite/generics/struct_def.mvir, language/functional_tests/tests/testsuite/generics/unpack.mvir, language/tools/cost_synthesis/src/module_generator.rs, language/vm/src/deserializer.rs, language/vm/src/file_format.rs, language/vm/src/printers.rs, language/vm/src/proptest_types.rs, language/vm/src/proptest_types/signature.rs, language/vm/src/resolver.rs, language/vm/src/serializer.rs, language/vm/src/views.rs, language/vm/vm_runtime/src/unit_tests/module_cache_tests.rs, language/vm/vm_runtime/src/unit_tests/runtime_tests.rs, language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, language/vm/vm_runtime/vm_runtime_types/src/native_structs/dispatch.rs
This implements the parser & compiler for generics. New tests are added.
```
cargo test
```
=> [language/move ir] implement parser & compiler for generics

network/src/transport.rs, network/src/validator_network/network_builder.rs
For a validator's full node that wants to accept connections from any public full node, we need permissioned connections on one end (public full node) and permissionless connections on the other (validator's full node). This is to allow any public node to be able to connect to and receive block updates from the validator full node. Since it's not possible for the trusted full node to a priori know the identity of all public full nodes that would want to connect to it, it's end of the network needs to be permissionless. On the other hand, the public full node would want to only connect to the validator's full node and needs to know its identity beforehand, making a permissioned transport suitable for this use case.
Yes
#686 #690
=> [network] Add ability to construct permissionless TCP + Noise transport

config/config_builder/src/bin/libra-config.rs, config/config_builder/src/swarm_config.rs, config/data/configs/full_node.config.toml, config/data/configs/node.config.toml, config/src/config.rs, consensus/src/chained_bft/chained_bft_consensus_provider.rs, libra_node/src/main_node.rs, libra_swarm/src/main.rs, libra_swarm/src/swarm.rs, state_synchronizer/src/coordinator.rs, state_synchronizer/src/tests.rs
Since we need to run multiple network stacks in parallel, each would need its own set of trusted peers, role and keys. As such this PR moves these fields into NetworkConfig.
Next step for enabling Full Nodes will be to allow multiple NetworkConfigs in a NodeConfig and initialize different network stacks for each.
Yes
Ran local libra swarm and tested with some transactions
#686
=> [config] Move trusted_peers, keys and role to NetworkConfig from BaseConfig

config/src/trusted_peers.rs
Copy the peer values into a BTreeMap so that they get written out in
sorted order. This should avoid unnecessary churn in the .toml file.
Test Plan: Ran "cargo test". Also ran "build.sh dev -n 4" in
the terraform/validator-sets/ directory and checked that the
order in the dev/trusted_peers.config.toml file was preserved.
=> [config] Serialize TrustedPeersConfig in sorted order

storage/libradb/src/lib.rs
We have places in the code that assume existence of all versions between (0, current_version). With pruning, this assumption breaks.
Instead of fixing these places in code, we're going to unblock ourselves quickly by disabling pruning (in a somewhat hacky way).
(y)
Tested with a build from https://github.com/fbandersnatch/libra/tree/testing-release
=> [storage] disable pruner (by hacking max-versions-to-keep)

state_synchronizer/src/coordinator.rs, state_synchronizer/src/tests.rs
as a protection from malicious peers and execution failures we need to switch to last commit timestamp to ensure progress
currently check is done based on last sync request timestamp
with such approach malicious node can keep sending us bad data and `check_progress` will be satisfied
so to ensure real progress we need to check timestamp of last commit instead
=> [state sync] switch ensuring progress to last commit

language/stdlib/modules/vector.mvir, language/vm/vm_runtime/vm_runtime_types/src/native_functions/dispatch.rs, language/vm/vm_runtime/vm_runtime_types/src/native_structs/dispatch.rs
Now that parser support for generics has landed, we can make the native struct type that backs a vector generic. This diff does that + updates the procedures of Vector appropriately.
Moving toward a real vector implementation!
Ran bytecode verifier on `Vector` after changes.
=> [language] make vectors generic

terraform/templates/dashboards/consensus.json, terraform/templates/dashboards/execution.json, terraform/templates/dashboards/overview_dashboard.json, terraform/templates/dashboards/performance.json, terraform/templates/prometheus/consoles/consensus-toplevel.html, terraform/templates/prometheus/consoles/performance.html, terraform/templates/prometheus/rules/recording_rules.yml
Use new counter names in dashboards.
This is a simple `sed` replace + verifying that only names that got updated were replaced.
(y)
Will test on new nightly noon.
No code impact
Counter names changed in creation_to_commit_ms
=> [dashboards] update counter names and filesystem monitoring

benchmark/Cargo.toml, testsuite/cluster_test/Cargo.toml
This PR lays ground for submitting transactions during cluster test and for using debug_interface to retrieve structured events from validator
While it seem small, adding those dependencies actually was not easy:
- Adding benchmark as dependency requires adding testing feature to benchmark crate itself in order to be able to include it in cluster_test (Thanks @huitseeker for figuring out how to fix it)
- Adding grpcio for accessing debug_interface introduces conflict with `rusoto_` libraries. By default, rusoto uses hyper-tls, that depends on openssl-sys crate. This crate requires `libssl-dev`, or similar package to be installed. However, this does not work well when grpcio also added as dependency - it result in linking problems. Currently my solution is to switch `rusoto` crates to use …
=> [cluster_test] Add dependencies to benchmark and debug_interface

language/functional_tests/src/evaluator.rs
Previously we won't add a module to the dependency list if we turn off the verifier pass, which is not ideal.
Yes
=> [fucntional_tests] fix publish modules with verifier disabled

language/vm/vm_runtime/src/runtime.rs
Make debug level logging sane again.
Printing all transaction content make all other logging disappear in the sea of bytecodes
This is a 1 word change: `debug!` -> `trace!`
(y)
Hope for the best + CI
=> [logging] do not print full transaction content in Debug level

language/tools/test_generation/src/abstract_state.rs, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/control_flow_graph.rs, language/tools/test_generation/src/lib.rs
This commit allows for correct random assignment of locals to basic blocks in the control flow
graph through implementation of local merging.
Yes.
Local testing via `cargo test` and running on bytecode verifier.
N/A
=> [VM][Tools] Randomly assign basic block locals

network/src/connectivity_manager/mod.rs, network/src/connectivity_manager/test.rs
+ Previously, we only ever attempted to dial the first listen address
that a peer advertises.
+ With this change, we will actually attempt all advertised listen
addresses. This change is a necessary prerequisite to resolve the
network partition issue discovered and documented in issue #587.
+ Next, we will append seed peers' configured listen addresses to the
set of addresses to attempt so the parition will eventually heal, even
with the stale discovery note race.
=> [network] Attempt dial all advertised listen addrs round robin

network/memsocket/src/lib.rs
When searching for an open port there is the potential for overflowing
which would cause a panic when trying to convert a 0 into a
`NonZeroU16`. Instead of overflowing, detect that the overflow would
happen and instead resume searching from port 1 if the switchboard isn't
full.
=> [memsocket] fix overflow bug

state_synchronizer/src/coordinator.rs, state_synchronizer/src/executor_proxy.rs, state_synchronizer/src/tests.rs
Before coordinator can process chunk response, we need to check that there are 2f+1 signatures on ledger info and each of them are valid (signed by trusted nodes). Later on executor should check each chunk before applying it to storage, but putting in state sync layer for now since executor doesn't check for signatures at the moment.
Yes
Updated tests in state_synchronizer crate + integration test passes
=> [state-sync] Verify signatures on LedgerInfo before processing

testsuite/cluster_test/src/deployment.rs, testsuite/cluster_test/src/main.rs
Previously ECS in cluster_test was configured to use `nightly` tag.
This introduced problem, because we don't control when nightly tag changes. If it changes during reboot experiment, validator come back with newer code, that might be incompatible with existing cluster.
This PR changed cluster_test to use separate `cluster_test` image tag. When `nightly` tag changes, we first re-tag this image with `cluster_test` tag, and then update cluster. This makes sure we are in control of a image version that cluster test currently running
=> [cluster_test] Use intermediate tag for cluster_test validators

language/tools/test_generation/src/abstract_state.rs, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/control_flow_graph.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/arithmetic_instructions.rs, language/tools/test_generation/tests/bitwise_instructions.rs, language/tools/test_generation/tests/boolean_instructions.rs, language/tools/test_generation/tests/comparison_instructions.rs, language/tools/test_generation/tests/load_instructions.rs, language/tools/test_generation/tests/local_instructions.rs, language/tools/test_generation/tests/special_instructions.rs, language/tools/test_generation/tests/transaction_instructions.rs
This PR replaces the use of `SignatureToken`s with `AbstractValue`s within the bytecode test generation tool. The `AbstractValue` contains both a `SignatureToken` and a `Kind` of `Resource`, `Unrestricted`, or `All`.
Yes.
Local testing with `cargo test` and running on bytecode verifier.
N/A
=> [VM][Tools] AbstractValue: Extend stack values to include their kind

docker/cluster_test/build.sh, docker/cluster_test/cluster_test.Dockerfile, docker/cluster_test/cluster_test_builder.Dockerfile, docker/cluster_test/run.sh
This PR introduces scripts for building cluster_test on mac(or any other platform that supports docker)
To use simply run `docker/cluster_test/build.sh`. First time build will take a lot of time, but then its going to be pretty much as fast as local build: build is incremental, unless `cluster_test_builder.Dockerfile` is changed, which should be rare (it pretty much depends on rust compiler version only)
Currently `build.sh` does not build docker image by default, but instead just produces binary compiled for x64 linux.
`build.sh --build-docker-image` can be used to build docker image as well.
This commit also contains separate run.sh file that can be used to launch cluster_test with nohup. Currently this file should be manually copied to node.
=> [cluster_test] Build scripts

config/config_builder/src/swarm_config.rs, config/src/config.rs, libra_node/src/main_node.rs, network/benches/network_bench.rs, network/src/interface/mod.rs, network/src/transport.rs, network/src/validator_network/network_builder.rs, network/src/validator_network/test.rs, state_synchronizer/src/tests.rs
This PR builds on top of #692. To support public full nodes, the validator-trusted full nodes will need to run a permission-less network end-point -- i.e., accept connections from any public entity without knowing about it beforehand.
This PR allows instantiation of network stack without the discovery and connectivity manager modules which are designed to operate in a permissioned mode only.
Side-effect of this change is that a node started in permission-less mode will not dial any peer, but will accept incoming connections from any peer.
Yes.
Added a new test where we instantiate 2 network end-points - the listener is permission-less and the dialer is permissioned. We observe that the dialer is able to successfully connect to the listener and execute the mempool sync protocol.
#703, #692
=> [network] Add ability to create permissionless network end-point

consensus/Cargo.toml, consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/block_tree.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_fuzzing.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/pacemaker.rs, consensus/src/chained_bft/liveness/pacemaker_timeout_manager.rs, consensus/src/chained_bft/mod.rs, consensus/src/chained_bft/test_utils/mock_state_computer.rs, consensus/src/chained_bft/test_utils/mod.rs, consensus/src/lib.rs, consensus/src/util/mod.rs, testsuite/libra_fuzzer/Cargo.toml, testsuite/libra_fuzzer/fuzz/Cargo.toml, testsuite/libra_fuzzer/src/fuzz_targets.rs, testsuite/libra_fuzzer/src/fuzz_targets/consensus_proposal.rs, testsuite/libra_fuzzer/src/main.rs
**MOTIVATION:**
This PR sets up two things:
* an `event_processor_fuzzing.rs` next to `event_processor_test.rs`. The file contains a necessary function for a fuzzer, and a test so that breaking changes in EventProcessor won't break the fuzzer.
* calls from our test suite's Libra fuzzer.
The fuzzer is not finished, but this brings the foundation we can work on to finish the fuzzer.
**TEST PLAN:**
```
cargo test -p consensus
```
=> [consensus] init commit for fuzzing proposals messages

types/src/event.rs, types/src/proto/transaction.proto, types/src/transaction/module.rs, types/src/transaction/program.rs, types/src/transaction/script.rs, types/src/unit_tests/transaction_proto_conversion_test.rs, types/src/unit_tests/write_set_test.rs, types/src/write_set.rs
Now that SignedTransaction is fully in LCS we can eliminate all this
unnecessary code. Yay.
=> [types] Eliminate unused proto functions (Easy)

language/vm/src/deserializer.rs
=> [vm] avoid a vector clone in deserializer

language/tools/cost_synthesis/src/common.rs, language/tools/cost_synthesis/src/module_generator.rs, language/tools/test_generation/src/abstract_state.rs, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/lib.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/struct_instructions.rs
This commit adds module state to abstract states. This module state is then referenced for the creation and destruction of structs.
This commit also fixes a bug in `cost_synthesis` where a structure may be generated with duplicate field names. 
Yes.
Local testing with `cargo test` and running on bytecode verifier. Added tests for `Pack` and `Unpack`.
N/A
=> [VM][Tools] Add support for structs in bytecode generation

testsuite/cluster_test/Cargo.toml, testsuite/cluster_test/src/lib.rs, testsuite/cluster_test/src/log_prune.rs, testsuite/cluster_test/src/main.rs
Since cluster_test do a lot of restarts, it create tons of log streams in a log group.
It looks like AWS does not handle this well, it cause logging tools like `awslogs` to be completely stuck, which makes it impossible to debug issues in cluster.
More specifically, call to `describe-log-streams` hangs:
```
aws logs describe-log-streams --log-group-name cluster-test
```
We do have log retention set to 7 days, however, this retention only delete log entries, it does not delete log streams themselves.
--prune-logs action in cluster_test going to delete old log streams
Also it seems cluster_test at some point should be split into some cluster_util, since it starting to have a lot of general cluster management functionality(reboot validators, wipe db, now log prune)
=> [cluster_test] Add --prune-logs command to cleanup old log streams

types/src/transaction.rs
With unwrap here, a client can send a bad key or signature and cause
the AC to crash.
=> [types] Prefer error escalation over unwrap

common/proptest_helpers/src/lib.rs, storage/libradb/src/test_helper.rs, types/src/event.rs, types/src/proptest_types.rs
Introducing the `Arena` and `xyzGen` types.
The `Universe` keeps track of a collection of accounts along with sequences numbers and event handles (which in turn has sequence numbers tracked).
The `xyzGen` types resolve "local" randomness upon creation and when they `materialize()`, get/update "global" info in the arena.
For example, a `RawTransactionGen` has determined Payload upon creation, while gets and increases the account sequence number in the `Universe` when it `materialize()`.
1. We don't need things like `renumber_events()` that's hacky and confusing.
2. Similarly, easy to support more "real" transaction sequence numbers in transaction batches.
Yes
Existing coverage.
(If this PR adds or changes functionality, please take some time to update the docs at …
=> [types] proptest refactor to ease generating logical transaction update batches.

scripts/circle_validate_configs.sh
This PR changes the instructions about what to do when config-validation script fails during CI.
The current instructions point to the original script that builds the config (`build.sh`), but it's hard to use because one would have to use it multiple times, for all the configs we use.
Now, we just instruct the config validation script itself -- since it does all config generation too.
(y)
Tested locally, we'll see on circle
=> [ci][config] add instructions to failures in config-validate script

client/src/client_proxy.rs, storage/libradb/src/lib.rs, storage/libradb/src/libradb_test.rs, types/src/access_path.rs, types/src/account_config.rs, types/src/get_with_proof.rs
1. rename to `get_events_by_query_path`, to be consistent with its own parameter
2. `AccountResource::get_event_handle_by_query_path()` now takes the `path` part of the access path, since the address part is not used.
3. ACCOUNT_SENT_EVENT_ACCESS_PATH is now a lazy static so the API doesn't need to create a new Vec<u8> every time it checks against the parameter.
Yes
Existing Coverage
=> [storage] refine get_events_by_event_access_path

language/tools/test_generation/src/abstract_state.rs, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/common.rs, language/tools/test_generation/src/control_flow_graph.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/common.rs
This commit adds handling for possible errors that come up when checking instruction
preconditions and applying instruction effects. MIRAI was also run over the code
and the errors brought up have been addressed.
Yes.
Local testing with `cargo test`. MIRAI analysis run via `RUSTC_WRAPPER=mirai RUST_BACKTRACE=1 MIRAI_LOG=error cargo build --features "mirai-contracts"`
N/A
=>  [VM][Tools] Improve safety of bytecode test generator

language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/control_flow_graph.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/special_instructions.rs, language/tools/test_generation/tests/struct_instructions.rs, language/tools/test_generation/tests/transaction_instructions.rs
This commit adds support to the bytecode test generator for the remaining
non-reference bytecode instructions.
Yes.
Local testing with `cargo test`. Added tests for new instructions. Safety analysis with MIRAI.
N/A
=> [VM][Tools] Bytecode test generator: Complete non-reference instructions

language/functional_tests/src/config/global.rs, language/functional_tests/src/config/transaction.rs, language/functional_tests/src/tests/global_config_tests.rs, language/functional_tests/src/tests/transaction_config_tests.rs
New contributor to the project and noticed at TODO in [global_config_tests.rs](https://github.com/libra/libra/blob/master/language/functional_tests/src/tests/global_config_tests.rs#L17):
```rust
#[test]
fn parse_account() {
for s in &[
"//! account: alice",
"//!account: bob",
"//! account: bob, 100",
"//!account:alice,",
// TODO: The following should parse. Fix it.
// "//!   account :alice,1, 2",
"//! account: bob, 0, 0",
] {
s.parse::<Entry>().unwrap();
}
for s in &["//! account:", "//! account", "//! account: alice, 1, 2, 3"] {
s.parse::<Entry>().unwrap_err();
}
}
```
and am taking a stab are fixing this.
Yes
executing the following:
`cd language/functional_tests/`
`cargo test`
=> [language] improve account parsing in functional tests

language/compiler/ir_to_bytecode/Cargo.toml, language/compiler/ir_to_bytecode/src/parser.rs
Due to an incorrect regex for stripping of comments in the IR to bytecode
testing tool, comments ending in different line endings were not properly
stripped from IR source files. Furthermore, we no longer want to use the
hacky regex that we had previously, and instead take a more principled
approach to both the allowed character classes and line endings that are
permitted, and the manner in which they are removed from the source string
before being passed off to the parser.
As the IR compiler is largely a testing tool (and developer experience is
not a primary concern), this pull request addresses these issues by greatly
restricting the character classes that are allowed in IR files to either
be:
* ASCII printable (space through ~).
* \n for newlines
* \t for tabs
All other characters …
=> [language] Restrict character classes allowed in IR

storage/scratchpad/src/accumulator/accumulator_test.rs, storage/scratchpad/src/accumulator/mod.rs
I'm planning to re-implement the function so it returns a new accumulator instead of just the new root hash. Then we will no longer be able to use it to compute the root hash. Use the old way to compute root hash.
Yes.
None.
=> [Storage] Remove append_siblings

Cargo.lock
Seems like CI is failing on master after `Cargo.lock` was checked in.
Y.
CI.
None.
=> Fix Cargo.lock on master

Cargo.lock, storage/libradb/Cargo.toml
Regroup / reorder it so that external and internal dependencies are separate and in alphabetic order respectively.
Yes
Existing coverage.
=> [storage] trivial: libradb cargo.toml ordering

mempool/src/shared_mempool.rs
`inbound_network_task()` will panic if it ever receives an `Event` enum that is not listed.
As this list of event enums might grow, we should not panic here.
=> [mempool] removing unreachable

.circleci/config.yml
Cargo.lock now exists in the repo, so generating it to run cargo audit is no longer needed.
yes
cargo audit now succeeds without needing to call generate-lockfile. Prior to #814 Cargo.lock needed to be generated first or cargo audit would fail.
=> [ci] Remove lock file generation now that the lock file exists

language/vm/vm_runtime/src/lib.rs
This commit addresses issue #781  by including `foreign_contracts` in `vm_runtime/src/lib.rs`.
Yes.
Local testing with `cargo test`.
N/A
=> [VM] Fix foreign contracts in VM runtime unhooked

types/src/proof/accumulator/accumulator_test.rs, types/src/proof/accumulator/mod.rs, types/src/proof/position/mod.rs, types/src/proof/position/position_test.rs
In addition to appending a list of leaves to an accumulator represented by frozen subtrees, we can now replace the leaves with a list of subtrees. This allows the client to construct a new accumulator from a smaller one using a small amount of information.
Y.
CI.
None.
=> [Proof] Implement append_subtrees

terraform/templates/dashboards/execution.json, terraform/templates/dashboards/overview_dashboard.json, terraform/templates/dashboards/performance.json, terraform/templates/dashboards/validators.json
* Update latency widgets that use *ms* as display units, but the actual value is in sec (floating point, so it satisfies lower values).
* Make same unit change in other dashboards with latency widget
* Update execution dashboards to add percentile view in addition to avg
(y)
Tried locally
=> [dashboards] make latency widgets use seconds; and other updates

language/compiler/ir_to_bytecode/src/context.rs, language/compiler/ir_to_bytecode/syntax/src/ast.rs, language/compiler/ir_to_bytecode/syntax/src/syntax.lalrpop
I'm touching some of this code right now, wanted to clean some of this up and avoid some copies.
I removed the as_bytes methods because they weren't being used.
=> [ir_to_bytecode_syntax] cleanup to align with Rust conventions

consensus/src/chained_bft/chained_bft_smr_test.rs, consensus/src/chained_bft/network_tests.rs, consensus/src/chained_bft/test_utils/mod.rs, execution/execution_tests/src/tests/execution_service_test.rs, language/e2e_tests/src/account_universe/universe.rs, language/stackless_bytecode/bytecode_to_boogie/src/translator.rs, language/vm/src/transaction_metadata.rs, language/vm/vm_genesis/src/lib.rs, network/benches/network_bench.rs, network/src/protocols/discovery/test.rs, network/src/validator_network/consensus.rs, network/src/validator_network/mempool.rs, network/src/validator_network/state_synchronizer.rs, network/src/validator_network/test.rs, scripts/clippy.args, state_synchronizer/src/tests.rs, storage/jellyfish_merkle/src/jellyfish_merkle_test.rs, storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/nibble/nibble_path_test.rs, storage/libradb/src/lib.rs, storage/libradb/src/mock_genesis/mod.rs, types/src/validator_verifier.rs
Right now this lint `clippy::identity-conversion` is allowed. Remove it from `clippy.args` and fix everything.
Yes.
CI.
None.
=> Clean up clippy::identity-conversion

terraform/network.tf, terraform/terraform.tfvars, terraform/validators.tf, terraform/variables.tf
Easily allow Validators to have public IPs, and also allow for custom IP access rules to validators.
Yes
Diff versus existing master below shows only expected changes:
Terraform will perform the following actions:
-/+ resource "aws_security_group_rule" "validator-node" {
~ cidr_blocks              = [ # forces replacement
+ "0.0.0.0/32",
+ "10.0.0.0/16",
]
from_port                = 6180
~ id                       = "sgrule-35464105" -> (known after apply)
~ ipv6_cidr_blocks         = [ # forces replacement
+ "::/128",
+ "2600:1f14:9ff:c500::/56",
]
- prefix_list_ids          = [] -> null
protocol                 = "tcp"
security_group_id        = "sg-0ecb41195112ec114"
~ self                     = true -> false # forces replacement
~ source_security_group_id = "sg-0ecb41195112ec114" -> …
=> [terraform] Allow validator public IPs

storage/libradb/src/lib.rs, storage/libradb/src/libradb_test.rs, storage/libradb/src/schema/mod.rs, storage/libradb/src/schema/transaction_by_account/mod.rs, storage/libradb/src/schema/transaction_by_account/test.rs, storage/libradb/src/transaction_store/mod.rs, storage/libradb/src/transaction_store/test.rs, types/src/proptest_types.rs
(This is a resend of https://github.com/libra/libra/pull/798, which I couldn't reopen because I accidentally force- pushed after a rebase.)
Built an index table to support looking up transaction versions by account_address and sequence_number. So that to serve the corresponding public API we don't need to binary search on the full state history, which in turn makes possible the pruning of state history on any node that serves read APIs.
To enable pruning state history.
Yes
Unit tests.
This used to break smoke tests because both the genesis transaction and the first mint transaction are under the Association account and both have a sequence number of 0.
It used to run fine because in the binary search approach this replaces, the genesis transaction is never returned, because the algorithm …
=> [storage] `TransactionStore::lookup_transaction_by_account()`

common/canonical_serialization/src/canonical_serialization_test.rs, common/proptest_helpers/src/lib.rs, common/proto_conv/tests/derive.rs, consensus/src/chained_bft/common.rs, crypto/crypto/src/hash.rs, execution/execution_proto/src/lib.rs, execution/executor/src/block_tree/block_tree_test.rs, language/e2e_tests/src/account_universe.rs, scripts/clippy.args, storage/jellyfish_merkle/src/lib.rs, storage/jellyfish_merkle/src/node_type/mod.rs, storage/storage_proto/src/lib.rs, types/src/access_path.rs, types/src/account_address.rs, types/src/account_config.rs, types/src/account_state_blob/mod.rs, types/src/contract_event.rs, types/src/event.rs, types/src/get_with_proof.rs, types/src/ledger_info.rs, types/src/proof/definition.rs, types/src/proptest_types.rs, types/src/transaction.rs, types/src/validator_change.rs, types/src/validator_public_keys.rs, types/src/vm_error.rs
It seems that we are suppressing this lint everywhere, so having it is not providing a lot of value. I think allowing this one globally would not be terrible.
Y.
CI.
None.
=> Clippy: allow unit_arg globally

storage/libradb/src/lib.rs
https://github.com/libra/libra/commit/c433798c5282124014582a00e2d94be135e2f23c  made the client rely on `get_transaction_by_account` to wait for completion of a transaction, which unfortunately depends on full state history, hence the pruner won't be allowed on any node that serves read requests.
After #835 `get_transaction_by_account` no longer depends on full state history.
Resume testing the pruner in production.
changed `MAX_HISTORICAL_VERSIONS_TO_KEEP` to 0 and started a local swarm, client was able to do txns etc which was not the case before #835 
#835
=> [storage] enable the pruner

types/src/access_path.rs
This is weirdly duck typed and doesn't appear to be used at all.
Also clean up imports slightly.
=> [types] remove some unused code around access paths

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/block_store_test.rs, consensus/src/chained_bft/block_storage/block_tree.rs, consensus/src/chained_bft/block_storage/mod.rs, consensus/src/chained_bft/consensus_types/block.rs, consensus/src/chained_bft/event_processor.rs, consensus/src/chained_bft/event_processor_test.rs, consensus/src/chained_bft/liveness/proposal_generator.rs, consensus/src/chained_bft/safety/safety_rules.rs, consensus/src/chained_bft/safety/safety_rules_test.rs, consensus/src/state_replication.rs
Introduce `ExecutedBlock` which encapsulates a block and its executed result and children hash pointers.
Y
CI
=> [consensus] Introduce ExecutedBlock to refactor block_tree

Cargo.lock, crypto/crypto/Cargo.toml
This plugs in a version of curve25519-dalek that uses formalized cryptographic operations from [fiat-crypto](https://github.com/mit-plv/fiat-crypto/).
The backend is exposed through the [curve25519-fiat](https://github.com/calibra/rust-curve25519-fiat/) package (to be published imminently), which packages certified Rust field arithmetic primitives extracted from Coq.
The curve25519-fiat package is then used in an alternate backend for the dalek suite of libraries linked therein, which should ultimately be exposed as maintained forks.
The key commit adding this backend is https://github.com/huitseeker/curve25519-dalek/commit/5fabb0be26a4e00b1dca415cd298a6acf00c60be
**This PR modifies the following behavior**:
- when compiled (tested ...) with the following options, the `crypto` and …
=> Add a formalized backend option to the crypto dependencies

benchmark/src/bin/ruben.rs, benchmark/src/grpc_helpers.rs, benchmark/src/lib.rs, benchmark/src/load_generator.rs, benchmark/src/submit_rate.rs
Small code cleanup: remove prints from code, change a const that 
Rename counters to something a bit less confusing (I'm was confused by what each name means).
Not much will change after this commit except for counters and also smoother operation, because there's no waiting for thousands of `UpdatetoLatestLedger` requests.
Tested on my test-env, with image from nightly + this commit.
Got smoother operation compared to before this change, counters are named OK
=> [benchmark] cleanup: change timeouts; remove prints and confusing names

language/bytecode_verifier/invalid_mutations/src/bounds.rs, language/bytecode_verifier/src/resources.rs, language/bytecode_verifier/src/type_memory_safety.rs, language/functional_tests/tests/testsuite/generics/id_function.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/borrow_field.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/borrow_global.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/call.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/imm_borrow_field.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/move_from.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/pack.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/struct_non_nominal_resource.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/type_param_all.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/type_param_resource.mvir, language/functional_tests/tests/testsuite/generics/resource_safety/unpack.mvir, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/struct_instructions.rs, language/vm/src/errors.rs, language/vm/src/file_format.rs, language/vm/src/lib.rs, language/vm/src/views.rs, types/src/proto/vm_errors.proto, types/src/vm_error.rs
This implements type & memory safety checking for generics. More specifically, it defines how the kind of a (generic) type should be derived, and enforces subkind checking in the verifier.
Here is the list of changes:
- `SIgnatureTokenView`:
- Reimplemented `fn kind` & fixed `fn contains_nominal_resource`
- Right now the implementation is kinda hacky. I'm planning to refactor views in the future.
- `bytecode_verifier::type_memory_safety`
- `ReadRef`, `WriteRef`, `Eq`, `Pop`, `CopyLoc`
- Now uses the new `SIgnatureTokenView::kind()`. 
- Other logic unchanged.
- `Pack`, `Unpack`
- Kind checking** & substitution*.
- `Call`
- Kind checking & substitution.
- `Exists`, `BorrowGlobal`, `MoveFrom`, `MoveToSender`
- Kind checking.
- Fixed the type to be put onto the abstract interpreter stack (if …
=> [language/verifier] fix type & memory safety checks for generics

language/functional_tests/tests/testsuite/generics/coin_wrapper.mvir, language/vm/vm_runtime/src/code_cache/module_cache.rs, language/vm/vm_runtime/vm_runtime_types/src/lib.rs, language/vm/vm_runtime/vm_runtime_types/src/loaded_data/types.rs, language/vm/vm_runtime/vm_runtime_types/src/type_context.rs, language/vm/vm_runtime/vm_runtime_types/src/value_serializer.rs
This will be a partial implementation for the runtime support for generics. To be specific, this diff will allow us to publish resources like:
`Resource FooCoin{
f: Foo<LibraCoin.T>,
}`
And we can't publish resource with top level type arguments, such as
`Resource FooCoin<T> {
f: Foo<T>
}`
and do `move_to<FooCoin<LibraCoin.T>>`.
In general the VM doesn't need to know about generic type parameters at runtime. The only exceptions are these global instructions (borrowGlobal, MoveFrom, MoveTo, Exists) as we need to know the exact struct layout to store them on chain. 
Yes
Added a unit test for testing the caching behavior of type instantiation of generics.
=> [vm_runtime] Implement runtime for generics

language/stackless_bytecode/bytecode_to_boogie/Cargo.toml, language/stackless_bytecode/bytecode_to_boogie/run_boogie.sh, language/stackless_bytecode/bytecode_to_boogie/src/bytecode_instrs.bpl, language/stackless_bytecode/bytecode_to_boogie/src/main.rs, language/stackless_bytecode/bytecode_to_boogie/src/translator.rs, language/stackless_bytecode/bytecode_to_boogie/tests/run_functional_tests.rs
I added a script in `tests/run_functional_tests` that would run every test in `functional_tests/tests/testsuite` except for tests in `generics` since we don't support those now. 
The script runs the translator on all the mvir files that have passed `bytecode_verifier`, outputs Boogie code into `FOLDERNAME__FILENAME_TXNUMBER.bpl` inside `output` folder. We need to include transaction number because there might be multiple transactions inside a test file. For example, the first transaction of `testsuite/borrow_tests/borrow_copy_ok.mvir` will be outputted into `output/borrow_tests__borrow_copy_ok_0.bpl`.
I have also written a bash script `run_boogie.sh` that would run Boogie on everything in `output` folder.
Yes.
```
cargo test
```
=> [language] add testing script running all verified tests in functional_tests

consensus/src/chained_bft/block_storage/block_store.rs, consensus/src/chained_bft/block_storage/block_store_test.rs, consensus/src/chained_bft/consensus_types/block.rs, consensus/src/chained_bft/consensus_types/quorum_cert.rs, consensus/src/chained_bft/test_utils/mod.rs, execution/execution_tests/src/lib.rs, execution/executor/src/executor_test.rs, execution/executor/src/lib.rs, state_synchronizer/src/tests.rs, storage/libradb/src/ledger_store/ledger_info_test.rs, storage/libradb/src/mock_genesis/mod.rs, storage/libradb/src/test_helper.rs, types/src/ledger_info.rs, types/src/proof/unit_tests/proof_test.rs, types/src/proto/ledger_info.proto, types/src/validator_public_keys.rs, types/src/validator_set.rs
Summary: next_validator_set is not None for the very last LedgerInfo of an epoch:
it keeps the validator set for the next epoch.
This change is just introducing a field and is technically a noop: no one is writing or reading this field yet.
Tests: current test coverage
Issues: ref #849
=> Add an optional field `next_validator_set` to LedgerInfo

language/tools/cost_synthesis/src/module_generator.rs, language/tools/test_generation/src/abstract_state.rs, language/tools/test_generation/src/bytecode_generator.rs, language/tools/test_generation/src/summaries.rs, language/tools/test_generation/src/transitions.rs, language/tools/test_generation/tests/control_flow_instructions.rs, language/tools/test_generation/tests/reference_instructions.rs, language/tools/test_generation/tests/struct_instructions.rs
This commit adds instructions that use references, modeling them in terms of type safety
and global state. Memory safety is not yet supported.
Yes.
Added tests for each instruction. Testing with `cargo test`. Safety analysis with MIRAI.
N/A
=> [VM] Add instructions that use references

testsuite/cluster_test/src/deployment.rs, testsuite/cluster_test/src/main.rs
We have quite a bit of changes that breaks db compatibility or change genesis block
Currently handling every one of those changes require manual work, so to simplify we just going to wipe db before every deploy
=> [cluster_test] Wipe db before deploy

testsuite/cluster_test/README.md, testsuite/cluster_test/src/health/debug_interface_log_tail.rs, testsuite/cluster_test/src/suite.rs
When @bothra90 tried to run cluster_test on 4 nodes cluster, he discovered some issues. This PR fixes them
* [cluster_test] Don't reboot more then 1/3 during reboot experiment
For small clusters we don't want to reboot more than 1/3 of validators during experiment, to preserve liveliness.
* [cluster_test] Fix startup of debug_interface_log_tail
On smaller cluster there is race condition when debug_interface_log_tail starts before first data is polled. This make test spuriously fail when run on small cluster because it sees cluster 'unhealthy', while it just did not yet receive data.
* Add README
=> [cluster_test] Fixes to support small clusters

consensus/src/chained_bft/event_processor.rs
Summary:
There are too many log lines warning about the proposals from the old rounds.
This is a pretty common case especially with secondary proposers sending them as well, so removing the log.
Testing: unit tests
=> [Consensus][tiny] Cleanup some log lines

state_synchronizer/src/coordinator.rs, state_synchronizer/src/peer_manager.rs
Additional invalid chunk logic for peer scoring when version received from a peer is out of sync. We cannot penalize whenever a peer sends chunk with wrong version, because it could have been due to previous peer acting maliciously. We only penalize peer if peer sent out of version chunk that the node has not explicitly requested for.
unit test
https://github.com/libra/libra/pull/932
=> [state-sync] Additional invalid chunk logic for peer scoring

state_synchronizer/src/coordinator.rs, state_synchronizer/src/peer_manager.rs, state_synchronizer/src/tests/unit_tests.rs
It is important to keep the requests map in sync with the committed version, so that the map doesn't continue to increase with old/stale versions that were not removed once the versions were committed. If we miss the version checks for removal due to some race condition, it could theoretically increase the requests map indefinitely and cause OOM. To prevent this, I have switched the requests hashmap to a btreemap, so that once a version is committed, all requests for versions equal to or less than that committed version can easily be removed.
Added unit test for btree map ranged removal
=> [state-sync] Use btreemap to store sync requests

config/management/operational/src/command.rs, config/management/operational/src/validator_config.rs, config/management/operational/src/validator_set.rs, config/management/src/error.rs, secure/json-rpc/src/lib.rs, testsuite/tests/libratest/smoke_test.rs
This now outputs all commands as a JSON blob no matter what the output
type was.  ValidatorInfo drops voting power, ValidatorConfig named
simpler, and output keys are dropped from rotation outputs.
```
$  cargo run -p libra-operational-tool -- rotate-consensus-key --config config.yaml
{
"Result": {
"address": "39f0d3313a4c2bd28786569a5b1b9620",
"sequence_number": 11
}
}
$  cargo run -p libra-operational-tool -- rotate-consensus-key --config not-a-config.yaml
{
"Error": "Unable to load config: No such file or directory (os error 2)"
}
$ cargo run -p libra-operational-tool -- validate-transaction --config config.yaml  --account-address ""39f0d3313a4c2bd28786569a5b1b9620"" --sequence-number 11
{
"Result": "Executed"
}
$ cargo run -p libra-operational-tool -- validate-transaction --config …
```
=> [management] simplify output of operational commands

network/src/counters.rs, network/src/peer_manager/mod.rs
In order to not conflict with the current metrics, a different metric is
kept for per peer and directional metrics all in one.
An example dashboard:
http://grafana.ct-2-k8s-testnet.aws.hlw3truzy4ls.com/d/bvXz6aVMk/validator-network-connections?orgId=1
=> [network] move directional connections to different metric

language/move-prover/spec-lang/src/env.rs, language/move-prover/spec-lang/src/translate.rs, language/move-prover/src/boogie_wrapper.rs, language/move-prover/src/bytecode_translator.rs, language/move-prover/src/cli.rs, language/move-prover/src/lib.rs, language/move-prover/src/prelude.bpl, language/move-prover/src/spec_translator.rs, language/move-prover/tests/sources/functional/aborts_if.exp, language/move-prover/tests/sources/functional/aborts_if_with_code.exp, language/move-prover/tests/sources/functional/aborts_if_with_code_partial_error.exp, language/move-prover/tests/sources/functional/arithm.exp, language/move-prover/tests/sources/functional/cast.exp, language/move-prover/tests/sources/functional/loops.exp, language/move-prover/tests/sources/functional/pragma.exp, language/move-prover/tests/sources/functional/restrictions.exp, language/move-prover/tests/sources/functional/restrictions.move, language/move-prover/tests/sources/functional/schema_exp.exp, language/move-prover/tests/sources/functional/script_incorrect.exp, language/move-prover/tests/sources/functional/unused_schema.exp, language/move-prover/tests/sources/functional/unused_schema.move
This PR pulls out some bug fixes and feature additions from the evolving errors PR. This is also so we do not have those changes in the PR which need to be marked as breaking.
- fixed a crash in error location handling of abort code verification failures.
- enabled lets in schemas. This was omitted previously, indeed lets also work in schemas.
- fixed a crash with aborts_if with a code in presence of schema expressions.
- printing error codes now in hex format, for better decoding.
- added a cli flag to report or not report warnings (like unused schemas). The default is now false until we come up with a better solution for schemas exported to other modules.
- Restricted the heuristic to find usages of a source to *only* consider `use` declarations. Previously, it was also looking for …
=> [move-prover] Prover changes and fix resulting from work on error model.

config/src/config/storage_config.rs
DB files living in
/opt/libra/data/common/libradb/db/libradb
/opt/libra/data/common/libradb/db/consensusdb
is confusing..
moving to
/opt/libra/data/common/db/libradb
/opt/libra/data/common/db/consensusdb
It'd look even cleaner if we remove common/db as well, but looks like cluster-test delete common keeping other useful things, and there are tests deleting the common parent of libradb and concensus db (It makes some sense to separate db files as well, for example, the swarm stores the mint key at the parent dir). Hence the change being like this.
reduce confusing. It happened multiple times that people open db at /opt/libra/common/libradb and got unexpectged empty DB.
Y
existing coverage.
=> [breaking][storage] trivial: one less level of db dir

.github/workflows/land-blocking.yml
This enables necessary CI checks to run on the `canary` branch so that the new `canary`/`try` feature of bors can be used to perform a dry-run of the land-blocking tests without blocking the merge queue.
=> ci: enable land-blocking test on the 'canary' branch

language/move-vm/natives/src/account.rs
There is a mistake in `pub fn native_destroy_signer(...)` at `language/move-vm/natives/account.rs`, which uses wrong `NativeCostIndex` so the gas is charged wrongly.
Yes
It should be a clear typo mistake, and the change of the code can be tested the same as the original code.
=> [fix] fix gas consume of native_destroy_signer

consensus/src/epoch_manager.rs, consensus/src/round_manager.rs, consensus/src/round_manager_test.rs
This commit makes `process_local_timeout` returns Err when the messages
are broadcasted.
It can help reduce the log amount without losing visibility. After this
change, we only log round state when errors occur.
Y
https://github.com/libra/libra/issues/5597
=> [consensus] return Err with successful timeout

consensus/consensus-types/src/epoch_retrieval.rs, consensus/src/epoch_manager.rs
We only log process_proposal/vote/sync_info metrics but not cover all
process_messages.
This commit adds the remaining parts.
Y
=> [consensus] add missing monitor for epoch messages

execution/executor/src/lib.rs
One of the most repeated log lines that provides no extra info is
`Skipping the first 0 transactions.`.  This skips writing this log
unless there is actually a transaction to skip.
It's possible that this may be useful in debugging to regularly print out this line so let me know if that's the case.  It just one of 3 repeated logs that is an order of magnitude larger than some others.  You can check it out on my logging dashboard:
https://search-premainnet-logging-aiee5pnmt2aav4272fuf4ilwze.us-west-2.es.amazonaws.com/_plugin/kibana/goto/fedc7a3dc03c77912aebb96420a7c99b
=> [execution] Only log skipping when skipping transactions

language/move-prover/src/cli.rs
This PR makes two changes when use_array_theory flag is used.
- Disables extensionality reasoning to improve performance
- Removes high setting of eager and lazy QI thershold
This PR does not change any behavior when array theory is not used.
The motivation for this change is to provide a feasible path in Move Prover where a high QI threshold can be avoided.  The main reason for the high QI threshold currently is the use of array axioms.  I suspect that the high threshold causes instability in cases when the solver is looking for an error.  Using a low threshold should cause the solver to terminate faster in such cases.  The use of native array theory (without extensionality) allows us to get by with a low threshold without losing completeness (i.e., provability for correct programs).  I …
=> [move-prover] Disable extensionality when array theory is used

config/src/config/state_sync_config.rs, state-synchronizer/src/coordinator.rs
add configurable size limit on pending LIs to store, to prevent OOM if state sync is too slow
Existing tests
=> [state sync] add size limit to pending LI store to prevent OOM

common/logger/src/lib.rs, common/logger/src/struct_log.rs, common/logger/src/tests/mod.rs, common/logger/src/tests/struct_log.rs
There were previously no tests around logging, so hopefully these new
tests will prevent accidental mistakes, as well as illustrate how
logging can be used throughout the codebase.
In addition, microseconds seems to be a better choice for the timestamp.
=> [logging] added tests around logging and levels

testsuite/cluster-test/src/cluster.rs, testsuite/cluster-test/src/main.rs, testsuite/cluster-test/src/tx_emitter.rs
When used in swarm mode against an existing network, the chain ID won't
necessarily be `TESTING`. Add a `--chain-id` param to set the chain ID
and use this when constructing transactions.
=> [cluster-test] Add --chain-id argument

scripts/cti
In some rare cases LBT needs to do expensive cleanup from previous job, in this case we need to allow more time for it to complete
=> [cluster-test] Increase default cti timeout

.github/workflows/dep-summaries.yml
=> fix typo in github workflow step

language/move-prover/src/bytecode_translator.rs, language/stdlib/modules/Errors.move, language/stdlib/modules/doc/Errors.md
There appears to be either a bug in what "cargo test" does or my understanding of what it does.  Over the weekend, I introduced a bug in Errors.move which is not caught by 
cargo test test_runner_stdlib::modules/Errors.move
I happened to run 
cargo run -- ../../../../stdlib/modules/Errors.move -d ../../../../stdlib/modules/ --verbose debug
today and discovered verification failures.  This PR fixes those bugs.
My inability to detect the problems I had introduced in Errors.move led me to a wrong  conclusion about impact of the use of arithmetic modulus in computing error codes.  I erroneously came to the conclusion that the use of modulus is harmless.  I came to the opposite conclusion (mod indeed creates timeouts) once I fixed the bugs in Errors.move and repeated my experiments.  This PR …
=> [move-prover] fixed specs in Errors

devtools/x/src/clippy.rs, devtools/x/src/config.rs, x.toml
Libra uses clippy for various Rust lints. Currently, there are lints that do not emit warnings (as they are on the "allowed" list), but can easily cause panics, memory leaks or other issues. Hence, I modified clippy.rs in order to enable lints that we specify in x.toml. 
Also I enabled the clippy::wildcard_dependencies lint (https://rust-lang.github.io/rust-clippy/master/#wildcard_dependencies) in order to prevent devs to use wildcard dependencies in Cargo.toml as that is bad practice and could also have security implications (since dependabot needs to know the library version in order to check for existing vulnerabilities).
Yes.
Ran "cargo x clippy" with various lints in the "warn" argument section to verify that the warnings work. Also ran "cargo test"
N/A
=> enabled adding lints to warning list to clippy

secure/key-manager/README.md
This PR adds a small README file to the key manager. This should help provide better clarity and insights as to the role of the key manager in our ecosystem.
Yes.
Viewing the file as markdown locally seems to render correctly.
None.
=> [Key Manager] Add the missing README to the key manager directory.

Cargo.lock, common/libradoc/Cargo.toml, language/transaction-builder/generator/Cargo.toml, language/transaction-builder/generator/examples/golang/stdlib_demo.go, language/transaction-builder/generator/src/golang.rs, summaries/summary-release.toml
* Improve Golang codegen (e.g. `type Foo struct { Value uint64 }` -> `type Foo uint64`)
*  C++ : Fix bug in operator==  over `128`-bit integers
```
cargo x test -p transaction-builder-generator -- --ignored
```
https://github.com/facebookincubator/serde-reflection/pull/53
=> [dependency] update serde-generate to 0.13.0

types/src/account_config/resources/currency_info.rs
We need to construct an instance of `CurrencyInfoResource` in AOS - currently the only way to do this is to deserialize a json which is probably not the best way to do this.
cargo build
=> Create constructor for CurrencyInfoResource

secure/storage/src/crypto_storage.rs
This PR removes the "unimplemented!()" macro from the default implementation of "import_private_key" for CryptoStorage. Right now it seems that all CryptoStorage implementations use either their own implementation of "import_private_key" (e.g., vault), or the default implementation provided by CryptoKVStorage. As a result, we don't need this default implementation. Moreover, we probably want to avoid providing a default that is not implemented, and instead force the compiler to tell the user that they should provide an implementation for this.
Yes.
All test still pass locally.
None.
=> [Secure Storage] Remove "unimplemented!()" as default implementation for CryptoStorage.

json-rpc/docs/type_event.md
The `sequence_number` property of the transaction event object was erroneously defined as string. Changed to unsigned int64, as it currently appears in the Libra Blockchain.
=> JSON-RPC spec: fixed the data type of event.sequence_number

.circleci/config.yml, .github/workflows/land-blocking.yml
This cherry-pick was triggerd by a request on #5671
> 
> Set up a latches to allow the first master build on any given day to:
> 
> 1. generate and push code coverage.
> 2. generate a new circleci base image.  libra/build_environment:circleci-latest
> 
> ### Have you read the [Contributing Guidelines on pull requests]
> 
> Yes
> 
> ## Test Plan
> 
> All the CIs
> 
> 
> None
cc @sausagee
=> Cherry-pick PR #5671 into release-0.20: Set up cache file as a daily latch for code coverage and fresh circleci build images

consensus/safety-rules/src/error.rs
The old code literally prints out "0" instead of the intended string.
Y
it compiles
=> [easy][safety-rules] fix the error representation

docker/mint/server.py
Faucet doesn't wait long enough for waiting on sequence number update to be processed, which results in 500 timeout errors frequently. To mitigate, change timeout to 4 seconds. 
For `application.client.delaybeforesend`, when the libra CLI starts up, it prints out a whole bunch of help text, and if users’ development machines are slow enough, pexpect will start writing the mint command to stdin before the libra CLI is finished writing the help text, and so the help text will become interleaved with the mint command.  Then the help command finishes, and ends with a newline, which causes the (not yet finished) mint command to be processed by the CLI, which causes a parse error and the mint command is never successfully processed. This leads to the mint server returning 500's, with an error …
=> [faucet] Add longer delay for timeout

language/testing-infra/e2e-tests/src/account.rs
Event handle generation in e2e tests is nondeterministic, which is not desired for a lot of tests. This makes it use the same deterministic logic used in the Move stdlib. 
In the long run, we should get rid of the rust representation of LibraAccount in e2e tests and instead use Move scripts/function invocations to initialize the accounts.
Rebase https://github.com/libra/libra/pull/5877 on top of this, and the failing tests should pass.
=> [language][e2e tests] make event handle generation deterministic

Cargo.lock, consensus/safety-rules/Cargo.toml, consensus/safety-rules/src/fuzzing_utils.rs, consensus/safety-rules/src/test_utils.rs
This PR aims to improve the fuzzing target coverage for safety rules. More specifically, it offers two improvements (in separate commits) to help get the fuzzer past "sticky points" that we're currently seeing in the fuzzing coverage graphs:
1. Initialize the internal state of safety rules (e.g., the signer) before calling appropriate fuzz targets. This will help to get past the `self.signer()?;` method call which is currently blocking the fuzzer.
2. Generate real signatures for input data to the fuzz targets (instead of random signature bytes). This will help to get past signature verification (or at the very least, execute it).
Yes.
All tests pass locally. Moreover, running the fuzzers locally seems to work.
None.
=> [Fuzzing] Initialize safety rules in fuzz targets and generate signatures for improved coverage.

secure/key-manager/src/lib.rs, secure/key-manager/src/logging.rs, secure/key-manager/src/main.rs
This also fixes the issue where all log lines were reported coming from a single location in source by removing and `log` function and using the log macros explicitly.
=> key-manager: define and use a typed log schema

.github/workflows/dep-summaries.yml
This should fix the spurious issues from the dependency verifier. It turned out that GitHub's checkout action doesn't checkout the PR but a new ref that is the PR merged into master. This broke the assumptions of the verifier and caused much havoc.
=> Fix dep verifier

json-rpc/src/runtime.rs, json-rpc/types/src/response.rs, json-rpc/types/src/views.rs
Small step to create new json rps response for client, current client does not handle response body chain id, version and timestamp, we need decode them in client for chain id and server side ledger version and timestamp.
This diff adds new JsonRpcResponse to json rpc types, and use the type for server response.
Existing unit test should cover the response data validation.
=> [json-rpc] standard jsonrpc response object

state-synchronizer/src/coordinator.rs, state-synchronizer/src/executor_proxy.rs, state-synchronizer/src/tests/helpers.rs
remove unused `ExecutedTrees` arg in `ExecutorProxyTrait::execute_chunk`
Existing tests
=> [state sync] rm dead arg in ExecutorProxyTrait::execute_chunk

testsuite/libra-fuzzer/src/fuzz_targets.rs
This target harness has an issue with proptest strategy where too many
input value rejections lead to runner error in proptest.
This error in turn broke the fuzzing coverage workflow. Temporarily
disable this harness to unblock coverage.
Tested on devserver.
=> [fuzz] disable JellyfishGetWithProof harness

types/src/account_config/events/received_mint.rs
This should fix the "unknown" json-rpc response DDs were seeing using this key. cc @ankushagarwal 
Test:
`curl http://localhost:58918 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"get_events","params":["0000000000000000000000000000000000000000000000dd", 0, 100],"id":1}'
{"libra_chain_id":4,"libra_ledger_version":11490,"libra_ledger_timestampusec":1600111869262684,"jsonrpc":"2.0","id":1,"result":[{"data":{"amount":{"amount":9223372036854775807,"currency":"Coin1"},"destination_address":"000000000000000000000000000000dd","type":"receivedmint"},"key":"0000000000000000000000000000000000000000000000dd","sequence_number":0,"transaction_version":0},{"data":{"amount":{"amount":9223372036854775807,"currency":"Coin2"},"destination_address":"000000000000000000000000000 …
=> Reordering of ReceivedMintEvent

.github/workflows/dep-summaries.yml
@davidiw noticed that the dependency verifier action had a weird behavior in https://github.com/libra/libra/pull/6037. This happened because right before bors lands a PR it rebases and force pushes the new commit to the pull request. This re-triggers the dependency verifier flow, which is a little odd.
This change prevents running the workflow if the action was triggered by bors-libra.
=> [ci] Don't run dependency verifier workflow on bors-libra events

docker/tools/Dockerfile, docker/tools/boto.cfg
`gsutil` needs this config before it will look for a service account
from instance metadata :-(
=> [dkr] Fix service account auth with gsutil

storage/backup/backup-cli/src/coordinators/restore.rs, storage/jellyfish-merkle/src/mock_tree_store.rs, storage/jellyfish-merkle/src/restore/mod.rs, storage/jellyfish-merkle/src/restore/restore_test.rs, storage/libradb/src/backup/restore_handler.rs
so that a network glitch won't ruin everything.
1. epoch endings and state snapthots are small in V1, this makes sure they can be overwritten.
2. skip transactions when possible, in whole batches though, meaning there will still be some overwriting
Y
playing locally by Ctrl-C ing
will add fail points in smoke tests as a follow up.
=> [backup] `restore auto` able to resume from previous failure

storage/backup/backup-cli/src/coordinators/restore.rs, storage/jellyfish-merkle/src/mock_tree_store.rs, storage/jellyfish-merkle/src/restore/mod.rs, storage/jellyfish-merkle/src/restore/restore_test.rs, storage/libradb/src/backup/restore_handler.rs
This cherry-pick was triggerd by a request on #6106
> 
> so that a network glitch won't ruin everything.
> 
> 1. epoch endings and state snapthots are small in V1, this makes sure they can be overwritten.
> 2. skip transactions when possible, in whole batches though, meaning there will still be some overwriting
> 
> 
> Y
> 
> ## Test Plan
> 
> playing locally by Ctrl-C ing
> will add fail points in smoke tests as a follow up.
> 
> 
> (If this PR adds or changes functionality, please take some time to update the docs at …
=> Cherry-pick PR #6106 into release-0.22: [backup] `restore auto` able to resume from previous failure

network/src/counters.rs, network/src/peer_manager/mod.rs, network/src/protocols/rpc/mod.rs
[network] rename rpc latency metric and add protocol_id label
+ Rename to "libra_network_outbound_rpc_request_latency_seconds"
+ Add "protocol_id" label
[network] Add inbound rpc handler latency metric
+ Adds histogram metric "libra_network_inbound_rpc_handler_latency_seconds"
+ Should give us better visibility into how long each rpc handler takes to respond to inbound requests.
[network] Add pending connection upgrades metric
+ Add gauge metric "libra_network_pending_connection_upgrades"
+ Should give us a lot more visibility into how many connections we're currently trying to negotiate. Could probably set an alert on this to warn during potential DDoS scenarios.
[network] Add connection upgrade time histogram metric
+ Adds metric "libra_network_connection_upgrade_time_seconds" histogram …
=> [network] add more detailed connection upgrade metrics and expand rpc latency metrics

storage/accumulator/src/lib.rs
old msg: The other accumulator is bigger than this one
new msg: Can't get accumulator consistency proof for a version newer than the local version.
Y
eyes
=> trivial: improve error message

storage/libradb/src/lib.rs
1. avoids some in vein operations if it's gonna fail the `ledger_store.get_consistency_proof()` anyways later.
2. more readable error message than lower in the stack.
Y
=> [storage] ensure client known_version no newer than leger version, earlier

Cargo.lock, language/tools/transaction-replay/Cargo.toml, language/tools/transaction-replay/src/main.rs
A pretty simple PR that adds a subcommand to the `transaction-replay` tool to allow diffing an account state at two different versions. 
```
$ cargo run -- -u https://testnet.libra.org/v1 diff-account 000000000000000000000000000000dd 0 2340288
```
=> [language/tools] Add account diff to transaction-replay tool

consensus/src/epoch_manager.rs
Continually capture the time of consensus process via the event loop to ensure that clock skew between validators is reasonable and to find any unusual (possibly byzantine) clock behavior.
=> [consensus][observability] Capture time as a gauge

secure/key-manager/src/main.rs
This PR updates the key manager to log its config on startup. In many cases, this is useful to provide better observability to parties who don't have access to the key manager deployment directly but do have access to the logs (e.g., the blockchain on-call who might help debug issues, or subject matter experts). 
Note: it seems this is already happening in most of the processes we spawn (e.g., safety rules, libra-node). It might make sense for this to be a requirement in general (just as long as we don't think anything sensitive will be logged -- but I'd think this is unlikely).
Yes.
Running the key manager locally shows the config now being logged.
None.
=> [Key Manager] Log the key manager config on startup for better observability.

language/move-core/types/src/account_address.rs, language/move-core/types/src/language_storage.rs, language/tools/move-cli/tests/testsuite/events_emit_view/args.exp, language/tools/move-cli/tests/testsuite/libra_smoke/args.exp, language/tools/move-cli/tests/testsuite/module_run_view/args.exp
When running 'move view', addresses are shortened from left to right. This can often lose information, so this PR instead shortens the addresses by stripping all leading zeros. For example, 0x0000000000000000000000000000000a becomes 0xa.
Yes
Steps to repro:
1. cd ~/libra/language/tools/move-cli/tests/testsuite/module_run_view
2. NO_MOVE_CLEAN=1 cargo xtest
3. move view move_data/0x0000000000000000000000000000000a/resources/0x00000000000000000000000000000002::Test::R.lcs
Old output:
resource 00000000::Test::R {
i: 6
}
New output:
resource 0x2::Test::R {
i: 6
}
I wrote a separate function, short_str_lossless, since it seems like short_str is used elsewhere in the codebase and the functionality of short_str_lossless is somewhat different. Furthermore, the ShortHexStr struct seems to enforce …
=> [move-cli] print compressed addresses in 'move view'

testsuite/cluster-test/src/tx_emitter.rs
This cherry-pick was triggerd by a request on #6480
> reusable generation account is using a same rng to generate consistency seeds, which can guaranty accounts addresses are always the same. But falsely clone the rng cause the result of each batch of account generation are same. And performance of CT on premainnet on board  is different with client side data. We need to make rng is mutable
> 
> 
> (Write your motivation for proposed changes here.)
> 
> 
> (Write your answer here.)
> 
> ## Test Plan
> czh@czh-mbp libra-libra % ./target/debug/cluster-test --swarm …
=> Cherry-pick PR #6480 into release-0.23: [cluster-test] fix feature of reusable account

types/src/chain_id.rs
We should be able to start using a stable chain ID for pre-mainnet, add
a named chain.
=> Add NamedChain for pre-mainnet

Cargo.lock, language/tools/move-cli/Cargo.toml, language/tools/move-cli/src/main.rs, language/tools/move-cli/src/test.rs, language/tools/move-cli/tests/cli_tests.rs, language/tools/move-cli/tests/cli_testsuite.rs, language/tools/move-cli/tests/metatests/args.exp, language/tools/move-cli/tests/metatests/args.txt, language/tools/move-cli/tests/metatests/cov/args.exp, language/tools/move-cli/tests/metatests/cov/args.txt, language/tools/move-cli/tests/metatests/cov/move_src/modules/M.move, language/tools/move-cli/tests/metatests/cov/move_src/scripts/test.move
The Move CLI provides a `test` command for running expected value tests and a (separate) code coverage tool for measuring instruction coverage at the bytecode level. This task is to integrate these two tools so that `test` optionally produces a coverage report for the code under test. This will provide an awesome experience for new developers starting with Move: free code coverage info integrated with testing!
Yes
Add an additional `--track-cov` flag to the end on how `move-cli test` is supposed to run, e.g.,
`cargo run --bin move-cli -- test tests/testsuite/module_run_view/args.txt --track-cov`
Coverage information will be printed, per module, per function.
This is a duplication of #6411, but rebased onto `feature-dev` instead of `master`.
=> [move-cli] add the option to show coverage within `move-cli test`

common/debug-interface/src/node_debug_service.rs, libra-node/src/lib.rs
Periodically dump some interesting state:
* Config and arguments used to start up the process
* latest ledger version and root hash at that version as well as the
chain_id
Fixes: #5634
=> libra-node: periodically dump interesting state

json-rpc/API-CHANGELOG.md, json-rpc/docs/type_metadata.md, json-rpc/src/methods.rs, json-rpc/src/tests/unit_tests.rs, json-rpc/src/tests/utils.rs, json-rpc/tests/integration_test.rs, json-rpc/types/src/views.rs, storage/accumulator/src/lib.rs, storage/accumulator/src/test_helpers.rs, storage/accumulator/src/tests/write_test.rs, storage/libradb/src/ledger_store/mod.rs, storage/libradb/src/lib.rs, storage/libradb/src/libradb_test.rs, storage/storage-interface/src/lib.rs
This cherry-pick was triggerd by a request on #6536
> 
> To expose the information. related to effort seen in #5803 and #5634 
> 
> 
> Y
> ## Test Plan
> 
> unit tests.
> 
> 
cc @sausagee
=> Cherry-pick PR #6536 into release-1.0: [storage, json-rpc] Expose root hash through json-rpc

state-synchronizer/src/coordinator.rs, state-synchronizer/src/tests/integration_tests.rs
`PendingLedgerInfo` prunes out LIs that we can potentially set to as a target LI in chunk requests based on committed version, not synced version. This causes problems in the following FN long-poll scenario:
1. A FN sends an upstream node a chunk request with known version X and target version Y (X < Y)
2. The upstream that receives this is behind version X when it receives the FN's request, so it caches it for long-poll subscription.
3. Within the long-poll time window, the upstream reaches a version Z > X, and it fulfills the cached long-poll request with a target version of Z and a chunk of transactions X .. W, where W > Y
4. FN processes that response successfully and the resulting local synced version is W, but because of the way PendingLedgerInfos is pruned, the outdated LI Y is …
=> [state sync] prune outdated LIs from PendingLedgerInfo

state-synchronizer/src/coordinator.rs, state-synchronizer/src/tests/integration_tests.rs
This cherry-pick fixes a state-sync bug encountered in premainnet. The symptom is that state sync will be stuck for.a FN (see technical details below), and this PR addresses this problem. This change affects Libra nodes - they will have to restart with the updated software. 
`PendingLedgerInfo` (state sync's in-memory store of candidates for target LI in chunk request) prunes out LIs based on the local committed version, not synced version. This causes problems in the following FN long-poll scenario:
1. A FN sends an upstream node a chunk request with known version X and target version Y (X < Y)
2. The upstream that receives this is behind version X when it receives the FN's request, so it caches it for long-poll subscription.
3. Within the long-poll time window, the upstream reaches a …
=> [cherry-pick] [state sync] prune outdated LIs from PendingLedgerInfo

json-rpc/docs/method_get_metadata.md, json-rpc/docs/type_metadata.md, json-rpc/src/methods.rs, json-rpc/tests/integration_test.rs
JSON-RPC get_metadata method responses server error when client request an old version that storage layer dropped the account state for the version.
This PR fixes the error by only return libra version and move script hashing information only when client request latest ledger version.
Why we must have it for V1 launch: without this fix, get_metadata is likely can only get recent transaction metadata, it seems lots of people use it to get transaction timestamp when got a transaction version somewhere that has no timestamp with it.
What workarounds and alternative we have if we do not push the PR: call get_transactions for the transaction timestamp by version.
#6594
=> cherry-pick [json-rpc] get_metadata only return move version info when requesting latest version

.github/workflows/land-blocking.yml, .github/workflows/post-land.yml
Google's project-zero recently disclosed an injection vulnerability in
Github Actions due to GHA's parsing STDOUT in order to execute commands,
specifically the use of the `set-env` command can result in remote code
execution in some circumstances. For more information on this
vulnerability please see
https://bugs.chromium.org/p/project-zero/issues/detail?id=2070.
The current recommended fix from Github
(https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
is to migrate from using the `set-env` command and instead use
environment files for setting environment variables for subsequent
workflow steps.
This patch follows Github's recommended mitigation and removes all uses
of the `set-env` command from our Github Action workflows.
=> ci: stop using set-env

config/src/config/consensus_config.rs
What this affects:
Memory usage of consensus
Why is this critical:
Can result in excessive memory usage for validator nodes that is never used.
We prefer not to modify configs unless we have to -- the default config should always be in the best state.
What is the workaround (even if it is unintuitive / horrible):
Modify the value in partners repo
> 
> 
> 
> Reduce the memory pressure when the block is full.
> 
> 
> (Write your answer here.)
> 
> ## Test Plan
> 
> test on dryrun mainnet, memory spike disappear
> 
> 
> (If this PR adds or changes functionality, please take some time to update the docs at …
=> Cherry-pick PR #6647 into release-1.0: [consensus] reduce default max pruned block size

config/src/config/state_sync_config.rs, state-synchronizer/src/tests/integration_tests.rs
**What this affects:**
Performance of state sync will be more in line with consensus allowing for more practical state syncs
**Why is this critical:**
Without a config update, state sync can run slower than consensus and peers may never catch up or do so slowly.
We prefer not to modify configs unless we have to -- the default config should always be in the best state.
**What is the workaround (even if it is unintuitive / horrible):**
Modify the value in partners repo
**testing:**
* smoke tests
* PFN running locally
* recommended to upstreams (they may or may have applied it)
> state syncs txn rate is approximately:
> chunk size / (RTT to upstream + execution time)
> consensus txn rate is approximately:
> chunk size / (2 x slowest latency + execution time)
> 
> in addition consensus chunk …
=> Cherry-pick PR #6627 into release-1.0: [config] set chunk size for state sync to 1k

common/logger/src/libra_logger.rs
Logs used to be opened with write() only, meaning that if the logfile
already existed, logs would not be produced.
Changing write() to append() (which is effectively write() +
append()).
Yes.
Ran the following command twice: `cargo run -p libra-node -- --test --config /tmp/efd6dc5656ee8edf92569c330b8de8bb/0/` and verified that:
- Second run also produced logs
- The logfile contained logs from the first run
No related PRs.
=> [logger] Opening logs for write+append, instead of only write

config/management/genesis/README.md, config/management/genesis/src/storage_helper.rs, config/management/genesis/src/validator_config.rs, config/management/operational/src/account_resource.rs, config/management/operational/src/auto_validate.rs, config/management/operational/src/command.rs, config/management/operational/src/governance.rs, config/management/operational/src/lib.rs, config/management/operational/src/owner.rs, config/management/operational/src/print.rs, config/management/operational/src/test_helper.rs, config/management/operational/src/validate_transaction.rs, config/management/operational/src/validator_config.rs, config/management/operational/src/validator_set.rs, config/management/src/config.rs, config/management/src/lib.rs, config/management/src/validator_config.rs, config/management/src/waypoint.rs, testsuite/cluster-test/src/genesis_helper.rs, testsuite/smoke-test/src/client.rs, testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/operational_tooling.rs, testsuite/smoke-test/src/test_utils.rs
This PR affects the genesis tool (./libra-genesis-tool) and the operational tool (./libra-operational-tool), both located in libra/config/management.
This PR provides 4 critical bug fixes for these tools:
1. First, it fixes a bug related to whitespace handling in cryptographic key files when performing crucial operations, such as creating a new validator account or a validator operator account. See here for more information: https://github.com/libra/libra/pull/6548
2. Second, it provides a way to disable network address validation checks when performing operations that update the on-chain ValidatorConfig of a validator account. This avoids spurious errors that currently prevent an operator from updating their ValidatorConfig (including key rotations!). See here for more information: …
=> [Tooling] Crucial bug fixes and better debugging support for operators

.github/workflows/land-blocking.yml, .github/workflows/post-land.yml
LBT workflow in GH Actions.
It addresses the vulnerability found by Google's project-zero (see details in PR landed in master #6642). The set-env cmd will be deprecated soon (https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).
Disable LBT workflow.
Canary https://github.com/libra/libra/runs/1356229364?check_suite_focus=true
=> Cherry-pick PR #6642 into release-1.0: ci: stop using set-env

network/src/protocols/health_checker/mod.rs
* This removes health checker logs, which are roughly a quarter of all logs, but don't serve any usable purpose.  This should decrease pressure on the logging system.
* No breaking changes, decreased health check logs, but they're never used
* Logging in all (validator/full) nodes with healthchecking
We could accomplish the same thing by filtering logs in logstash, but that would just stop the logs from being stored, but continue put pressure on the log throughput.
* Original PR https://github.com/libra/libra/pull/6672
=> [network] Decrease Healthchecker logs

storage/backup/backup-cli/src/utils/mod.rs
So when we do concurrent downloading of chunks to memory, they won't take too much of it.
It's possible to use more sophisticated streaming and buffering, but this is straightforward.
Y
@mgorven helped testing on his network.
=> [backup] default chunk size: 128M

Cargo.lock, common/lcs/Cargo.toml, common/lcs/tests/serde.rs, crypto/crypto/src/unit_tests/lcs_test.rs, crypto/crypto/src/unit_tests/mod.rs
We are going to move LCS to its own repo soon.
CI
=> [LCS] remove test dependency to libra-crypto

config/src/config/storage_config.rs
This cherry-pick was triggerd by a request on #6668
> 
> Looks like it's common that people run fullnodes on volumes that are smaller than a few hundred gigabytes.
> 
> 
> Y
> 
> ## Test Plan
> 
> eyes
> https://github.com/libra/partners/pull/610
cc @msmouse
=> Cherry-pick PR #6668 into release-1.0: [storage] shrink default prune_window

storage/backup/backup-cli/src/utils/mod.rs
This cherry-pick was triggerd by a request on #6699
> 
> 
> So when we do concurrent downloading of chunks to memory, they won't take too much of it.
> It's possible to use more sophisticated streaming and buffering, but this is straightforward.
> 
> 
> Y
> ## Test Plan
> @mgorven helped testing on his network.
cc @msmouse
=> Cherry-pick PR #6699 into release-1.0: [backup] default chunk size: 128M

json-rpc/types/src/proto/jsonrpc.proto
The field was added by PR https://github.com/libra/libra/pull/6536, this change makes sure clients depending on jsonrpc.proto can generate right Metadata struct
Yes
N/A
=> [json-rpc] add field Metadat#accumulator_root_hash to protobuf definition

Cargo.lock, common/libradoc/Cargo.toml, language/transaction-builder/generator/Cargo.toml, language/transaction-builder/generator/examples/java/custom_libra_code/AccountAddress.java
Upgrade to `serde-generate 0.16.0`.
This is needed to fix equality tests in Java SDK (https://github.com/novifinancial/serde-reflection/pull/73)
```
cargo test -p transaction-builder-generator
cargo test -p transaction-builder-generator -- --ignored
```
=> [serde-generate] upgrade to 0.16.0

consensus/src/block_storage/block_store.rs, consensus/src/block_storage/mod.rs, consensus/src/block_storage/tracing.rs, consensus/src/counters.rs, consensus/src/round_manager.rs
This commit unifies and adds a few tracing of different stages of a block:
- signed
- received
- synced
- executed
- voted
- qc aggregated
- qc received == next block synced
- committed
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)
=> [consensus] better tracing

Cargo.lock, mempool/Cargo.toml, mempool/src/shared_mempool/tasks.rs
Reduce vm_validation from 10ms to 3ms.
Y
canary
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)
=> [mempool] parallel validation

consensus/safety-rules/src/error.rs, consensus/safety-rules/src/persistent_safety_storage.rs, consensus/safety-rules/src/safety_rules.rs, consensus/src/epoch_manager.rs
This PR improves the error handling/logging in consensus under failures to initialize safety rules (LSR). More specifically, it:
- Better distinguishes missing keys/data in secure storage vs. unexpected failures. 
- Improves the errors logged by consensus by adding additional context around how to react to the errors.
(This PR is small but mostly just creates a space for discussion around the best approach, so we can come to some state of consensus)
Yes.
All tests pass locally.
This PR follows a previous discussion here: https://github.com/libra/libra/pull/6671.
=> [Consensus] Improve error handling for failure to initialize safety rules

.github/dependabot.yml
Dependabot normally is limited to 5 prs.    We have too many stuck dependency prs for dependabot to help us stay up to date.   Allow dependabot to open 15 prs.
Yes
CI
All the dependabot prs?
=> [ci] turn dependabot up to eleven

.circleci/config.yml
Use the target determinator for unit tests. We can probably also use it
for high-level filtering of builds in the future (stacked with sccache),
but this PR is specifically for unit tests.
=> [circleci] use target determinator to only run a subset of unit tests

devtools/x/src/changed_since.rs
Realized that you can do something silly like just delete a file without
affecting any others.
Tested by deleting storage/libradb/src/metrics.rs, then running `cargo xbuild
--changed-since HEAD` and seeing that libradb and a bunch of other packages
were re-tested.
=> [x] don't ignore deleted files in changed-since

README.md
A hyper link of `Execution` seems to be broken in README.md.
Yes.
=> Update a broken link of Execution in README.md

language/benchmarks/src/move_vm.rs, language/libra-tools/transaction-replay/src/lib.rs, language/move-lang/functional-tests/tests/functional_testsuite.rs, language/move-lang/src/bin/move-build.rs, language/move-lang/src/bin/move-check.rs, language/move-lang/src/expansion/ast.rs, language/move-lang/src/lib.rs, language/move-lang/src/parser/ast.rs, language/move-lang/tests/move_check_testsuite.rs, language/move-lang/tests/stdlib_sanity_check.rs, language/move-prover/spec-lang/src/lib.rs, language/move-vm/integration-tests/src/compiler.rs, language/stdlib/src/lib.rs, language/tools/move-cli/src/main.rs, language/tools/move-cli/src/package.rs
- Allow for general start/stop of the compiler
- Simplified and reduced number of entry points
- For supporting republishing, we need the ability to parse the files and check for the address/modules that exist in that file so we know which to remove from the dependency list 
- general start/stop and "state machine"-like control allows the compiler to continue after parsing. 
- Cargo test
=> [move source language] Update compiler API

state-synchronizer/src/coordinator.rs, state-synchronizer/src/counters.rs, state-synchronizer/src/request_manager.rs
* Cleaned up the version counters
* Moved target version counter to a saner and earlier location
* Made target version more sensible such that it is always updated otherwise we end up with charts where target < synced | committed
* Added a highest version because this actually gives us an indication of how far behind the node is where as target is more indicative of when the next commit will occur
=> [state-sync] version counters updates

docker/cluster-test/buildspec.yaml, docker/init/buildspec.yaml, docker/mint/buildspec.yaml, docker/safety-rules/buildspec.yaml, docker/tools/buildspec.yaml, docker/validator/buildspec.yaml
Dockerhub api enforcement ratcheted up over the month of November finally effecting us in the last week (100 api calls per hour).   So sign in to dockerhub when we have to build docker image in aws codebuild.   
Because the more CI's the merrier.
Yes
Been working in master the last 9 days.
PR in to master:   https://github.com/libra/libra/pull/6730
=> [codebuild] use dockerhub login

consensus/safety-rules/src/error.rs, consensus/safety-rules/src/persistent_safety_storage.rs, consensus/safety-rules/src/safety_rules.rs, consensus/safety-rules/src/tests/suite.rs, consensus/src/epoch_manager.rs, testsuite/smoke-test/src/consensus.rs, testsuite/smoke-test/src/lib.rs, testsuite/smoke-test/src/operational_tooling.rs
This PR changes the way that consensus interacts with safety rules when safety rules fails to initialize under an epoch change:
- At present, if safety rules fails to initialize when an epoch changes (e.g., due to not being able to find the expected consensus key in storage), consensus will panic and stop operating.
- Instead, consensus should not panic but continue to operate and simply observe the progress being made by the rest of the network. This is what we already do in some cases today (e.g., if the validator is not in the validator set for the new epoch).
There are several practical reasons why safety rules might fail to initialize under a new epoch change. A notable one is when secure storage no longer contains the consensus key expected for that epoch. The reasons for this might …
=> [Cherry-pick] Consensus shouldn't panic on a failure to initialize safety rules

Cargo.lock, config/management/genesis/src/verify.rs, config/management/genesis/src/waypoint.rs, config/src/config/storage_config.rs, consensus/src/consensusdb/mod.rs, execution/db-bootstrapper/Cargo.toml, execution/db-bootstrapper/src/bin/db-bootstrapper.rs, execution/executor-benchmark/src/lib.rs, language/libra-tools/libra-validator-interface/Cargo.toml, language/libra-tools/libra-validator-interface/src/storage_interface.rs, libra-node/src/lib.rs, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/inspector/Cargo.toml, storage/inspector/src/main.rs, storage/libradb/Cargo.toml, storage/libradb/src/lib.rs, storage/schemadb/Cargo.toml, storage/schemadb/src/lib.rs, storage/schemadb/tests/db.rs, storage/schemadb/tests/iterator.rs
- Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
All the node will be affected with the new default rocksdb options.
- Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
Theoretically it doesn't affect libra system behavior but db behaviors. The current cluster tests and dry-run longevity test has proven it is working and not breaking anything.
- Why we must have it for V1 launch.
Because for long run it may trigger OOM.
- What workarounds and alternative we have if we do not push the PR.
provide unlimited memory to each node which seems impractical
=> Cherry-pick PR #6656 [config] rocksdb options to release 1.0

config/src/config/storage_config.rs, storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/utils/mod.rs
max_open_files defaults to 1000 instead of 10k used for a node to save some memory. The restore tool appends without reading exiting values most of the time (execpt for when it's replaying transactions) so performance is less of a concern.
Y
built and ran locally
=> [backup] allow passing in rocksdb options on command line

.circleci/config.yml, Cargo.lock, Cargo.toml, devtools/x-core/Cargo.toml, devtools/x-lint/Cargo.toml, devtools/x/Cargo.toml
Managed to get these out on to crates.io, so we don't need an override any more.
=> [x] update guppy and determinator to versions on crates.io

testsuite/smoke-test/src/key_manager.rs
This PR reduces the aggression of the key manager smoke test. It's a duplicate of the previous PR which wouldn't land because of flaky land blocking tests and the fact that the rename has borked my ability to update the PR after the conflict 😢 (https://github.com/diem/diem/pull/6868)
Yes.
Tests pass locally.
https://github.com/diem/diem/pull/6868
=> [Key Manager] Make the key manager smoke test less aggressive.

storage/backup/backup-cli/src/bin/db-backup.rs, storage/backup/backup-cli/src/coordinators/backup.rs, storage/backup/backup-cli/src/metrics/backup.rs, storage/backup/backup-cli/src/metrics/mod.rs
We used to rely on metrics from the server side to dashboard and alert, but those are reported only when a backup is being done. If the node gets restarted and no new backup is needed, the gauge values will disappear from the dashboard and trigger alerts.
We now report those metrics from the coordinator and report periodically in case the push gateway gets restarted.
Y
on my testnet
=> [backup] backup coordinator metrics

Cargo.lock, common/logger/Cargo.toml, common/logger/src/diem_logger.rs, common/logger/src/metadata.rs
This PR is a copy of a previously accepted but prematurely closed PR (https://github.com/diem/diem/pull/6778). The PR was prematurely closed for technical reasons (inability to rebase). 
Note: the only differences between this PR and the closed one are: (i) this PR has been rebased to the head of master (post rename); and (ii) this PR removes the first 3 unnecessary backtrace frames from each backtrace (see the diff by comparing the examples embedded in each PR).
Yes.
All tests pass locally. Moreover, displaying the metadata error, we now get:
```
thread 'diem_logger::tests::basic' panicked at 'METADATA: Metadata { level: Error, target: "diem_logger", module_path: "diem_logger::diem_logger::tests", file: "common/logger/src/diem_logger.rs", line: 575, location: …
```
=> [Logger] Add backtraces to error logs.

language/move-prover/docgen/tests/sources/DiemTest.move, language/move-prover/docgen/tests/sources/DiemTest.spec_inline.md, language/move-prover/docgen/tests/sources/DiemTest.spec_inline_no_fold.md, language/move-prover/docgen/tests/sources/DiemTest.spec_separate.md, language/stdlib/modules/Diem.move, language/stdlib/modules/doc/Diem.md
Fixes a couple places where the ASCII hex encoding of "LBR" wasn't updated to the hex encoding of "XDX" in comments
=> [diem framework] Update hex in comments to reflect new "XDX" name

developers.diem.com/docs/move/creating-coins.md
Simple replace `libra` with `diem` in move cli install instructions
=> [small] Replace libra -> diem in repo name in docs

mempool/src/tests/shared_mempool_test.rs, network/src/connectivity_manager/mod.rs, network/src/connectivity_manager/test.rs, network/src/peer_manager/conn_notifs_channel.rs, network/src/peer_manager/mod.rs, network/src/peer_manager/tests.rs, network/src/protocols/health_checker/test.rs, network/src/protocols/network/mod.rs, state-synchronizer/src/tests/integration_tests.rs
When a new connection is formed, there is a lot of information available
and rather than just expose what we need for now, let's expose all that
information and let the recipients take what they need.
1. We have already extended the data here once if not twice
2. We have another requirement to extend it to include trusted peer / role
The interesting thing is that state sync and mempool already translate
these events into yet another event so there will need to be ensuing PRs
to address that.
(If this PR adds or changes functionality, please take some time to update the docs at …
=> [network] emit metadata on new and lost peers

.circleci/get_pr_info.sh
CI may not pull the base branch consistently. 
CI + canary fc57d76 in https://app.circleci.com/pipelines/github/diem/diem/37096/workflows/927b9918-7e13-4067-93d7-d0f92d2b6d5e/jobs/277166
=> [ci] check remote for target base branch

language/move-prover/src/boogie_wrapper.rs, language/move-prover/src/prover_task_runner.rs
If the BOOGIE_EXE is not found, the current prover_task_runner hangs. That is because a panicking thread does not terminate the program, but just dies, blocking other threads waiting for it. This PR propagates the error out of the task runner to the caller and panics in the main thread. It also prints the path where the boogie program was looked for.
Better UX
Yes
manual
NA
=> [move-prover] Fix hanging if boogie is not found and print which path was tried.

Cargo.lock, language/diem-tools/diem-validator-interface/Cargo.toml, language/diem-tools/diem-validator-interface/src/lib.rs, language/diem-tools/transaction-replay/Cargo.toml, language/diem-tools/transaction-replay/src/lib.rs, language/diem-tools/transaction-replay/src/main.rs, language/tools/move-cli/src/lib.rs, language/tools/move-cli/src/main.rs, testsuite/smoke-test/src/replay_tooling.rs, types/src/access_path.rs, types/src/account_state.rs, types/src/transaction/mod.rs
Add save_write_sets option to transaction-replay CLI that converts each write set to the on-disk representation that the Move CLI
understands. This makes it easy to get a local mirror of a state of interest, then use the CLI to inspect the state, run `move doctor`,
experiment with running txes on top of the latest state, etc.
```
cargo run --bin diem-transaction-replay -- --url https://mainnet.diem.com -s replay-transactions 0 1
move view storage/0x00000000000000000000000000000001/modules/XUS.mv 
move doctor
```
=> [tools] connect CLI to transaction replay

storage/diemdb/src/pruner/mod.rs, storage/diemdb/src/pruner/test.rs
This cherry-pick was triggerd by a request on #7113
> 
> PR #6803 avoided repeatedly seeking to the beginning in the stale node index, which was costly, by doing it beforehand and only once at construction time. However that one time yet costly call sit in the critical path of the node start up, which can result in a slow node start if the pruning window was large.
> 
> This moves the initial seek to the work thread.
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?
> 
> Y
> 
> ## Test Plan
> 
> existing coverage.
> 
> 
> #6803 
cc @msmouse
=> Cherry-pick PR #7113 into release-1.1: [storagte] state pruner: offload the first seek to the worker thread

language/move-model/src/builder/module_builder.rs, network/netcore/src/transport/mod.rs, network/src/connectivity_manager/mod.rs, network/src/peer/mod.rs, network/src/peer_manager/mod.rs, network/src/protocols/wire/handshake/v1/mod.rs, network/src/transport/mod.rs, storage/backup/backup-cli/src/metadata/view.rs, storage/diemdb/src/backup/backup_handler.rs, types/src/account_state.rs, types/src/chain_id.rs
Serde had a `serde::export` module exposed for use in its proc-macro derive crates, though it was never intended to be used publicly.
With the latest serde release (1.0.119) the `serde::export` module was finally renamed to `serde::__private` to more clearly express that downstream crates should not depend on it: (https://github.com/serde-rs/serde/blob/master/serde/src/lib.rs#L275).
This diff removes all occurances of `use serde::export::{..}` and replaces them with their `use std::{..}` equivalents.
=> [diem] Don't use serde::export private types

secure/storage/vault/src/lib.rs
This PR offers 3 small improvements to the vault secure storage client:
1. First, set the timeout() and timeout_connection() values explicitly. Right now timeout() is not being set, so vault could potentially hang on reads/writes and the client code could block indefinitely.
2. Second, ensure we are calling "ureq::Response.into_string()" on all response handling paths. This is required to clear the response buffers. This relates to: https://github.com/algesten/ureq/issues/94
3. Third, use "SyntheticError" and "SerializationError" where appropriate inside the client error handling code instead of "InternalError". "InternalError" is a bit too generic.
Yes.
All tests pass locally.
None, but these changes come as a result of the on-going investigation of: …
=> [Secure Storage] Update vault request timeout and error handling.

config/management/src/secure_backend.rs, config/src/config/secure_backend_config.rs, secure/storage/github/src/lib.rs, secure/storage/src/error.rs, secure/storage/src/github.rs, secure/storage/src/tests/github.rs, secure/storage/src/tests/suite.rs
We leverage github for genesis ceremonies and post genesis validator operations. Currently the code only supports a single branch. We cannot perform post genesis validator operations on the genesis repository without potentially corrupting the data that feeds into genesis. We also have operators generate genesis when onboarding. This adds support for branches so that we can lock genesis branch and still have folks build it when onboarding.
This is a tooling change only as github isn't used as a secure backend otherwise.
Tested via integration tests.
=> Cherry-pick PR #7150 into release-1.1: [secure-storage] support github branches

diem-node/src/lib.rs, json-rpc/tests/node.rs, network/simple-onchain-discovery/src/lib.rs
`stream.select_next_some()` returns a `FusedFuture`, which expects callers to check `is_terminated` before polling to ensure callers don't poll the future after it's completed.
In this case, `simple-onchain-discovery` was incorrectly using `select_next_some` inside a loop, expecting that the `reconfig_events` channel would never close. However, it appears that we get occasional panics during node shutdown, as referenced by this comment in diem-node:
> Shutdown network runtimes to avoid panic error log after DiemHandle is dropped:
> thread ‘network-’ panicked at ‘SelectNextSome polled after terminated’,...
> stack backtrace:
>    ......
>    8: network_simple_onchain_discovery::ConfigurationChangeListener::start::{{closure}}
>      at network/simple-onchain-discovery/src/lib.rs:175
> …
=> [network] Fix incorrect usage of `select_next_some` in onchain discovery 

config/src/config/storage_config.rs
This cherry-pick was triggerd by a request on #7197
> 
> Considering we don't currently open APIs for querying state history, it's agreed we should use a minimal prune_window, to be more friendly to any one who aims to clone a full chain to their disk.
> 
> (discussion is in https://github.com/diem/partners/issues/724)
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?
> 
> Y
> ## Test Plan
> 
> Will deploy a testnet with the new config.
> 
> 
> 
> 
> (https://github.com/diem/partners/pull/733 removes overrides from configs, so this value is in effect for both the validator and the fullnode)
cc …
=> Cherry-pick PR #7197 into release-1.1: [storage] smaller prune_window

.github/actions/matches/action.yml, .github/workflows/ci-test.yml
GHA doesn't do a good job of providing the identity of a job that has succeeded/failed.   Less so for a workflow file.
In order for bors to have something to hold on to, creating a success job that'll fast fail if any job fails.
So this was a bit tricky.   The result from a job is a string of "failure","skipped","success" or "cancelled", see:
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
Fun to figure out.
Also if a needed job was skipped by default, the dependent job is skipped as well (hence the "always()" in the if line of the job).  Commented inline.
Need to test this by creating failure cases and testing, as well as success case.  Created a PR for each and tested there:
Success PR: …
=> [gha] single job if needed for bors

mempool/src/core_mempool/index.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/core_mempool/ttl_cache.rs, mempool/src/lib.rs, mempool/src/shared_mempool/coordinator.rs, mempool/src/shared_mempool/network.rs, mempool/src/shared_mempool/peer_manager.rs, mempool/src/shared_mempool/runtime.rs, mempool/src/shared_mempool/tasks.rs, mempool/src/shared_mempool/types.rs, mempool/src/tests/common.rs, mempool/src/tests/core_mempool_test.rs, mempool/src/tests/fuzzing.rs, mempool/src/tests/mocks.rs, mempool/src/tests/mod.rs, mempool/src/tests/shared_mempool_test.rs
This PR removes the `#![deny(missing_docs)]` annotation from the mempool component code. The use of this annotation forces mandatory documentation (e.g., on methods and structs). However, this results in developers just adding documentation for the sake of it, rather than documentation that is actually useful (see the various examples removed in this PR). 
To address this, we remove the annotation from mempool and clean up redundant documentation. This PR offers the following commits:
1. Remove the `#![deny(missing_docs)]` annotation and remove/clean up documentation from core_mempool.
2. Remove/clean up documentation from shared_mempool.
3. Remove/clean up documentation from tests.
Note: this PR doesn't verify the correctness of the current comments/documentation (someone with more …
=> [Mempool] Remove `deny(missing_docs)]` annotation and clean up redundant documentation.

Cargo.lock, language/ir-testsuite/Cargo.toml, language/ir-testsuite/tests/testsuite.rs
- Keyed compiled module dependencies in the IRCompiler instance of the testing Compiler trait
- Uniqueness is needed in an upcoming IR update
- ran tests
- Theoretically a perf increase if there were a TON of duplicate modules, as the IR compiler generates the dep before adding it to it's own map (and shadowing the old one). In practice, no change as there really aren't duplicate modules except for about 5 IR tests
=> [move][testing] Make dependencies in IR tests unique

language/move-prover/bytecode/src/borrow_analysis.rs, language/move-prover/bytecode/src/clean_and_optimize.rs, language/move-prover/bytecode/src/dataflow_analysis.rs, language/move-prover/bytecode/src/function_target.rs, language/move-prover/bytecode/src/packed_types_analysis.rs, language/move-prover/bytecode/src/usage_analysis.rs
These are all used by the upcoming read/write set analysis, but are unrelated/independently useful.
- Make `AbstractDomain` implement `Debug`, which makes it easier to do debug printing of analysis results
- Add a `join_insert` utility function for `MapDomain`
- Add a `singleton` utility function for `SetDomain`
- Allow a `FunctionTarget` to iterate over its parameter indexes
=> [move prover] minor improvements to domains and utility functions

Cargo.lock, config/src/config/json_rpc_config.rs, json-rpc/Cargo.toml, json-rpc/src/runtime.rs, json-rpc/src/tests/utils.rs
If `tls_cert_path` and `tls_key_path` are provided, enable TLS on the
JSON-RPC port. This may be necessary in deployments without a load
balancer, or to provide additional security between a load balancer and
the node.
Test Plan: Ran fullnode with and without TLS, tested JSON-RPC request.
=> [json-rpc] Support TLS on JSON-RPC port

language/move-prover/bytecode/src/compositional_analysis.rs, language/move-prover/bytecode/src/packed_types_analysis.rs, language/move-prover/bytecode/src/usage_analysis.rs
…sults to new domain
Resubmitting https://github.com/diem/diem/pulls?page=2&q=is%3Apr+is%3Aopen with clean git history. Initial motivation to allow client to map summary of compositional analysis to new value.
Yes
=> [move-prover] Extend compositional analysis to allow summaries of different type v2

storage/diemdb/src/lib.rs
Correct it to the right name with dash instead of underscore.
=> [diemdb] correct rocksdb property names

language/vm/src/normalized.rs
A struct type `a::M::T` used in module `a'::M'` was incorrectly normalized to `a'::M'::T` due to a bug that used the module handle associated with the declaring module rather than the module handle associated with the StructHandleIndex.
=> [vm] Fix bug in creation of normalized types

.circleci/config.yml, .github/workflows/ci-publish-base-image.yml, .github/workflows/ci-test.yml, .github/workflows/daily.yml, .github/workflows/docker-publish.yml
Since we have a better relationship with, and are provided more capacity by gha migrating docker image builds to gha.
Leaving the config to perform docker image release in circleci, just disabled intentionally as a fall back until we've rock solid confidence in gha and a manual release playbook.
Yes
A test branch in diem/diem:  run is here:
https://github.com/diem/diem/runs/1750457255?check_suite_focus=true
An older build had the release audit working on both branches.
None.
=> [gha] docker pushes and release audit

consensus/src/state_computer.rs, diem-node/src/lib.rs, network/src/peer/fuzzing.rs, network/src/protocols/wire/handshake/v1/mod.rs, specifications/network/messaging-v1.md, specifications/state_sync/README.md, state-sync/src/client.rs, state-sync/src/coordinator.rs, state-sync/src/counters.rs, state-sync/src/fuzzing.rs, state-sync/src/network.rs, state-sync/src/request_manager.rs, state-sync/tests/integration_tests.rs, state-sync/tests/test_harness.rs, testsuite/cluster-test/src/experiments/load_test.rs, testsuite/generate-format/tests/staged/network.yaml
Note: no logic changes in this PR. 😄
This PR concludes the efforts to address the consistency issues in state sync by replacing instances of "synchronization/synchronizer" with "sync" (see https://github.com/diem/diem/pull/7299 for the first PR). Nothing should semantically change in this PR.
1. Rename "StateSynchronizerDirectSend" to "StateSyncDirectSend".
2. Rename "StateSynchronizerMsg" to "StateSyncMessage"
3. Clean up a few remaining comments and strings.
Note: these changes *should all be backward compatible*:
1. In commit 1, we change the name of the protocol, but the underlying protocol id integer is the same. This id is the data that is sent across the wire. 
2. In commit 2, we rename the state sync messages sent between validators and full …
=> [State Sync] Fix "Synchronization/Sync" consistency issues in network code.

language/move-prover/src/prelude.bpl, language/move-prover/src/spec_translator.rs, language/move-prover/tests/sources/functional/emits.exp, language/move-prover/tests/sources/functional/emits.move, language/stdlib/modules/Diem.move, language/stdlib/modules/Event.move, language/stdlib/transaction_scripts/update_exchange_rate.move
This PR updates the Prover in the following parts:
(1) The Prelude includes
- the definition of EventStore in Boogie,
- the Boogie model of the native function `write_to_event_store` to update EventStore properly,
- the Boogie model of `emit_event` that abstracts away the `counter` behavior (i.e., `counter` is not mutated in the verification world)
(2) `spec_translator.rs` converts the `emits` specs into the corresponding postconditions of the Boogie procedures
(3) Examples
- multiple test cases are added to `tests/sources/functional/emits.move`. Some are proved, and others are disproved by the Prover.
- `Diem::update_xdx_exchange_rate` and `Diem::mint_with_capability` are specified and verified.
- The transaction script `update_exchange_rate` is specified and verified
TODOs:
- Correctly …
=> [move-prover] Extending the Prover for the `emits` statements

storage/backup/backup-cli/src/storage/command_adapter/command.rs
`ChildStdoutAsDataSource` behaves wrongly with tokio 1.1.0. Issue is with the way we determine the EOF.
Y
existing coverage. And with manual overwrite of tokio version to 1.1.0
https://github.com/diem/diem/pull/7147
=> [backup] fix failure with updated tokio

Cargo.lock, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/backup_types/epoch_ending/restore.rs, storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/bin/db-backup.rs, storage/backup/backup-cli/src/coordinators/verify.rs, storage/backup/backup-cli/src/utils/mod.rs
Two possible uses:
1. set the genesis or the latest waypoint to confirm the backup is compatible.
2. set waypoints at versions where writeset transactions were used to overwrite the validator set, so that the signature check is skipped.
=> [backup] support for specifying trusted waypoints in restore / verify

Cargo.lock, testsuite/cluster-test/Cargo.toml
Handle the oh-so-annoying shared update of kube/k8s-openapi which must be updated together.
Yes
A kinda-sorta-speedy CI run.
kube update: https://github.com/diem/diem/pull/7344
k8s-openapi update: https://github.com/diem/diem/pull/7350
=> [deps] kube update

language/vm/src/deserializer.rs, language/vm/src/file_format_common.rs, language/vm/src/unit_tests/signature_token_tests.rs
- Threaded version information through the VM's deserializer
- It was a bit tricky to do this because the deserializer was so light weight
- An alternative option would be to stick the whole thing in some sort of deserializer struct/object and add the environment variable as a version, but that felt weird since there was only one thing in the env...
- We will need to case on the version information for future work
- none yet really, the code is not used yet
=> [move][vm] Versioned deserializer

Cargo.lock, network/Cargo.toml, network/src/peer/fuzzing.rs, network/src/peer/mod.rs, network/src/peer/test.rs, network/src/peer_manager/mod.rs, network/src/protocols/rpc/mod.rs
+ `Peer`, `InboundRpcs`, and `OutboundRpcs` now have a `TimeService` member, which they use to create async timeout futures.
+ `Peer` tests now use `TimeService::mock()`. For most tests, this effectively disables timeouts. For `peer_send_rpc_timeout` and `peer_recv_rpc_timeout`, we use the `MockTimeService` to advance time and trigger the request timeout.
+ Parent modules like `PeerManager` just hand `Peer` a real time service for now.
=> [network] Integrate `TimeService` into `Peer` actor and its tests.

language/compiler/bytecode-source-map/src/source_map.rs, language/move-lang/src/shared/remembering_unique_map.rs, language/move-lang/src/shared/unique_map.rs
- Added size_hint to unique map iterators for proper integration with ast_debug
- Fixed FunctionSourceMap::make_local_name_to_index_map. Parameters should be first
- bugs are bad
- Verified debug fix
- I am unsure of any tests for the source map
=> [Move] Fixed size_hint for unique map iterators. Fixed FunctionSourceMap::make_local_name_to_index_map

language/move-lang/functional-tests/tests/move/commands/if_assignment.move, language/move-lang/src/cfgir/eliminate_locals.rs, language/move-lang/src/cfgir/mod.rs
- Fixed bug where the eliminate_locals pass would inline assignments to function parameters
- The eliminate_locals pass heavily relies on the invariants of Move for correctness. It had has no knowledge of blocks or control flow and assumes that if a local was assigned only once, and never borrowed, that value can be inline. It did not consider the initial "assignment" of the parameter, causing a bug when that parameter was assigned in the function 
- Bugs are bad
- new test
=> [move source language] Don't inline asisgnments to parameters

.github/workflows/docker-publish.yml, docker/docker_republish.sh
Multiple steps run even if prior errors occur in gha docker push
First we build locally and tag and push to docker.io/diem/
Then republish to  docker.io/libra/
Then republish to ecr/diem/
If any image fails to push in a step, mark the step as a failure and print out the image name at the end of the step.
Yes
gha-test-1 branch:
forced failure:  https://github.com/diem/diem/runs/1772453602?check_suite_focus=true
success: https://github.com/diem/diem/runs/1772302304?check_suite_focus=true
None.
=> [gha] report on all docker errors at end of each step:

mempool/README.md
Urgent fix needed for 'Zero day notice SEV1 hotfix drill'
https://libra.pagerduty.com/incidents/PWTBYPW
There is an unacceptable line break in the documentation!
CI and manual checking
=> [mempool][documentation] Fixed line break in mempool README.md

language/move-lang/functional-tests/tests/diem/admin_scripts/basic_admin_script.exp, language/move-lang/functional-tests/tests/diem/admin_scripts/basic_admin_script.move, language/move-lang/functional-tests/tests/diem/authenticator/authenticator.exp, language/move-lang/functional-tests/tests/diem/authenticator/authenticator.move, language/move-lang/functional-tests/tests/diem/block/block_prologue.exp, language/move-lang/functional-tests/tests/diem/block/block_prologue.move, language/move-lang/functional-tests/tests/diem/block/expired_transaction.exp, language/move-lang/functional-tests/tests/diem/block/expired_transaction.move, language/move-lang/functional-tests/tests/diem/block/get_block_height.exp, language/move-lang/functional-tests/tests/diem/block/invalid_initialization_address.exp, language/move-lang/functional-tests/tests/diem/block/invalid_initialization_address.move, language/move-lang/functional-tests/tests/diem/block/none_validator_propser.exp, language/move-lang/functional-tests/tests/diem/block/none_validator_propser.move, language/move-lang/functional-tests/tests/diem/block/older_timestamp.exp, language/move-lang/functional-tests/tests/diem/block/older_timestamp.move, language/move-lang/functional-tests/tests/diem/block/vm_proposer.exp, language/move-lang/functional-tests/tests/diem/block/vm_proposer.move
Suspicious tests: none.
However I found that block prologue transactions do not print out a `Transaction(X)` header, making the log confusing. Will put up a fix for this.
=> [language] switch diem tests to exp mode -- admin_scripts/authenticator/block

Cargo.lock, state-sync/Cargo.toml, state-sync/src/client.rs, state-sync/src/coordinator.rs, state-sync/src/error.rs, state-sync/src/executor_proxy.rs, state-sync/src/fuzzing.rs, state-sync/src/lib.rs, state-sync/src/logging.rs, state-sync/src/shared_components.rs, state-sync/tests/test_harness.rs
This PR begins adding unit tests to StateSyncCoordinator. In addition, it also begins to move state sync away from anyhow errors into explicit error types (which will not only improve testing and error handling, but also observability and reduce code).
This PR offers the following commits:
1. Create a unit tests module for StateSyncCoordinator and move shared logic into a shared components file.
2. Clean up process_state_sync_request and add better error handling, as well as a unit test structure.
3. Clean up get_sync_state and add better error handling, as well as a unit test structure.
4. Clean up wait_for_initialization and add better error handling, as well as a unit test structure.
5. Clean up process_commit_notification and add better error handling, as well as a unit test …
=> [State Sync] Begin adding unit tests for coordinator, better error support and cleaning up code.

language/move-lang/src/naming/translate.rs, language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_pack.exp, language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_pack.move, language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_unpack.exp, language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_unpack.move
- Fixes #7385 
- Caused by #6630
- The old instantiation code would have caught this, but the logic for this case was not moved to Naming with the rest of the arity checks for apply types 
- new tests
=> [move source language] Fix arity bug in pack/unpack

common/time-service/src/lib.rs, common/time-service/src/mock.rs, common/time-service/src/real.rs, secure/key-manager/src/tests.rs
+ Now provides monotonic but opaque clock source (`Instant`) through
`TimeService::now`. Absolute but non-monotonic clock source is now
provided through `TimeService::now_unix_time`.
+ Add `deadline: Instant` APIs to `Sleep`, `Interval`, `Timeout`, etc...
Instead of specifying a relative duration to sleep, you can now specify
an absolute deadline. This should help support rate-limiter crate.
+ Make sure `Sleep` enum always dispatches to `SleepTrait`.
=> [time-service] Add `Instant` support to time service

Cargo.lock, common/time-service/src/interval.rs, network/builder/Cargo.toml, network/builder/src/builder.rs, network/src/peer_manager/builder.rs, network/src/peer_manager/mod.rs, network/src/peer_manager/tests.rs, network/src/protocols/health_checker/builder.rs, network/src/protocols/health_checker/mod.rs, network/src/protocols/health_checker/test.rs, network/src/transport/mod.rs, network/src/transport/test.rs
+ Integrate TimeService into PeerManager and its tests
+ Push TimeService into DiemTransport and tests 
+ Integrate `TimeService` into `HealthChecker` 
+ Remove the `TTicker` generic and just create a new `time_service.interval` in `HealthChecker::start`. This removes a bunch of extra type noise and a dependency on `tokio_stream`.
+ Add an impl for `FusedStream` to `diem_time_service::Interval`, so it's more convenient for API consumers to use intervals in `futures::select!`. We can do this because `Interval`s never end, so `FusedStream::is_terminated` just always returns `false`.
+ Remove some now unnecessary structs / type aliases in `health_checker::builder`.
+ Remove `ping_timeout` test, which was no longer testing anything different than the `outbound_failure_*` tests, as timeouts …
=> [network] Integrate TimeService into PeerManager, DiemTransport, and HealthChecker

.github/actions/build-setup/action.yml
Let's re-enable sccache.
There are still a couple issues I'm tracking down (sccache fix to notice changes in CARGO's location) and a pr for trybuild to read the env location every time, but nothing is stopping us from using and benefiting from sccache today - to save a few minutes off of each build.
Yes
CI.
None
=> [gha] re-enable sccache

language/bytecode-verifier/src/binary_views.rs, language/bytecode-verifier/src/cyclic_dependencies.rs, language/bytecode-verifier/src/dependencies.rs, language/bytecode-verifier/src/lib.rs, language/compiler/src/main.rs, language/move-vm/runtime/src/loader.rs, language/stdlib/compiled/src/lib.rs, language/stdlib/src/lib.rs, language/testing-infra/functional-tests/src/evaluator.rs, language/tools/move-cli/src/main.rs
- Cleanup for dependency checker
- Should make new visibility checks easier
- The code had a lot of function parameters that were not needed, and the generation of this "checker" object was very brittle 
- ran tests
Conflicts with #7399
=> [move][bytecode verifier] Restructure dependency verifications

Cargo.lock, storage/diemdb-benchmark/Cargo.toml, storage/diemdb-benchmark/src/lib.rs, storage/diemdb/src/lib.rs, storage/diemdb/src/metrics.rs, storage/diemdb/src/schema/mod.rs
print out the live data size versus live sst file size after the benchmark
Y
cargo run -- -n 1000 -v 100000 --db-dir=/tmp/test
=> [diemdb_bench] expose rocksdb stats after bench

language/transaction-builder/generator/tests/generation.rs, x.toml
This was originally caught in #7449.
Tested through:
```
echo >> language/stdlib/compiled/transaction_scripts/abi/burn_txn_fees.abi
git commit -am 'test'
cargo x changed-since HEAD^
```
(I really should make it easier to just test a path, whoops)
=> [x] add a custom rule abi -> transaction-builder-generator

language/ir-testsuite/tests/move/commands/if_branch_diverges_5.mvir, language/ir-testsuite/tests/move/commands/if_branch_diverges_6.mvir, language/ir-testsuite/tests/move/commands/if_branch_diverges_8.mvir, language/move-lang/functional-tests/tests/move/commands/unpack_top_level.move, language/testing-infra/functional-tests/src/evaluator.rs
Currently in functional tests, temporary files (with random names) are used as inputs to the Move compiler. This causes the tests to be non-deterministic as the file names may appear in error messages. This gets it fixed by filtering out those file names in the compiler error messages with regex. 
This hack should work reasonably well in the short term. We will keep evaluating other solutions.
=> [language] filter out file names in compiler error messages

language/move-core/types/src/identifier.rs, language/move-core/types/src/parser.rs
Fixing issue reported in https://github.com/diem/diem/issues/7151 and adding some tests. While adding tests, I found one other problem: `signer` does not parse. I fixed this as well.
=> [move core types] fix bugs in parse_type_tag

config/src/config/state_sync_config.rs, state-sync/src/client.rs, state-sync/src/coordinator.rs, state-sync/src/error.rs, state-sync/src/fuzzing.rs, state-sync/src/logging.rs, state-sync/src/request_manager.rs, state-sync/src/shared_components.rs
This PR completes the skeleton set of unit tests for StateSyncCoordinator as well as improves error handling (continuing on from https://github.com/diem/diem/pull/7394).
This PR offers the following commits:
1. Clean up the check_progress method and add better error handling, as well as a unit test structure.
2. Clean up new and lost peer message logic and add better error handling, as well as a unit test structure.
3. Clean up process_chunk_message and add better error handling, as well as a unit test structure.
With this PR in place, we now have a basic "test skeleton" that will allow us to change StateSyncCoordinator logic in future PRs and add appropriate tests to verify correctness!
Yes.
All tests pass locally, including the newly added ones.
This PR continues on from …
=> [State Sync] Complete unit test skeleton for coordinator, better error support and clean up code.

testsuite/generate-format/src/diem.rs, testsuite/generate-format/tests/staged/diem.yaml, types/src/transaction/metadata.rs
New RefundMetadata struct is proposed for refund transaction to store original transaction version.
YES
Unit test
=> add RefundMetadata struct for generating types

language/move-lang/src/cfgir/liveness/mod.rs, language/move-lang/src/expansion/translate.rs, language/move-lang/src/naming/translate.rs, language/move-lang/src/parser/ast.rs, language/move-lang/src/parser/syntax.rs, language/move-lang/tests/move_check/expansion/assign_non_simple_name.exp, language/move-lang/tests/move_check/expansion/assign_non_simple_name.move, language/move-lang/tests/move_check/expansion/invalid_local_name.exp, language/move-lang/tests/move_check/expansion/spec_block_in_spec_context.exp, language/move-lang/tests/move_check/expansion/spec_block_in_spec_context.move
- Fixed #7387. Spec blocks should not be allowed in a spec context.
- Fixed #7385. Expansion needs to check for module accesses after resolving lvalue names. Caused by alias refactor.
- Some other unrelated formatting changes
- bugs are bad
- new tests
=> [move source language] Fix spec context bugs

language/move-prover/src/boogie_wrapper.rs, scripts/dev_setup.sh
This PR updates Boogie to 2.8.25.  To distinguish Boogie compilation errors from verification errors, a different strategy is used.  Move Prover exits early if compilation errors are detected.
Yes
=> [move-prover] Update boogie

language/benchmarks/Cargo.toml, language/benchmarks/benches/transaction_benches.rs, language/benchmarks/benches/vm_benches.rs
Create a separate bench target for measuring how many txns per second can a Diem Adapter process with a in memory storage. This will also help create a report in the CI for this metric.
Yes
`cargo bench` under `benchmarks`. Observed both `vm_benches` and `txn_benches` to be run.
=> [language-benches] Split out txn_bench into a separate binary.

state-sync/src/chunk_request.rs, state-sync/src/coordinator.rs, state-sync/src/error.rs, state-sync/src/request_manager.rs
At present, state sync does not ensure chunk request are correctly formed before it attempts to process them. Specifically, it doesn't check if:
1. The known version of the chunk request is greater than the target version.
2. The current epoch of the chunk request is greater than the target epoch.
3. The chunk limit is set to 0 (in which case, the request is dubious).
4. The long poll timeout is set to 0 (in which case, the request is not well formed).
If any of these 4 properties are violated in the current version of state sync, they should ultimately be caught somewhere in the state sync pipeline (e.g., by storage, or the request manager, etc.). However, this leaves ambiguity about what can happen and whether or not there are potential vulnerabilities here. Moreover, it may burn …
=> [State Sync] Perform basic chunk request verification before processing.

language/compiler/ir-to-bytecode/src/compiler.rs, language/compiler/ir-to-bytecode/syntax/src/lexer.rs, language/compiler/ir-to-bytecode/syntax/src/syntax.rs, language/compiler/src/unit_tests/function_tests.rs, language/move-ir/types/src/ast.rs
Fill the gap in `public(script)` implementation.
- #7534 adds the changes to file format and bytecode verifier
- This PR adds support in the IR compiler to parse `public(script)` and produce bytecode with the new `script` visibility (once #7534) lands.
- #7497 adds support in the source compiler, which will rely on this PR.
Yes
A new test case, `compile_module_with_script_visibility_functions`, is added to the unit tests of the IR compiler.
=> [ir-compiler] parser support for public(script)
