- language/diem-vm/src/diem_vm.rs
- language/move-vm/integration-tests/src/tests/bad_entry_point_tests.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/logging.rs
- Switches a missing module/function in 'load_function' to an invariant violation
- Moved invariant check to the diem adaptor
- Makes room for an execute_script_function that uses the same loading functionality
- @runtian-zhou, any ideas?
- #7534
> [move vm][loader] Execute funciton should verify a missing module and function

- json-rpc/src/runtime.rs
- json-rpc/src/tests/unit_tests.rs
Justification: Provides a way to validate a meaningful healthcheck of the node via json-rpc
Verification: Comprehensive tests
Requirement: Necessary to build a JSON-RPC load balancer that takes into consideration the state of the chain at a given node
Workarounds: Constructing a service that sits between the ALB and the json-rpc server that would perform this query (ALB only supports querying a URL and receiving back a 200 or error)
> [json-rpc] health-check for checking latest ledger info timestamp

- language/diem-tools/transaction-replay/src/lib.rs
- language/diem-tools/transaction-replay/src/main.rs
- language/diem-tools/transaction-replay/src/unit_tests/bisection_tests.rs
- language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
- language/move-core/types/src/effects.rs
- language/move-core/types/src/lib.rs
- language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- language/move-vm/test-utils/src/lib.rs
- language/move-vm/test-utils/src/misc.rs
- language/move-vm/test-utils/src/storage.rs
This moves `move-vm-test-utils::effects` into `move-core-types`. `effects::ChangeSet` will become the canonical representation of side effects produced by the Move VM and will replace `TransactionEffects`. A subsequent PR (#7599) will make the switch and let Move VM return serialized values.
> [language] move move-vm-test-utils::effects into move-core-types

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/compositional_analysis.rs
- language/move-prover/bytecode/src/dataflow_analysis.rs
- language/move-prover/bytecode/src/livevar_analysis.rs
- language/move-prover/bytecode/src/stackless_control_flow_graph.rs
This  PR has two contributions:
1. It fixes an infinite loop in dataflow analysis that manifests when there is a self-loop on a block.
2. Live variable analysis won't be able to create information for blocks that cannot reach some exit block.  Absence of this information can cause a crash downstream.  So this PR makes allows backward analysis to happen from all blocks and uses this feature in live variable analysis.
These problems were discovered by running move prover on move-lang/tests/move_check/typing/loop_body.move.
Yes
Existing tests
> [move-prover] Fix bugs in flow analysis

- config/src/config/state_sync_config.rs
- state-sync/src/coordinator.rs
- state-sync/src/counters.rs
- state-sync/src/shared_components.rs
- state-sync/tests/integration_tests.rs
- state-sync/tests/test_harness.rs
This PR replaces the PendingLedgerInfos structure from state sync with a single (rolling) highest target ledger info. PendingLedgerInfos is used by full nodes in state sync. It maintains a queue of ledger info's that have been received from other nodes. This allows a full node to incrementally sync to these ledger infos as it catches up to the head of the blockchain (as opposed to, e.g., syncing to a ledger info only on an epoch change). 
Unfortunately, the use of PendingLedgerInfos makes state sync a lot more complicated than it needs to be. This PR maintains "incremental commit" for state sync, but replaces PendingLedgerInfos with a single ledger info as the next highest target. When that target is reached, a new one is selected based on the responses of the peers.
This PR offers …
> [State Sync] Remove the pending_li_queue and use a single highest target for full node sync.

- language/move-prover/src/prelude.bpl
- language/move-prover/src/spec_translator.rs
- language/move-prover/tests/sources/functional/emits.exp
- language/move-prover/tests/sources/functional/emits.move
- Newly modeled EventStore (in Prelude) using "multiset" rather than
array (due to the limitation of array)
- Updated the spec translator according to the updated EventStore model, 
and added a comment in `spec_translators.rs` to explain the idea behind
the verification conditions to generate
- To `functional/emits.move`, added the test cases of emitting events
with the same message multiple times, and checked that Prover can
correctly handle these scenarios thanks to multiset.
To re-model the EventStore using multiset
yes
cargo test
> [move-prover] Multiset implementation for verifying emits specs

- state-sync/src/coordinator.rs
- state-sync/src/error.rs
- state-sync/src/logging.rs
- state-sync/tests/integration_tests.rs
This PR updates state sync to perform optimistic chunk request fetching when processing waypoint and verifiable ledger info responses. This is in contrast to the approach of verifying the chunk response before making the request. As such, it should help to reduce the latency of chunk request/responses in the happy path.
Note: the code currently uses optimistic chunk request fetching when processing waypoint ledger infos. It doesn't do this for verifiable ledger infos (despite there being a code comment which says otherwise.. 😮)
To do this, the PR offers a single commit that updates the code to make the chunk request before verifying the response. Unfortunately, due to the way the code is structured, this is not as simple as just switching the order of a few lines of code -- it requires a …
> [State Sync] Use optimistic fetch when making waypoint and verifiable ledger info requests.

- testsuite/cluster-test/src/experiments/compatibility_test.rs
- testsuite/cluster-test/src/experiments/cpu_flamegraph.rs
- testsuite/cluster-test/src/experiments/load_test.rs
- testsuite/cluster-test/src/experiments/performance_benchmark.rs
- testsuite/cluster-test/src/experiments/performance_benchmark_three_region_simulation.rs
- testsuite/cluster-test/src/experiments/reconfiguration_test.rs
- testsuite/cluster-test/src/experiments/recovery_time.rs
- testsuite/cluster-test/src/experiments/twin_validator.rs
- testsuite/cluster-test/src/experiments/versioning_test.rs
- testsuite/cluster-test/src/main.rs
- testsuite/cluster-test/src/suite.rs
- testsuite/cluster-test/src/tx_emitter.rs
- Refactory current code path for flag --invalid-tx
- Added new experiment with mixing invalid tx
- Added new test suite ```--suite invalid```
Related PR: 
[cluster-test] new invalid tx type for duplication: https://github.com/diem/diem/pull/7422
[cluster-test] Add stat for CT burst mode: https://github.com/diem/diem/pull/7527 Postponed since the perf regression bug
./scripts/cti --pr 7583 --suite invalid
http://grafana.ct-0-k8s-testnet.aws.hlw3truzy4ls.com/d/performance/performance?orgId=1&from=1612920551000&to=1612921444000
Exposed related bug linked:
https://github.com/diem/diem/issues/7577
(If this PR adds or changes functionality, please take some time to update the docs at …
> [cluster-test] Added new invalid tx suite

- language/move-prover/bytecode/src/borrow_analysis_v2.rs
- language/move-prover/bytecode/src/dataflow_analysis.rs
- language/move-prover/bytecode/src/lib.rs
These changes add borrow edge info to borrow analysis. These changes will be used in memory_instrumentation to differentiate between weak and strong writebacks. We will be able to encode strong writebacks more cleanly into boogie than in current implementation.
Yes
These changes are pushed to borrow_analysis_v2 which is not currently in verification pipeline. Testing will be done after prs for memory_instrumentation and boogie prelude file are in.
> [move-prover] Add borrow edge info to borrow analysis (v2 experimental version)

- config/management/operational/src/network_checker.rs
- config/src/config/mod.rs
- config/src/config/network_config.rs
- config/src/network_id.rs
- diem-node/src/lib.rs
- network/builder/src/builder.rs
- network/builder/src/dummy.rs
- network/simple-onchain-discovery/src/lib.rs
- network/src/counters.rs
- network/src/noise/mod.rs
- network/src/peer_manager/mod.rs
- state-sync/tests/test_harness.rs
RoleType usage in Network was so confusing, as it represented the type of network (Validator vs FullNode), which was kinda silly when it was one network Id vs all other network Ids.  This change replaces RoleType with NetworkType for appropriate usages, and puts the actual RoleType of the Node into the NetworkContext for logging and metrics purposes.
> [network] Rename Network Role to Network Type

- Cargo.lock
- common/short-hex-str/Cargo.toml
- common/short-hex-str/src/lib.rs
- config/Cargo.toml
- config/src/config/network_config.rs
- config/src/config/upstream_config.rs
- config/src/network_id.rs
- consensus/Cargo.toml
- consensus/consensus-types/Cargo.toml
- consensus/consensus-types/src/block_retrieval.rs
- consensus/consensus-types/src/proposal_msg.rs
- consensus/consensus-types/src/vote.rs
- consensus/src/block_storage/block_store.rs
- crypto/crypto/Cargo.toml
- crypto/crypto/src/hash.rs
- language/move-core/types/Cargo.toml
- language/move-core/types/src/account_address.rs
- network/simple-onchain-discovery/Cargo.toml
- network/simple-onchain-discovery/src/lib.rs
- network/src/connectivity_manager/mod.rs
- network/src/counters.rs
- network/src/noise/handshake.rs
- network/src/peer/mod.rs
- network/src/peer_manager/mod.rs
- network/src/protocols/health_checker/mod.rs
- network/src/protocols/network/mod.rs
- network/src/protocols/rpc/mod.rs
- network/src/transport/mod.rs
In an effort to reduce the number of crates that need to be published in order to publish a subset of our crates, lets try and eliminate the dep on short-hex-str from diem-crypto and move-core-types.
> short-hex-str: use trait to eliminate dep for crypto and move-core-types

- config/src/config/network_config.rs
- config/src/network_id.rs
- network/src/connectivity_manager/mod.rs
This change moves ConnectionManager to use `Peer` instead of `Addresses` as a stepping stone to peer prioritization in making outbound connections.  There needs to be more done at a high level to move directly to a prioritization strategy that doesn't cause excess connections across multiple network interfaces.
Additionally, this provides a way for applications and connmgr to have a canonical way for identifying whether a peer is Upstream or Downstream, and a simple prioritization scheme in it, based on the tuple of `NetworkId` and `RoleType`.  This is however needed for `RoleType` to actually be the role of the node, and not the network see: https://github.com/diem/diem/pull/7604
* A few more tests that test the logic around the role choices.
* Possible ability to change Role type in the …
> [network] Connection Manager and PeerRole improvements

- language/move-prover/doc/user/prover-guide.md
This PR fixes a broken link in the move prover guide.
> [move prover] fix broken link in prover guide

- language/move-prover/bytecode/src/global_invariant_instrumentation.rs
Example of using the transformation pipeline framework to make a global analysis over all functions before the bytecode transformation of individual functions.
Yes
NA
NA
> [move-prover] Add illustration of computing global information for a pipeline step

- .github/actions/build-setup/action.yml
- .github/actions/dockerhub_login/action.yml
- .github/workflows/ci-publish-base-image.yml
- .github/workflows/ci-test.yml
- docker/ci/github/Dockerfile
- scripts/dev_setup.sh
Make a single layer for all installed tools/created dirs in docker image so that dotnet installer doesn't shoot us in the foot.
Downgrading boogie via the dotnet installer worked... w00t: https://github.com/diem/diem/runs/1922801595?check_suite_focus=true#step:5:131
Removes busted arch build as well. (also blocking PR builds today)
And I've been building the docker image used by these builds in gha-test-1 branch with a hack (it'll be rebuilt once this lands on release-1.1.)
Yes
CI and more CI.   Tested docker builds in gha-test-1/gha-test-2 in several different ways outlined below.   And when PRs used those images in CI they worked as expected.
All of 'em for release-1.1, and all to ever land in the future.
Release branch in CI is broken and nothing can be processed until this lands.  No …
> [release] docker base image for each release/master branch and one single large layer so dotnet doesn't fail to install tooling.

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/borrow_analysis_v2.rs
- language/move-prover/bytecode/src/clean_and_optimize.rs
- language/move-prover/bytecode/src/eliminate_mut_refs.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation.rs
- language/move-prover/bytecode/src/memory_instrumentation.rs
- language/move-prover/bytecode/src/reaching_def_analysis.rs
- language/move-prover/bytecode/src/stackless_bytecode.rs
Changes to bytecode instruction writeback to allow for edge information.
Yes
Current coverage is fine (as edge information not actually used yet).
> [move-prover] Changes to bytecode instruction set to allow writeback to have edge information.

- language/transaction-builder/generator/tests/cli.rs
- language/transaction-builder/generator/tests/generation.rs
I had to make a few fixes in preparation of https://github.com/diem/diem/pull/7635 (adding CI to Move Sdk).
This PR lands them early on while we are figuring out what to do with CI.
The pyre fix is similar to https://github.com/novifinancial/serde-reflection/pull/83
On my laptop:
```
cargo test -p transaction-builder-generator -- --ignored
```
Tested in CI as part of https://github.com/diem/diem/pull/7635
> [transaction builder generator] make python test ready for CI

- language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md
- language/diem-framework/transaction_scripts/publish_shared_ed25519_public_key.move
- language/diem-framework/transaction_scripts/rotate_authentication_key.move
- language/diem-framework/transaction_scripts/rotate_authentication_key_with_nonce.move
- language/diem-framework/transaction_scripts/rotate_authentication_key_with_nonce_admin.move
- language/diem-framework/transaction_scripts/rotate_authentication_key_with_recovery_address.move
We were specifying an ed25519 public key in the script documentation,
when in reality it needed to be an authentication key (sha3_256 hash of
an ed25519 public key). 
Only documentation changed.
> [diem framework] Fix naming issue in script docs

- config/management/operational/src/command.rs
- config/management/operational/src/print.rs
Currently there is no easy way to get x25519 public keys from the private keys in storage, which significantly complicates docker-compose setups. https://github.com/diem/diem/issues/7477
yes
run tool on storage, get expected x25519
> Add printing of x25519 keys to optool

- config/management/network-address-encryption/src/lib.rs
- config/management/src/config.rs
- config/management/src/secure_backend.rs
- config/src/config/secure_backend_config.rs
- consensus/safety-rules/benches/safety_rules.rs
- consensus/safety-rules/src/tests/vault.rs
- secure/storage/src/tests/vault.rs
- secure/storage/src/vault.rs
- secure/storage/vault/src/dev.rs
- secure/storage/vault/src/lib.rs
- testsuite/cluster-test/src/cluster_builder.rs
This PR updates the vault client to support configurable timeouts for: (i) creating new connections to vault; and (ii) performing vault operations (e.g., reading and writing data).  The values chosen for these timeouts can now be specified in the various component config files (e.g., key manager and safety rules configs), however, they aren't required. If no values are provided for these timeouts, the default timeout value will be chosen (as hard coded in the vault client).
This change relates to the ongoing investigation into transient vault outages we're seeing for safety rules requests (https://github.com/diem/partners/issues/727). With this PR, we'll be able to reduce the timeouts in the future and thus avoid having the vault client hang for too long (rather, it should now timeout …
> [Vault Storage] Make the vault client support configurable timeouts

- .github/workflows/ci-test.yml
Since this machine size change landed https://github.com/diem/diem/pull/7635, we should change the machine size reporter.
Yes
CI
https://github.com/diem/diem/pull/7635
> [gha] switch to machine size, means we should switch the parameters we're looking for to default

- Cargo.lock
- config/src/config/network_config.rs
- execution/executor/src/lib.rs
- language/move-core/types/Cargo.toml
- language/move-core/types/src/account_address.rs
- language/move-core/types/src/language_storage.rs
- language/move-core/types/src/unit_tests/address_test.rs
- network/simple-onchain-discovery/src/lib.rs
- network/socket-bench-server/src/lib.rs
- network/src/noise/fuzzing.rs
- network/src/noise/handshake.rs
- network/src/noise/stream.rs
- network/src/transport/test.rs
- storage/diemdb/src/diemdb_test.rs
- storage/diemdb/src/event_store/test.rs
- storage/diemdb/src/state_store/mod.rs
- storage/diemdb/src/state_store/state_store_test.rs
- storage/diemdb/src/transaction_store/test.rs
- storage/storage-interface/src/state_view.rs
- storage/storage-service/src/storage_service_test.rs
- types/Cargo.toml
- types/src/account_address.rs
- types/src/account_state_blob.rs
- types/src/proptest_types.rs
This PR does 2 things:
* Remove the dependency on proptest-helpers for diem-types
* remove the dependency on diem-crypto for move-core-types
> diem-types and move-core-types dependency cleanups

- common/logger/src/counters.rs
- common/logger/src/diem_logger.rs
- common/logger/src/event.rs
- common/logger/src/filter.rs
- common/logger/src/kv.rs
- common/logger/src/logger.rs
- common/logger/src/macros.rs
- common/logger/src/metadata.rs
- common/logger/src/sample.rs
- common/logger/src/security.rs
- common/logger/src/struct_log.rs
I looked at the logging docs when I referred someone to them, and realized I had some weird confusion earlier about the difference between `Filter` vs `DiemFilter` and `Logger` vs `DiemLogger` etc.  So, I just tried to fill in a bunch of the gaps in docs, even if they're not much just to give a little clue about the difference between all these structs and what they're used for.
Feel free to be critical about what I wrote, mostly because this is from my understanding of what I know about it.  I also figured now is a good time to slap down some docs, since it's not changing much now.
> [logging] Add documentation to all structs and macros

- Cargo.lock
- devtools/x-core/Cargo.toml
- devtools/x-core/src/errors.rs
- devtools/x-core/src/git.rs
- devtools/x-core/src/workspace_subset.rs
- devtools/x-lint/Cargo.toml
- devtools/x-lint/src/file_path.rs
- devtools/x-lint/src/lib.rs
- devtools/x-lint/src/package.rs
- devtools/x-lint/src/runner.rs
- devtools/x/Cargo.toml
- devtools/x/src/lint/allowed_paths.rs
- devtools/x/src/lint/guppy.rs
- devtools/x/src/lint/license.rs
- devtools/x/src/lint/toml.rs
- devtools/x/src/lint/whitespace.rs
- devtools/x/src/lint/workspace_hack.rs
`camino` brings about `Utf8Path` and `Utf8PathBuf` wrappers, which
together simplify our path handling code quite a bit.
Going to release new versions of guppy and friends before landing this.
> [x] switch to new versions of guppy and camino

- .github/workflows/daily.yml
[Justification and who does it affect]
hyper v0.13.9 was flagged in RUSTSEC-2021-0020, and the advisory was picked up in the nightly audit workflow.  Upon close discussion with folks in network, json-rpc and deployment, the vulnerability doesn't appear to impact the operation. As a result, there is no need to update the dependency.  The advisory  is added to the ignore list so as not to create spam and drawn out future advisory alerts. 
Separately, the advisory is addressed in the master branch.
[Breaking nature]
N/A.  This is not a breaking change. 
[What happens if we don't have this]
The nightly audit will continue to generate alert and lead to degraded fidelity. 
[What are the alternatives]
The alternative would be bump the hyper version, as in #7548.
CI and cargo audit
> [deps][audit] ignore rustsec in hyper 0.13.9

- Cargo.lock
- network/builder/src/builder.rs
- network/simple-onchain-discovery/Cargo.toml
- network/simple-onchain-discovery/src/builder.rs
- network/simple-onchain-discovery/src/lib.rs
Original: https://github.com/diem/diem/pull/7217
It's possible that a user could set their network identity onchain and
then continue communicating on the network with the wrong network
identity.  This causes a strange 1 way communication, which makes it
very confusing.  The metric allows us to know that there's an issue and that we can mitigate it faster
On several occasions, it's been clear that a validator key mismatched the one onchain, causing confusion for both those trying to connect, and the person running the node.  The reason for this change is to make that mismatch visible to operators and oncalls.
None, since attempting to make the NetworkIdentity mismatch crash the node caused more issues (basically nodes never really started up after rotation), this only adds a new metric, …
> [cherry-pick-release-1.1][network] Metric if network identity doesn't match onchain

- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/duplication_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/generic_ops_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/bytecode-verifier/invalid-mutations/src/bounds.rs
- language/bytecode-verifier/src/check_duplication.rs
- language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
- language/vm/src/access.rs
- language/vm/src/check_bounds.rs
- language/vm/src/deserializer.rs
- language/vm/src/file_format.rs
- language/vm/src/proptest_types.rs
- language/vm/src/serializer.rs
Friend modules and dependencies modules should not overlap, therefore, it might be good to keep them separate in the file format.
The original design repurposes `module_handles` and ask the `friend_decls` to take a `ModuleHandleIndex` off the `module_handles` table. This essentially overloads  `module_handles` to contain both dependencies modules as well as friend modules, which changed its semantic meaning and leads to a series of complexities, such as
- the need for an `unused` checker
- loaded APIs in `ModuleAccess`
- complicated logic in the compatibility checker
For detailed discussions, see #7640.
The new format escalates `friend_decls` from being a vector of `ModuleHandleIndex` into a vector of `ModuleHandle`. In this way, `friend_decls` and `module_handles` have clear and distinct …
> [file-format] make a separate vec of module handles for friend decls

- Cargo.lock
- storage/diemdb/Cargo.toml
- storage/diemdb/src/diemdb_test.rs
- storage/diemdb/src/event_store/mod.rs
- storage/diemdb/src/event_store/test.rs
- storage/diemdb/src/lib.rs
- storage/storage-interface/src/lib.rs
- types/src/account_config/events/new_block.rs
Via binary search on the event by key index.
This is for audit report generation. There's on proof in this version, but proof can be two consecutive NewBlockEvents (with their proofs) showing the timestamp bump from before to at/after the timestamp in the request.
Y
Unit test.
> [storage] get_last_version_before_timestamp()

- .github/workflows/daily.yml
The ignore list is used to suppress advisories that don't affect operation.
CI
> [gha] add ignore list to audit

- language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
- language/diem-vm/src/diem_transaction_executor.rs
- language/diem-vm/src/diem_vm.rs
- language/move-vm/integration-tests/src/tests/function_arg_tests.rs
- language/move-vm/integration-tests/src/tests/mod.rs
- language/move-vm/integration-tests/src/tests/return_value_tests.rs
- language/move-vm/runtime/src/interpreter.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/runtime/src/session.rs
- language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
- language/testing-infra/test-generation/src/lib.rs
- language/tools/vm-genesis/src/lib.rs
This allows `execute_function` to return values in serialized format, which will make it easier for the adapter to query Move states.
> [language][vm] make execute_function return values (in serialized format)

- language/bytecode-verifier/src/cyclic_dependencies.rs
- language/bytecode-verifier/src/dependencies.rs
- language/bytecode-verifier/src/friends.rs
- language/bytecode-verifier/src/lib.rs
- language/bytecode-verifier/src/verifier.rs
- language/diem-framework/compiled/src/lib.rs
- language/diem-framework/src/lib.rs
- language/move-core/types/src/vm_status.rs
- language/move-model/src/model.rs
- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/runtime.rs
- language/testing-infra/functional-tests/src/evaluator.rs
- language/tools/move-cli/src/lib.rs
- language/tools/move-cli/src/main.rs
- language/vm/src/access.rs
Add checking rules to the bytecode verifier on checking the correctness of friend declarations as well as calls to `public(friend)` functions.
```
0x2 {
module A {
friend 0x2::B;                      --> subject to friend declaration rules
friend 0x2::C;
public(friend) fun foo() {}         --> subject to `public(friend)` visibility rules
public(friend) fun bar() {}
fun i_am_private() {}
public fun i_am_public() {}
}
}
```
1. Cannot declare the module itself as a friend (checked in `friends.rs`)
- e.g., `0x2::M` cannot declare `0x2::M` as a friend.
2. Cannot declare modules at different addresses as a friend (checked in `friends.rs`)
- e.g., `0x2::M` cannot declare `0x3::N` as a friend.
3. Cannot create a cycle in friendship relation (checked in `cyclic_dependencies.rs`)
- e.g., `0x2::A` …
> [bytecode verifier] checks for friend list and public(friend)

- language/move-model/src/model.rs
- language/move-model/src/pragmas.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/tests/testsuite.rs
- language/move-prover/src/cli.rs
- language/move-prover/src/lib.rs
[move-prover] Preparation for new invariant handling
More general global invariant processing, dealing with opaque
functions and temporarily disabled invariants.
This is a first simple step.
* Added flag --inv_v2 to enable new processing (false by default).
* Added pragmas disable_invariant_in_body (allows invariant not to hold
in the body of a function)
* Added pragma delegate_invariant_to_caller (says that invariant does
not necessarily hold when this function is called, and does not need
to be proved in the function).
* Added regular expression to find declarations of friend modules to
identify a superset of all modules that we need to process
* Created a version 2 of global_invariant_instrumentation.  When --inv_v2
is set, GlobalInvariantProcessorV2 is added to the pipeline.
(Write …
> [move-prover] Preparation for new invariant handling

- language/move-model/src/ast.rs
- language/move-model/src/pragmas.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/bytecode/src/spec_translator.rs
- language/move-prover/src/prelude.bpl
- language/move-prover/tests/sources/functional/emits.exp
- language/move-prover/tests/sources/functional/emits.move
- (emits_is_partial == false) by default. If emits_is_partial == true, Prover skips the completeness check of the emits specs.
- By default, (emits_is_strict == false), and Prover checks nothing about events if a function has no emits spec. If emits_is_partial == true, Prover checks that each function with no emits specs actually emits no events.
TODO:
- Support the `emits` verification with `opaque` functions
To support the "emits_is_partial" and "emits_is_strict" pragmas
Yes
cargo test
> [move-prover] Implemented the spec pragmas "emits_is_partial" and "emits_is_strict"

- language/tools/move-cli/src/main.rs
- language/tools/move-cli/tests/testsuite/compile_modules_and_scripts/args.exp
- language/tools/move-cli/tests/testsuite/diem_smoke/args.exp
- language/tools/move-cli/tests/testsuite/diem_smoke/args.txt
- language/tools/move-cli/tests/testsuite/events_emit_view/args.exp
- language/tools/move-cli/tests/testsuite/module_publish_view/args.exp
- language/tools/move-cli/tests/testsuite/module_run_view/args.exp
- language/tools/move-cli/tests/testsuite/republish/args.exp
- language/tools/move-cli/tests/testsuite/republish_cyclic/args.exp
- language/tools/move-cli/tests/testsuite/republish_cyclic_transitive/args.exp
This PR prints the # of bytes in the StructTag + the # of bytes in the resource blob for each element of a WriteSet. This makes it easier to eyeball changes to space consumption and get ballpark numbers to questions like "how big is a WriteSet in an average tx?"
I also added a few new txes to the diem_smoke test that show the WriteSet size of a typical P2P tx between VASP child accounts.
> [move cli] print number of bytes written in verbose output

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/runtime.rs
- language/vm/src/compatibility.rs
- language/vm/src/normalized.rs
Two versions (denoted as `OLD` and `NEW`) of the module are compatible if
- The structs defined are compatible (not changed in this commit)
* The **exposed** functions defined are compatible (updated in this commit), in particular
- `OLD` module's `public` functions are a subset of the `NEW` module's public functions
- `OLD` module's `public(script)` functions are a subset of the `NEW` module's script functions
* for any `public(friend)` function that is removed or changed in the `OLD` module:
* if the function visibility is upgraded to `public`, it is OK
* otherwise, it is considered incompatible
* The friend declarations are compatible (newly introduced in this commit), in particular,
* Adding a new module in the friend list is compatible
* Removing a module from the friend list is …
> [bytecode-verifier] add compatibility checking for friend visibility

- config/management/src/secure_backend.rs
- secure/storage/vault/src/lib.rs
This PR:
- Reduces the default timeout for vault from 10 seconds (for connections and all other operations) to 0.1 seconds for connections and 1 seconds for all other operations (e.g., reads and writes).
- Updates the operator tool to maintain custom timeouts of 10 seconds for vault (as are the current defaults). This is preferable in the case of the operator tooling because operators may connect to vault deployments further away and also don't require aggressive timeouts.
Notes:
- We may have to discuss whether or not we want to be more or less aggressive for the corresponding timeouts, but I'll leave that up to the reviewers 😄
Yes.
All tests pass locally.
This relates to an issue we're seeing with transient vault outages for safety rules (https://github.com/diem/partners/issues/727) and …
> [Vault Storage] Reduce default timeouts and support custom timeouts for operator tooling

- language/move-lang/test-utils/src/lib.rs
- language/move-lang/tests/move_check/typing/global_builtins_script.exp
- language/move-lang/tests/move_check/typing/global_builtins_script.move
- language/move-lang/tests/move_check_testsuite.rs
- Restricted stdlib usage in move_check tests to reduce overhead
- For simplicity/convenience, the stdlib was included with each move_check test. 
- By removing the diem-framework and restricting it to a set of core modules, it removes most of the work for each of the 721 tests
- ran them
- fixed the one test that used the diem framework
> [tests][move-lang] Reduce move_check_testsuite time by 97%

- diem-node/src/lib.rs
- docker/compose/validator-testnet/docker-compose.yaml
- docker/compose/validator-testnet/validator_node_template.yaml
this is definitely a hack so that we can enable consensus slow down for docker(-compose)
> [testnet] support a template config for testnet

- specifications/move_adapter/README.md
Update the Move adapter spec for some recent changes in the code and clarify that the transaction validation checks should be performed in the order listed. In particular:
PR #7252 added a restriction that currency codes must be uppercase.
PR #7599 replaced the TransactionEffects type and changed the errors that can be reported when processing transaction changes.
This is split into several commits, the first of which wraps all the long lines in the doc so that subsequent diffs are easier to read and see what changed. Review the subsequent commits separately to see the smaller changes.
There may have been other changes that should be reflected in the VM section. I haven't checked that yet.
Keep the specs up to date
Yes
N/A
#7252
#7599
> [specifications] minor fixes and updates to the Move adapter spec

- Cargo.lock
- consensus/src/state_computer.rs
- state-sync/Cargo.toml
- state-sync/src/chunk_response.rs
- state-sync/src/client.rs
- state-sync/src/coordinator.rs
- state-sync/src/error.rs
- state-sync/src/executor_proxy.rs
- state-sync/src/lib.rs
- state-sync/src/logging.rs
- state-sync/src/network.rs
- state-sync/src/request_manager.rs
- state-sync/src/shared_components.rs
- state-sync/tests/integration_tests.rs
- state-sync/tests/test_harness.rs
This PR cleans up error handling in the state sync code base. Specifically, it: (i) removes the use of anyhow errors and replaces them with the structured error types; and (ii) makes the code more consistent regarding failure cases and error messages (e.g., we remove the use of anyhow::bail and anyhow::ensure, and standardize the error outputs). The PR offers a number of commits going through each of the files in state sync.
Note:
- This change doesn't affect backward compatibility. Error types on messages passed between components within each node have changed (e.g., see client.rs), but these messages are not passed between nodes, so we shouldn't need to worry about breaking changes.
Yes.
All tests pass.
This relates to: https://github.com/diem/diem/issues/6795
> [State Sync] Remove anyhow and use structured errors

- .github/workflows/ci-test.yml
E2e test failure messages should be pushed to slack.
Yes
CI + time + eyeballs.
None
> [gha] e2e tests should have messages pushed on e2e test failures

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/dataflow_analysis.rs
changed name of join function of "joinresult" to make clear that this is not an abstract domain.
yes
existing tests are fine
> [move-prover] changed name of join function of "joinresult"

- docker/build-common.sh
- docker/tools/Dockerfile
Add writeset tools into the tools docker image, to make it easy for oncall to use. During incident, this would save us some time on building binaries locally.
Yes
- submit remote build to aws ecr.
- pull image locally 853397791086.dkr.ecr.us-west-2.amazonaws.com/diem/tools:dev_f825c1a1
- check if the writeset tool is working.
```
+ docker run -v /Users/sherryxiao/mainnet/tmp:/cwd --network=host -i 853397791086.dkr.ecr.us-west-2.amazonaws.com/diem/tools:dev_f825c1a1 sh -x
+ diem-transaction-replay
+ socat TCP-LISTEN:,bind=localhost,fork TCP:host.docker.internal:
2021/03/06 02:12:04 socat[7] E empty port/service
diem-transaction-replay 0.1.0
USAGE:
diem-transaction-replay [FLAGS] [OPTIONS] <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-s               If true, persist the …
```
> [docker] Add writeset tools into docker image

- .github/workflows/ci-test.yml
- .github/workflows/docker-publish.yml
split current docker publish workflow into 2 parts:
- Added new step build-images to ci-test workflow for further usage by LBT merging. It has condition by github.event_name == 'push' && needs.prepare.outputs.test-rust == 'true' and only push pre_build_image
- Removed auto branch task from docker-publish workflow, which ci-test workflow will be also triggered by auto branch
- tested new step will skip by pr pull
- tested with /canary, current ci-test passed and new build-images step pushed pre_master_018999af image succeeded 
* …
> [GHA] Added build-images step into ci-test workflow

- secure/storage/vault/src/lib.rs
This PR updates the connection timeout for vault from 100ms to 1 second. This is due to a bug/unclear documentation that currently exists in ureq 1.5.4, where the connection timeout overrides all other timeout values, including timeouts for reads and writes (https://github.com/algesten/ureq/blob/1.5.4/src/stream.rs#L459). Note: there's also another bug where the read timeout is reset instead of the write timeout, but that is unrelated (https://github.com/algesten/ureq/blob/1.5.4/src/stream.rs#L467).
This functionality has been fixed in version 2 of ureq (https://github.com/algesten/ureq/commit/a52c6021cfd01e2c3441ba0383b075ddfe7c7f1b#diff-aa0a8d713ea64389a4b4916384d286b01c0de291edf10fec2f213123419e2647R335), which means it's possible to set separate timeouts, but until we migrate to …
> [Secure Storage] Vault timeout workaround due to ureq bug.

- specifications/trusted_computing_base/execution_correctness/README.md
Link was pointing to TCB.md, when it should be pointing to the ../README.md file.
Improving the docs
- view file using Github's markdown renderer via web browser
> [doc] fix broken link in execution_correctness spec

- language/diem-framework/modules/Diem.move
- language/diem-framework/modules/DiemAccount.move
- language/diem-framework/modules/doc/Diem.md
- language/diem-framework/modules/doc/DiemAccount.md
- language/move-prover/tests/sources/functional/emits.exp
- language/move-prover/tests/sources/functional/emits.move
- Removed the emits spec of `DiemAccount::preburn` which was incorrect,
so causing the timeout
- Corrected the mislocated emits spec in `Diem::preburn_to`
- Added some more test cases for the emits verification
To fix the emits spec in the Diem Framework
Yes
cargo test
> [diem-framework] Updated the emits spec in the Diem Framework

- language/move-lang/src/cfgir/ast.rs
- language/move-lang/src/cfgir/translate.rs
- language/move-lang/src/hlir/ast.rs
- language/move-lang/src/hlir/translate.rs
- language/move-lang/src/to_bytecode/context.rs
- language/move-lang/src/to_bytecode/translate.rs
- language/move-lang/src/typing/translate.rs
The last piece of friend visibility in the source compiler.
Since friend list info is not used in hlir, cfgir, etc, most of the
translation is simply unpacking and repacking.
This completes the implementation of friend visibility.
Yes
cargo xtest
> [move-lang] propogate friend list to bytecode

- language/diem-framework/modules/DesignatedDealer.move
- language/diem-framework/modules/DiemAccount.move
- language/diem-framework/modules/DiemConfig.move
- language/diem-framework/modules/DiemSystem.move
- language/diem-framework/modules/SlidingNonce.move
- language/diem-framework/modules/doc/DesignatedDealer.md
- language/diem-framework/modules/doc/DiemAccount.md
- language/diem-framework/modules/doc/DiemConfig.md
- language/diem-framework/modules/doc/DiemSystem.md
- language/diem-framework/modules/doc/SlidingNonce.md
- language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md
- language/diem-framework/transaction_scripts/preburn.move
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/tests/sources/functional/ModifiesTypeTest.exp
- language/move-prover/tests/testsuite.rs
Since the introduction of `modifies` a while ago we did not check whether an opaque function specification declares `modifies` for all the memory it updates. This is crucial because otherwise it can create unsoundness at caller sites where the post-condition is assumed and may postulate memory changes, which on the other hand without a `modifies` is assumed to be unchanged. Example:
```
module Bug {
struct S has key { x: u64 }
public fun update_S(addr: address) acquires S {
borrow_global_mut<S>(addr).x = borrow_global_mut<S>(addr).x + 1;
}
spec fun update_S {
pragma opaque = true;
ensures global<S>(addr).x == old(global<S>(addr).x) + 1;
// missing: modifies global<S>(addr);
}
}
```
Now wherever we call `update_S`, we introduce unsoundness.
This PR adds a compile time check to detect the …
> [move-prover] Add a check that opaque functions specs use modifies correctly.

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/stackless_bytecode.rs
- language/move-prover/src/prelude.bpl
…
Strong edges for vector writebacks should further improve verification runtime. This commit also fixes a bug in the previous version of strong direct reference writebacks.
Yes
Plan to add some unit tests in to the bytecode test suite in future commit. This was tested on all existing benchmarks. Also recall that strong writebacks are off by default when using the move-prover, so this won't affect any integration testing at this time.
> [move-prover] add strong edges for vector writebacks

- state-sync/tests/integration_tests.rs
This PR adds two integration tests (back) to the ignore list for state sync: 
(i) `test_fn_failover` (which has failed only once in CI up to now, but I've yet to see any failures locally)
(i) `test_multicast_failover` (which hasn't failed yet in CI, but I suspect it too will flake at some point given that it's built very similarly to `test_fn_failover`)
The PR also adds a warning comment to the files to emphasize that the tests are still useful for verifying behaviour, so they shouldn't be removed. Perhaps, in the future we can update the state sync test harness to be more deterministic. But, for now, it's not high priority.
Yes.
All (non-ignored) tests still pass.
None.
> [State Sync] Ignore flaky tests and add a warning.

- language/move-lang/functional-tests/tests/functional_testsuite.rs
- language/move-lang/src/cfgir/ast.rs
- language/move-lang/src/cfgir/translate.rs
- language/move-lang/src/compiled_unit.rs
- language/move-lang/src/expansion/translate.rs
- language/move-lang/src/hlir/ast.rs
- language/move-lang/src/hlir/translate.rs
- language/move-lang/src/lib.rs
- language/move-lang/src/naming/ast.rs
- language/move-lang/src/naming/translate.rs
- language/move-lang/src/parser/ast.rs
- language/move-lang/src/to_bytecode/translate.rs
- language/move-lang/src/typing/ast.rs
- language/move-lang/src/typing/core.rs
- language/move-lang/src/typing/translate.rs
- language/move-model/src/lib.rs
- Added clone to ASTs
- Added move-lang endpoint to save ASTs from each pass for dependency/libraries
- Saved the compilation of the stdlib/diem framework for functional tests. Reducing test time by 60%
- Before the change, tests took about 354s on my machine. 
- After, it's down to about 135s
- ran affected tests
> [move-lang-functional-tests] Reduce test time by 60%

- .github/workflows/daily.yml
Add client backward compatibility to CI by leveraging clsuter-test's json-rpc interface.
It uses the old client in cluster-test from the release (prod) and pre-release (rc) to test against the new server on devnet from the main branch. 
Canary
> [ci] json-rpc compat test through cluster-test

- language/move-prover/boogie-backend/src/boogie_wrapper.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/function_target_pipeline.rs
- language/move-prover/bytecode/src/options.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/src/cli.rs
- language/move-prover/tests/sources/functional/inconsistency.exp
- language/move-prover/tests/sources/functional/inconsistency.move
- scripts/dev_setup.sh
- Added "--check-inconsistency" flag into the Prover CLI
- With the flag above, Prover performs the inconsistency checking in  addition to the regular verification
- In order to perform the inconsistency checking, Prover creates another function variant as a target, and `assert false;` is inserted at the end of the "return" block of the new function variant
- If the assertion above passes, then Prover reports it as an inconsistency error
- (Prover masks the expected errors (e.g., the "assert false" failures and the timeouts) from the negative test for the inconsistency checking, and does not report them to the users.)
- Some examples are in `.../functional/inconsistency.move`.
The presence of inconsistency is a serious issue. If there is an inconsistency in the verification assumption …
> [move-prover] Implemented the feature of automatic inconsistency checking

- common/datatest-stable/src/runner.rs
Support the terse format while listing tests, since that's what the upcoming test runner will use.
> [datatest-stable] support --format terse

- language/move-model/src/model.rs
- language/move-prover/bytecode/src/function_target.rs
- language/move-prover/bytecode/src/memory_instrumentation.rs
- language/move-prover/docgen/Cargo.toml
As title suggests. This PR also changes the `is_public()` API to `is_exposed()` which encapsulates not only `public` functions but also `public(script)` and `public(friend)`. Several TODO marks are added too to signal more changes.
Yes
Existing tests should not fail
> [move-model] expose friend info to move model

- storage/backup/backup-cli/Cargo.toml
- storage/backup/backup-cli/src/metadata/cache.rs
When not specified explicitly, it's probably people playing around on their own machine, and the cache conflicts with different backups, which confuses people.
Y
locally.
> [backup] metadata cache defaults to temp dir

- config/src/network_id.rs
- state-sync/src/coordinator.rs
- state-sync/src/logging.rs
- state-sync/src/request_manager.rs
- state-sync/tests/integration_tests.rs
This PR updates state sync to make use of `PeerRole` information to prioritize sending chunk requests to preferred peers. This works by giving preferred upstream peers a higher internal weighting when compared to non-preferred nodes (thus making them more likely to be selected as the endpoint to send a chunk request).
1. Remove reliance of state sync on UpstreamConfig and instead use NetworkId's directly. Note: we may need to think about the correct abstractions that NetworkId exposes in the future (as state is leaking into components). However, I've left this as a TODO.
2. Update state sync to give preferred upstream peers a higher likelihood of being selected when sending chunk requests. This commit also adds a unit test for this functionality.
Yes. …
> [State Sync] Update state sync to prioritize preferred peers

- language/move-lang/src/expansion/ast.rs
- language/move-lang/src/expansion/dependency_ordering.rs
- language/move-lang/src/expansion/mod.rs
- language/move-lang/src/expansion/translate.rs
- language/move-lang/src/naming/mod.rs
- language/move-lang/src/naming/translate.rs
- language/move-lang/tests/move_check/dependencies/use_cycle_2.exp
- language/move-lang/tests/move_check/dependencies/use_friend_direct.exp
- language/move-lang/tests/move_check/dependencies/use_friend_transitive_by_use.exp
- language/move-model/src/lib.rs
- This pass was in Naming due to old algorithms before module member 'uses'
- Moving to expansion allowed for the inclusion of specs and spec blocks in dep ordering
- Missing functionality needed for the Move prover
- Ran existing tests
- Punted on new tests to unblock prover quickly
>  [move-lang] Move dependency ordering to expansion. Added specs to dependency ordering calculation

- x.toml
Whenever changes in diem-framework or move-stdlib are found, rerun the
tests in the move-prover.
`testsuite.rs` under the `move-prover` crate grabs files outside its crate for datatests AND `move-prover` do not depends on those crates. This commit ensures that whenever the files it grabs changes, the tests are run.
Yes
CI
> [x] add determinator rules for move-prover

- language/diem-framework/modules/XDX.move
- language/diem-framework/modules/doc/XDX.md
- This PR fixed the inconsistency in the verification of `txn::burn_txn_fees` and `TransactionFee::burn_fees`
- The root cause is the specification mistake in the "unverified" opaque function `XDX::is_xdx`, which made those functions above always abort.
- The specification mistake is overlooking the fact that `==` has a higher precedence than `&&` in the following line of spec: `ensures result == Diem::spec_is_currency<CoinType>() && spec_is_xdx<CoinType>();`
- For `XDX::is_xdx`, the `verify` flag was set to be `false` because the its spec was not verifiable by Prover which asserted that the type values of CoinType and XDX are the same. This PR rewrites `spec_is_xdx` in a correct and straightforward way, so that `is_xdx` is verifiable by Prover (i.e., the `verify` flag is back on), and so …
> [diem-framework] Fixed the inconsistency in the verification of `txn::burn_txn_fees` and `TransactionFee::burn_fees`

- Cargo.lock
- language/bytecode-verifier/Cargo.toml
- language/bytecode-verifier/src/ability_field_requirements.rs
- language/bytecode-verifier/src/acquires_list_verifier.rs
- language/bytecode-verifier/src/binary_views.rs
- language/bytecode-verifier/src/check_duplication.rs
- language/bytecode-verifier/src/constants.rs
- language/bytecode-verifier/src/control_flow.rs
- language/bytecode-verifier/src/cyclic_dependencies.rs
- language/bytecode-verifier/src/dependencies.rs
- language/bytecode-verifier/src/friends.rs
- language/bytecode-verifier/src/instantiation_loops.rs
- language/bytecode-verifier/src/instruction_consistency.rs
- language/bytecode-verifier/src/locals_safety/mod.rs
- language/bytecode-verifier/src/reference_safety/abstract_state.rs
- language/bytecode-verifier/src/script_signature.rs
- language/bytecode-verifier/src/signature.rs
- language/bytecode-verifier/src/stack_usage_verifier.rs
- language/bytecode-verifier/src/struct_defs.rs
- language/bytecode-verifier/src/type_safety.rs
- x.toml
This makes the bytecode-verifier no longer depend on diem-types.
> [language] remove diem-types dependency from bytecode-verifier

- Cargo.lock
- language/bytecode-verifier/bytecode-verifier-tests/Cargo.toml
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/constants_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/generic_ops_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/negative_stack_size_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/bytecode-verifier/invalid-mutations/Cargo.toml
- language/bytecode-verifier/invalid-mutations/src/bounds.rs
- language/bytecode-verifier/invalid-mutations/src/bounds/code_unit.rs
- x.toml
This removes the dependency on `diem-types` from `bytecode-verifier-tests` and `invalid-mutations`.
> [language] remove diem-types dependency from bytecode-verifier-tests and invalid-mutations

- consensus/safety-rules/tests/binary.rs
- execution/execution-correctness/tests/binary.rs
It looks like some child processes weren't being killed at the end of
tests, leaving them hanging forever. Fix that by killing them at the end
of the test.
Detected by the new test runner I'm writing.
> [tests] kill child processes on exit

- Cargo.lock
- language/move-ir/types/Cargo.toml
- language/move-ir/types/src/ast.rs
- language/move-ir/types/src/spec_language_ast.rs
- x.toml
This removes the dependency from `move-ir-types` to `diem-types`.
> [language] remove diem-types dependencies from move-ir-types

- Cargo.lock
- language/move-lang/Cargo.toml
- language/move-lang/src/cfgir/translate.rs
- language/move-lang/src/to_bytecode/context.rs
- language/move-lang/src/to_bytecode/translate.rs
- x.toml
This removes the dependency on `diem-types` from `move-lang`.
> [language] remove diem-types dependencies from move-lang

- language/move-prover/src/cli.rs
- Prover actually uses 4 cores by default. The information in the Prover's "--help" message was not right.
To correct some information in the help message
Yes
cargo test
> [move-prover] Corrects the default "--cores" value displayed in the help message

- .github/dependabot.yml
Looks like there's plan to move off of dependabot, possible to whackadep.
Following documented disabling process here:  https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#example-disabling-version-updates-for-some-dependencies
Yes
Time (no new rust dep prs will be opened).
None.
> [dependencies] disable rust dependabot

- .github/workflows/daily.yml
The vulnerable version of generic-array is a transitive dep. Adding it to the nightly ignore list to keep the audit actionable. 
CI + cargo audit
> [ci] add RUSTSEC-2020-0146 to nightly ignore list

- json-rpc/src/counters.rs
- json-rpc/src/fuzzing.rs
- json-rpc/src/runtime.rs
- json-rpc/src/tests/unit_tests.rs
- json-rpc/src/util.rs
When the association scrapes fullnode /metrics endpoints, we would also like to get the sdk language being used for the jsonRPC requests
yes
unit tests
Affects jsonRPC endpoints. No breaking changes- just prometheus metrics changes
We would like to have this in for the launch so that the ecosystem team can understand what SDKs people are using for development, and guide our resource allocation accordingly.
> Add sdk versions to prometheus

- state-sync/src/chunk_request.rs
- state-sync/src/chunk_response.rs
- state-sync/src/coordinator.rs
- state-sync/tests/integration_tests.rs
This PR makes 3 improvements to state sync:
1. (Code Simplification) First, it merges the two state sync flows (i.e., syncing to a target for consensus and syncing to the highest available for fullnodes) into a single flow. To achieve this, the PR updates state sync to avoid sending `TargetLedgerInfo` requests and `VerifiableLedgerInfo` responses. These are replaced with `HighestAvailable` requests and `ProgressiveLedgerInfo` responses, respectively.
2. (Performance/Resource Usage) Second, by merging the flows as above, the PR updates syncing to a target for consensus to support long polling. Right now, when a node syncs to a target for consensus, it sends requests to other nodes for a specific target. However, if those nodes aren't up-to-date with the requestor, they will send *empty …
> [State Sync] Merge flows, prevent empty message sending and improve incremental sync.

- language/tools/move-cli/README.md
`cargo install --git` uses the `master` branch by default, but diem recently switched its primary branch name from `master` to `main`. Pointing at `main` will ensure that users get the latest copy of the CLI.
> [move cli] specify `main` branch in `cargo install --git` command

- language/move-prover/tests/README.md
- language/move-prover/tests/testsuite.rs
-  This PR adds the `MVP_TEST_INCONSISTENCY` flag to the `cargo test` for Prover
- To check the inconsistency during the unit test for Prover, use the following command:
```
MVP_TEST_INCONSISTENCY=1 cargo test -p move-prover
```
Running time measured from a experiment on a local Macbook machine (using the default value of cores (i.e., 4))
- Without the "MVP_TEST_INCONSISTENCY flag
-  53s when "T=20", "T=40" and "T=80"
- With the "MVP_TEST_INCONSISTENCY=1" flag
-  4m 39s when "T=20"
-  7m 10s when "T=40"
-  12m 32s when "T=80"
Inconsistency check in CI
Yes
cargo test
MVP_TEST_INCONSISTENCY=1 cargo test
> [move-prover] Add the `MVP_TEST_INCONSISTENCY` to `cargo test -p move-prover`

- Cargo.lock
- Cargo.toml
- client/assets-proof/Cargo.toml
- client/assets-proof/src/lib.rs
- client/assets-proof/src/main.rs
Adds a small CLI tool for collecting and aggregating a VASPs current on-chain assets (including parent VASP and child VASP accounts) into an easily digestible json output via public-facing Diem json-rpc services.
```sh
$ cargo run -p diem-assets-proof -- collect \
--json-server 'https://testnet.diem.com/v1' \
--parent-vasp 'ed34ba9396da470da8de0945555549f8' \
--child-vasps 'f236d4d977cbf08fe6e8e796bb6b41bd' \
--child-vasps 'ad8c1f9be3b9de371567eda247c1f290' \
--child-vasps '228d25d0c232c010be8bc1613f833ea0'
```
```json
{
"diem_chain_id": 2,
"diem_ledger_version": 88497519,
"diem_ledger_timestampusec": 1616457122815922,
"accumulator_root_hash": "75e03d04f13f15450807ced2d8707fd90b3a95d71ce981396deacf6134f20b64",
"all_child_vasps_valid": true,
"total_unfrozen_balances": {
"XUS": 100000000000 …
```
> [proof-of-solvency] Add diem-assets-proof CLI tool

- storage/scratchpad/src/sparse_merkle/mod.rs
- storage/scratchpad/src/sparse_merkle/node.rs
1. replace IDE generated `use self::xx` with `use crate::`
2. remove unnecessary `ref` in a match clause.
3. remove unnecessary `as_ref()` on a ArcSwap load guard.
Y
introduced by #7957
> [scratchpad] fix clowntown

- config/management/genesis/src/config_builder.rs
- config/src/config/network_config.rs
- config/src/config/test_data/validator.yaml
- config/src/config/test_data/validator_full_node.yaml
- config/src/generator.rs
- config/src/network_id.rs
- network/src/connectivity_manager/mod.rs
Having a 2nd public network interfaces causes tons of confusion, as well as makes it hard to keep track of the number of connections to individual nodes.  This removes it, and allows us to run a single network interface for known and unknown connections and simplifies this confusion.
Additionally, this prioritizes connections to other peers, now that there is only one connectivity manager due to there only being one public interface.
Currently builds upon https://github.com/diem/diem/pull/7925
> [network] Prioritize peer connections and Remove VFN 2nd public network interface

- Cargo.lock
- Cargo.toml
- language/move-model/src/ast.rs
- language/move-model/src/builder/exp_translator.rs
- language/move-model/src/model.rs
- language/move-model/src/ty.rs
- language/move-prover/Cargo.toml
- language/move-prover/boogie-backend-v2/Cargo.toml
- language/move-prover/boogie-backend-v2/src/boogie_helpers.rs
- language/move-prover/boogie-backend-v2/src/boogie_wrapper.rs
- language/move-prover/boogie-backend-v2/src/bytecode_translator.rs
- language/move-prover/boogie-backend-v2/src/lib.rs
- language/move-prover/boogie-backend-v2/src/options.rs
- language/move-prover/boogie-backend-v2/src/prelude.bpl
- language/move-prover/boogie-backend-v2/src/prover_task_runner.rs
- language/move-prover/boogie-backend-v2/src/spec_translator.rs
- language/move-prover/bytecode/src/function_data_builder.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/bytecode/src/spec_translator.rs
- language/move-prover/bytecode/src/stackless_bytecode.rs
- language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
- language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
- language/move-prover/src/cli.rs
- language/move-prover/src/lib.rs
- x.toml
This is a larger PR which moves us a step closer to full monomorphization. All changes are protected beyond the flag `--vnext` and not on by default; this is achieved by branching the entire `boogie-backend` crate into `boogie-backend-v2`, as well as branching the prelude.
The PR generalizes the existing box/unbox approach from local expressions to paramaters and temporaries. That is a local declared in Move as `x: u64` will be actually represented in Boogie as `x: int` and not the boxed version `x: $Value`. $Value stays around for `f<T>(x: T)` where `x: $Value` in Boogie, and according box/unbox will be introduced for instantiated calls `f<u64>`.
A big source of unneeded polymorphism still remains, as the underlying representation of structs and vectors still stays to be `$ValueArray`, …
> [move-prover] Monomorphization via unboxing.

- Cargo.lock
- json-rpc/Cargo.toml
- json-rpc/src/counters.rs
- json-rpc/src/runtime.rs
- json-rpc/src/tests/unit_tests.rs
- json-rpc/src/util.rs
Add the versions to existing languages that SDK metrics are publishing now
yes
Unit tests
PR #8007
Affects jsonRPC endpoints. No breaking changes- just prometheus metrics changes
We would like to have this in for the launch so that the ecosystem team can understand what SDKs people are using for development, and guide our resource allocation accordingly.
> [RPC][Metrics] Add SDK language + version to prometheus metrics

- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/tests/testsuite.rs
- language/move-prover/src/cli.rs
- language/move-prover/src/pipelines.rs
Strong edge borrow analysis should have better verification time than weak edge borrow analysis. Strong edges are currently off by default and this commit will turn them on by default.
Yes
> [move-prover] turning strong edges on by default in borrow analysis

- language/tools/move-cli/README.md
- language/tools/move-cli/src/main.rs
Show syntax for the accepted argument types in both the README and help message.
> [move cli] better documentation for `--args` syntax

- client/assets-proof/src/lib.rs
- json-rpc/API-CHANGELOG.md
- json-rpc/docs/method_get_account.md
- json-rpc/docs/type_account.md
- json-rpc/src/methods.rs
- json-rpc/src/tests/unit_tests.rs
- json-rpc/tests/integration_test.rs
- json-rpc/types/src/proto/jsonrpc.proto
- json-rpc/types/src/views.rs
There are use cases require getting account data at same version, e.g. sum of child VASPs account balances.
Batch request may not fit for the case because the number of child VASPs maybe exceed the batch size limit.
Y
Integration test.
> [json-rpc] get_account by version

- language/move-lang/src/cfgir/ast.rs
- language/move-lang/src/cfgir/cfg.rs
- language/move-lang/src/cfgir/translate.rs
- language/move-lang/src/to_bytecode/remove_fallthrough_jumps.rs
- language/move-lang/src/to_bytecode/translate.rs
- remove_fallthrough_jumps is now turned off for loop heads with specs
- Specs need distinct loop heads for analyzing loop invariants
- remove_fallthrough_jumps coalesced loops heads into a single loop head making this analysis difficult 
- current tests pass, but unsure how to test the specs
- #8039
> [move-lang] Don't coalesce loop heads for the move-prover

- language/move-model/src/model.rs
- language/move-prover/bytecode/src/verification_analysis.rs
- language/move-prover/src/cli.rs
This PR adds an additional option `--verify-only FUNCTION_NAME` to Move prover. When this flag is present, prover only verifies the function in the target module with the specified name. If no such function exists in the target module, an error is generated.
Yes
cargo test
> [move prover] support verifying only one function

- language/diem-framework/modules/AccountLimits.move
- language/diem-framework/modules/doc/AccountLimits.md
- Added the invariant that only ParentVASP and ChildVASP can have the
account limits
Add the invariant to the Diem Framework
Yes
cargo test
> [diem-framework] Updated the access control specs in the Diem Framework

- developers.diem.com/docs/move/signer.md
- language/tools/move-cli/README.md
Reflecting recent Move changes in the documentation.
> [docs] change &signer to signer in script docs

- specifications/transactions/README.md
- specifications/transactions/offchain-api/README.md
this pulls out the core component of the off-chain from DIP-1
there's quite a bit more work that needs to be done to really smoothen
out the relationship between the onchain and offchain spec... my intent
is to write each section and then circle around once more and make sure
it is cohesive -- that way I don't end up with huge, unwieldy commits
note this is largely what was in the original, proposed update to DIP-1
https://github.com/diem/diem/issues/8045
> initial off-chain api spec

- .github/workflows/ci-test.yml
a full LBT run with comp suite need around 25mins, sometimes if there has no cluster available to run, the waiting time also be counted in test duration which only has 30mins, extend to 45 mins to avoid test failed 
* Comprehensive test results that demonstrate the fix working and not breaking existing …
> [GHA] extend LBT time duration to avoid test failed

- state-sync/Cargo.toml
Let @davidiw's code land.   Also correctly define the dev-deps of state sync.   Or at least improve it's definition.
Yes
Throw the kitchen sync at the problem and double check all our feature resolver behavior, and then realize the simple definition error.   Fix that error.   Compile.   Get a sliver of the day back.
https://github.com/diem/diem/pull/8055
> [cargo] include missing dev-dep

- specifications/move_adapter/README.md
This updates the Move Adapter specification for the addition of script
functions in the version 1.2 release.
I also made a pass over the VM sections which haven't been as well
maintained as other parts of the document:
- To simplify things and make it easier to keep updated, I removed the
internal APIs for the VM Runtime and moved the Session APIs to the
sections that describe those functions.
- Reformatted to use less bold and underline text.
- Added some updates for Version 2 of the binary file format, specifically
for function visibility and friend decls. Fixed incorrect values for Table
Kind IDs. Still missing ability sets...
Keeping docs up to date!
Yes
Viewed changes in a Markdown editor to make sure they are formatted as expected
> [specifications] update the move_adapter spec with script function info

- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/tests/sources/functional/aborts_if.move
In Prover, there was a problem with "aborts_if_is_partial":
- when a callee is opaque, Prover is supposed to check whether the callee has the "aborts_if_is_partial" flag. However, Prover was checking a wrong condition (it was checking whether the "caller" has such flag).
To fix a bug regarding "aborts_if_is_partial"
Yes
cargo test
> [move-prover] Fix the problem with the pragma "aborts_if_is_partial"

- config/src/config/mod.rs
- config/src/config/test_data/public_full_node.yaml
- config/src/config/test_data/validator_full_node.yaml
- config/src/config/upstream_config.rs
- docker/compose/public_full_node/public_full_node.yaml
- helm/fullnode/files/fullnode.yaml
- mempool/src/counters.rs
- state-sync/tests/integration_tests.rs
- state-sync/tests/test_harness.rs
- testsuite/cluster-test/src/cluster_swarm/configs/fullnode.yaml
This PR removes the "UpstreamConfig" configuration struct from the codebase. The last dependency on this config was state sync, which now no longer needs this config to operate (https://github.com/diem/diem/pull/7902).
Note that:
- I've tried to remove all references of UpstreamConfig in the code. However, LBT is failing below (I suspect because there's an old config being pulled from somewhere else? e.g., the compatibility test?). @sausagee, any suggestions?
- We'll need to update the configs and templates in the partners repo. I'll submit a PR for that once we decide on landing this.
Yes.
All tests pass locally.
None.
> [Configs] Remove UpstreamConfig.

- network/src/counters.rs
- network/src/peer_manager/mod.rs
Now we have a metric every time there's a disconnect due to hitting the connection limit.
> [network] Add connection limit metrics

- Cargo.lock
- language/move-prover/bytecode/Cargo.toml
- language/move-prover/bytecode/src/packed_types_analysis.rs
- x.toml
This makes the stackless bytecode crate no longer depend on diem-types.
> [language][prover] remove diem-types as a dependency from stackless bytecode

- .github/workflows/dep-summaries.yml
- .github/workflows/hyperjump-comment.yml
- .github/workflows/hyperjump-labels.yml
- .github/workflows/hyperjump-request-review.yml
- .github/workflows/jsonrpc-compat.yml
Use the latest version of diem/actions, with new port/protocol for hyperjump
Yes
CI
None
> [gha] use latest version of actions

- language/move-lang/src/naming/translate.rs
- language/move-lang/src/typing/translate.rs
Coding style consistency, as `ModuleDefinition` is destructed in all other source compiler passes.
Yes
CI
> [move-lang] use destruction pattern consistently for ModuleDefinition

- testsuite/cluster-test/src/prometheus.rs
Link doesn't point anywhere, so I'm pointing it to somewhere that exists
> [cluster-test] Fix invalid dashboard link

- common/debug-interface/src/lib.rs
- config/management/genesis/src/config_builder.rs
- testsuite/cli/src/client_proxy.rs
- testsuite/diem-swarm/src/main.rs
- testsuite/diem-swarm/src/swarm.rs
- testsuite/smoke-test/src/client.rs
- testsuite/smoke-test/src/full_nodes.rs
- testsuite/smoke-test/src/genesis.rs
- testsuite/smoke-test/src/operational_tooling.rs
- testsuite/smoke-test/src/smoke_test_environment.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/smoke-test/src/storage.rs
After spending many hours staring out the test framework, I found it was very `validator` centric, and hadn't been adjusted to a full node ecosystem.  Additionally, there were a lot of rough edges that make the average reader be confused, so hopefully that cleans up those.
Additionally, this makes a simple test to test out `PrivateFullNodes` and the ability to route traffic through `Upstream` nodes, and register `Downstream` nodes only to access them.
Yeah
See CI
None
> [diem-swarm] Add PrivateFullNode tests and Improve test framework for Full Node testing

- storage/scratchpad/src/sparse_merkle/mod.rs
- storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
The SMTs are chained to its bases between prunes, which might trigger a stack overflow due to default recursive drop implementation, if the block is large (more than a few thousands of transactions.)
Y
unit test added.
introduced in #7857
> [scratchpad] iterative drop

- Cargo.lock
- language/tools/disassembler/Cargo.toml
- x.toml
This removes the (unused) diem-types dependency from crate disassembler.
> [language] remove unused diem-types dependency from disassembler

- network/src/counters.rs
At one point the rate limiter gave per key metrics, but that became too
expensive, so it aggregates on direction.
I must have missed removing key in the first place when I removed it from the emitter https://github.com/diem/diem/blob/main/common/rate-limiter/src/rate_limit.rs#L274-L281
> [network] Remove rate-limit key from metrics

- .github/workflows/ci-publish-base-image.yml
- .github/workflows/ci-test.yml
- .github/workflows/ci-update-sccache.yml
- .github/workflows/daily.yml
- .github/workflows/docker-publish.yml
Since bouncer is now running, use secrets provided from environments.
1) When build attempts to use an environment it is considered a deployment by github actions.
2) If the environment is "protected" by users then the deployment can not be built (it will be left in a waiting state) until one of the users who are stewards of that environment approve the "deployment" to run.
3) jobs can only reference one environment
4) environments can be restricted to branchs (and recently added protected branches).
bouncer looks at deployement-requests in the waiting state and approves them if:
the branch is protected, and the user who pushed the latest commit is bor-libra.
Tested in /canary as well as standard pr.   Waiting to see how triggers to check for edge cases and will fix in place if the logic …
> [gha] use environments for secrets.

- sdk/compatibility/src/lib.rs
- sdk/src/transaction_builder.rs
- sdk/src/types.rs
This enables TransactionFactory to be able to selectively produce ScriptFun txns based on a supplied diem version.
Also renames the KeyRing type to AccountKey to more clearly indicate what the type represents.
> sdk: teach TransactionFactory to create script function transactions

- network/src/counters.rs
At one point the rate limiter gave per key metrics, but that became too
expensive, so it aggregates on direction.
Prevents metrics mismatch if rate limiter is turned on
Yes
Testnet
Original PR: https://github.com/diem/diem/pull/8142
* Rate limiting doesn't work without this change because it crashes due to a cardinality mismatch on the metrics
* Only affects nodes using rate limiting
* Without it, when rate limiting is turned on it crashes.
* Don't use rate limiting
> [cherry-pick][network] Fix rate limit metrics

- language/diem-framework/releases/artifacts/current/docs/modules/AccountAdministrationScripts.md
- language/diem-framework/releases/artifacts/current/docs/modules/AccountCreationScripts.md
- language/diem-framework/releases/artifacts/current/docs/modules/AccountLimits.md
- language/diem-framework/releases/artifacts/current/docs/modules/DesignatedDealer.md
- language/diem-framework/releases/artifacts/current/docs/modules/Diem.md
- language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
- language/diem-framework/releases/artifacts/current/docs/modules/DiemConfig.md
- language/diem-framework/releases/artifacts/current/docs/modules/DualAttestation.md
- language/diem-framework/releases/artifacts/current/docs/modules/PaymentScripts.md
- language/diem-framework/releases/artifacts/current/docs/modules/TransactionFee.md
- language/diem-framework/releases/artifacts/current/docs/modules/TreasuryComplianceScripts.md
- language/diem-framework/releases/artifacts/current/docs/modules/VASP.md
- language/diem-framework/releases/artifacts/current/docs/modules/XDX.md
- language/diem-framework/releases/artifacts/current/docs/scripts/script_documentation.md
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/model.rs
- language/move-prover/docgen/src/docgen.rs
- language/move-prover/docgen/tests/sources/DiemTest.spec_inline.md
- language/move-prover/docgen/tests/sources/DiemTest.spec_inline_no_fold.md
- language/move-prover/docgen/tests/sources/DiemTest.spec_separate.md
- language/move-stdlib/docs/Event.md
- language/move-stdlib/docs/Option.md
As title. TypeConstraint (i.e., copyable, resource) no longer exists, use the AbilityConstraint instead.
Only the first commit needs to be reviewed, the second one is doc update which is auto-generated.
Found this when converting Spec types into Move types.
Yes
CI
> [move-model] replace TypeConstraint with AbilityConstraint

- developers.diem.com/docs/core/run-local-network.md
- More explicit instructions for restoring an old ledger state
- Removed some redundant wording/explanations
- Got rid of a confusing section at the end + moved the valuable content elsewhere
> [dev docs] clarify local network instructions

- testsuite/cluster-test/src/experiments/compatibility_test.rs
The first batch of transactions in the LBT are being sent to validator nodes now instead of the full nodes. This might result in the recent flaky LBT. 
Yes
Manually ran the cluster test on a few previously failed LBR runs. Those runs passed.
#7959
> [cluster-test] Revert 7959

- Cargo.lock
- language/move-vm/runtime/Cargo.toml
This removes the diem-types dependency from move-vm-runtime. This dependency is currently unused.
> [language] remove unused dependency on diem-types from move-vm-runtime

- .github/actions/build-setup/action.yml
- Cargo.lock
- docker/ci/github/Dockerfile
- language/move-prover/Cargo.toml
- language/move-prover/boogie-backend/src/boogie_wrapper.rs
- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/src/lib.rs
- language/move-prover/tests/README.md
- language/move-prover/tests/sources/functional/aborts_if.cvc4_exp
- language/move-prover/tests/sources/functional/aborts_if.move
- language/move-prover/tests/sources/functional/aborts_if_with_code.cvc4_exp
- language/move-prover/tests/sources/functional/aborts_if_with_code.move
- language/move-prover/tests/sources/functional/address_quant.cvc4_exp
- language/move-prover/tests/sources/functional/address_quant.move
- language/move-prover/tests/sources/functional/arithm.cvc4_exp
- language/move-prover/tests/sources/functional/arithm.move
- language/move-prover/tests/sources/functional/cast.cvc4_exp
- language/move-prover/tests/sources/functional/cast.move
- language/move-prover/tests/testsuite.rs
This PR refines the test driver to deal better with "features". A feature is a special setting of flags for the prover. The first feature we enable is to test with `--use-cvc4`.
A feature can be either exclusive or inclusive:
- A feature which is inclusive includes all tests until explicitly excluded by a `// exclude_for: <feature>` comment in the source. This is currently used for the `default` feature configuration of the prover.
- A feature which is exclusive must be enabled by a comment `// also_include_for: <feature>` in the test source. This is currenly used for the `cvc4` feature configuration.
Some cvc4 tests in `sources/functional` have been enabled this way. They create a different baseline file than the default.
There seem to be some basic issue with cvc4 and boogie which can …
> [move-prover] Enable some cvc4 functional tests.

- language/move-model/src/exp_generator.rs
- language/move-model/src/lib.rs
- language/move-model/src/spec_translator.rs
- language/move-prover/bytecode/src/data_invariant_instrumentation.rs
- language/move-prover/bytecode/src/debug_instrumentation.rs
- language/move-prover/bytecode/src/function_data_builder.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/src/loop_analysis.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
Both components are moved from the crate move-prover/bytecode into
move-model.
- Exp generator originally locates in FunctionDataBuilder, now the exp
generator is turned into a trait and FunctionDataBuilder implement
this trait to produce move-model exps. This minimizes the code change.
FunctionDataBuilder still remains but now only handles
bytecode-related operations, such as `emit_*` or operations related to
`AttrId` or `Label`, which are not known to move-model
- The SpecTranslator file is completely removed from bytecode and fully
substituted by the version in move-model. Other necessary changes are
made to hook-up with the new SpecTranslator. There are no logic
changes to the translator. The main change is that functions that
used to takes a `FunctionDataBuilder` now takes a `T: …
> [move-model] bytecode-agnostic exp generator and spec translator

- language/move-model/src/builder/exp_translator.rs
- language/move-prover/tests/sources/functional/resources.move
The spec language created an empty value on `S{}`, whereas the Move compiler inserts a dummy field by design with the value of false for empty structs. This lead to mismatch in intepretation of bytecode and spec language during verification.
User reported bug.
Yes
Added new test.
NA
> [move-prover] Fixes a bug with empty struct pack in the spec language

- .github/workflows/ci-test.yml
Enable branch specific KS for LBT, e.g. `main|release-1.2`
Canary
- `KILL_SWITCH_LAND_BLOCKING_TEST=main|release-1.2`, LBT is bypassed -> https://github.com/diem/diem/actions/runs/734614672
- `KILL_SWITCH_LAND_BLOCKING_COMPAT=main|release-1.2`, non-compat LBT is run -> https://github.com/diem/diem/actions/runs/734605272
- No KS is set, compat LBT is run -> https://github.com/diem/diem/actions/runs/734658413
> [gha] add LBT KS

- .github/workflows/ci-test.yml
Rename the switches for LBT to remove confusion when they are enabled and disabled.  Rework the workflow control accordingly due to rename. 
Canary
- LBT is not triggered when neither switch is set https://github.com/diem/diem/actions/runs/742158362
- non-compat LBT is triggered when `BRANCHES_TO_ENABLE_LBT` is set with `main|release-` https://github.com/diem/diem/actions/runs/742227046
- compat LBT is triggered when `BRANCHES_TO_ENABLE_LBT_COMPAT_SUITE` is set with `main|release-` plus the above https://github.com/diem/diem/actions/runs/742430004
> [gha] rename lbt switches and rework its workflow ctrl

- language/move-lang/functional-tests/tests/functional_testsuite.rs
- language/move-lang/src/lib.rs
- language/move-model/src/lib.rs
`sources_shadow_deps` allows a module definition found in source file
shadow the same module definition found in dependency files. It is an
argument in `move_check`, `move_compile`, and
`move_construct_pre_compiled_lib` and in all these files, we can see the
following common code snippet:
```rust
let pprog = if sources_shadow_deps {
shadow_lib_module_definitions(pprog)
} else {
pprog
};
```
Perhaps a better place for this flag is `move_parse`, and more
specifically, its worker function, `parse_program`. And logically it
makes sense as well since the shadowing should be a parser concept.
A second change in this commit is that the meaning of
`sources_shadow_deps` is extended. In `move_parse`, there is a check,
`check_targets_deps_dont_intersect` (the same says all). However, it
creates a …
> [move-lang] make sources_shadow_deps part of parsing

- Cargo.lock
- language/move-model/src/lib.rs
- language/move-model/tests/testsuite.rs
- language/move-prover/Cargo.toml
- language/move-prover/bytecode/tests/testsuite.rs
- language/move-prover/lab/src/benchmark.rs
- language/move-prover/src/lib.rs
Removed the `build_move_model` and the associated regex-matching logic
from move-prover to move-model. The regex-matching logic is also removed
in favor of using `move_parse` to find the dependencies.
NOTE: the first commit is the same as #8180, only the second commit needs to be reviewed.
I'll be needing this as well for spec instrumentation.
Yes
CI
> [move-model] relocate model building logic fully to move model

- testsuite/cluster-test/src/suite.rs
This PR adds the state sync performance test to the `new_pre_release` test suite. This allows us to run the performance benchmark on all continuous pushes to keep better track of state sync performance (e.g., these numbers will automatically be posted in the #changelog channel).
Yes.
I've run the state sync test suite manually using the cluster test tool.
None.
> [Cluster Test] Add state sync performance test to new_pre_release suite

- client/json-rpc/src/broadcast_client.rs
- sdk/client/src/client.rs
https://github.com/diem/diem/pull/8206 does this for the blocking client, so lets also make sure its fixed for the async client.
> sdk: use correct response types in experimental proof API's

- testsuite/cluster-test/src/experiments/state_sync_performance.rs
This PR formats the throughput number reported by the state sync benchmark in cluster test to display only 2 decimal places (e.g., `1755.24`), as opposed to displaying the entire float (e.g., `1755.235294117647`).
Note: given that Duration::as_millis(..) returns the whole number of seconds as milliseconds (as opposed to the counted milliseconds [1]), this PR also updates the calculation to just use seconds. We shouldn't lose anything here.
[1] https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_millis
Yes.
Running this produces the following test output for the state sync performance benchmark (this is the same output that will be displayed on continuous runs):
```
2021-04-14T21:21:52.997028Z [main] INFO testsuite/cluster-test/src/experiments/state_sync_performance.rs:133 …
```
> [Cluster Test] Update the state sync benchmark to format the throughput displayed.

- language/move-lang/src/cfgir/ast.rs
- language/move-lang/src/cfgir/translate.rs
- language/move-lang/src/expansion/ast.rs
- language/move-lang/src/expansion/dependency_ordering.rs
- language/move-lang/src/expansion/translate.rs
- language/move-lang/src/hlir/ast.rs
- language/move-lang/src/hlir/translate.rs
- language/move-lang/src/lib.rs
- language/move-lang/src/naming/ast.rs
- language/move-lang/src/naming/translate.rs
- language/move-lang/src/parser/ast.rs
- language/move-lang/src/parser/lexer.rs
- language/move-lang/src/parser/syntax.rs
- language/move-lang/src/to_bytecode/translate.rs
- language/move-lang/src/typing/ast.rs
- language/move-lang/src/typing/core.rs
- language/move-lang/src/typing/translate.rs
- language/move-lang/tests/move_check/expansion/friend_decl_aliased_duplicates.exp
- language/move-lang/tests/move_check/expansion/friend_decl_imported_duplicates.exp
- language/move-lang/tests/move_check/expansion/friend_decl_qualified_duplicates.exp
- language/move-lang/tests/move_check/parser/attribute_no_closing_bracket.exp
- language/move-lang/tests/move_check/parser/attribute_no_closing_bracket.move
- language/move-lang/tests/move_check/parser/attribute_num_sign_no_bracket.exp
- language/move-lang/tests/move_check/parser/attribute_num_sign_no_bracket.move
- language/move-lang/tests/move_check/parser/attribute_placement.move
- language/move-lang/tests/move_check/parser/attribute_variants.move
- language/move-model/src/lib.rs
- Added attributes to Move
- Syntax is based on Rust attribute syntax, which is in turn based on the standards found in ECMA-334 and ECMA-335
- Attributes can currently be added on address blocks, modules, scripts, and any module top level member. 
- Eventually they should be able to be parsed on expression blocks, expression spec blocks, and expression use statements. 
- There is no sanity checking currently 
- we probably eventually want some way for attributes to register with the compiler so they can be checked
- We will likely hard code this temporarily for unit tests
- Blocking for unit test framework
- Should be helpful for other tools too, particularly the prover. 
- Added a few tests 
Built on top of #8143, so waiting for that to land
> [move-lang] Attributes

- sdk/src/transaction_builder.rs
- sdk/src/types.rs
- testsuite/cluster-test/src/experiments/load_test.rs
- testsuite/cluster-test/src/experiments/reconfiguration_test.rs
- testsuite/cluster-test/src/experiments/versioning_test.rs
- testsuite/cluster-test/src/main.rs
- testsuite/cluster-test/src/tx_emitter.rs
- testsuite/forge/src/backend/local.rs
test on local swarm with one validator node:
```cargo run -p cluster-test -- --mint-file "/private/var/folders/qd/tg50mr0d7k75qvztr_8yk2km0000gn/T/5b88e78fac18c65fbc2ab3908c86c5a5/mint.key" --swarm --peers "127.0.0.1:8080" --emit-tx --chain-id TESTING```
test with novi fnode with AOS DD and VASP accounts:
```
cargo run -p cluster-test \
-- \
--emit-tx \
--swarm \
--vasp \
--peers premainnet.libra.novi.com:80 \
--chain-id 21 \
--accounts-per-client 4 \
--workers-per-ac 4 \
--duration 60
```
* Justification and breaking nature (who does it …
> [cluster-test] deprecate accountData in CT

- language/move-prover/tests/sources/functional/parse_error.exp
- language/move-prover/tests/sources/functional/parse_error.move
This seems to have regressed. As you can see in the current baseline, position information is not available. This is because in GlobalEnv::to_loc, no file is defined when the error comes from Move parsing. (Before, to_loc crashed in this case, but this was changed in a previous PR to unblock this use case. Perhaps after fixing, we may want to crash again.)
Repro for bug and future regression test.
Yes
Added test
NA
> [move-prover] Add a test for checking parse errors.

- language/move-model/src/lib.rs
- language/move-model/src/model.rs
- language/move-prover/tests/sources/functional/parse_error.exp
As title, fix the issue in #8222.
Add all sources to `GlobalEnv` even when `move_parse` failed. This allows the env to translate the locations of parse errors.
> [move-model] fix source collection bug

- docker/tag-and-push.sh
This partially reverts 9ed22830.  The buildspec in Codebuild still needs tag-and-push script. 
CI
> [dkr] restore script needed in buildspec

- .github/workflows/ci-test-complete.yml
- .github/workflows/dep-summaries.yml
- .github/workflows/hyperjump-comment.yml
- .github/workflows/hyperjump-labels.yml
- .github/workflows/hyperjump-request-review.yml
- .github/workflows/jsonrpc-compat.yml
- Cargo.lock
- devtools/x/src/nextest.rs
This PR starts making the JUnit output generated in `nextest` available for developer consumption. This initial effort just implements a summary, but I hope to add more reporting soon.
This has to be implemented as a separate action because forks don't have the right permissions. Unfortunately, it also means that we can't test it until it lands on `main`. [This blog post](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) covers the `workflow_run` action.
I've had to fork the action to add a `test_case_annotations` feature (which we may want to use to disable test annotations if they prove to be too noisy). We may have to keep iterating on this and/or use it more significantly so I expect we'll maintain a copy of the action in the `diem` org …
> [ci] start consuming JUnit report from nextest

- language/move-lang/src/expansion/ast.rs
- language/move-lang/src/expansion/dependency_ordering.rs
- language/move-lang/src/expansion/translate.rs
- language/move-lang/src/naming/translate.rs
- language/move-model/src/lib.rs
This PR contains two commits that changes move source compiler and move model builder respectively:
The first commit: *[move-lang] summarize module dependencies after expansion*, provides enough information for the model builder to selectively compile (and build model for) modules in later compilation phases. This also collects friendships declared via the `pragma friend = ...` statement. Although the only use case is `pragma friend = 0x1::Genesis;` in the `DiemTimestamp`, it is important to have `Genesis` in the `dependency_summary` in order for the model builder to pick it up for compilation later. Otherwise, verification verification of many Move modules will fail if `Genesis.move` is not compiled. One example is `DiemSystem.move`:
```
error: global memory invariant does not hold
┌── …
```
> [move-lang][move-model] selective compilation for move-model building

- .github/workflows/daily.yml
Instead of sending nightly audit alerts in slack, create a GH issue for RUSTSECs found in each branch.  The issue is assigned to the diem-core-oncall. 
Canary with denying RUSTSEC warnings to force trigger audit failure and https://github.com/diem/actions/pull/13
- https://github.com/sausagee/libra/actions/runs/766082431 --> https://github.com/sausagee/libra/issues/148
> [gha] create issue for RUSTSEC found in audit

- language/move-prover/bytecode/src/compositional_analysis.rs
- language/move-prover/bytecode/src/packed_types_analysis.rs
- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/src/usage_analysis.rs
Previously, this function took ownership of a `FunctionData`, mutated its `annotations` to add the summary, then handed it back. This is convenient because the caller doesn't have to remember to update the annotations, but it creates ownership problems in the case that the caller analysis wants to store a `FunctionTarget` or `FunctionEnv` as part of its analysis state (which is useful if, e.g., you want to know if a variable is a formal parameter of the current function or a local). This was creating problems for some upcoming changes to the read/write set analysis that require a `FunctionEnv` in the analysis state.
> [move prover] CompositionalAnalysis::summarize returns a Summary

- execution/executor/src/mock_vm/mock_vm_test.rs
- language/benchmarks/src/move_vm.rs
- language/diem-tools/diem-validator-interface/src/lib.rs
- language/diem-vm/src/data_cache.rs
- language/testing-infra/e2e-tests/src/data_store.rs
- language/tools/resource-viewer/src/lib.rs
- language/tools/vm-genesis/src/genesis_context.rs
- specifications/move_adapter/README.md
- storage/state-view/src/lib.rs
- storage/storage-interface/src/state_view.rs
@hermanventer pointed out that this is not implemented anywhere. Let's get rid of it before someone calls it and crashes.
> [storage] delete unimplemented multi_get interface

- language/move-prover/bytecode/src/access_path_trie.rs
- language/move-prover/bytecode/tests/read_write_set/update_return.exp
- language/move-prover/bytecode/tests/read_write_set/update_return.move
The analysis had an assertion that was meant to guard against updating `Return` variables more than once (since that should never happen). However, the assertion was overzealous in that although a `Return` can only be assigned once, the value associated with a `Return` can be updated via a join (e.g., when a procedure returns from several different control locations).
This PR adds a test that crashed the old analysis + removes the overzealous assertion.
> [read/write set analysis] fix crash when updating return value via join

- storage/scratchpad/src/sparse_merkle/mod.rs
- storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
This cherry-pick was triggerd by a request on #8123
> 
> The SMTs are chained to its bases between prunes, which might trigger a stack overflow due to default recursive drop implementation, if the block is large (more than a few thousands of transactions.)
> 
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
> Y
> ## Test Plan
> unit test added.
> introduced in #7857
> 
> (If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)
cc @msmouse
> Cherry-pick PR #8123 into release-1.2: [scratchpad] iterative drop

- .github/workflows/ci-test.yml
- Cargo.lock
- common/workspace-hack/Cargo.toml
- devtools/x/Cargo.toml
- devtools/x/src/cargo/build_args.rs
- devtools/x/src/nextest.rs
This will cause two things to happen:
* If a test fails, it will automatically be retried.
* If a test succeeds the second or further times, it will be marked as
successful but flaky.
While we don't do anything with flaky test data at the moment, this
should improve land reliability because spurious test failures will be
retried. In the future, we plan to start filing GitHub issues for flaky
tests.
Also add timestamps to testcases.
Example output: https://gist.github.com/sunshowers/c2dc0989cda41c5b9646e52768cf6088
JUnit output: https://gist.github.com/sunshowers/74acf9d7b594698157157758dcfebff6
> [ci-test] enable nextest retries + flaky test detection

- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/tests/read_write_set/counter.exp
- language/move-prover/bytecode/tests/read_write_set/counter.move
The access domain is tracking which memory locations have been read/written, so it is never appropriate to perform a strong update.
Added a test where the analysis would previously perform an incorrect strong update, but now does the right thing.
> [read/writes set analysis] always use weak updates in access domain

- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/tests/read_write_set/borrow.exp
- language/move-prover/bytecode/tests/read_write_set/borrow.move
- language/move-prover/bytecode/tests/read_write_set/counter.exp
- language/move-prover/bytecode/tests/read_write_set/functions.exp
- language/move-prover/bytecode/tests/read_write_set/summary.exp
This access type was useful for sanity checks when building/debugging the initial analysis. But it is not needed by clients and just takes up space in the abstract state.
> [read/write set analysis] Remove Borrow access type

- Cargo.lock
- language/move-binary-format/Cargo.toml
- language/move-vm/types/Cargo.toml
- x.toml
This removes a few unused Diem dependencies from a few Move crates. This also adds comments to `x.toml` further explaining what exactly some of the remaining Move-to-Diem dependency are.
> [language] remove unused Move-to-Diem dependencies

- .github/workflows/ci-publish-base-image.yml
- .github/workflows/ci-test.yml
- .github/workflows/ci-update-sccache.yml
- .github/workflows/daily.yml
- .github/workflows/docker-publish.yml
This pick includes the following 6 PRs on GHA workflows
- #8133: switch GHA to use env secrets
- #8153: fix typo in env secret
- #8171: disable debug log in LBT during PR landing
- #8168: add LBT kill switch
- #8190: rename LBT kill switch and rework its workflow
- #8199: failed CI workflow when sccache enabled unit test and codegen unit test fail 
Canary + CI
> * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
This change affects GHA/CI workflow.  It does not affect mainnet or AOS.
> * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
CI in-place + Canary (https://github.com/diem/diem/actions/runs/786131119)
> * Why we must have it for V1 launch.
This allows the oncalls to use one …
> Cherry-pick GHA changes into release-1.2

- .github/workflows/daily.yml
- docker/tools/Dockerfile
This cherry-pick was triggerd by a request on #8247
cc @sausagee
> Cherry-pick PR #8247 into release-1.2: ci: pin the azcopy version used for the transaction reply job

- json-rpc/API-CHANGELOG.md
- json-rpc/docs/type_event.md
- json-rpc/types/src/proto/jsonrpc.proto
- json-rpc/types/src/views.rs
When we have a new event that is not deserialized by json-rpc Event view, exposing the raw BCS bytes of the event data helps client to decode the data before we update server view 
Yes
Unit test
> [json-rpc]: add raw BCS bytes to unknown event data

- json-rpc/src/data.rs
- json-rpc/src/lib.rs
- json-rpc/src/methods.rs
Streaming RPC uses many of the same data fetching as the json RPC server: by separating out pure data fetching vs server implementation, these can be reused (and also tested much more easily)
Yes
This is a refactor; existing tests
> [JSONRPC] Separate data fetching from RPC Server implementation

- Cargo.lock
- language/move-prover/Cargo.toml
- language/move-prover/abigen/Cargo.toml
- language/move-prover/abigen/tests/testsuite.rs
- language/move-prover/bytecode/Cargo.toml
- language/move-prover/docgen/Cargo.toml
- language/move-prover/docgen/tests/testsuite.rs
- language/move-prover/tests/testsuite.rs
- x.toml
This replaces a few usages of `diem-temppath` in the prover with `tempfile`, thus getting rid of the dependencies on the said Diem crate.
> [move-prover] replace diem-temppath with tempfile

- .github/workflows/ci-test.yml
- docker/build-common.sh
- docker/client/Dockerfile
- docker/cluster-test/Dockerfile
- docker/diem-build.sh
- docker/docker_republish.sh
- docker/faucet/Dockerfile
- docker/init/Dockerfile
- docker/safety-rules/Dockerfile
- docker/tools/Dockerfile
- docker/validator/Dockerfile
Attempt to split docker builds/build time in half.
Canaryed here:
https://github.com/diem/diem/runs/2453772955
15.75 minutes for non test docker images (init tools validator validator-tcb) 
11.5 minutes for test docker images (client faucet cluster-test)
We could enable sccache to cut these builds in half, but I'd want to overly secure the aws sccache creds first.
Should cut our total /land time from 50 minutes to 40.  Cluster test is still the long pole.
Yes
Ci, Canary
None.
> [gha] split docker build in to a matrix build, should cut time in half.

- testsuite/cluster-test/src/experiments/state_sync_performance.rs
> [cluster-test] extend newly added StateSyncPerformance test duration

- language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
- language/diem-vm/src/data_cache.rs
- language/diem-vm/src/diem_transaction_executor.rs
- language/diem-vm/src/diem_transaction_validator.rs
- language/diem-vm/src/diem_vm.rs
- language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- language/move-vm/runtime/src/data_cache.rs
- language/move-vm/runtime/src/move_vm.rs
- language/move-vm/runtime/src/runtime.rs
- language/move-vm/runtime/src/session.rs
- language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
- language/move-vm/test-utils/src/storage.rs
- language/testing-infra/e2e-tests/src/data_store.rs
- language/tools/move-cli/src/on_disk_state_view.rs
- language/tools/resource-viewer/src/lib.rs
- language/tools/resource-viewer/src/resolver.rs
Adjust the internal api for DiemVM to allow for a more generic transaction scheduler. The main change is to replace `StateViewCache` with a trait so that it could be replaced with some other data structure in the future.
Yes
`cargo test`
> [diem-vm] Adjust the internal api for diem-vm

- language/move-prover/boogie-backend-exp/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/loop_analysis.rs
- language/move-prover/bytecode/src/stackless_bytecode.rs
The `Stop` operation was originally designed to halt the execution in Boogie and hence, does not need to know where the backedge originally goes into. However, for stackless bytecode execution, having a `Stop` will confuse the executor because in concrete execution, it should go back to the loop header.
This PR allows the `Stop` instruction to carry the label of the loop header where the backedge supposes to go into.
Yes
CI
> [move-prover] record the loop header label in stop operation

- execution/executor-test-helpers/src/integration_test_impl.rs
- execution/executor/tests/db_bootstrapper_test.rs
- json-rpc/src/data.rs
- json-rpc/types/src/views.rs
- sdk/client/src/error.rs
- sdk/client/src/lib.rs
- sdk/client/src/response.rs
- sdk/client/src/verifying_client.rs
- testsuite/cli/src/client_proxy.rs
- testsuite/cli/src/diem_client.rs
- types/src/trusted_state.rs
- types/src/unit_tests/trusted_state_test.rs
- types/src/waypoint.rs
+ Note: this diff implements the bare minimum to get a single non-verifying API call working (`get_account`). Would like to get feedback on whether this looks like the right approach.
+ `VerifyingClient` wraps a base non-verifying json-rpc `Client` and converts normal non-verifying json-rpc calls, like `get_account(address)`, into a set of verifying calls `[get_account_with_proof(diem_root), get_account_with_proof(address)]`, issues the requests to the remote, untrusted json-rpc server, then verifies the proofs in the response, and finally presents the response as a normal `AccountView`.
+ I tested this implementation against testnet, and it seems to correctly sync and make a verifying `get_account` call. It seems like the sdk testing framework is still a bit of a moving target, so I've …
> [sdk] Add json-rpc VerifyingClient

- config/management/genesis/src/key.rs
- config/management/network-address-encryption/src/lib.rs
- config/management/operational/src/test_helper.rs
- config/management/operational/src/validator_config.rs
- config/management/operational/src/validator_set.rs
- config/management/src/secure_backend.rs
- testsuite/smoke-test/src/consensus.rs
- testsuite/smoke-test/src/genesis.rs
- testsuite/smoke-test/src/operational_tooling.rs
This PR updates the operational tool to allow backends to be made optional for two commands: `validator-set` and `validator-config`. Both of these commands use a backend to fetch the network encryption keys to decrypt the on-chain validator addresses before printing the data to the command line. However, decryption is not always required by users (e.g., if someone just wants to view a validator config on-chain without having access to the network key). With this PR, the backend need not be specified in these cases.
The PR offers two commits to achieve this:
1. First, we add an empty encryptor to the Encryption struct. This allows us to run the commands with a dummy encryptor, so that not much internal code needs to change.
2. Second, we update the commands to support optional backends and …
> [Operational Tool] Make backend arguments optional for non-required commands

- sdk/client/src/blocking.rs
- sdk/client/src/client.rs
- sdk/client/src/request.rs
- sdk/client/src/verifying_client.rs
- sdk/compatibility/src/lib.rs
We previously added support for getting an account at a historical version at the json-rpc server layer here: https://github.com/diem/diem/pull/7983
This PR finally adds support to the client. Here, we add a new method `get_account_by_version` for convenience, while the actual `MethodRequest::GetAccount` enum just gets an extra `Option<u64>` version parameter.
> [sdk] Add client support for get_account_by_version

- Cargo.lock
- language/move-lang/Cargo.toml
- language/move-lang/src/shared/mod.rs
- x.toml
This makes the move compiler no longer depend on `fallible`, which is a Diem crate.
> [move-compiler] remove dependency on fallible

- Cargo.lock
- language/benchmarks/Cargo.toml
- language/benchmarks/src/transactions.rs
- x.toml
This removes `diem-proptest-helpers` as a dependency from `language-benchmark`.
> [language] remove dependency on diem-proptest-helpers from language-benchmark

- devtools/x-core/src/lib.rs
- devtools/x-lint/src/runner.rs
- devtools/x/src/cargo/selected_package.rs
- devtools/x/src/changed_since.rs
Workaround x context git dep to allow unzipped code to benefit from x (namely fuzzing done by fb's in house fuzzer, lionhead).
Yes
CI/local unzipped diem repo.
Local Downloaded Artifact:
```
rexhoffman@rexhoffman-mbp diem-main % cargo x changed-since ghjkl67890-
Finished dev [unoptimized + debuginfo] target(s) in 0.37s
Running `target/debug/x changed-since ghjkl67890-`
fatal: not a git repository (or any of the parent directories): .git
Error: git root error: unable to find a git repo at /Users/rexhoffman/Downloads/diem-main
(hint: did you download an archive from GitHub? x requires a git clone)
```
```
rexhoffman@rexhoffman-mbp diem-main % cargo xtest --changed-since 3456789o0p-
Finished dev [unoptimized + debuginfo] target(s) in 0.39s
Running `target/debug/x test --changed-since …
```
> [x] Workaround x context to let us build and run xtest without a git repo

- helm/fullnode/templates/tests/test-fullnode-connection.yaml
- helm/fullnode/values.yaml
Testnet era increased during release-1.2
Also to separate helm test from metrics exposed, especially since there have been some state sync metrics changes. Just test via jsonrpc instead, and fail on HTTP error via curl flag.
Tested by deploying PFN locally via minikube, and running the helm test. Also CI passed :) [ci-test/helm-test](https://github.com/diem/diem/pull/8327/checks?check_run_id=2503063855)
> [helm] bump era and use get_metadata for test

- devtools/x-core/src/lib.rs
- devtools/x-lint/src/runner.rs
- devtools/x/src/cargo/selected_package.rs
- devtools/x/src/changed_since.rs
This cherry-pick was triggerd by a request on #8314
> 
> Workaround x context git dep to allow unzipped code to benefit from x (namely fuzzing done by fb's in house fuzzer, lionhead).
> 
> ### Have you read the [Contributing Guidelines on pull requests]
> 
> Yes
> 
> ## Test Plan
> 
> CI/local unzipped diem repo.
> 
> Local Downloaded Artifact:
> 
> ```
> rexhoffman@rexhoffman-mbp diem-main % cargo x changed-since ghjkl67890-
>     Finished dev [unoptimized + debuginfo] target(s) in 0.37s
>      Running `target/debug/x changed-since ghjkl67890-`
> fatal: not a git repository (or any of the parent directories): .git
> Error: git root error: unable to find a git repo at …
```
> Cherry-pick PR #8314 into release-1.2: [x] Workaround x context to let us build and run xtest without a git repo

- json-rpc/types/src/views.rs
1. To keep consistent behavior when output null value field.
2. Current Rust jsonrpc types generated from protobuf definition does not accept field value == null case for a string type; this change avoids the problem for the client.
Yes
Unit Test
> * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
Not a breaking change
> * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
Unit test confirms a server side rendered JSON can be deserialized by protobuf generated client data structure.
> * Why we must have it for V1 launch.
AOS is depending on client data structure in the release branch, we have new client developed, but it is too risky for AOS to switch at current time. The plan is: …
> Cherry-pick PR #8319 into release-1.2: [json-rpc]: remove the json field metadata if the value is null

- Cargo.lock
- language/diem-tools/diem-validator-interface/src/json_rpc_interface.rs
- language/diem-tools/diem-validator-interface/src/lib.rs
- language/diem-tools/diem-validator-interface/src/storage_interface.rs
- language/diem-tools/transaction-replay/Cargo.toml
- language/diem-tools/transaction-replay/src/lib.rs
- language/diem-tools/transaction-replay/src/main.rs
- language/diem-tools/transaction-replay/src/unit_tests/mod.rs
Added a command to fetch events stored on chain and annotate them with `transaction-replay`.
Yes
Spawned a local network and did following command:
```
cargo run --bin diem-transaction-replay -- --url http://localhost:54278 annotate-events 01000000000000000000000000000000000000000a550c18 0 1 
```
The result look like following:
```
Transaction Version: 4
Event index: 0
Event payload: drop store 0x1::DiemAccount::AdminTransactionEvent {
committed_timestamp_secs: 1619474369
}
```
> [transaction-replay] Implement an api for fetching annotated event data

- Cargo.lock
- common/workspace-hack/Cargo.toml
- x.toml
This crate has features that should only be enabled for certain builds.
Requested by @zekun000.
> [workspace-hack] exclude the fail crate

- .github/workflows/ci-test.yml
- .github/workflows/ci-update-sccache.yml
- .github/workflows/daily.yml
- devtools/x/src/cargo.rs
- devtools/x/src/utils.rs
- docker/ci/alpine/README.md
- scripts/dev_setup.sh
- x.toml
Move to a sccache fork/pr maintained in diem/sccache, which has it's changes rebased to the lastest master version of mozilla/sccache.   Also improves the printing out of sccache statistics.
Yes
Local build, and inspect sccache status with ```sccache -s```.
/canary.
Logs here:
https://github.com/diem/diem/runs/2506354859#step:6:785
None, aside from https://github.com/mozilla/sccache/pull/869, which will be brought up to speed with diem/sccache rusoto branch once this succeeds.
> [x] use diem/sccache rusoto branch for build, rather than rexhoffman/sccache

- language/move-prover/bytecode/src/memory_instrumentation.rs
- language/move-prover/bytecode/tests/memory_instr/basic_test.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/loop.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/loop.move
Otherwise we see patterns like the following:
```
26: destroy($t3)
27: write_back[LocalRoot($t0).D]($t3)
```
It is not an issue with boogie translator because `destroy` will be
translated to a nop. But it will create a problem for the interpreter
(and possibly the write-set analysis too)
After this commit it will be like,
```
26: write_back[LocalRoot($t0).D]($t3)
27: destroy($t3)
```
Yes
CI
> [move-prover] instrument write-backs before the Destroy operation

- .github/workflows/daily.yml
Create a GH issue or update an existing one when db-restore fails the transaction-replay job in nightly.
yes
canary in https://github.com/sausagee/libra/runs/2520895957?check_suite_focus=true which created issue https://github.com/sausagee/libra/issues/160
> [gha] open issue when db-restore fails in CI

- language/benchmarks/src/move_vm.rs
- language/diem-framework/src/lib.rs
- language/diem-tools/transaction-replay/src/lib.rs
- language/diem-tools/writeset-transaction-generator/src/admin_script_builder.rs
- language/move-lang/functional-tests/tests/functional_testsuite.rs
- language/move-lang/src/bin/move-build.rs
- language/move-lang/src/bin/move-check.rs
- language/move-lang/src/lib.rs
- language/move-lang/src/parser/mod.rs
- language/move-lang/src/parser/sources_shadow_deps.rs
- language/move-lang/src/shared/mod.rs
- language/move-lang/tests/move_check_testsuite.rs
- language/move-lang/tests/stdlib_sanity_check.rs
- language/move-model/src/lib.rs
- language/move-vm/integration-tests/src/compiler.rs
- language/tools/move-cli/src/commands.rs
- language/tools/move-cli/src/package.rs
- language/tools/move-unit-test/src/lib.rs
- Moved shadowing lib logic into expansion, as it needs to be there after named addresses
- Moved the no_shadow flag into the Flags struct
~~- Makes named address logic a lot easier~~
- Originally I thought I needed this for named addressing, but I don't. Regardless, I think moving this into flags is cleaner. 
- Updated endpoints. Ran tests
> [move-lang] Clean up shadowing lib logic

- Cargo.lock
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/local.rs
- testsuite/forge/src/interface/network.rs
- testsuite/forge/src/interface/node.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/forge/src/lib.rs
- testsuite/forge/src/main.rs
- testsuite/forge/src/tx_emitter.rs
Implemented tx emitter in forge itself instead of rely on current CT tx_emitter with lots of underlying conversion. This let Forge has ability to emit e2e txn in a specified duration to do CT alike testing
TODO: stats report is going to add to expose metrics in the following pr
* Comprehensive test results that …
> [forge] Implemented Tx Emitter in Forge

- Cargo.lock
- common/workspace-hack/Cargo.toml
- language/move-model/Cargo.toml
- language/move-model/src/ast.rs
- language/move-model/src/builder/exp_translator.rs
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/exp_generator.rs
- language/move-model/src/exp_rewriter.rs
- language/move-model/src/model.rs
- language/move-model/src/spec_translator.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/bytecode/src/data_invariant_instrumentation.rs
- language/move-prover/bytecode/src/function_target.rs
- language/move-prover/bytecode/src/mono_analysis.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/bytecode/src/stackless_bytecode.rs
This PR switch the `model::ast::Exp` representation to use internalization (aka "pointer equality ==> structural equality"). We use the awesome new [internment](https://crates.io/crates/internment) crate for this which provides a uniform API, behaving similar than Rc, with different underlying implementations (process global, thread local, or Arc ref counted). The current choice is to use thread local, but it can be easily changed at later points.
The PR also introduces a new trait-based expression rewriter abstraction which attempts to preserve sharing. This new rewriter replaces three different existing rewriter implementations, eliminating some technical debt.
Internalization is highly desirable to make specification inference and other techniques relying on term rewriting feasible. …
> [move-prover] Internalization for expressions plus new rewriter design

- testsuite/cluster-test/src/experiments/state_sync_performance.rs
This PR adds two simple checks for possible error cases in the state sync performance test:
- Ensure that the validator syncs more than 0 transactions
- Ensure that the time taken to sync is more than 0 seconds (otherwise we get a division by zero error, as reported here: https://app.circleci.com/pipelines/github/novifinancial/libra-ops/4037/workflows/d047e444-98ed-4f6e-8cc6-4a7fab0f2969/jobs/15116)
Yes.
Will run locally before landing to ensure it still works (however, I won't exercise these error paths manually).
None.
> [State Sync Performance Test] Add additional checks for possible error cases.

- language/move-core/types/src/effects.rs
- language/move-prover/interpreter/src/concrete/mod.rs
- language/move-prover/interpreter/src/concrete/player.rs
- language/move-prover/interpreter/src/concrete/ty.rs
- language/move-prover/interpreter/src/concrete/value.rs
- language/move-prover/interpreter/src/lib.rs
- language/tools/move-unit-test/src/test_reporter.rs
- language/tools/move-unit-test/src/test_runner.rs
As title. The stackless bytecpde interpreter now also produces a changeset that captures changes of resources in the global storage.
The cross comparison also reveals a bug in the prior write-back implementation on vector and struct field updates. This is fixed now.
To bridge the gap between the two VMs.
Yes
CI, especially the tests on global ops and events.
> [stackless-vm] produce a changeset after execution

- Cargo.lock
- storage/scratchpad/Cargo.toml
- storage/scratchpad/benches/sparse_merkle.rs
- storage/scratchpad/src/lib.rs
- storage/scratchpad/src/sparse_merkle/mod.rs
- storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
- storage/scratchpad/src/sparse_merkle/test_utils.rs
- storage/scratchpad/src/sparse_merkle/utils.rs
(This is on top of https://github.com/diem/diem/pull/8386, including its two commits before it got landed.)
Based on the NaiveSmt newly introduced, benchmark the updating time in these three cases: 1. inserting to an empty SMT; 2. inserting to an SMT with a committed base (root is "unknown" hence all information about the base tree must be known through the proof reader; 3. updating an SMT with some in mem nodes.
The `NaiveSmt` is under the feature "bench", and when running the bench "--features bench" needs to be in the command line, which is not ideal. Probably `NaiveSmt` needs to be split into its own crate.
Y
benchmark updated
cargo bench -p scratchpad --features bench
```
Finished bench [optimized + debuginfo] target(s) in 9.68s
Running target/release/deps/scratchpad-7c837bd6e47fcdb2 …
```
> [scratchpad] sophisticated Criterion benchmarks

- Cargo.lock
- common/workspace-hack/Cargo.toml
- language/move-model/src/ast.rs
- language/move-prover/bytecode/Cargo.toml
- language/move-prover/bytecode/src/access_path.rs
- language/move-prover/bytecode/src/access_path_trie.rs
- language/move-prover/bytecode/src/borrow_analysis.rs
- language/move-prover/bytecode/src/clean_and_optimize.rs
- language/move-prover/bytecode/src/compositional_analysis.rs
- language/move-prover/bytecode/src/dataflow_analysis.rs
- language/move-prover/bytecode/src/dataflow_domains.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/src/livevar_analysis.rs
- language/move-prover/bytecode/src/packed_types_analysis.rs
- language/move-prover/bytecode/src/reaching_def_analysis.rs
- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/bytecode/src/usage_analysis.rs
- language/move-prover/bytecode/src/verification_analysis.rs
- language/move-prover/bytecode/src/verification_analysis_v2.rs
- language/move-prover/tests/sources/functional/disable_inv.exp
- language/move-prover/tests/sources/functional/disable_inv.inv_v2_exp
- language/move-prover/tests/sources/functional/disable_inv.move
This reimplements the collection types for DFA using base types from the [`im` crate](https://docs.rs/im/15.0.0/im/).
In DFA, we often have types like maps or sets which are copied and refined with each basic block. Traditional Rust collections are not well suited for this, because for each instruction we need to make a deep clone of the input domains. The `im` types are designed with structure sharing in mind. Clone is O(1), and subsequent write leads only to a delta with a reference to the original value.
The API of those collections is slightly different which lead to some adoptions in our code. The PR also attempts to complete the wrapping traits for SetDomain and MapDomain such that they (mostly) behave as the underlying representation.
Make the DFA framework more sensible.
Yes …
> [move-prover] Using immutable collections for SetDomain and MapDomain

- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
- language/move-binary-format/src/check_bounds.rs
- language/move-binary-format/src/proptest_types.rs
- language/move-binary-format/src/proptest_types/functions.rs
- language/move-binary-format/src/proptest_types/types.rs
The `self_module_handle_idx` in not bound checked by the bytecode verifier. This PR (the first commit) fixes that.
This issue was originally reported in https://community.diem.com/t/is-this-a-vulnerability-to-move-vm/3571 and a repro example can be found in https://github.com/suirui17/input_samples.
Before the fix, the module deserializes fine and will trigger an out-of-bound access when `self_module_handle_idx` is used to dereference the handle. After the fix, the module no longer deserializes. To verify that, save the example in some test file `test.mv` and run `move-cli view test.mv`. Expect an error saying that the module does not deserialize.
While fixing the issue, we also found that the proptest hardcoded `self_module_handle_idx` to always be zero in the valid module generation …
> [bytecode-verifier] bound check for self_module_handle_idx

- network/builder/src/builder.rs
- network/simple-onchain-discovery/src/builder.rs
- network/simple-onchain-discovery/src/lib.rs
- network/src/connectivity_manager/mod.rs
- network/src/connectivity_manager/test.rs
- testsuite/cluster-test/src/experiments/load_test.rs
ConfigurationChangeListener is very generic, and the changes that it
listens to are not generic.  This is renaming it appropriately and all subsequent pieces that refer to `OnChain`
to keep it specific to `ValidatorSet` changes.
Yes.
None, rename so tests should handle it.
N/A
> [network] Rename ConfigurationChangeListener to ValidatorSetChangeListener

- storage/scratchpad/benches/sparse_merkle.rs
- storage/scratchpad/src/sparse_merkle/test_utils/mod.rs
- storage/scratchpad/src/sparse_merkle/test_utils/proof_reader.rs
- testsuite/diem-fuzzer/src/fuzz_targets.rs
The Criterion benchmark was broken and normal build process was not able to detect it.
Also added the fuzz target to the list so it can actually be run.
`cargo bench -p scratchpad --features bench`
`cargo run -p diem-fuzzer --bin diem-fuzzer -- fuzz SparseMerkleCorrectness`
#8388
> [scratchpad] fix benchmark

- language/move-lang/src/interface_generator.rs
- Fixed syntax for friends in interface generation
- Fix for #8403
- Verified fix works
- It will be run on every test after #8403 lands, but we should think about a dedicated test
> [move-lang] Fix interface generator for 'friend'

- Cargo.lock
- language/move-core/types/src/errmap.rs
- language/move-core/types/src/lib.rs
- language/move-prover/errmapgen/src/errmapgen.rs
- language/tools/move-cli/Cargo.toml
- language/tools/move-cli/src/commands.rs
- language/tools/move-explain/Cargo.toml
- language/tools/move-explain/src/lib.rs
- sdk/transaction-builder/Cargo.toml
- sdk/transaction-builder/release_errmap/error_description.errmap
- sdk/transaction-builder/src/error_explain.rs
- sdk/transaction-builder/src/lib.rs
In order to unblock a PR (#8398) which needs the ability to get Move error explanations from a _published_ crate, this PR adds a small sdk crate `diem-move-error-explain` (very creative name :)) with no unpublished dependencies (so it's easy to publish) and allows us to continue deferring on how we want to publish `diem-framework-release` (pending the Move separation).
We need to pull out the `ErrorMapping` definitions so they're separated from the generation logic, which depends on the internal, unpublished `move-model` crate. This separation will allow us to easily publish a small `diem-move-error-explain` crate without publishing any internal move modules.
A crate for looking up the human-readable explanation of a Diem Move transaction abort code. This crate mostly exists as a …
> [sdk] Add move error explanations to transaction builder

- client/assets-proof/src/lib.rs
- execution/executor-test-helpers/src/integration_test_impl.rs
- execution/executor/tests/db_bootstrapper_test.rs
- json-rpc/src/data.rs
- json-rpc/src/methods.rs
- json-rpc/src/tests/unit_tests.rs
- json-rpc/types/src/views.rs
- sdk/client/src/verifying_client.rs
- types/src/account_config/constants/diem.rs
- types/src/account_state.rs
**Problem:** In order to project an `AccountState` into a json-rpc `AccountView`, we need to pull out the balance resources from the `AccountState`, which currently requires a list of currency code `Identifiers` (e.g. "XUS" or "XDX") to build the access `Path` needed to lookup the resource bytes from the state. To get the list of currency codes, we first need to lookup the global `RegisteredCurrencies` set, which requires an extra request for the verifying client's `get_account` implementation and doubles the read-amplification for normal `get_account` requests.
**Solution:** Instead of indexing by currency code to get the balance resources, this diff just reads all balance resources directly and extracts the currency code from the generic type parameter. That way, we don't need to first …
> [json-rpc] Avoid extra get_currencies lookup for get_account

- language/move-stdlib/modules/Signer.move
Conceptually, Signer is a droppable struct.
To correct the Signer module doc
yes
cargo test
> Correct the Signer module documentation

- language/move-prover/interpreter-testsuite/tests/concrete_check/event.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/event.move
- language/move-prover/interpreter/src/concrete/runtime.rs
- language/move-prover/interpreter/src/lib.rs
- language/tools/move-unit-test/src/test_runner.rs
The emit-event test case is turned off when the global invariant processing is set to v2 by default. But it seems to be passing now. So let's re-enable it.
This PR also has two additional cleanups that
- re-stored verbose debug printing when running the stackless bytecode interpreter in the move unit test framework (I accidentally removed the setting in a prior commit)
- simplified the APIs for the entrypoint of the stackless bytecode interpreter a bit. The inner runtime does not need to take a whole GlobalState, instead, a `&mut` is enough.
testing and cleaning-up
Yes
CI
> [stackless-vm] re-enable the emit test case and minor clean-up

- language/move-stdlib/nursery/Vault.move
- language/move-stdlib/nursery/docs/Vault.md
- This PR adds the function `is_delegation_enabled` to the Vault module
- It was necessary while doing an exercise with Vault. It seems useful to have it.
To add the function `is_delegation_enabled` to the Vault module
yes
cargo test
> [move-stdlib] Add Vault::is_delegation_enabled

- storage/scratchpad/Cargo.toml
- storage/scratchpad/benches/sparse_merkle.rs
- storage/scratchpad/src/sparse_merkle/updater.rs
1. Don't split if depth is big -- limiting total tasks in parallel, also eliminate potential stack overflow in DEBUG mode due to how Rayon works.
1. Don't introduce Rayon overhead if work is small, makes `serial_update` (if call the updater, which it will in my follow up PR) as fast as no rayon is involved.
Performance improvement was observed.
```
insert to committed base/batch_update_by_updater/2
time:   [70.834 us 70.983 us 71.143 us]
thrpt:  [28.113 Kelem/s 28.176 Kelem/s 28.235 Kelem/s]
change:
time:   [-23.625% -22.946% -22.324%] (p = 0.00 < 0.05)
thrpt:  [+28.740% +29.779% +30.933%]
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
1 (1.00%) high mild
2 (2.00%) high severe
insert to committed base/batch_update_by_updater/4
time:   [103.65 us 103.79 us 103.96 …
```
> [scratchpad] limit concurrency for the updater

- language/diem-tools/writeset-transaction-generator/src/main.rs
- language/diem-tools/writeset-transaction-generator/src/release_flow/artifacts.rs
- language/diem-tools/writeset-transaction-generator/src/release_flow/create.rs
- language/diem-tools/writeset-transaction-generator/src/release_flow/verify.rs
- testsuite/smoke-test/src/release_flow.rs
…ier.
Fixes a number of minor issues in WriteSet generator tool:
1. Fix the deserialization for verification pass: The creation path emits a serialized `TransactionPayload` whereas the verification path emits a `WritesetPayload`
2. Automatically inserts a newline at the end of the artifact file so that linter won't complain.
3. Add a `use_latest_version` option for `verify-release` command to fetch the latest diem-framework modules instead of the diem framework modules at the version when the payload gets created. This will help verify the payload when the writeset is created a while ago and the state is already pruned by the database.
Yes
Manually created the writeset and verify that 1 and 2 are fixed. It is hard to test 3 tho cuz this option would only matter when the states are already …
> [writeset-generator] Fix a few minor issues for writeset generator tool

- json-rpc/API-CHANGELOG.md
- json-rpc/docs/type_account.md
- json-rpc/docs/type_event.md
- json-rpc/tests/integration_test.rs
- json-rpc/types/proto/src/jsonrpc.proto
- json-rpc/types/src/views.rs
- types/src/account_config/resources/role.rs
- types/src/account_state.rs
Adding TC account type to Accounts view and adding tests for reading DiemIdDomainEvents once domains have been added or removed.
json rpc integration_test.rs 
https://github.com/diem/diem/pull/8363
> DiemIdDomainEvents

- language/documentation/book/src/SUMMARY.md
- language/documentation/book/src/abort-and-assert.md
- language/documentation/book/src/address.md
- language/documentation/book/src/bool.md
- language/documentation/book/src/coding-conventions.md
- language/documentation/book/src/conditionals.md
- language/documentation/book/src/constants.md
- language/documentation/book/src/creating-coins.md
- language/documentation/book/src/equality.md
- language/documentation/book/src/functions.md
- language/documentation/book/src/generics.md
- language/documentation/book/src/global-storage-operators.md
- language/documentation/book/src/global-storage-structure.md
- language/documentation/book/src/integers.md
- language/documentation/book/src/introduction.md
- language/documentation/book/src/loops.md
- language/documentation/book/src/modules-and-scripts.md
- language/documentation/book/src/overview.md
- language/documentation/book/src/references.md
- language/documentation/book/src/signer.md
- language/documentation/book/src/standard-library.md
- language/documentation/book/src/structs-and-resources.md
- language/documentation/book/src/tuples.md
- language/documentation/book/src/uses.md
- language/documentation/book/src/variables.md
- language/documentation/book/src/vector.md
This adds a preliminary version of the Move language documentation as an mdBook, keeping the same content that is currently published on the Diem developer documentation website. It has not yet been updated to reflect changes in version 1.2. Further changes in the formatting are probably also needed to organize the book into larger chapters, e.g., "Primitive Types", instead of just a list of small sections as independent chapters. And, we will need to figure out how and when to build the html content.
We have decided to go back to keeping the Move language documentation in GitHub, but will now use mdBook to format the document.
Yes
Ran `mdbook build` and sanity checked the generated content
> [language] add Move language documentation as an mdBook

- Cargo.lock
- common/workspace-hack/Cargo.toml
- sdk/offchain/Cargo.toml
- sdk/offchain/src/identifier.rs
- sdk/offchain/src/lib.rs
- sdk/offchain/src/subaddress.rs
- sdk/src/transaction_builder.rs
- testsuite/cluster-test/src/experiments/reconfiguration_test.rs
The Diem Offchain API largely resides in python (https://github.com/diem/client-sdk-python). This PR continues the transition to the rust offchain API by adding the Diem Intent Identifier functionality as described in DIP 5: https://dip.diem.com/dip-5/#format.
This PR converts the python SDK identifier implementation for rust: https://github.com/diem/client-sdk-python/blob/master/src/diem/identifier/__init__.py.
Yes.
```
$ cd sdk/offchain
$ cargo test
```
> Rust Offchain API: Add Diem Intent Identifier and accompanying fields

- language/move-model/src/exp_rewriter.rs
- language/move-model/tests/sources/use_erroneous_schema.exp
- language/move-model/tests/sources/use_erroneous_schema.move
The bug was in the expression rewriter. The rewriter must deal with `Invalid` expressions because it is used during type checking, where Invalid expression nodes can appear as result of type check errors.
Fix crash
Yes
Added a new test.
NA
> [move-prover] Fixes a crash when someone tries to include a schema with a type check error.

- language/move-prover/interpreter-testsuite/tests/concrete_check/function_call.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/function_call.move
- language/move-prover/interpreter-testsuite/tests/concrete_check/return_mut_ref.exp
- language/move-prover/interpreter-testsuite/tests/concrete_check/return_mut_ref.move
- language/move-prover/interpreter/src/concrete/local_state.rs
- language/move-prover/interpreter/src/concrete/player.rs
- language/move-prover/interpreter/src/concrete/ty.rs
- language/move-prover/interpreter/src/concrete/value.rs
[This PR is self-contained within the stackless bytecode interpreter]
PR #8357 refactored the borrow analysis and memory instrumentation
to use inter-procedural analysis to determine borrow behavior of called
functions. This PR has several implictions to the interpreter:
- elimination of weak edges in the memory model,
- addition of hyper edges in complex cases of `&mut` return values
across function calls
- refactored the approach on how and when to check whether a
`write_back` is active or not (via the new `IsParent` operation)
This PR incorporates these new changes and adds support (as well
as type checking) to the new `Hyper` type in `BorrowEdge` and the
`IsParent` operation.
However, currently, there is an issue in the live variable analysis pass
that makes a mutable reference to be …
> [stackless-vm] update the interpreter with the new memory model

- Cargo.lock
- Cargo.toml
- language/diem-tools/e2e-tests-replay/Cargo.toml
- language/diem-tools/e2e-tests-replay/src/lib.rs
- language/diem-tools/e2e-tests-replay/src/main.rs
- language/testing-infra/e2e-tests/Cargo.toml
- language/testing-infra/e2e-tests/src/executor.rs
- x.toml
As promised in #8354, we want to make the e2e replayer a standalone tool in the diem-tool suite instead of polluting the `e2e-tests` lib crate with a `main.rs`. The first commit did that.
The second commit forces a trace dump when the e2e tests with Genesis of all DIem Framework versions and allow the replayer to select which version of trace to replay.
To run the replayer:
First, collect execution traces from the language e2e test suite:
```
cd language/e2e-testsuite
TRACE=<path-to-trace-dir> cargo test
```
Then, replay the trace with cross comparison between the Move VM and stackless VM
```
cd language/diem-tools/e2e-tests-replay
cargo run -- -t <path-to-trace-dir> -x -d 2 -v 1
```
To replay without the stackless VM, remove the `-x`:
```
cargo run -- -t <path-to-trace-dir> -d 2 -v 1
``` …
> [test-infra][e2e] make the replayer a standalone diem-tool with version selection

- config/management/genesis/src/config_builder.rs
- config/management/genesis/src/lib.rs
- config/management/genesis/src/storage_helper.rs
- config/management/genesis/src/swarm_config.rs
- config/management/genesis/src/validator_builder.rs
- config/management/genesis/src/verify.rs
- config/management/genesis/src/waypoint.rs
- config/management/operational/src/test_helper.rs
- config/management/src/storage.rs
- diem-node/src/lib.rs
- json-rpc/tests/integration_test.rs
- json-rpc/tests/node.rs
- language/diem-tools/oncall-trainer/src/init.rs
- testsuite/diem-swarm/src/swarm.rs
- testsuite/smoke-test/src/operational_tooling.rs
- testsuite/smoke-test/src/test_utils.rs
This PR introduces a new and improved ValidatorBuilder. The intent of this new builder is to improve the clarity of what happens during genesis as well as ensuring each validator's environment is a bit cleaner (e.g. the root key should not be present in each validator's secure-store).
> forge: new validator config builder

- language/tools/move-cli/README.md
- language/tools/move-cli/src/sandbox/commands/test.rs
The code examples in readme do not run correctly, and once fixed, their output differs from the example output given in the readme.
1. The first example script accesses a `signer` without taking a reference to it.
2. Several examples seem to use an earlier syntax for abilities (e.g., placement of the `has` struct annotation).
3. The expected output for inspected compiled bytecode and a few other `sandbox` commands has changed.
Additionally, running `move sandbox test` with the `--track-cov` flag does not print out coverage information unless the CLI was compiled with the `--debug` flag. Added a note about this to the readme.
This PR also changes the directory structure for tests from:
```
test_name
└── src
├── modules
└── scripts
```
To:
```
test_name
├── scripts
└── src
```
Yes
Changes …
> [move-cli] Update readme to reflect changes to Move syntax and CLI output

- specifications/network/README.md
In conversion to Github, the links were not updated to the appropriate
docs.
Resolves https://github.com/diem/diem/issues/8521
See https://github.com/gregnazario/diem/tree/fix-links/specifications/network for testing
> [network-spec] Fix dead links

- .github/workflows/ci-test.yml
- devtools/x/src/build.rs
- devtools/x/src/cargo.rs
- devtools/x/src/context.rs
- devtools/x/src/fmt.rs
- devtools/x/src/generate_workspace_hack.rs
- devtools/x/src/installer.rs
- devtools/x/src/nextest.rs
- devtools/x/src/test.rs
- devtools/x/src/utils.rs
- x.toml
Fix code coverage since the last rust update broke it.
Yes
Run by pushing code to gha-test-1 branch, results:
Runs:
https://github.com/diem/diem/runs/2814501836?check_suite_focus=true
Results:
https://ci-artifacts.diem.com/coverage/unit-coverage/2021-06-13-7ba68db8/index.html
None
> [x] Improve code coverage generation (turn off sccache in code coverage by default, better warnings/logging, refactor)

- .github/workflows/ci-test-complete.yml
Right now we've two actions in diem/actions that can download and unzip artifacts.  This is prep to consolidate on one which is written in shell - shell one also can work across jobs - rather than the javascript coupled to gha.
Yes
CI, this run will spark execution of changes after running in ci-test-complete.yml
None yet (will open one to remove old action).
> [gha] consolidate artifact downloaders in prep to delete dupe in diem/actions

- crypto/crypto/src/test_utils.rs
- language/testing-infra/e2e-tests/src/account_universe/bad_transaction.rs
- language/testing-infra/e2e-tests/src/account_universe/rotate_key.rs
- language/testing-infra/e2e-tests/src/common_transactions.rs
This updates the keygen generation for invalid auth key and key rotation transactions. Previously they would use the same deterministic seed which could lead to issues where in a previous transaction the account will have rotated to one key, and then the invalid auth key generation will generate that same key and assume that it is invalid.
This also fixes an issue where we weren't passing a type argument to the `EMPTY_SCRIPT` transaction even though it had a type argument. 
Tested against failing fuzz result and all tests passed.
> [account universe] Update keygen for invalid auth key txns

- CHANGELOG/CHANGELOG-1.3.md
- language/RELEASES.md
This also updates the Diem 1.3 CHANGELOG with some changes that were previously incorrectly classified as Move changes.
Document Move changes since 1.2
Yes
> [language] add Move release notes for version 1.3

- .github/workflows/ci-test.yml
Ensure the canary to determine if coverage has broken is due to tooling changes or a legitimate drop in coverage in commons/logger so we'll always build for common/logger as well.
Yes
CI
None
> [gha] in case diem/logger coverage drops this will alert the author who can lower coverage restrictions.

- scripts/dev_setup.sh
This will allow the github actions workflow ci-update-sccache.yml to complete when it had been failing to link the go lang.
Yes
Ran the action and saw it work: https://github.com/diem/diem/actions/runs/941095055
None
> [gha] allow go to force link on mac managed by github, should be safe locally as well.

- language/tools/move-unit-test/src/test_reporter.rs
- language/tools/move-unit-test/tests/test_sources/missing_data.exp
- language/tools/move-unit-test/tests/test_sources/missing_data.move
Previously if a non-abort error was encountered we'd display the VM error, but would not try to provide the source location of where that error occurred.
This PR adds support to report the location of non-abort errors in tests. You can see an example of this in the new test case added.
> [move-unit-test] Add location reporting for non-abort errors

- Cargo.lock
- language/bytecode-verifier/invalid-mutations/Cargo.toml
- language/bytecode-verifier/invalid-mutations/src/bounds.rs
- language/bytecode-verifier/invalid-mutations/src/bounds/code_unit.rs
- language/bytecode-verifier/invalid-mutations/src/helpers.rs
- language/bytecode-verifier/invalid-mutations/src/lib.rs
- x.toml
This duplicates a simple helper function in the crate so it doesn't need to depend on diem-proptest-helpers, which is a diem dependency.
> [bytecode verifier][invalid mutations] remove diem-dependency: diem-proptest-helper

- Cargo.lock
- language/move-binary-format/Cargo.toml
- language/move-binary-format/src/file_format.rs
- language/move-vm/types/src/gas_schedule.rs
- x.toml
This replaces crate `num-variants` (a diem dependency) with `variant_count`, which has the same functionality.
> [language][binary-format] remove diem-dependency: num-variants

- language/move-prover/interpreter/src/concrete/runtime.rs
- language/move-vm/runtime/src/tracing.rs
Fix the warning when compiling move prover in release mode.
Yes
Not sure why this is not caught in CI...
Manually do a `cargo build --release` in `move-prover` directory should yield no warnings.
> [move-vm][stackless-vm] fix warnings on unused items caused by conditional compilation in debug mode

- docker/forge/buildspec.yaml
Add dockerhub account secrets to forge codebuild to avoid pull rate limit
./docker/build-aws.sh --build-forge --version pull/8571
> [forge] added dockerhub secrets for forge codebuild

- language/move-prover/doc/user/spec-lang.md
Edited the user doc to describe the pragmas `pragma
disable_invariants_in_body` and `pragma delegate_invariants_to_caller`
* What workarounds and alternative we have if we do not …
> [move-prover] Added invariant disabling pragmas to user doc

- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
Test that the bound checker's error codes are the ones we expect to find. This is important because the error codes are part of our interface and are supposed to be stable.
Yes.
`cargo xtest -p bytecode-verifier-tests`
This is an improvement suggested in the discussion on #8536.
> [move][vm] Test bounds checker error codes

- scripts/dev_setup.sh
install_pkg is a shell function, and if the pre-command e.g. expands to `sudo` like in my ubuntu system, this leads to failure.
devsetup fails on my Ubuntu/PopOS box.
Yes
Manual
> [dev-infra] Removing pre-command from install_pkg invocation

- Cargo.lock
- language/move-prover/interpreter/crypto/Cargo.toml
This fixes the `no curve25519-dalek backend cargo feature enabled!`
cargo build error.
Wondering why this is not caught by CI though as `cargo build` fails.
The original PR that introduces the crate is #8573
Fix `cargo build` failure.
Yes
`cargo build`
> [stackless-vm][crypto] fix missing feature section

- CHANGELOG/CHANGELOG-1.3.md
- language/RELEASES.md
- language/changes/4-unit-testing.md
Add the 1.3 release notes for Move to the release-1.3 branch.
Release notes should be present on the release branch.
Yes
N/A: no code changes
This includes both #8483 and #8548
* Justification: No code changes. This is important info to provide on the release branch.
* Comprehensive test results: N/A
* We do not strictly need this for launch. The workaround is for people to look on the main branch for the Move release notes, but that isn't very nice.
> [language][release-1.3] cherry-pick Move release notes and change log

- crypto/crypto/src/test_utils.rs
- language/testing-infra/e2e-tests/src/account_universe/bad_transaction.rs
- language/testing-infra/e2e-tests/src/account_universe/rotate_key.rs
- language/testing-infra/e2e-tests/src/common_transactions.rs
This cherry-pick was triggerd by a request on #8550
> This updates the keygen generation for invalid auth key and key rotation transactions. Previously they would use the same deterministic seed which could lead to issues where in a previous transaction the account will have rotated to one key, and then the invalid auth key generation will generate that same key and assume that it is invalid.
> 
> This also fixes an issue where we weren't passing a type argument to the `EMPTY_SCRIPT` transaction even though it had a type argument. 
> 
> ### Testing
> 
> Tested against failing fuzz result and all tests passed. 
cc @tzakian
> Cherry-pick PR #8550 into release-1.3: [account universe] Update keygen for invalid auth key txns

- Cargo.lock
- language/tools/move-cli/Cargo.toml
(copied and re-organized from the discussion on Slack)
- Crate `move-stdlib` has a feature flag `testing`, which if present,
enables a few more Move VM native functions for debugging and testing.
- Crate `move-cli` depends on `move-stdlib` indirectly and it has a few
test cases that depends on the existence of these special native
functions. (e.g., `debug` functions)
- However, the crates that indirectly import `move-stdlib` for `move-cli`
(e.g., the `move-lang` crate) does not import `move-stdlib` with
the `testing` feature requested.
This PR is a temporary fix that explicitly import `move-stdlib` with
the `testing` feature flag set in the Cargo.toml file for `move-cli`.
Without this fix, `cargo test` under the `move-cli` will fail.
Quick fix and unblock testing
Yes
`cargo test` or …
> [move-cli] add explicit dependency to stdlib with testing feature

- language/move-prover/bytecode/src/access_path.rs
- language/move-prover/bytecode/src/access_path_trie.rs
- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/tests/read_write_set/bool_footprint.exp
- language/move-prover/bytecode/tests/read_write_set/borrow.exp
- language/move-prover/bytecode/tests/read_write_set/counter.exp
- language/move-prover/bytecode/tests/read_write_set/exists.exp
- language/move-prover/bytecode/tests/read_write_set/fields.exp
- language/move-prover/bytecode/tests/read_write_set/footprint.exp
- language/move-prover/bytecode/tests/read_write_set/functions.exp
- language/move-prover/bytecode/tests/read_write_set/multi_deps.exp
- language/move-prover/bytecode/tests/read_write_set/multi_deps.move
- language/move-prover/bytecode/tests/read_write_set/summary.exp
- language/move-prover/bytecode/tests/read_write_set/update_return.exp
- language/tools/move-cli/tests/testsuite/concretize_read_write_set/args.exp
- language/tools/move-cli/tests/testsuite/read_write_set/args.exp
Avoid "locals" part of a function summary for the read/write set analysis to contain redundant entries such as `Formal(0)/0x1::BoolFootprint::B/b: Formal(0)/0x1::BoolFootprint::B/b`
yes
Smoke tests updated accordingly
Closes #8585
> [move] [read/write set analysis] Prune read write state summary

- consensus/consensus-types/src/experimental/commit_decision.rs
- consensus/consensus-types/src/experimental/commit_vote.rs
- consensus/consensus-types/src/experimental/mod.rs
- consensus/consensus-types/src/lib.rs
- consensus/src/network_interface.rs
- testsuite/generate-format/tests/staged/consensus.yaml
Commit phase broadcasts commit proposals to seek agreement on the execution state.
Upon receiving a valid quorum of signatures on the same execution state, the nodes
will commit the execution result, and asynchronously broadcast a new commit
decision message containing the accumulated signatures to help slower nodes catch
up quickly. A node receiving a valid commit decision message does not have to wait
for commit proposals any more. It can directly commit the execution result.
Message handling is not included in this commit.
This is part of the decoupled-execution project.
Yes
(If this PR adds or changes functionality, please take some time to update or …
> [decoupled-execution] add new message types: CommitProposal and Committ Decision

- Cargo.lock
- scripts/fgi
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/k8s.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/backend/mod.rs
- testsuite/forge/src/interface/network.rs
- testsuite/forge/src/lib.rs
- testsuite/forge/src/main.rs
- testsuite/forge/src/report.rs
- testsuite/forge/src/runner.rs
- testsuite/forge/src/txn_emitter/mod.rs
This is the last piece of forge framework MVP, it introduces the ability for Forge to build up swarm on k8s cluster which is deployed by standard testnet deployment.
This PR includes the work:
- fgi script for end user to interactive with forge test framework, dispatching between different swarm types
- new forge pod template (The first two items are split to https://github.com/diem/diem/pull/8603 for more modifications by @rustielin, this pr rebased on latest changes)
- rust side k8s backend implementation
- test statistics report
**Test whole Forge by both swarm types (local, k8s)**
Local swarm test by passing --local-swarm arg
```
./scripts/fgi --local-swarm 
running 4 tests
Wait for startup attempt: 0 of 10 …
```
> [forge] k8s backend implementation

- json-rpc/types/src/views.rs
It was recently reported in https://github.com/diem/diem/issues/8643
that a client built from the release-1.2 branch failed to deserialize a
response from a server built from the release-1.3 branch with the
following error:
```
"unknown variant `treasury_compliance`, expected one of `unknown`, `child_vasp`, `parent_vasp`, `designated_dealer`"
```
Looking at the difference between the code in
`json-rpc/types/src/views.rs` for the two difference releases it looks
like the TreasuryCompliance Role didn't exist in the 1.2 release but
does in the 1.3 release. So the old client wouldn't be able to properly
understand, parse and interpret that role since the old client doesn't
know about it. Despite this the older client should still be able to
properly deserialize a response from a newer server. …
> jsonrpc-types: add default unknown variants to various enums

- language/tools/move-cli/tests/testsuite/concretize_read_write_set_smoke/args.exp
- language/tools/move-cli/tests/testsuite/concretize_read_write_set_smoke/args.txt
This flag had the unintended effect of forcing devs to update the expected value of the smoke test each time a module is added to/removed from the Diem Framework.
> [Move RW set tests] remove -v flag from smoke test

- mempool/src/shared_mempool/peer_manager.rs
This metric had the possibility of double decrementing, causing negative values and lots of confusion.
> [mempool] Prevent double decrements of upstream peers metric

- .github/workflows/ci-publish-base-image.yml
- .github/workflows/ci-test-complete.yml
- .github/workflows/ci-test.yml
- .github/workflows/ci-update-sccache.yml
- .github/workflows/docker-publish.yml
Allows for the creation of gh issues from flaky tests detected in a single auto branch run that succeeds and is committed to main/releases.
If a flake it reported there _is_ a problem in a test.
Yes
Already run in another branch.
https://github.com/diem/diem/runs/2955458669?check_suite_focus=true
Producing issues like:
https://github.com/diem/diem/issues/8671
https://github.com/diem/actions/pull/26
> [gha] use latest actions, enables gh issues for flaky tests detect in a single run.

- Cargo.lock
- docker/forge/Dockerfile
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/main.rs
Fetch root and TC keys from vault for each testnet within `forge` itself, rather than having to pass them in via arguments. This makes `forge` more portable (not relying on external tools or processes such as `fgi` to get the keys first), and also maintains a better test abstraction.
Also install `vault` in the forge docker image.
Yes
Build the image and run a a debug pod on my forge cluster. First, check that forge can use the keys fetched via the vault secure storage backend, programatically:
```
root@forge-debug-s4srv:/etc/forge# forge
running 4 tests
Local kube pod healthcheck passed
error: listen tcp 127.0.0.1:8001: bind: address already in use
test fund_account ... ok
test transfer_coins ... ok
test get_metadata ... ok
Will use 10 workers per endpoint with total 40 endpoint clients …
```
> [forge] init with cluster vault

- json-rpc/types/src/views.rs
This cherry-pick was triggerd by a request on #8646
> It was recently reported in https://github.com/diem/diem/issues/8643
> that a client built from the release-1.2 branch failed to deserialize a
> response from a server built from the release-1.3 branch with the
> following error:
> 
> ```
> "unknown variant `treasury_compliance`, expected one of `unknown`, `child_vasp`, `parent_vasp`, `designated_dealer`"
> ```
> 
> Looking at the difference between the code in
> `json-rpc/types/src/views.rs` for the two difference releases it looks
> like the TreasuryCompliance Role didn't exist in the 1.2 release but
> does in the 1.3 release. So the old client wouldn't be able to properly
> understand, parse and interpret that …
> Cherry-pick PR #8646 into release-1.3: jsonrpc-types: add default unknown variants to various enums

- .github/workflows/daily.yml
For a widely used crate, the output from cargo audit failure can be too long to fit in GHA (ex https://github.com/diem/diem/runs/3020018531?check_suite_focus=true)
CI
> [gha] limit cargo audit log

- mempool/src/shared_mempool/peer_manager.rs
This cherry-pick was triggerd by a request on #8676
> This metric had the possibility of double decrementing, causing negative values and lots of confusion.
cc @msmouse
> Cherry-pick PR #8676 into release-1.3: [mempool] Prevent double decrements of upstream peers metric

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/function_target_pipeline.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/interpreter/src/shared/variant.rs
Existing implementation takes a static string with the assumption that
all verification variants can be statically known. This is true as of
now but even in this case, it feels better to use an enum instead of raw
strings to match the verification invariants.
This commit is also up to support an incoming transformation which may
create a statically-unknown number of verification variants when
unrolling functions with type parameters instantiated.
Yes
CI
> [move-prover] make Verification variant taking a flavor enum

- language/bytecode-verifier/bytecode-verifier-tests/src/lib.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/support/mod.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/negative_stack_size_tests.rs
- language/move-binary-format/src/file_format.rs
`dummy_procedure_module` is only used by bytecode-verifier-tests. Place it in a test support module close to its only usages, in order to discourage it from being used elsewhere.
> [move] Extract bytecode-verifier test helper

- Cargo.lock
- language/bytecode-verifier/bytecode-verifier-tests/src/support/mod.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/constants_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/duplication_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/generic_ops_tests.rs
- language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
- language/bytecode-verifier/src/verifier.rs
- language/compiler/ir-to-bytecode/src/compiler.rs
- language/diem-tools/writeset-transaction-generator/Cargo.toml
- language/diem-tools/writeset-transaction-generator/src/release_flow/mod.rs
- language/diem-tools/writeset-transaction-generator/src/release_flow/unit_tests/release_tests.rs
- language/diem-tools/writeset-transaction-generator/src/release_flow/verify.rs
- language/move-binary-format/src/deserializer.rs
- language/move-binary-format/src/file_format.rs
- language/move-binary-format/src/proptest_types.rs
- language/move-model/src/lib.rs
- language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
- language/testing-infra/module-generation/src/generator.rs
- language/testing-infra/test-generation/src/abstract_state.rs
- language/testing-infra/test-generation/src/lib.rs
Delete `CompiledScript::freeze` and `CompiledModule::freeze` in favor of explicitly bounds-checking scripts and modules, as a follow-up on #8667.
> [move] Remove `Compiled{Script,Module}::freeze`

- sdk/client/src/blocking.rs
- sdk/client/src/client.rs
The existing timeout is probably a little aggressive, lets bump up the default to match what we have in client_proxy.rs.
> client: increase wait_for_transaction timeout

- Cargo.lock
- language/diem-tools/df-cli/Cargo.toml
- language/diem-tools/df-cli/src/main.rs
- language/tools/move-cli/src/lib.rs
This allows other crates (in particular `df-cli`) to extend `move-cli` with other subcommands
yes
/cc @sblackshear @tzakian
> [move-cli] Refactor move-cli to make it extensible

- config/src/config/consensus_config.rs
- consensus/src/counters.rs
- consensus/src/epoch_manager.rs
- consensus/src/experimental/commit_phase.rs
- consensus/src/experimental/execution_phase.rs
- consensus/src/experimental/tests/commit_phase_tests.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_fuzzing.rs
- consensus/src/round_manager_test.rs
This is the third (and the last) part of integrating decoupled execution.
We add the back pressure to hold back the consensus progress when the execution
progress is falling behind much.
* Why we must have it for V1 …
> [decoupled-execution] Integration Part 3 - Back Pressure and Final Integration

- .github/actions/slack-file/message_file_to_slack.sh
If the file is too large slack rejects the message.   Truncate the message to 50 lines.   If you're reading more than that, just click the link.
Yes
CI - currently running: https://github.com/diem/diem/runs/3165951975?check_suite_focus=true
None.
> [gha] work around very large logs sent to slack by prover daily tests.

- language/move-vm/runtime/src/loader.rs
- language/move-vm/runtime/src/runtime.rs
As promised in #8811, this PR attempts to make the code loading
logic more maintainable and better engineered. This PR is follow-up
and clean-up of #8809 with functions renamed  and code better
documented. The solution stays the same.
Perhaps a better solution is to use a typestate transition system
to model different steps in the module verification process: i.e.,
`BytecodeVerified`, `LinkingVerified`, and `FullyVerified` etc. 
Unofficially modeled,
- `deserialize_and_verify_module -> BytecodeVerified`
The module deserializes and passes the all bytecode verifier
checks that do not require information from other modules.
- `verify_module_dependencies_* -> LinkingVerified`
Everything in `BytecodeVerified` + the module links against
all its immediate dependencies.
- `load_module_internal -> …
> [move-vm] improve the code loading logic

- .github/workflows/dep-update-review.yml
If a pull request modifies any `Cargo.lock` or `Cargo.toml` files,  a CI action will post a summary review report of the update(s) in the PR. 
Note that if the report exceeds the max. character allowed in a GitHub comment, we only print a warning comment to run `depdive` locally. My estimate is, the allowed length should cover 7-8 dep updates. 
yes
1. Tested with a test update in this PR on `tower`. See comment by `libra-action` below.
2. Tested without any dep change. Nothing happens as intended. The CI action doesn't even kick off as `Cargo.lock` is not in the diff. 
3. tested with downgrading `hakari`. The Ci action kicks off but returns a blank output and therefore, does not post any comment as there is no `update` in version. 
4. Tried full `cargo update`. The test report is in this …
> [ci] add ci action to post depdive update report on PR

- language/diem-framework/modules/DiemAccount.move
- language/diem-framework/modules/doc/DiemAccount.md
- language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
- language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
- language/move-prover/bytecode/src/verification_analysis_v2.rs
An inconsistency was discovered in PR #8668, which first used the new feature
to disable invariants in the the Diem Framework.  Fixing that inconsistency in
this PR resulted in Prover not being able to prove some current specifications.
Fixing that will take a bit more time, so, to get a consistent and working
system, I have weakened and removed some invariants.
Major changes:
1. Removed improper assumptions of disabled invariants
2. Fixed bug where it was only using memory directly modified by a function,
instead of indirectly modified.
3. Added code to compute the set of disabled invariants
4. Removed some "pragma disable"s from DiemAccount.move, changed
some <==> to ==> and commented out a few invariants.
5. Added some more debug print functions.
(Write your motivation for proposed …
> [move-prover] Fix an inconsistency in global invariant processing

- Cargo.lock
- language/compiler/Cargo.toml
- language/compiler/bytecode-source-map/Cargo.toml
- language/compiler/bytecode-source-map/src/utils.rs
- language/compiler/ir-to-bytecode/Cargo.toml
- language/compiler/ir-to-bytecode/src/parser.rs
- language/compiler/ir-to-bytecode/syntax/Cargo.toml
- language/compiler/ir-to-bytecode/syntax/src/lexer.rs
- language/compiler/ir-to-bytecode/syntax/src/syntax.rs
- language/compiler/src/lib.rs
- language/compiler/src/main.rs
- language/compiler/src/unit_tests/testutils.rs
- language/compiler/src/util.rs
- language/ir-testsuite/Cargo.toml
- language/ir-testsuite/tests/testsuite.rs
- language/move-ir/types/src/location.rs
- language/move-lang/Cargo.toml
- language/move-lang/functional-tests/tests/functional_testsuite.rs
- language/move-lang/src/diagnostics/mod.rs
- language/move-lang/src/expansion/byte_string.rs
- language/move-lang/src/parser/ast.rs
- language/move-lang/src/parser/comments.rs
- language/move-lang/src/parser/lexer.rs
- language/move-lang/src/parser/mod.rs
- language/move-lang/src/parser/syntax.rs
- language/move-model/Cargo.toml
- language/move-model/src/lib.rs
- language/move-model/src/model.rs
- testsuite/cli/Cargo.toml
- testsuite/diem-fuzzer/lsan_suppressions.txt
Use the newly added `move_symbol_pool` module from #8782 to represent file names in Move locations. This allows us to eliminate the use of "leak string" functions, and re-enable libc leak detection in LeakSanitizer.
> [move] `Loc::file` is a `move_symbol_pool::Symbol`

- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/bytecode/src/function_target_pipeline.rs
- language/move-prover/bytecode/src/inconsistency_check.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/src/pipeline_factory.rs
- language/move-prover/bytecode/src/spec_instrumentation.rs
The current inconsistency check instrumentation happens before the
global invariant instrumentation pass, with the assumption that there
will be no new verification targets created after the inconsistency
check instrumentation.
This is OK until recently we start to create function instantiations
according to the resource types touched by global invariants. Therefore,
a function may have the following variants:
- baseline
- verification(regular)
- verification(instantiation_1)
- ...
- verification(instantiation_n)
The current way of adding inconsistency invariant complicates the story.
- baseline
- verification(regular)
- + verification(inconsistency)
- verification(instantiation_1) --> overriden to inconsistency check of instantiation_1
- ...
- verification(instantiation_n) --> overriden …
> [move-prover] make inconsistency check instrumentation a separate pass

- Cargo.lock
- language/move-symbol-pool/Cargo.toml
- language/move-symbol-pool/src/lib.rs
- language/move-symbol-pool/src/pool.rs
- language/move-symbol-pool/src/symbol.rs
Internally, a `Symbol` behaves like a pointer. Naively serializing it as an address in the pool is incorrect, as it may be serialized by one process with its own pool, and deserialized by another process with a different pool. Instead, serialize and deserialize the string it represents.
> [move] Fix `Symbol` serialization

- language/move-prover/bytecode/src/inconsistency_check.rs
- language/move-prover/bytecode/src/options.rs
- language/move-prover/src/cli.rs
- language/move-prover/tests/sources/functional/inconsistency.exp
- language/move-prover/tests/sources/functional/inconsistency.move
- language/move-prover/tests/sources/functional/inconsistency.no_opaque_exp
- language/move-prover/tests/sources/functional/inconsistency_always_abort.exp
- language/move-prover/tests/sources/functional/inconsistency_always_abort.move
The motivation for this change is the inconsistency issue reported in
PR #8851, where `TransactionFee::burn_fees<CoinType>` runs into an
unconditional abort case when and only when `CoinType` is instantiated
with `XDX`.
This is subsequently flagged by the inconsistency checker as an
violation. Where in this case, the inconsistency checker flags the
case not because we are not proving an `assert false;`, but because the
verification finishes successfully when the inconsistency checker
expects it to fail.
The reason verification finishes successfully is because for a function
that unconditionally abort on all arguments (and hence, never returns),
the `assert false;` verification condition is either not instrumented
or not reachable.
The fix, is to not only instrument `assert false;` before …
> [move-prover] add a flag to toggle whether unconditional abort is inconsistency

- language/diem-framework/modules/DesignatedDealer.move
- language/diem-framework/modules/DiemAccount.move
- language/diem-framework/modules/DiemConfig.move
- language/diem-framework/modules/doc/DesignatedDealer.md
- language/diem-framework/modules/doc/DiemAccount.md
- language/diem-framework/modules/doc/DiemConfig.md
- language/diem-framework/releases/artifacts/current/docs/modules/DesignatedDealer.md
- language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
- language/diem-framework/releases/artifacts/current/docs/modules/DiemConfig.md
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/options.rs
- language/move-prover/src/cli.rs
- language/move-prover/tests/sources/functional/ModifiesErrorTest.move
- language/move-prover/tests/sources/functional/ModifiesErrorTest.no_opaque_exp
- language/move-prover/tests/sources/functional/ModifiesTypeTest.move
- language/move-prover/tests/sources/functional/ModifiesTypeTest.no_opaque_exp
- language/move-prover/tests/sources/functional/emits.cvc4_exp
- language/move-prover/tests/sources/functional/emits.move
- language/move-prover/tests/sources/functional/emits.no_opaque_exp
- language/move-prover/tests/sources/functional/global_invariants.move
- language/move-prover/tests/sources/functional/global_invariants.no_opaque_exp
- language/move-prover/tests/sources/functional/inconsistency.no_opaque_exp
- language/move-prover/tests/sources/functional/resources.move
- language/move-prover/tests/sources/functional/resources.no_opaque_exp
- language/move-prover/tests/sources/functional/script_incorrect.move
- language/move-prover/tests/sources/functional/script_incorrect.no_opaque_exp
Currently, the option `--ignore-pragma-opaque-when-possible` applies to
internal functions only, i.e., functions whose callers are all known at
the time of compilation.
This commit extends the scope to *all* functions, including public
functions whose callers may be unknown at verification time. The old
behavior, i.e., internal functions only, can be enabled with a new
option, `--ignore-pragma-opaque-internal-only`.
This commit also includes some better engineering content by isolating
the tweaking process from the individual *def_ana_* function into a
central location.
Towards spec elimination
Yes
- CI
- test cases are updated
> [move-prover] add the option to ignore opaque on public fun as well

- scripts/weekly-dep-report.sh
`weekly-dep-report.sh` in `weekly.yml` sometimes posts empty message. The shell script when run successfully should echo something at least. However, [failed GHA in the past](https://github.com/diem/diem/runs/3031015500?check_suite_focus=true) shows the script is successfully run but with no output. Adding two lines in the beginning to ensure the script is not early dying next time the the action fails to produce any output. 
Yes
The change is made to help in debugging next time the corresponding gha fails.
> adding a line in the beginning to help in debugging when gha fails

- language/move-model/src/ast.rs
- language/move-model/src/builder/module_builder.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/tests/sources/functional/choice.cvc4_exp
- language/move-prover/tests/sources/functional/choice.exp
- language/move-prover/tests/sources/functional/choice.move
The implementation of the choose operator attempts to reuse the generated uninterpreted function for the choice if the same source level choice is duplicated. This is needed to ensure that the choice result is the same if the expression is cloned, which happens e.g. if conditions of opaque functions are inserted at caller side, or if choices appear in schemas.
Consider
```
schema S { ensures result == choose i: int: i > 0; }
spec f { include S; include S; }
```
We require that the choice delivers the same value in both inclusions of `S` (otherwise we would create an inconsistency). While the logic for this was there, it was buggy before this PR.
The bug was that temporaries or variables used in the choice may substitute to different values in the insertion context. This PR fixes this bug …
> [move-prover] Fixes a bug in the `choose` operator.

- language/compiler/ir-to-bytecode/src/parser.rs
- language/compiler/ir-to-bytecode/syntax/src/lexer.rs
Rather than copy the source file into a string with its comments removed, skip over the comments while advancing the lexer.
~~Also, the lexer now verifies the source character set as it goes. Instead of iterating over each character before lexing and checking that it is part of the valid set, the lexer's default match arm for `ParseError::InvalidToken` catches any characters not explicitly accounted for.~~
~~The combination of these two changes means that commented-out Move IR may contain any characters, including emoji and bidirectional text. This isn't necessarily a "feature" -- the code is just less complex and more performant this way, and the lexer ought not care about commented-out text anyway.~~
Submitted on top of #8845 and #8860, in case you'd like to review those first.
> [move] Lex Move IR source buffers in-place

- consensus/consensus-types/src/executed_block.rs
- consensus/src/state_computer.rs
The bug is that we expect a compute result for every transaction in the block,
without considering the fact that if a block is suffix of a reconfiguration block, its
compute result is carried from its parent and should be viewed as empty.
ENABLE_FAILPOINTS=1 ./scripts/cti --pr 8879 --run reconfiguration
Reconfiguration: total epoch: 101 finished in 131 seconds
* Why we must have it for V1 …
> [reconfiguration] fix bug caused by #8484

- language/diem-framework/modules/PaymentScripts.move
- language/diem-framework/modules/doc/PaymentScripts.md
- language/diem-framework/releases/artifacts/current/docs/modules/PaymentScripts.md
- language/diem-framework/releases/artifacts/current/docs/scripts/script_documentation.md
- language/diem-framework/script_documentation/script_documentation.md
- language/move-model/src/ty.rs
- language/move-prover/boogie-backend/src/boogie_helpers.rs
- language/move-prover/boogie-backend/src/bytecode_translator.rs
- language/move-prover/boogie-backend/src/prelude/native.bpl
- language/move-prover/boogie-backend/src/prelude/prelude.bpl
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/tests/sources/functional/is_signer.cvc4_exp
- language/move-prover/tests/sources/functional/is_signer.exp
- language/move-prover/tests/sources/functional/is_signer.move
- language/move-prover/tests/sources/functional/is_signer.no_opaque_exp
- language/move-prover/tests/sources/functional/script_incorrect.no_opaque_exp
- language/move-stdlib/docs/Signer.md
- language/move-stdlib/modules/Signer.move
- Correctly re-implemented the Boogie encoding of `signer`
- this revealed a hidden bug in Prover. See the bug report: https://github.com/diem/diem/issues/8854.
- Added `is_signer` to the Signer module as a native spec function
- Added various test cases (see .../functional/is_signer.move)
- Next steps:
- Rewrite the role-based access control specs in the Diem Framework
- Extend it to work for the cap-based access control specs
- Specify the access control libraries like Vault
To implement `is_signer` in Prover
yes
cargo test
> [move-prover] Implemented is_signer in Prover

- consensus/consensus-types/src/executed_block.rs
- consensus/src/state_computer.rs
This cherry-pick was triggerd by a request on #8879
> 
> 
> 
> The bug is that we expect a compute result for every transaction in the block,
> without considering the fact that if a block is suffix of a reconfiguration block, its
> compute result is carried from its parent and should be viewed as empty.
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
> 
> (Write your answer here.)
> 
> ## Test Plan
> 
> ENABLE_FAILPOINTS=1 ./scripts/cti --pr 8879 --run reconfiguration
> 
> Reconfiguration: total epoch: 101 finished in 131 seconds
> 
> 
> (If this PR adds or changes functionality, please take …
> Cherry-pick PR #8879 into release-1.4: [reconfiguration] fix bug caused by #8484

- scripts/weekly-dep-report.sh
Add `set -xv` in `weekly-dep-report.sh` to enable debugging when it fails. The debug output is sent to `stderr` so the slack message is not modified by this.
Also forced git checkout as it may be the most probable step to face a failure if crag-guppy or any other command is generating new files. 
Yes
The changes are here to test.
> [ci] Add debugging option in weekly-dep-report

- Cargo.lock
- common/workspace-hack/Cargo.toml
There are two new rustics in hyper 0.14.4: [RUSTSEC-2021-0079](https://rustsec.org/advisories/RUSTSEC-2021-0079), [RUSTSEC-2021-0078](https://rustsec.org/advisories/RUSTSEC-2021-0078).
Yes
Existing tests
> [deps] update hyper to fix two rustsecs

- Cargo.lock
- config/management/genesis/src/config_builder.rs
- config/management/genesis/src/swarm_config.rs
- config/management/genesis/src/validator_builder.rs
- diem-node/Cargo.toml
- diem-node/src/lib.rs
- diem-node/src/main.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/factory.rs
- testsuite/forge/src/runner.rs
Allow passing in an rng seed when running in --test mode. This is useful if you want to seed the rng used for the creation of the root and treasury keys during genesis.
Specifically you can now do the following:
```
$ cargo run --bin diem-node -- --test --seed 0000000000000000000000000000000000000000000000000000000000000000
```
Where the seed is a hex encoded `[u8; 32]` (so 64 hex characters)
> diem-node: enable seeding the rng used when running in test mode

- .github/workflows/ci-post-land.yml
- .github/workflows/ci-test.yml
Eliminate the possibility of pre-landed sccache items from effecting coverage reports/post land compilations.
Yes
gha-test-1 branch execution.   
https://github.com/diem/diem/runs/3293494941?check_suite_focus=true
None
> [CI] move sccache update to post-land

- language/move-model/src/ast.rs
- language/move-model/src/builder/exp_translator.rs
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/model.rs
- language/move-model/src/ty.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/src/local_mono.rs
- language/move-prover/bytecode/src/local_mono_compat.rs
- language/move-prover/bytecode/src/pipeline_factory.rs
- language/move-prover/tests/sources/functional/generic_invariants.exp
- language/move-prover/tests/sources/functional/generic_invariants.move
- language/move-prover/tests/sources/functional/invariants_with_generics.exp
- language/move-prover/tests/sources/functional/invariants_with_generics.move
- language/move-prover/tests/sources/regression/mono_after_global_invariant.exp
- language/move-prover/tests/sources/regression/mono_after_global_invariant.move
This PR completes the implementation of the generic invariant processing pipeline
on the prover side. And there are a series of steps and decisions taken. Since these
decisions are all inter-connected, I think it might be good to group them all in this
single PR.
The major items are:
- Step 0: allow Move compiler to recognize the `invariant<T>` syntax [not in this PR]
- Step 1: allow `ExpTranslator` to recognize generics in expressions
- Step 2: `local` monomorphization to remove generic types in an expression
- Step 3: compatibility layer while we port everything.
The rest of the PR description is on the details of these steps.
**Step 0: allow Move compiler to recognize the `invariant<T>` syntax**
This is implemented in PR #8771
**Step 1: allow `ExpTranslator` to recognize generics in …
> [move-prover] generic invariant processing pipeline

- language/move-model/src/builder/module_builder.rs
- language/move-prover/tests/sources/functional/let.move
The change is simple, but finding the issue was not.
Closes #8854
Bug fix
Yes
Added test
NA
> [move-prover] Fixes a bug with shadowing of let-bound names in schemas

- .github/workflows/ci-post-land.yml
Cost savings measure -- remove osx sscache job from ci-post-land due to limited osx contributors
Yes, I have.
Change to github actions, so no good way to test without landing PR.  Current bug countermeasures including crossing my fingers, and throwing salt over my shoulder.  And I just knocked on wood.  Well.  Whatever you consider an ikea tabletop to be made of.
Standalone.
Applies to github actions across entire repo.
> Disable the OSX sscache job as cost savings

- .github/workflows/ci-post-land.yml
Fix broken sccache updating job.
Yes
Forced a run here:
https://github.com/diem/diem/runs/3324032586?check_suite_focus=true
None
> [gha] fix docker mount points

- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/cargo.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/forge/src/runner.rs
- testsuite/forge/src/txn_emitter/mod.rs
This PR does the following:
* One test failure, prints out where logs for the nodes are located
* prints out the stderr output of `cargo build` when building diem-node fails
* Displays the versions supported by the backend on startup, prior to running tests
> forge: improve debugging experience on test failures

- language/move-model/src/lib.rs
- language/move-prover/abigen/tests/sources/bad_script.abi
- language/move-prover/abigen/tests/sources/bad_script.move
This issue is identified by @junkil-park in #8970. The fix is easy but
finding the issue is much harder.
The model building seems to terminate at a state where an incomplete
`GlobalEnv` has warnings only. But the prover does not know that the
`GlobalEnv` is incomplete, so it produces no bytecode subsequently.
This commit allows the warning-only diagnostics to be added to the
`GlobalEnv` first and also allows the model building to continue from
there.
Allows prover to continue proving when there are compiler warnings only.
Yes
CI
#8971 is an alternative solution that stops the prover on compiler warnings
out of precaution.
> [move-model] allow the spec model to be built when compiler has warnings

- Cargo.lock
- config/management/genesis/src/config_builder.rs
- config/management/genesis/src/swarm_config.rs
- config/management/genesis/src/validator_builder.rs
- diem-node/Cargo.toml
- diem-node/src/lib.rs
- diem-node/src/main.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/factory.rs
- testsuite/forge/src/runner.rs
This cherry-pick was triggerd by a request on #8916
> Allow passing in an rng seed when running in --test mode. This is useful if you want to seed the rng used for the creation of the root and treasury keys during genesis.
> 
> Specifically you can now do the following:
> ```
> $ cargo run --bin diem-node -- --test --seed 0000000000000000000000000000000000000000000000000000000000000000
> ```
> 
> Where the seed is a hex encoded `[u8; 32]` (so 64 hex characters)
cc @ankushagarwal
> Cherry-pick PR #8916 into release-1.4: diem-node: enable seeding the rng used when running in test mode

- types/src/transaction/metadata.rs
There are several fields in metadata that are not public fields, so partners can't write any code that makes use of it. Changing to pub. Otherwise clients who depend on diem/diem for json rpc types won’t be able to use some of the types and will fail to parse some json rpc responses from the chain
Yes
Existing tests
> Change reference ID to pub

- language/transaction-builder/generator/src/common.rs
- language/transaction-builder/generator/src/cpp.rs
- language/transaction-builder/generator/src/rust.rs
This adds support for `vector<vector<u8>>` arguments to the transaction script builders for both Rust and C++. Support for other languages is in progress, however support for these will need to be added in after changes to the `serde-generate` crate to support nested byte vectors is landed.
Note that support for `vector<vector<u8>>` arguments to transaction scripts is explicitly _not_ supported in this PR.
> [transaction-builder] Add support for `vector<vector<u8>>` in script functions

- Cargo.lock
- common/workspace-hack/Cargo.toml
This cherry-pick was triggerd by a request on #8910
> 
> 
> 
> There are two new rustics in hyper 0.14.4: [RUSTSEC-2021-0079](https://rustsec.org/advisories/RUSTSEC-2021-0079), [RUSTSEC-2021-0078](https://rustsec.org/advisories/RUSTSEC-2021-0078).
> 
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
> 
> Yes
> 
> ## Test Plan
> 
> Existing tests
cc @sausagee
> Cherry-pick PR #8910 into release-1.4: [deps] update hyper to fix two rustsecs

- Cargo.lock
- common/workspace-hack/Cargo.toml
This is a cherry-pick of #8910. 
> 
> 
> 
> There are two new rustics in hyper 0.14.4: [RUSTSEC-2021-0079](https://rustsec.org/advisories/RUSTSEC-2021-0079), [RUSTSEC-2021-0078](https://rustsec.org/advisories/RUSTSEC-2021-0078).
> 
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
> 
> Yes
> 
> ## Test Plan
> 
> Existing tests
> Cherry-pick PR #8910 into release-1.3: [deps] update hyper to fix two rustsecs

- execution/executor-benchmark/src/lib.rs
This is what reported as "commit time" minus the cost of communication between the benchmark and the storage service.
y
> [executor-benchmark] report time in DB commission

- language/diem-framework/modules/NetworkIdentity.move
- language/diem-framework/modules/doc/NetworkIdentity.md
- language/diem-framework/releases/artifacts/current/docs/modules/NetworkIdentity.md
The element uniqueness constraint on the
`NetworkIdentityChangeNotification` is causing a timeout in CI when the
prover runs with inconsistency check, and this is likely caused by a
bufferfly effect which we are still debugging. In the meanwhile,
turn-off the offending spec and make sure the daily CI is happy.
NOTE: this is not a critical spec and might be a good example to
investigate whether manually supplying some triggers will help with
the quantification. The other element uniqueness spec, i.e., the one
in `struct NetworkIdentity`, is a critical one and shall never be disabled.
Fix timeout
Yes
CI
> [diem-framework] remove the spec in NetworkIdentity causing timeout

- Cargo.lock
- common/workspace-hack/Cargo.toml
> update crossbeam-deque to v0.8.1 to fix RUSTSEC-2021-0093

- Cargo.lock
- scripts/fgi/kube.py
- scripts/fgi/run
- testsuite/forge-cli/src/main.rs
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
Add the ability for Forge to resize its k8s backend clusters' worker nodegroups. Before, we could only uninstall helm releases, but would always have the worker nodes running. This saves us a lot of $$$.
Uses the `rusoto` and `rusoto_eks` crates to interact with EKS and make the API calls. An additional dep `hyper-proxy` is introduced to make things work with an http proxy.
Refactoring:
* `remove_validator`/`remove_testnet` now use `remove_helm_release`
* `k8s_client` -> `create_k8s_client`
* Separate `clean-up` subcommand for forge CLI into `clean-up` (to 0 validators) and `resize` (reset to N validators)
NOTE: for now, the cluster does not scale down/go into idle state after test run, as that logic seems to have been removed in a previous PR.
Run the operator …
> [forge] nodegroup resize

- language/compiler/bytecode-source-map/src/source_map.rs
- language/compiler/bytecode-source-map/tests/dummies.rs
A change to use `BinaryIndexedView` in `SourceMapping` (#8629 and #8655) resulted in a panic when attempting to create "dummy" source mappings for Move bytecode representing scripts. Fix the issue by preventing the mapping from attempting to access the script's name and address, which are only available on modules.
In addition, add a regression test for "dummy" source mappings.
This fixes an panic in the `disassembler` when disassembling script bytecode.
> [move] Fix empty source mappings for scripts

- Cargo.lock
- Cargo.toml
- consensus/Cargo.toml
- consensus/src/txn_manager.rs
- diem-node/Cargo.toml
- diem-node/src/lib.rs
- mempool/Cargo.toml
- mempool/src/counters.rs
- mempool/src/lib.rs
- mempool/src/logging.rs
- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/runtime.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/shared_mempool/types.rs
- mempool/src/tests/mocks.rs
- mempool/src/tests/node.rs
- mempool/src/tests/shared_mempool_test.rs
- state-sync/inter-component/mempool-notifications/Cargo.toml
- state-sync/inter-component/mempool-notifications/src/lib.rs
- state-sync/state-sync-v1/Cargo.toml
- state-sync/state-sync-v1/src/bootstrapper.rs
- state-sync/state-sync-v1/src/coordinator.rs
- state-sync/state-sync-v1/src/counters.rs
- state-sync/state-sync-v1/src/error.rs
- state-sync/state-sync-v1/src/fuzzing.rs
- state-sync/state-sync-v1/src/shared_components.rs
- state-sync/state-sync-v1/tests/test_harness.rs
Today, state sync is responsible for notifying mempool whenever new transactions are committed. However, the interface between the two components is very messy, e.g., the code leaks implementation details between the components and forces a very tight coupling. This makes it difficult to update (or swap out) component implementations.
To address this, the PR introduces an explicit interface and set of components between state sync and mempool:
- `MempoolNotificationSender` is the interface allowing state sync to send notifications to mempool (`MempoolNotifier` is the component that implements this interface).
- ` MempoolNotificationListener` is the component that mempool uses to listen for notifications and respond accordingly.
This structure avoids leaking implementation details (e.g., …
> [State Sync] Add MempoolNotifier interface and implementation.

- mempool/src/tests/shared_mempool_test.rs
- state-sync/inter-component/mempool-notifications/src/lib.rs
- state-sync/state-sync-v1/src/coordinator.rs
This (mini) PR offers two small cleanups for the newly added MempoolNotifier (https://github.com/diem/diem/pull/9006), each in their own commit:
1. First, remove the redundant `Result` wrapper when the MempoolNotificationListener acks a commit notification. The result is not used.
2. Second, it removes the need for mutability when methods of the MempoolNotifierSender are invoked. Mutability is also not required.
Yes.
Existing tests cover this.
> [State Sync] Small cleanups to MempoolNotifier.

- language/move-prover/bytecode/src/verification_analysis.rs
Two improvements are made in the new verification analysis pass:
- [move-prover] only verify functions that directly modifies a target invariant
The prior behavior is to verify functions that directly accesses a
target invariant, which unnecessarily leaves many functions to be marked
as verified.
NOTE: only memory modifications cause global invariants to be asserted;
memory accesses without modification leads to assumption of global invariants
only, but not assertions.
- [move-prover] improve error reporting on invariant suspension pramgas
The prior errors are too verbose.
Performance and error reporting
Yes
- CI
- This new pass is not turned on as of now. It will be made as default in a later PR.
> [move-prover] minor improvements to the verification analysis pass

- language/move-model/src/ty.rs
This algorithm deals with finding a complete set of instantiation
combinations for all type parameters when unifying two types.
// problem definition
The algorithm is encapsulated in `struct TypeInstantiationDerivation`
and is not conceptually hard to understand:
Suppose we aim to unify `T1 [X0, X1, ..., Xm]` vs `T2 [Y0, Y1, ..., Yn]`,
where `T1` and `T2` are types while `X`s and `Y`s are type parameters
that show up in `T1` and `T2`, respectively.
We want to find all instantiations to `<X0, X1, ..., Xm>` such that
for each instantiation `(x0, x1, ..., xm)`, there exists a valid
instantiation `(y0, y1, ..., yn)` which makes `T1` and `T2` equivelant,
i.e., `T1<x0, x1, ..., xm> == T2<y0, y1, ..., yn>`.
We put all these instantiation in a set denoted as `|(x0, x1, ..., xm)|`
and this …
> [move-prover] algorithm for progressive instantiation

- language/move-prover/src/lib.rs
Previous dumping location is at the first Move source location, which
may pollute the source directories. Furthermore, if we pass a directory
as the first source location, the process will panic.
This commit changes the default output location for `--dump-bytecode`
to the parent directory of the `output.bpl` file, and format ihe
bytecode dumps with `bytecode_{step_number}_{step_name}.bytecode`.
UX
Yes
- CI
- `cargo run -p move-prover -- <dir-name>/<file-name>.move --dump-bytecode`. Note that the bytecode dumps are generated at the current work directory instead of under `<dir-name>`.
> [move-prover] dump bytecode and result in output dir

- language/move-prover/bytecode/src/global_invariant_analysis.rs
- language/move-prover/bytecode/src/global_invariant_instrumentation.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/src/options.rs
- language/move-prover/src/cli.rs
An instrumentation pass that consumes the information produced by the
global invariant analysis pass and instrument the global invariants into
the function.
The instrumenter supports two mode of operations, depending on whether
the prover backend supports monomorphization or not:
1) With the option `--boogie-poly`, the instrumenter will instrument
*instantiated* invariants in the *generic* function (and the generic
instance is the only function instance).
2) Without the `--boogie-poly` option, the instrumenter will instrument
*instantiated* invariants *per each instantiation* of a generic
function (this is the traditional workflow). And this means that a
function will have multiple instances for verification.
This is not exactly the plan we had before (and does not clearly adhere
to the …
> [move-prover] an instrumentation pass for the global invariants

- docker/ci/github/Dockerfile
- docker/client/Dockerfile
- docker/cluster-test/Dockerfile
- docker/faucet/Dockerfile
- docker/forge/Dockerfile
- docker/init/Dockerfile
- docker/safety-rules/Dockerfile
- docker/tools/Dockerfile
Update debian base image.  This lumps all 7 outstanding dependabot PRs #9083 ~ #9090.
CI + canary
> [docker] update base image to debian:buster-20210902

- .github/actions/build-teardown/action.yml
- .github/workflows/ci-test.yml
Use https://github.com/Swatinem/rust-cache instead of https://github.com/actions/cache for caching of dependencies.
Here are some of the job performance wins
| Job  | Original | New | Speed Up % |
| ------------- | - | ------------- | - |
| lint | 5m 29s | 4m 47s | 18.2% |
| e2e-test-0 | 37m 12s | 28m 32s | 30.0% | 
| e2e-test-1 | 35m 33s | 26m 51s | 32.4% |
| crypto-unit-test | 10m 35s | 4m 31s | 134.3% |
> ci: use Swatinem/rust-cache for caching dependencies

- network/src/peer_manager/mod.rs
- network/src/peer_manager/tests.rs
- network/src/peer_manager/transport.rs
While I was looking through code to integrate NetworkInterface into PeerManager, I was getting a little confused on direction (Notification vs Request), so I've added direction to names of functions, and did a little cleanup in the `TransportManager` to hopefully make it mostly straightforward.
Yes
No functional change, unit tests should cover it.
> Refactor TransportManager to better indicate direction & have more comments / code reuse

- docker/client/Dockerfile
- docker/cluster-test/Dockerfile
- docker/forge/Dockerfile
- docker/init/Dockerfile
- docker/safety-rules/Dockerfile
- docker/tools/Dockerfile
- docker/validator/Dockerfile
#9112 missed updating the validator's base image (#9084 was still open) and resulted DLC misses in build (ex https://github.com/diem/diem/runs/3551074624?check_suite_focus=true).  This PR includes the missed update.
Additionally, specify base image only once across all Dockerfiles following the facuet's example to reduce edits in future updates.
CI + canary (https://github.com/diem/diem/runs/3551145597?check_suite_focus=true verified DLC miss is fixed.)
> [docker] fix up base image for DLC

- json-rpc/src/fuzzing.rs
- json-rpc/src/tests/utils.rs
Continuous fuzzing discovered a panic in the json-rpc fuzzer where one of the fuzzers managed to discover `get_accumulator_consistency_proof` and called it. The fuzzer, however, uses a MockDB rather than a real DiemDB. The MockDB didn't have `get_accumulator_consistency_proof` implemented and so the fuzz test panicked with `unimplemented!()`. This means the fuzz panic is a false positive, but something we should fix nonetheless so it can discover more useful stuff.
To fix the problem, this PR back-fills all of the missing DB methods called by the json-rpc service with dummy implementations so the fuzzer won't panic if it discovers other methods. We also add the rest of the json-rpc methods (except `get_resources`) to the `test_method_fuzzer` test so we can surface these `unimplemented!()` …
> json-rpc: implement missing MockDB methods to fix fuzzer

- network/src/protocols/wire/handshake/v1/mod.rs
We aren't using Cbor :).  Should only affect logging
> [network] Fix JSON consensus protocol name

- consensus/src/experimental/buffer_item.rs
- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/execution_phase.rs
- consensus/src/experimental/signing_phase.rs
1. change the semantic meaning of the roots
a) previously they mean the last processed item, where we will need a sentinel node at the beginning
b) now they point to the first unprocessed item.
2. add signing phase logic to buffer manager
3. add aggregating phase logic to buffer manager
4. remove aggregation root --- now when a prefix of items are ready to persist, we dequeue them and push them to the persisting phase. There will not be any retry for persisting phase (since we panick at the block store level in the previous implementations).
(If this PR adds or changes functionality, …
> [decoupled-execution] add signing / aggregating logic

- Cargo.lock
- common/channel/src/diem_channel.rs
- state-sync/inter-component/consensus-notifications/Cargo.toml
- state-sync/inter-component/consensus-notifications/src/lib.rs
- state-sync/inter-component/event-notifications/Cargo.toml
- state-sync/inter-component/event-notifications/src/lib.rs
- state-sync/inter-component/event-notifications/src/tests.rs
- state-sync/inter-component/mempool-notifications/Cargo.toml
- state-sync/inter-component/mempool-notifications/src/lib.rs
- state-sync/state-sync-v1/Cargo.toml
- state-sync/state-sync-v1/src/coordinator.rs
- state-sync/state-sync-v1/src/executor_proxy.rs
- state-sync/state-sync-v1/tests/test_harness.rs
This PR updates all state sync code to utilize the [claim](https://crates.io/crates/claim) crate for better assertion support. While I'm generally reluctant of adding new crate dependencies to code, the claim crate provides much nicer error messages on assertion failures and avoids situations where assertion failures produce unhelpful outputs (e.g., see here: https://github.com/diem/diem/issues/9062). Instead, using claim, we now get error messages like:
Failure on `assert_matches!`:
```
thread 'coordinator::tests::test_new_and_lost_peers' panicked at 'assertion failed, expression does not match any of the given variants.
expression: Ok(())
variants: Err(Error::InvalidStateSyncPeer(..))', state-sync/state-sync-v1/src/coordinator.rs:1978:9
```
Failure on `assert_ok!`:
```
thread …
```
> [State Sync] Use the claim crate for better test assertions

- language/move-prover/bytecode/src/verification_analysis.rs
- language/move-prover/tests/sources/functional/unused_global_invariant.exp
- language/move-prover/tests/sources/functional/unused_global_invariant.move
If the prover finds that a global invariant is not **checked**
in any function, throw a warning for that invariant.
The the new `unused_global_invariant.move` test case for the effect of
this checking.
This fixes #9167.
This warning is good to have and helps filter out unused specs.
Yes
CI, new test cases added
> [move-prover] warn on unused global invariants

- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/execution_phase.rs
- consensus/src/experimental/persisting_phase.rs
- consensus/src/experimental/pipeline_phase.rs
- consensus/src/experimental/tests/execution_phase_tests.rs
also removed the response from ther persisting phase (assuming state_computer's commit function handles the error by panics)
* What workarounds and alternative we have if …
> [decoupled-execution] buffer manager main loop logic (w/o message retry)

- testsuite/forge/src/backend/k8s/swarm.rs
> [forge] extend waiting time for node recovery to catch up peers

- language/move-lang/src/command_line/compiler.rs
- language/move-lang/src/diagnostics/codes.rs
- language/move-lang/src/parser/lexer.rs
- language/move-lang/src/parser/mod.rs
- language/move-lang/src/parser/syntax.rs
- language/move-lang/tests/move_check/expansion/unpack_all_field_cases.exp
- language/move-lang/tests/move_check/expansion/unpack_all_field_cases.move
- language/move-lang/tests/move_check/parser/address_too_long_decimal_exp.exp
- language/move-lang/tests/move_check/parser/address_too_long_exp.exp
- language/move-lang/tests/move_check/parser/doc_comments_placement.exp
- language/move-lang/tests/move_check/parser/doc_comments_placement.move
- language/move-lang/tests/move_check/parser/native_main.exp
- language/move-lang/tests/move_check/translated_ir_tests/move/commands/mixed_lvalue.exp
- language/move-lang/tests/move_check/translated_ir_tests/move/commands/mixed_lvalue.move
- language/move-lang/tests/move_check/typing/assign_nested.exp
- language/move-lang/tests/move_check/typing/assign_nested.move
- First step in slowly brining the parser more in line with other passes
- The parser can now register warnings/non blocking errors
- Despite being labeled nonblocking, token errors still stop parsing of that file
Might help a bit in the user experience of #9138
- Updated tests
> [move-lang] Don't stop at first parser error

- language/move-prover/bytecode/src/spec_instrumentation.rs
- language/move-prover/tests/sources/functional/global_vars.move
- language/move-prover/tests/sources/functional/global_vars.no_opaque_exp
This completes the implementation of the `update` condition to also work if used in opaque functions.
Specification state.
Yes
New tests.
#9154
> [move-prover] Implement opaque spec var updates.

- language/move-prover/boogie-backend/src/prelude/prelude.bpl
- language/move-prover/boogie-backend/src/spec_translator.rs
Both the code generator attached a `{:inline}` attribute to uninterpreted user spec functions, as well as the prelude declared is_txn_signer like this.
Closes #8995.
Bug fix
Yes
Manual
NA
> [move-prover] Do not generate or use inline attr for uninterpreted functions

- language/move-binary-format/src/check_bounds.rs
This PR refactors the move-binary-format BoundsChecker's `verify_impl` function to make it more modular and amenable to static analysis with MIRAI.
Yes
Since this is a refactoring, there should be no test differences. Confirmed via running existing tests.
N/A
N/A
> [language] Refactor BoundsChecker::verify_impl for MIRAI analysis

- docker/init/Dockerfile
- docker/tools/Dockerfile
Add experimental move modules bytecode to docker image, so that we can use them to bootstrap experimental testnet.
Yes
Build docker image and check if the new folder is there.
testing image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/diem/tools:dev_sherryxiao_pull_9234
> [docker] add experimental move bytecode

- config/src/config/upstream_config.rs
- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/peer_manager.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/shared_mempool/types.rs
- state-sync/state-sync-v1/src/coordinator.rs
- state-sync/state-sync-v1/src/request_manager.rs
Last of the "make X copyable" PRs, this makes `PeerNetworkId` copyable, as it's the main key for all things multi network.  It was clear this was a bit of an annoyance when working on Mempool updates.
Yes
Current tests
> [mempool/state-sync] Make PeerNetworkId copyable

- Cargo.lock
- api/src/accounts.rs
- api/src/context.rs
- api/src/index.rs
- api/src/test_utils.rs
- api/types/Cargo.toml
- api/types/src/address.rs
- api/types/src/error.rs
- api/types/src/ledger_info.rs
- api/types/src/lib.rs
- api/types/src/move_types.rs
- api/types/src/response.rs
1. implement U64 and U128 deserializer and use U64 for LedgerInfo fields
2. handle invalid URL path properly, response 404 error
3. response the latest diem ledger chain id, version and timestamp in the success response header.
4. remove unused From trait impl for Error
5. get account resources not found error includes ledger_version used for looking up the account
6. split get account resources handler logic into 2 steps: param parsing and processing
related issue #9193 
Unit tests
> [api] better error handlings and response ledger info in header

- Cargo.lock
- state-sync/storage-service/server/Cargo.toml
- state-sync/storage-service/server/src/lib.rs
- state-sync/storage-service/server/src/tests.rs
- state-sync/storage-service/types/Cargo.toml
- state-sync/storage-service/types/src/lib.rs
- types/src/account_state_blob.rs
- types/src/transaction/mod.rs
This PR completes the skeleton for the server-side of the storage service. Specifically, it stubs out the logic required for the remaining API calls (`get_transaction_outputs_with_proof()` and `get_account_states_chunk_with_proof()`) and adds support for fetching relevant metadata regarding these calls. With this PR, we now have a skeleton for the server side of the storage service that can be filled in to provide all the data we need for state sync v2.
1. Add a skeleton for the `get_transaction_outputs_with_proof()` API call. For now, the API call will return an error as we're waiting for `TransactionOutputs` to be supported by the DB.
2. Add a skeleton for the `get_account_states_chunk_with_proof()` API call. This requires introducing a new type …
> [State Sync] Complete the storage service skeleton (server-side).

- language/tools/mirai-dataflow-analysis/README.md
- language/tools/mirai-dataflow-analysis/analyses/ddlog.dl
- language/tools/mirai-dataflow-analysis/analyses/souffle.dl
- language/tools/mirai-dataflow-analysis/config/BoundsChecker_config.json
- language/tools/mirai-dataflow-analysis/config/CompiledModule_type_relations.json
- language/tools/mirai-dataflow-analysis/config/DuplicationChecker_config.json
- language/tools/mirai-dataflow-analysis/examples/BoundsChecker.md
- language/tools/mirai-dataflow-analysis/examples/DuplicationChecker.md
- language/tools/mirai-dataflow-analysis/examples/examples.md
This PR adds `mirai-dataflow` configuration files for analysis of the `BoundsChecker` and the `DuplicationChecker`. It also adds type relations to describe the structure of a `CompiledModule`.
Additionally, documentation has been added that explains both the `BoundsChecker` and `DuplicationChecker` analyses' configuration, justification, how to run, and results.
Finally, this PR makes a minor modification to the terminal non-transitive dataflow case of `TypedDataflowNotVia`. This change refines that case to exclude non-transitive dataflows to terminal nodes if those terminal nodes are dominated by the checker (`node2`).
Yes.
The existing Datalog tests pass.
N/A
N/A
> [tools][mirai-dataflow] Dataflow analysis examples and configuration

- Cargo.lock
- language/tools/move-cli/src/package/cli.rs
- shuffle/cli/Cargo.toml
- shuffle/cli/src/new.rs
- shuffle/genesis/src/lib.rs
- shuffle/genesis/src/main.rs
- shuffle/genesis/tests/e2e.rs
- shuffle/move/src/modules/SampleModule.move
Previously, we manually embedded move stdlib files. Now we use the [move package system](https://github.com/diem/diem/blob/main/language/tools/move-cli/src/package/cli.rs) to generate the new helloblockchain project.
1. `shuffle new` generates a new folder structure including helloblockchain/
Yes
`cargo test` in shuffle/cli runs unit tests and e2e tests.
> [shuffle] use move package system instead of manual files

- execution/executor/src/fuzzing.rs
- execution/executor/src/mock_vm/mod.rs
- language/diem-vm/src/adapter_common.rs
- language/diem-vm/src/data_cache.rs
- language/diem-vm/src/diem_vm.rs
- language/diem-vm/src/lib.rs
- language/tools/vm-genesis/src/lib.rs
- specifications/move_adapter/README.md
- specifications/trusted_computing_base/execution_correctness/README.md
- vm-validator/src/mocks/mock_vm_validator.rs
Replace the `dyn StateView` with `impl StateView` in the codebase. This is for `VMExecutor` and `VMValidator` we didn't expect the storage to be hetherogeneous and thus limitting it with `impl StateView` will get rid of the extra runtime cost of dynamic traited objects.
Yes
`cargo check`
> [diem-vm] Replace dyn StateView by impl StateView

- language/move-model/src/ast.rs
- language/move-model/src/model.rs
- language/move-prover/bytecode/src/escape_analysis.rs
- language/move-prover/bytecode/src/lib.rs
- language/move-prover/bytecode/tests/escape_analysis/global_spec_relevance.exp
- language/move-prover/bytecode/tests/escape_analysis/global_spec_relevance.move
- language/move-prover/bytecode/tests/escape_analysis/global_struct_eq.exp
- language/move-prover/bytecode/tests/escape_analysis/global_struct_eq.move
- language/move-prover/bytecode/tests/escape_analysis/return_internal_refs.exp
- language/move-prover/bytecode/tests/escape_analysis/return_internal_refs.move
- language/move-prover/bytecode/tests/escape_analysis/return_refs_into_vec.exp
- language/move-prover/bytecode/tests/escape_analysis/return_refs_into_vec.move
- language/move-prover/bytecode/tests/escape_analysis/return_refs_safe.exp
- language/move-prover/bytecode/tests/escape_analysis/return_refs_safe.move
- language/move-prover/bytecode/tests/escape_analysis/struct_eq.exp
- language/move-prover/bytecode/tests/escape_analysis/struct_eq.move
- language/move-prover/bytecode/tests/escape_analysis/struct_spec_relevance.exp
- language/move-prover/bytecode/tests/escape_analysis/struct_spec_relevance.move
- language/move-prover/bytecode/tests/escape_analysis/vec_eq.exp
- language/move-prover/bytecode/tests/escape_analysis/vec_eq.move
- language/move-prover/bytecode/tests/testsuite.rs
- language/move-prover/src/cli.rs
- language/move-prover/src/lib.rs
This is an experimental analysis used in an upcoming paper on robust safety for Move. The high-level idea is that:
- We have an abstract "prover" that can show that invariants hold locally within a module: i.e., if you assume `i` holds in the precondition of every public function of a module, the prover can establish when `i` also holds in the postcondition of the function. The Move Prover is a concrete instantiation of this abstract tool, but other instantiations are possible.
- We have an abstract "encapsulator" that can establish when module-local invariants are also global invariants (i.e., hold in every possible program execution, even when the module in question interacts with untrusted code). The analysis in this PR is a concrete instantiation of this abstract tool, but other …
> [prover] escape analysis to detect leaks of module-internal references

- testsuite/forge-cli/src/lib.rs
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
change compatibility test suite start with older version can save one time downgrading procedure at the start
* What workarounds and alternative we have if we do not push …
> [forge] change compatibility test suite start with older version

- Cargo.lock
- api/Cargo.toml
- api/src/context.rs
- api/src/runtime.rs
- api/src/test_utils.rs
- api/src/transactions.rs
- api/types/src/transaction.rs
- diem-node/src/lib.rs
- mempool/src/tests/mocks.rs
- types/src/mempool_status.rs
#9193
* submit transaction by post bcs encoded SignedTransaction to /transactions.
* response a pending transaction serialized from the SignedTransaction, include transaction hash.
* response 400 for invalid transaction or mempool rejection errors.
* response 202 accepted if mempool accepts the transactions.
* will have a follow up PR to render a Location header for looking up transaction by hash (after we implement GET /transactions/<txn-hash>)
> [api] post /transactions to submit bcs encoded signed transaction

- language/move-prover/bytecode/src/access_path_trie.rs
- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/move-prover/bytecode/tests/read_write_set/copy_struct.exp
- language/move-prover/bytecode/tests/read_write_set/copy_struct.move
- language/move-prover/bytecode/tests/read_write_set/secondary_index.exp
The transfer functions for read_ref used an outdated version of the assignment logic that predated support for addresses flowing into/out of structs. This PR uses the modern version everywhere and deletes the old one. 
Added E2E test that exercises the crash + passes now.
> [move-prover] fix crash in read/write set analysis

- testsuite/forge/src/backend/k8s/mod.rs
we do scaling node group to 0 and scaling up to 210 before each test, but it we do two scalings back to back immediately it seems will something wrong, just remove this step to scale to 0. I am going to find a better way to do "finally" cleanup  
* Comprehensive test results that demonstrate the fix …
> [forge] remove pre test scaling node group to 0

- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
Added drop crates implementation for k8sFactory to handle cluster cleanup instead of drop for k8sSwarm, Since some cluster operation errors happened before k8sSwarm constructed.
* Why we must have it for V1 …
> [forge] add drop for k8s_factory struct

- .github/workflows/ci-test.yml
`deno lint ./language/move-analyzer` is breaking in https://github.com/diem/diem/runs/4053327842?check_suite_focus=true despite correct deno ignore. This lint step was motivated by shuffle, let's not block move-analyzer.
Yes
deno lint ./shuffle
This PR's CI.
https://github.com/diem/diem/pull/9570
> deno only lints ./shuffle

- .github/actions/early-terminator/action.yml
- .github/workflows/ci-test.yml
Instead always run full workflow each time which takes around 50mins, we can terminate it once there have any job is failed.
https://github.com/diem/diem/actions/runs/1401703623
* Why we must have it for V1 …
> [GHA] Terminate ci-test workflow earlier once there is job failed

- api/doc/openapi.yaml
- api/src/tests/accounts_test.rs
- api/src/tests/events_test.rs
- api/src/tests/transactions_test.rs
- api/types/src/lib.rs
- api/types/src/move_types.rs
- api/types/src/transaction.rs
- shuffle/cli/repl.ts
- shuffle/move/examples/main/mod.ts
#9193 we render Move type as JSON object with nested type objects when there is generic type parameters. For example:
```
{
"type": "struct",
"address": "0x1",
"module": "DiemAccount",
"name": "Balance",
"generic_type_params": [
{ "type": "struct", "address": "0x1", "module": "XDX", "name": "XDX" }
]
}
```
We started with this representation because it is easier to be deserialized into `StructTag` type when a client send a request with type field (e.g. ScriptFunctionPayload generic type parameters).
This PR changes the move type representation to string format, for example, above struct definition can be rendered as:
```
"0x1::DiemAccount::Balance<0x1::XDX::XDX>"
```
This is much more cleaner and readable format comparing with above JSON object.
I found we have a parser can parse Move …
> [api] change type representation to string format instead of nested object

- shuffle/cli/src/node.rs
Restarting `shuffle node` would change the resulting waypoints, and other configurations, breaking future txns. This allows for consistent waypoints, allowing reruns.
Yes
cargo test -p shuffle
> [shuffle] node uses a seed rng for clean reruns

- .github/workflows/ci-test.yml
Build job may run on a node that has nodejs version==12, which fails the job.
Remove it for now.
> disable api lint on non-rust-lint job

- shuffle/cli/src/main.rs
- shuffle/cli/src/transactions.rs
We want shuffle transactions to print all transactions in the pretty format for easy readability. If the user wants the transaction to be printed out in one line however, we also want to give them the flexibility to do so by using the --raw flag. 
When I run cargo run -p shuffle -- transactions -n 127.0.0.1:8081, I get this output:
When I run cargo run -p shuffle -- transactions -n 127.0.0.1:8081 --raw, I get this output:
* Comprehensive test results that demonstrate the fix working …
> [shuffle] shuffle transactions --raw

- docker/init/Dockerfile
This fixes an issue created by #9308 where the directory structure of the releases changed, which then caused the copied `move` directory to have a different format than was expected.
This PR should fix this issue by flattening out the module structure to what was there before when building the docker image.
> [docker] Fix docker init so that it copies compiled Move modules to the expected place and format

- language/move-prover/tests/sources/functional/emits.cvc4_exp
The test `functional/emits.move` fails due to the difference with the baseline file. This commit updates `emits.cvc4_exp`
To fix the test failure of `functional/emits.move`
yes
cargo test
> [move-prover] Update emits.cvc4_exp

- language/move-prover/bytecode/src/global_invariant_analysis.rs
- language/move-prover/bytecode/tests/global_invariant_analysis/uninst_type_param_in_inv.exp
- language/move-prover/tests/sources/functional/uninst_global_invariant.exp
- language/move-prover/tests/sources/regression/mono_after_global_invariant.exp
- language/move-prover/tests/testsuite.rs
I mistakenly assumed that warnings are captured in the move prover tests
but turns out that this is not. This commit adds the capturing of
warnings as well.
Consequently, #9545 actually creates many warnings when trying to verify
DPN with Move Prover because a couple of invariants cannot be
instantiated. Although the DPN still verifies, seeing a log of warnings
are not pretty. So, let's temporarily disable the effects of #9545 (and
hence the warnings). This will allow me to investigate a bit more on how
we handle un-related type parameters in a generic invariant.
Don't give out these warnings as of yet. A more robust solution is on the way.
Yes
CI, in particular, `cargo test` in the move-prover directory
> [move-prover] disable #9545 temporarily and catch warnings in testsuite

- shuffle/cli/src/account.rs
- shuffle/cli/src/deploy.rs
- shuffle/cli/src/main.rs
- shuffle/cli/src/node.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/test.rs
- shuffle/transaction-builder/Cargo.toml
Diem Core Framework (DCF) developers work on .move files that are included in the genesis. This is a significantly different workflow to regular Move application developers in that
1. DCF devs are using the root mint.key to seed the genesis txn w move modules
2. This implies special privileges
3. DCF devs cannot be the default sender address of 0x241... on genesis writes
Adding the below flag will allow one to customize the genesis on creation of a new node:
Do note however that modifying the genesis after node creation is not yet supported, and will error out:
Yes
cd shuffle && cargo test
> shuffle node --genesis /path/to/move/package

- api/doc/openapi.yaml
#9193 
Optimizing the openapi specification for client code generation by (openapi-generator):
1. Removed some alias types, which are created for better doc rendered into HTML.
2. Removed `enum` definition for the `type` field, replaced with `discriminator` field for type has `oneOf`. Enum type generation has bug in rust language.
3. Always use camel case type name to ensure generated type / struct / class names are consistent.
4. Removed `visibility` enum value `private`, it is valid in Move, but we don't render private function.
5. Extract out XxxProperties type for the type has inline type definition (under `allOf`). This removes a type named XxxAllOf to be generated and generates `XxxProperties` instead.
6. update operationId fields to use underscore instead of hyphen, generated code …
> [api] optimizing openapi specificatoin for client code generation

- .github/workflows/ci-test.yml
- api/Makefile
- scripts/api_lint.sh
#9193 add a new build job for running api specification lint task and a simple test of rust code generation.
Intent to create a new job instead of mixing with non-rust-lint, because we will need add more specification test later.
Removed scripts/api_lint.sh, change to add Makefile to api directory, later will add more specification test tasks, it is easier to be maintained by a Makefile
> [api] api spec test job

- api/doc/openapi.yaml
- api/src/tests/accounts_test.rs
- api/src/tests/transactions_test.rs
- api/types/src/convert.rs
- api/types/src/lib.rs
- api/types/src/move_types.rs
- api/types/src/transaction.rs
#9193 
Similar to #9571, a string representation of Move module and script function is simpler for client to set instead of nested struct.
This change updates API responds and accepts Move module id string and script function id string.
> [api] change Move module id and script function to use a string id instead of struct type.

- mempool/src/shared_mempool/network.rs
MempoolRpc isn't currently supported, yet the current nodes think that
it is.  That's problematic as other nodes don't know that it isn't
supported.
yes
Caught this with backwards compatibility tests.
Blocks https://github.com/diem/diem/pull/9640
> [mempool] Unsupport MempoolRpc

- Cargo.lock
- mempool/Cargo.toml
- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/network.rs
- mempool/src/shared_mempool/tasks.rs
In order to put an asynchronous RPC call in place of a synchronous DirectSend call, I had to refactor the code for async.  Now the section has errors and can actually give information about why it's not broadcasting at any one point.
Yes
Current tests
Along with https://github.com/diem/diem/pull/9616 are required for Mempool RPC
> [mempool] Refactor execute broadcast

- state-sync/state-sync-v1/src/bootstrapper.rs
- state-sync/state-sync-v1/src/coordinator.rs
- state-sync/state-sync-v1/src/error.rs
- state-sync/state-sync-v1/src/shared_components.rs
- state-sync/state-sync-v1/tests/integration_tests.rs
- state-sync/state-sync-v1/tests/test_harness.rs
This PR extends state sync v1 to support a read-only mode, a mode in which state sync will respond to chunk requests from peers (to enable them to synchronize), but will not actively request data in order to synchronize itself. This is required to support the case where state sync v2 is synchronizing the node, and state sync v1 is only enabled to support backward compatibility. 
Note: most of the new code is just tests to ensure that things work as expected 😄 
1. Add a read-only mode to state sync v1 and add some simple unit/integration tests.
2. Add the ability to disable read-only mode, in the case that state sync v1 is read-only and the node is unable to make progress with state sync v2.
Yes.
New unit and integration tests have been added for the …
> [State Sync] Support a read-only mode for state sync v1.

- shuffle/cli/src/console.rs
- shuffle/cli/src/main.rs
- shuffle/cli/src/new.rs
- shuffle/cli/src/node.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/test.rs
Currently the network field is tied to the project folder. As shuffle grows and we connect to more networks, it's not intuitive to pull the network value from the project folders, instead we want to pull from a centralized location. Hence, this PR!
Run cargo run -p shuffle -- node in your terminal. As we know, the .shuffle folder should generate from this:
If we take a look inside the .shuffle folder, there is now a Networks.toml which currently supports the localhost network:
Note, as we connect to more networks or users want to other networks, they will be responsible for editing this Networks.toml file with the appropriate parameters. 
Now that we have a network name in our Networks.toml, I ran shuffle console -p "project_path" --network localhost. It works with this localhost string …
> [shuffle] generate Networks.toml in /.shuffle

- state-sync/state-sync-v2/data-streaming-service/src/data_notification.rs
- state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/lib.rs
- state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/mod.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/stream_engine.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/stream_progress_tracker.rs
Note: This PR makes no logical changes.
This PR offers two small refactors: (i) remove an unnecessary type definition and inline the type; and (ii) rename "Stream Progress Tracker" (and all references) to "Data Stream Engine". The reason for this rename is simply that the "Stream Progress Tracker" no longer just tracks the progress of each stream, but it now also drives each stream to completion. I think the name is clearer.
Each of these changes happen in their own commit.
Yes.
Existing tests cover this.
> [State Sync] Rename struct and remove unnecessary type declaration.

- diem-node/src/lib.rs
- diem-node/src/main.rs
- shuffle/cli/src/node.rs
Add an option `--lazy` to start test node without continuous commit blank metadata block.
Set this flag will set `consensus#mempool_poll_count` config to `u64::MAX` and only commit a block when there is user transaction in mempool.
1. Low CPU consumption when doing local test.
2. Keep server state when no new user signed transaction is submitted for consistent testing result.
> [diem-node] launch test node with lazy mode for only commit block with user signed txns

- .github/actions/build-setup/action.yml
- .github/workflows/ci-test.yml
- docker/ci/github/Dockerfile
- scripts/dev_setup.sh
For testing API specification, we need use node-js and python tools, this PR setup them in the dev_setup.sh script, so that we don't need special handling in the build script, and it should be consistent for all dependencies setup for diem local dev as well.
#9193 
1. Local manual test
2. CI Build
> [api] update dev_setup.sh to install nodejs & python tools for api build

- shuffle/cli/src/account.rs
- shuffle/cli/src/deploy.rs
- shuffle/cli/src/main.rs
- shuffle/cli/src/node.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/test.rs
As we're ramping up to connect to trove testnet, we need the ability to specify which network to use in shuffle deploy and shuffle test. This PR accomplishes this
The goal was to add the network argument and make sure shuffle deploy and shuffle test still functioned properly.
I ran cargo run -p shuffle -- deploy -p /Users/avinash00/a --network localhost and got the same output as I would've without the network flag:
Similarly I ran cargo run -p shuffle -- test e2e -p /Users/avinash00/a --network localhost and got the same output as I would've without the network flag:
* Justification and …
> [shuffle] add network arg to deploy and test

- Cargo.lock
- diem-move/diem-vm/Cargo.toml
- diem-move/diem-vm/src/read_write_set_analysis.rs
- language/move-binary-format/src/lib.rs
- language/tools/move-bytecode-utils/src/layout.rs
- language/tools/move-bytecode-utils/src/lib.rs
- language/tools/move-bytecode-utils/src/module_cache.rs
- language/tools/move-cli/src/sandbox/commands/generate.rs
- language/tools/move-cli/src/sandbox/utils/mod.rs
- language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
- language/tools/read-write-set/dynamic/Cargo.toml
- language/tools/read-write-set/dynamic/src/dynamic_analysis.rs
- language/tools/read-write-set/dynamic/src/normalize.rs
As promised in #9484 , I refactored `ModuleCache` to `move-bytecode-util` alogn with a sync and single thread version of ModuleCache.
Yes
> [move-bytecode-util] Move ModuleCache to `move-bytecode-util`

- language/move-prover/boogie-backend/src/spec_translator.rs
This is motivated by the following expression generated by the spec
simplifier, which causes a type error in Boogie (but no type error in
our AST):
```boogie
(x > 0) && if (true) then (0) else (1) >= 0;
```
In this case, Boogie complains that the then-else branches return
different types which is int (for the then branch) and bool (for the
else branch).
This is caused by the fact that the ITE expression itself is not
enclosed in a parenthesis. The correct encoding should be:
```boogie
(x > 0) && (if (true) then (0) else (1)) >= 0;
```
This commit fixes this issue by wrapping the ITE expression with ().
Fix an encoding issue
Yes
CI, everything should continue to verify
> [move-prover] parenthesis the ITE expression when translating to boogie

- api/Operation.md
- api/README.md
- config/src/config/api_config.rs
- diem-node/src/lib.rs
- docker/validator/Dockerfile
- shuffle/cli/src/shared.rs
- testsuite/forge/src/backend/k8s/swarm.rs
#9193 
To keep configuration simple, changed enable REST API by default and used same port that is used by JSON-RPC API (removed 8081 default config).
Added diem-node operation document for API: `Operation.md`
> [api] enable api by default and change rest api and json-rpc to use same port

- Cargo.lock
- consensus/Cargo.toml
- consensus/safety-rules/src/error.rs
- consensus/safety-rules/src/safety_rules.rs
- consensus/src/metrics_safety_rules.rs
- consensus/src/test_utils/mock_storage.rs
When a node starts and initializes safety rules, fast-forwarding the waypoint of the persistent storage will fail if the waypoint is far behind the current waypoint of the non-secured storage [(Issue #9139).](https://github.com/diem/diem/issues/9139) The current retry is limited: it only re-tries once upon failures. The initialization during startup can be improved by having the initialization keep doing fast-forwarding the waypoint until it is up-to-date.
Yes.
The unit test emulates a scenario where multiple initialize() calls are required to bring the waypoint up-to-date. Specifically, the first N-1 initialize() calls will return an error saying that the waypoint is still not up-to-date. The N-th call will return Ok (i.e., waypoint is up-to-date). The test then checks that the …
> [consensus] Fast-forward waypoint in Safety Rules.

- consensus/src/liveness/proposal_generator.rs
- consensus/src/liveness/proposal_generator_test.rs
- consensus/src/round_manager.rs
- consensus/src/state_replication.rs
- consensus/src/test_utils/mock_txn_manager.rs
- consensus/src/txn_manager.rs
This should fit the last piece of slowing down the empty blocks without impacting user experience.
Broadcast syncinfo will send out the newest qc that the leader aggregates which may commit the latest block. …
> [consensus] disseminiate sync info when mempool waits for available txns

- Cargo.lock
- language/move-binary-format/Cargo.toml
- language/move-prover/bytecode/Cargo.toml
- language/move-prover/bytecode/src/read_write_set_analysis.rs
- language/tools/read-write-set/Cargo.toml
- language/tools/read-write-set/dynamic/Cargo.toml
- language/tools/read-write-set/dynamic/src/dynamic_analysis.rs
- language/tools/read-write-set/dynamic/src/normalize.rs
- language/tools/read-write-set/src/lib.rs
- language/tools/read-write-set/types/Cargo.toml
Rename `read-write-set-types` to `move-read-write-set-types` and changed its version number to publish this crate. The crate needs to be published because of #9648.
Also published `move-binary-format` because of the transitive dependencies. The version numbers were picked to follow the current version of `diem-types`.
Yes
`cargo test`
> [read-write-set] Rename `read-write-set-types` to `move-read-write-set-types`

- shuffle/cli/src/test.rs
Before, we had to handle a panic that fired when we ran move commands on a move folder more than once. PR #9491 fixed that panic. In this PR, i remove the panic handling that was once in our code. 
I ran `cargo run -p shuffle -- test unit -p project_path` many times and now there are no panics that come up:
> [shuffle] removed panic handling in move_unit_tests()

- Cargo.lock
- execution/executor-benchmark/Cargo.toml
- execution/executor-benchmark/benches/executor_benchmark.rs
- execution/executor-benchmark/src/lib.rs
- execution/executor-benchmark/src/transaction_committer.rs
- execution/executor-benchmark/src/transaction_generator.rs
- execution/executor/src/block_executor_impl.rs
- storage/diemdb/src/lib.rs
Some improvements to the Executor Benchmark:
1. fix the accumulative metrics reported.
2. no longer persist all generated accounts as part of the test case (too slow to persist and reload), instead, regenerated part of the accounts at test case run time.
3. remove the storage service in between the executor and the DB, mimicking the new real scenario in product.
On @lightmark's test DB with 10 million accounts, the benchmark runs at ~1.8k TPS (up from ~420 TPS, on my MacPro)
Y
local machine
> [executor-benchmark] improvements

- api/README.md
- api/doc/openapi.yaml
- api/src/context.rs
- api/src/index.rs
- api/src/runtime.rs
- api/src/tests/index_test.rs
- api/src/tests/test_context.rs
- api/src/tests/transactions_test.rs
- api/src/transactions.rs
- config/src/config/api_config.rs
#9193 
1. Add request content length limit to routes that accept request body. Default to 4mb, the JSON format transaction size is larger than BCS transactions. We only have 2 endpoints accepts request body, submit transaction and create signing message.
2. Switched to use `warp::body::json` to deserialize POST json request body.
3. We need response json error body for the API, but `warp` built-in rejection handling responses text, thus we need to convert the `warp` rejections properly inside recover handler.
4. Correct response code for unsupported content-type.
5. Updated openapi spec doc to include 413 and 415 error in post endpoints.
> [api] handle POST requests properly

- Cargo.lock
- crates/transaction-emitter/Cargo.toml
- crates/transaction-emitter/src/cluster.rs
- crates/transaction-emitter/src/instance.rs
- crates/transaction-emitter/src/lib.rs
- crates/transaction-emitter/src/main.rs
Tested with same fullnode which is running longevity test
1. test diag:
```
cargo run -p transaction-emitter --  --diag --peers=premainnet.libra.novi.com:80:80 --vasp --chain-id=21
```
Test result:
```
Getting faucet account sequence number on premainnet.libra.novi.com:80(premainnet.libra.novi.com)...seq=44733
Submitting txn through premainnet.libra.novi.com:80(premainnet.libra.novi.com)...seq=44734
Waiting all full nodes to get to seq 44734
[premainnet:44733]  
[premainnet:44734]  
Looks like all full nodes are healthy!
```
2. test tx-emit:
```
cargo run -p transaction-emitter -- --emit-tx --peers=premainnet.libra.novi.com:80:80 --vasp --chain-id=21
```
Test result:
```
Will use 10 workers per endpoint with total 10 endpoint clients
Will create 15 accounts_per_client with total 150 …
```
> [forge] Implemented AOS support and all missed features in txn_emitter

- language/tools/move-package/src/compilation/build_plan.rs
- language/tools/move-package/src/compilation/compiled_package.rs
- language/tools/move-package/tests/test_removal_second_compilation.rs
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.exp
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.toml
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/sources/A.move
- language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/sources/ATest.move
This fixes an issue where testing or dev-mode artifacts could still exist on disk if you first compiled a package in dev or test mode and then compiled in non-dev or test mode.
This adds a test to make sure these artifacts are deleted.
> [move-package] Fix issue where we werent' removing build artifacts between builds

- Cargo.lock
- language/tools/move-cli/src/package/cli.rs
- shuffle/cli/Cargo.toml
- shuffle/cli/src/test.rs
- shuffle/integration-tests/src/lib.rs
- shuffle/move/examples/main/sources/Message.move
- shuffle/move/examples/main/sources/MessageTests.move
Previously, shuffle forge integration test skipped move unit tests because it exited early via `std::process:exit(1)` on a failed unit test. This refactor allows optional early failure on invocation of move package unit tests, and incorporates that into the force shuffle test.
This diff seems noisy, but it's mostly because of a poor rendering of the changes in move-cli, moving run_move_unit_tests outside of the handle_package_command
Yes
`cargo xtest -p shuffle-integration-tests`
> [shuffle] forge shuffle integration test runs move unit tests

- shuffle/cli/src/test.rs
Fixed base_url error we faced in shuffle test e2e.
> [shuffle] shuffle test e2e bug fix

- diem-move/diem-framework/DPN/releases/artifacts/current/build/DPNFramework/BuildInfo.yaml
- language/tools/move-package/src/resolution/digest.rs
- language/tools/move-package/tests/package_hash_skips_non_move_files.rs
This PR updates the source digest creation for Move packages to only hash Move files and the `Move.toml` file. Before we were hashing all contents of certain directories of the package, and this lead to issues where hidden and/or git ignored files could be present and result in a different package hash even though the repository/package would appear in a "clean" state.
> [move-package] Only hash Move and package-specific files

- api/Makefile
- api/doc/openapi.yaml
- api/doc/spec.html
- api/src/index.rs
#9193 
When load the spec.html from a diem-node, we enable `try it`, and hide it by default:
Added `title` to schema definition, added more examples to each schema:
Related PR: #9778
> [api] update openapi doc with more examples and better fit with renderer

- language/move-model/src/ast.rs
- language/move-prover/boogie-backend/src/options.rs
- language/move-prover/boogie-backend/src/spec_translator.rs
- language/move-prover/tests/sources/functional/choice.cvc4_exp
- language/move-prover/tests/sources/functional/choice.exp
- language/move-prover/tests/sources/functional/choice.move
The choice operator is currently implemented with a property that
if the same choice operator is referred multiple times, the chosen
evidence should stay the same.
This semantics is captured in the newly added
`// Semantics when the same-choice operator is referred`
section in the `choice.move` test case.
This property is implemented by converting a choice operator into
an uninterpreted function in Boogie followed by an axiom to constrain
this uninterpreted function.
However, in this translation process, there is an implicit assumption
that one choice operator will only be called with a one and only one set
of variables (e.g., function arguments/locals, free vars, and memories).
This assumption is valid in the verification of DPN given the limited
uses of the choice operator, but there …
> [move-prover] create a choice boogie function on unique `ExpData`

- shuffle/cli/src/deploy.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/transactions.rs
Quick bug fix. Before if a GET or POST transactions request failed, we'd get an error like so: 
`send_module_transaction json: Object({"code": Number(400), "message": String("invalid transaction: INVALID_MODULE_PUBLISHER")})`.
Now we're checking responses after a GET/POST transactions and bubbling up an error message if there is an invalid request. 
main is broken when creating accounts so to test out this code, first `git checkout bb59dc7164f6a3c57f0868385f84a2e45dc053b0"
Then pass in Invalid requests where I `check_get_transactions_response_status` and `check_post_transactions_response_status`:
When there are no errors, this is the output:
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, …
> [shuffle] check response statuses after POST/GET transactions

- language/bytecode-verifier/transactional-tests/tests/reference_safety/imm_borrow_global.mvir
- language/bytecode-verifier/transactional-tests/tests/reference_safety/imm_borrow_global_invalid.mvir
- language/bytecode-verifier/transactional-tests/tests/reference_safety/imm_borrow_global_lossy_acquire_invalid.mvir
- language/ir-testsuite/tests/move/commands/if_branch_diverges_8.mvir
- language/move-ir-compiler/ir-to-bytecode/src/compiler.rs
- language/move-ir-compiler/ir-to-bytecode/syntax/src/syntax.rs
- language/move-ir/types/src/ast.rs
- language/move-vm/transactional-tests/tests/control_flow/if_branch_diverges_7.mvir
- language/move-vm/transactional-tests/tests/example_programs/sorted-linked-list.mvir
The documentation comment for the `EmptyStatement` claims it eases parsing to allow for an empty statement `;` in Move IR, but I think that it actually makes things more difficult: the statement `assert(e_1, e_2);` was being parsed incorrectly for some time, as an assert statement followed by the empty statement `;`. (Unless it was intentional that every `CommandStatement` ended in a semicolon except for `assert`, which personally I find a little confusing.)
I could see how it may make sense to allow for empty statements in a user-facing programming language such as Move, but for a language we primarily use to test Move, I think the empty statement should either lower to a "noop" bytecode instruction, or it should be treated as an error. And seeing as how there is no "noop" bytecode …
> [move] Remove empty `;` statement from Move IR

- shuffle/cli/src/account.rs
- shuffle/cli/src/main.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/test.rs
- shuffle/integration-tests/src/helper.rs
The final piece that we need to connect to trove testnet is by using a faucet to create an account onto the network. This PR achieves this. 
Note: To mimic creating an account on trove testnet using the faucet, I set the contents of trove_testnet in the Networks.toml to the localhost information with the faucet url matching the faucet url, I used when spinning up a local faucet.
Also I changed line 247 to `let faucet_account_creation_endpoint = network.get_faucet_url()?;` for my testing.
When creating an account for the first time on trove testnet, I ran `cargo run -p shuffle -- account --network trove_testnet`. I'm prompted with this message: 
I then add the …
> [shuffle] create account via faucet

- language/documentation/book/src/packages.md
Enhance the package manager documentation with a description of how to use the git dependency feature.
> [move package manager] document git dependencies

- README.md
There are some broken links to documentation in the top-level README file. Three of them can be directly replaced with updated URLs, but I don't see a direct equivalent of "Diem Protocol: Key Concepts". This replaces that with a "Basic Concepts" link to the start of the "Basics" section in the developer guides.
Fixes: #9803
Yes
> [README] fix broken links to documentation

- language/tools/move-bytecode-utils/src/layout.rs
- language/tools/move-bytecode-utils/src/module_cache.rs
- language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
- language/tools/read-write-set/dynamic/src/dynamic_analysis.rs
Relax the api for `GetModule` so that the implementer can choose freely to whether return a reference or a value. This will significantly increase the inference time for read write set estimator as we can avoid copying the entire `CompiledModule`.
Yes
`cargo check`
> [move-bytecode-util] Relax api for GetModule

- Cargo.lock
- diem-move/diem-transaction-benchmarks/Cargo.toml
- diem-move/diem-transaction-benchmarks/src/transactions.rs
Change the transaction bencher for parallel execution to include a blockmetadata transaction at the beginning. This would better simulate the traffic in the production.
In our current implementation, there was a significant regression after adding such blockmetadata transaction, which I would fix shortly in a later PR. The current benchmark results are as following:
```
peer_to_peer            time:   [308.86 ms 312.06 ms 315.56 ms]                       
change: [-6.0021% -3.3703% -1.3783%] (p = 0.01 < 0.05)
Performance has improved.
Benchmarking peer_to_peer_parallel: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 10.7s.
peer_to_peer_parallel   time:   [376.31 ms 379.99 ms 383.68 ms]                                
change: …
```
> [diem-transaction-bench] Insert blockmetadata transaction for benchmark

- diem-move/diem-vm/src/diem_vm.rs
- diem-move/diem-vm/src/diem_vm_impl.rs
- diem-move/diem-vm/src/parallel_executor/vm_wrapper.rs
- language/move-vm/runtime/src/move_vm.rs
This is a follow up PR for #9875 as a fix for our performance regression in parallel execution. After adding a block metadata transaction at the beginning of each transaction block, the overall system perf dropped by 2x and causes parallel execution to be slower than the sequential version. The reason was following:
Blockmetadata transaction will modify the timestamp resources that will be read by every transaction's prologue. Thus when parallel executor starts, only one thread get to execute the block metadata transaction, and all other threads are just waiting for that transaction to be executed. This causes a serious issue: the system is now spending 2x time on cold starting the MoveVM (one spent on the first block metadata transaction and one for all the other threads). This explains …
> [move-vm] Expose API for load modules

- shuffle/cli/src/account.rs
- shuffle/cli/src/console.rs
- shuffle/cli/src/context.rs
- shuffle/cli/src/deploy.rs
- shuffle/cli/src/lib.rs
- shuffle/cli/src/main.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/test.rs
- shuffle/cli/tests/common/mod.rs
- shuffle/cli/tests/shuffle-forge-cli-tests.rs
- shuffle/cli/tests/shuffle-forge-integration-tests.rs
- shuffle/move/examples/e2e/message.test.ts
- shuffle/move/examples/integration/context.test.ts
- shuffle/move/examples/integration/helpers.test.ts
- shuffle/move/examples/main/context.ts
- shuffle/move/examples/main/devapi.ts
- shuffle/move/examples/main/helpers.ts
- shuffle/move/examples/main/mod.ts
1. Introduce support for a 2nd ephemeral account in both `shuffle console` and `shuffle test e2e` to support peer to peer transfer scenarios like TransferNFT.
2. Prepare harness and console typescript SDK to support multiple accounts (ie: alice, bob, charlie) by introducing `UserContext` and `ConsoleContext` in `context.ts` and `context.rs`.
--
1. Introduce UserContexts into both TS and Rust. UserContext { username, address, privateKeyPath }
1. Pass an array of UserContexts to run_deno_tests and console so that ENV variable handoff of users can better support N users, rather than hardcoding to `latest`.
1. Generate ENV vars iteratively following a convention: ADDRESS_\<username>, PRIVATE_KEY_PATH_\<username>. ie: ADDRESS_LATEST, PRIVATE_KEY_PATH_LATEST, ADDRESS_TEST, etc
1. Cleanup: …
> [shuffle] Support for 2nd ephemeral account during console, test

- Cargo.lock
- api/Cargo.toml
- api/README.md
- api/src/accounts.rs
- api/src/events.rs
- api/src/failpoint.rs
- api/src/index.rs
- api/src/lib.rs
- api/src/transactions.rs
- diem-node/Cargo.toml
- testsuite/cluster-test/src/cluster_swarm/configs/fullnode.yaml
#9193 
API failpoint name pattern: "api::endpoint_<endpoint name>"
Test: 
```
cargo build -p diem-node --all-features
```
update node configuration to enable failpoints:
```
failpoints:
api::endpoint_index: 100%return
```
Curl the index endpoint should return 500 error
```
curl http://localhost:8080/
{"code":500,"message":"unexpected internal error for endpoint_index"}
```
> [api] inject fail points to each endpoint

- scripts/dev_setup.sh
- Bump up the Z3 version from 4.8.9 to 4.8.12
- according to the [release note](https://github.com/Z3Prover/z3/blob/master/RELEASE_NOTES), the newest version has some update on the arithmetic solver, and also has many general bug fixes
- The running time of `MVP_TEST_ON_CI=1 cargo test -p move-prover
--release` almost remains the same (comparing "before" and "after").
- `MVP_TEST_ON_CI=1` was given in this benchmark test to exclude the cvc4 tests. The cvc4 tests are not related to the Z3 performance, and the cvc4 tests don't work at the moment.
- Commented out an unused line from `diem/shuffle/move/examples/main/context.ts` because the deno linter complains about it in CI
- See https://github.com/diem/diem/runs/4250122831?check_suite_focus=true#step:7:38
To upgrade the Z3 version
yes …
> [move-prover] Upgrade Z3 version

- language/tools/move-cli/src/package/cli.rs
- language/tools/move-cli/src/sandbox/commands/publish.rs
- language/tools/move-cli/src/sandbox/commands/test.rs
- language/tools/move-cli/tests/testsuite/cyclic_multi_module_publish/args.exp
- language/tools/move-cli/tests/testsuite/republish/args.exp
- language/tools/move-package/src/compilation/compiled_package.rs
- shuffle/move/examples/main/sources/nft/NFTTests.move
This should resolve an issue that @modocache observed where the publish order for modules is not deterministic after #9871 landed.
This is because the `modules()` method on a package was not returning the units in dependency order, and therefore there were chances for non-determinism introduced at that point.
This fixes this issue by making the `modules()` method always return compiled units in dependency order.
> [move-cli] Fix ordering issues in sandbox publish

- shuffle/cli/src/account.rs
- shuffle/cli/src/dev_api_client.rs
- shuffle/cli/src/shared.rs
- shuffle/cli/src/test.rs
Before shuffle test e2e --network would run an end to end test with an account created with devapiclient where instead we needed to faucet an account. This PR ensures that whenever a network that supports a faucet url is used, the e2e test will faucet an account. 
1. Add trove_testnet details to Networks.toml.
2. `cargo run -p shuffle -- new <project_path>`
3. `cargo run -p shuffle -- test e2e -p <project_path> --network trove_testnet`
* Comprehensive test results that demonstrate …
> [shuffle] add faucet support for e2e test

- shuffle/move/examples/e2e/message.test.ts
- shuffle/move/examples/integration/helpers.test.ts
- shuffle/move/examples/main/helpers.ts
- shuffle/move/examples/main/mod.ts
- shuffle/move/examples/main/move.ts
We continue to run into edge cases that prevent us to automatically encode a script function's argument. This PR introduces a type system into the typescript ecosystem to unambiguously encode arguments correctly for their move counterpart.
Examples described below:
```
Javascript/Typescript has a very loose type system, resulting in ambiguity
when trying to encode string values for onchain Move programs, a space that
has a very strong type system.
Let's look at two examples:
1)
invokeScriptFunction("0xDEADBEEF::Module::set_u64", [], ["9"]);
invokeScriptFunction("0xDEADBEEF::Module::set_ascii", [], ["9"]);
In set_u64 , we want "9" to remain a string, because javascript does
not have support for integers, especially of the size u64. The proper encoding
happens in rust in the Dev API.
In …
```
> [shuffle] add strong typing to typescript SDK and invokeScriptFunction

- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/interface/node.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/state_sync_performance.rs
```
The fullnode has caught up to version: 77386
Time to state sync 30
State sync throughput : 2579 txn/sec
test StateSyncPerformance ... ok
Test Statistics: 
State sync throughput : 2579 txn/sec
```
> [forge] state-sync performance test in Forge

- shuffle/cli/Cargo.toml
Fresh compilation on M1 Macs failed because of the following error. Adding the serde feature to the url import fixes the issue.
```
error[E0277]: the trait bound `Url: Serialize` is not satisfied
--> shuffle/cli/src/shared.rs:371:5
|
371  |     json_rpc_url: Url,
|     ^^^^^^^^^^^^ the trait `Serialize` is not implemented for `Url`
```
Yes
CI
Fresh compilation on M1
> [shuffle] add serde feature to url import

- api/doc/openapi.yaml
- api/src/tests/mod.rs
- api/src/tests/string_resource_test.rs
- api/src/tests/test_context.rs
- api/types/src/move_types.rs
- shuffle/cli/tutorials/HelloBlockchain.md
- shuffle/move/examples/main/mod.ts
- shuffle/move/examples/main/sources/Message.move
- shuffle/move/examples/main/sources/MessageTests.move
#9193 
1. Convert bytes into string for client, so that clients do not need handle ASCII::String struct.
2. Updated shuffle message example to use ASCII::String type to store message as well.
unit test
> [api] decode Move ASCII::String type as JSON string

- config/src/config/state_sync_config.rs
- diem-node/src/lib.rs
- state-sync/diem-data-client/src/diemnet/mod.rs
- state-sync/diem-data-client/src/diemnet/tests.rs
- state-sync/state-sync-v2/state-sync-multiplexer/src/lib.rs
Existing Diem data client uses hardcoded values for request timeout and data summary polling. This PR removes these hardcoded values and makes these constants configurable as part of `StateSyncConfig`
Yes.
Manually test by:
- Changing the default values of `DiemDataClientConfig` in `state_sync_config` and verifying that `DiemNetDataClient` uses these default values if no config file is given. 
* Why we must …
> [data-client] Add Diem Data Client Config to State Sync Config

- language/documentation/tutorial/README.md
- language/move-analyzer/editors/code/README.md
Invoking `cargo install` places binary's in a user's Cargo binary directory, which will likely be included in their `PATH` (provided that the `dev-setup.sh` script was run successfully). This is simpler and less error-prone than invoking `cargo build` and asking the user to find the executable from within their build directory.
Update the tutorial installation steps to use `cargo install`, and modify the Visual Studio Code installation instructions accordingly.
> [move] Update Move tutorial to use `cargo install`

- state-sync/state-sync-v2/data-streaming-service/src/lib.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/stream_engine.rs
- state-sync/state-sync-v2/state-sync-multiplexer/Cargo.toml
This (tiny) PR removes some dead code from the data streaming service. Now that we have it plugged into diem node, there's no need to use `#![allow(dead_code)]`.
Yes.
Existing unit tests cover this functionality.
> [State Sync] Remove some dead code from the streaming service.

- diem-move/vm-genesis/src/lib.rs
- diem-move/writeset-transaction-generator/src/admin_script_builder.rs
- language/e2e-testsuite/src/tests/parallel_execution.rs
- language/tools/read-write-set/dynamic/src/normalize.rs
- language/tools/read-write-set/types/src/lib.rs
Trim the analysis result by removing the child information (i.e: struct field access information). This will offer a better performance since we are not resolving those secondary index information anyway and we don't need those finer grained details at runtime.
Yes
`cargo test`.
Also this PR will be able to increase the inference speed by 50% on my local benchmarks.
> [read-write-set] Trim the inference result for a better performance

- language/documentation/tutorial/README.md
Minor fixes only:
* Fixes a wrong path that came up in the dry run.
* Removes a leftover `move_to`; and 
* Pluralizes "Exercise" in step 2
> [move-tutorial] update path in step 1 and minor fixes

- language/move-analyzer/editors/code/package-lock.json
- language/move-analyzer/editors/code/package.json
This version adds support for sending completion suggestion requests to the language server, and displaying the results of those requests. It also bumps the version of the Visual Studio Code extension manager, `vsce`.
> [move] Update move-analyzer extension to 0.0.4

- Cargo.lock
- crates/diem-logger/Cargo.toml
- crates/diem-logger/src/diem_logger.rs
- crates/diem-logger/src/kv.rs
- crates/diem-logger/src/tracing_adapter.rs
- crates/diem-logger/tests/tracing_translation_tests.rs
- crates/diem-workspace-hack/Cargo.toml
- language/testing-infra/test-generation/Cargo.toml
Resolves https://github.com/diem/diem/issues/9884. Few notes on this PR: 
- Note that this branch isn't complete because the span values are double-escaped. I'm decently sure this is happening because there are _two_ visitors (tracing's and diem's logger's) recording the data. Here's a sample of the current output:
```rust
2021-12-04T17:19:53.086624Z [verify_tracing_kvs] ERROR  {"another_value":"hello","message":"hello world","outer.inner.one":"\"hello\"","outer.inner.two":"\"two\"","outer.one":"\"hello\"","outer.two":"\"two\""}
```
- To resolve this, I think that the `Value` enum needs to be given an additional variant representing raw strings _or_ the visitors need to be unified. Up to y'all on which approach I take.
- To avoid clobbering span fields (in the instance where an parent and …
> draft: print `tracing::Span` data through diem::Logger

- language/move-analyzer/editors/code/package.json
Diem developers themselves tend to lag behind Visual Studio Code's latest version, but now that Diem is automatically upgrading to 1.58.2, now the move-analyzer extension can as well.
Bump the target version from 1.55.2 to 1.58.2.
> [move] Bump extension's target VS Code to 1.58.2

- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/partial_nodes_down_test.rs
- testsuite/testcases/src/state_sync_performance.rs
We used to use json_rpc_client to fetch faucet account which is initialized at the first when tx_emitter is created, but in 10% down test, the client's corresponded node has chance to be stopped which end point is not availiable anymore. 
```
./scripts/fgi/run --pr 9963 --suite pre_release -W forge-2
```
```
Test Statistics: 
fixed-tps-test : 10 TPS, 1369 ms latency, 3000 ms p99 latency,no expired txns
all up : 2420 TPS, 1841 ms latency, 2150 ms p99 latency,no expired txns
gas-price-unit-1 : 2325 TPS, 1915 ms latency, 2550 ms p99 latency,no expired txns
10%-down : 2147 TPS, 1871 ms latency, 4150 ms p99 latency,no expired txns
Reconfiguration: total epoch: 101 finished in 197 seconds
State sync throughput : 2286 …
```
> [forge] fix pre release test suite in changelog

- scripts/fgi/run
If we do not pass in args for `args.report`, forge test exit code will be 1 which ci/cd pipeline will treat it as failed.
We should remove the condition outside for wrong logic here
* Why we must have it for …
> [forge] Fix forge test exit code

- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/error.rs
- state-sync/state-sync-v2/state-sync-driver/src/lib.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/utils.rs
- testsuite/smoke-test/src/lib.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/smoke-test/src/state_sync_v2.rs
This PR adds the final component to the state sync driver: the bootstrapper. This is the component required to bootstrap a node up to the latest epoch ending ledger info version before it can begin syncing continuously from that point. To achieve this, the PR offers several commits:
1. First, we add several new smoke tests to test that a fullnode can bootstrap correctly. At this point, the tests fail because bootstrapping is not supported.
2. Next, we provide some small cleanups to the state sync utils and ensure errors are thrown correctly whenever we terminate an active data stream.
3. Finally, we add the boostrapper component and plug it into the state sync driver. This is the missing piece of the puzzle that enables the new smoke tests to pass!
4. Simplify some of the unit tests (for …
> [State Sync] Add bootstrapper component to state sync driver.

- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/interface/network.rs
- testsuite/forge/src/runner.rs
- testsuite/testcases/src/lib.rs
Added support for all optional args used be in CT:
```
--account-per-client
--workers-per-ac
--wait-millis
--burst
--emit-to-validator
```
also added support to run single test instead of whole suite
```
./scripts/fgi/run -T dev_czh_pull_10011 --accounts-per-client 50 --workers-per-ac 4 --wait-millis 1000 --burst --emit-to-validator true --suite bench  
```
```
====json-report-begin===
{
"metrics": [
{
"test_name": "all up",
"metric": "submitted_txn",
"value": 1004300.0
},
{
"test_name": "all up",
"metric": "expired_txn",
"value": 0.0
},
{
"test_name": "all up",
"metric": "avg_tps",
"value": 0.0
},
{
"test_name": "all up",
"metric": "avg_latency",
"value": 0.0
},
{
"test_name": "all up",
"metric": "p99_latency", …
```
> [forge] Add support for more experiment optional args

- language/documentation/examples/math-puzzle/Move.toml
- language/documentation/examples/math-puzzle/README.md
- language/documentation/examples/math-puzzle/sources/puzzle.move
This PR adds the `examples` folder in `language/documentation`.
`math-puzzle` is added to the `examples/experimental` directory.
TODO:
- make `examples` a cargo project
- add the document generation and the test features to the `examples` project
To add Move examples
yes
cargo test
> [move-prover] Added examples/experimental/math-puzzle

- config/src/config/state_sync_config.rs
- state-sync/diem-data-client/src/diemnet/mod.rs
This is a small PR which changes the type of [`DiemDataClientConfig`'s fields from `Duration`](https://github.com/diem/diem/blob/4958cf2ff7ecc9dbc9fef944f51c0e1aa1638035/config/src/config/state_sync_config.rs#L163-L164) to `u64`. This improves the `DiemDataClientConfig`'s readability and makes it less error-prone.
Yes.
Manually tested the config changes and re-ran existing tests in `diem/state-sync/`.
https://github.com/diem/diem/pull/9949
> [data-client] change data client config type to u64

- execution/executor/src/components/block_tree/mod.rs
Previous to this, we get the following build error:
```
Compiling executor v0.1.0 (/Users/droc/workspace/diem/execution/executor)
error: 1 positional argument in format string, but no arguments were given
--> execution/executor/src/components/block_tree/mod.rs:97:58
|
97 |                     .ok_or_else(|| anyhow!("parent block {} doesn't exist."))
|                                                          ^^
error: could not compile `executor` due to previous error
warning: build failed, waiting for other jobs to finish...
warning: `move-model` (lib) generated 1 warning
error: failed to compile `shuffle v0.1.0 (/Users/droc/workspace/diem/shuffle/cli)`, intermediate artifacts can be found at `/Users/droc/workspace/diem/target`
Caused by:
build failed
```
Yes
CI
> [executor] fix anyhow error msg interpolation

- api/types/src/transaction.rs
- crates/diem-rest-client/src/dpn.rs
- crates/diem-rest-client/src/lib.rs
- shuffle/cli/tests/common/mod.rs
- shuffle/cli/tests/shuffle-forge-cli-tests.rs
- testsuite/forge/src/interface/admin.rs
- testsuite/smoke-test/src/client.rs
- testsuite/smoke-test/src/full_nodes.rs
- testsuite/smoke-test/src/genesis.rs
- testsuite/smoke-test/src/release_flow.rs
- testsuite/smoke-test/src/scripts_and_modules.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/smoke-test/src/state_sync_v2.rs
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/test_utils.rs
- types/src/on_chain_config/mod.rs
This is first step to migrate smoke-tests to call REST API (#9193): update test utils to call rest api.
I'm taking the following strategy to ensure I can migrate code efficiently:
1. Migrating small pieces / util functions first, using a tokio Runtime#block_on to call these async functions and leverage compiler to tell me where I need to add runtime.block_on.
2. Eventually we will have runtime doing block_on in the test everywhere. Then it will be easy to convert test into [tokio::test] or adding an async_run for forge test.
> Migrate smoke-tests test utils to call REST API 

- execution/executor/src/chunk_executor.rs
- state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/notification_handlers.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/utils.rs
- testsuite/smoke-test/src/state_sync_v2.rs
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/test_utils.rs
This PR adds two new smoke tests to verify (simple) state sync v2 behaviour for validator nodes. It also offers several small cleanups in different commits:
1. Move the `transfer_and_reconfig()` helper method to smoke test utils (to be shared by tests).
2. Add two new smoke tests for basic validator verification for state sync v2. These tests currently fail.
3. Remove the storage synchronizer cache. This will be reintroduced when I land decoupled execute/commit as it requires refactors.
4. Allow continuous streams to be created even if the end of stream target is not yet advertised (useful in case advertised data is lagging slightly behind what consensus knows about).
5. Notify mempool and the event subscription service of committed events and transactions. With this change, the smoke …
> [State Sync] Add simple smoke tests for validator behaviour.

- state-sync/diem-data-client/src/diemnet/mod.rs
- state-sync/diem-data-client/src/lib.rs
- types/src/ledger_info.rs
`GlobalDataSummary` could be huge and a data client may end up logging a lot of info about `GlobalDataSummary`. This small PR helps avoid the problem by logging only important info that is useful for debugging.
Yes.
Manually test by printing out the debug information.
#9994 
> [data-client] Print less debug info for GlobalDataSummary

- language/move-bytecode-verifier/src/absint.rs
- language/move-bytecode-verifier/src/lib.rs
Make absint module and its definitions public.
This will allow us to define abstract interpretation-based verifier passes outside of the Diem repo.
> Make absint public

- .config/nextest.toml
Followup to #10075 -- I changed the default for nextest to cancel the
test run on the first failing test. In CI we should keep going on,
though.
> [x] don't cancel test run on first failing test

- consensus/consensus-types/src/timeout_2chain.rs
- consensus/consensus-types/src/vote.rs
- consensus/consensus-types/src/vote_msg.rs
- consensus/safety-rules/src/error.rs
- consensus/safety-rules/src/safety_rules_2chain.rs
- consensus/safety-rules/src/tests/suite.rs
Add the missing round > qc_round check for struct timeout.
Added a negative test case.
> [consensus] add one missing checks on 2-chain timeout

- state-sync/diem-data-client/src/diemnet/mod.rs
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/storage-service/server/src/lib.rs
- state-sync/storage-service/server/src/logging.rs
- state-sync/storage-service/types/src/lib.rs
This PR reduces some of the logging frequency/burden of the storage service and data client. This is to help reduce log spam. It offers the following commits:
1. We: (i) reduce the frequency of storage service responses when sending out storage summaries to peers (to every 5 seconds); and (ii) avoid printing out storage service response data (as these can quite large).
2. Next, we reduce the frequency of the global data summary log so that it's only displayed every 5 seconds. We may want to make this configurable in the future, but it should be fine for now.
3. We use display formatting to print epoch ending ledger infos whenever the bootstrapper identifies new ledger infos in the network.
Yes.
Viewing the logs after a run.
None, but this PR relates to: …
> [State Sync] Reduce logging burden of storage service and data client

- testsuite/forge/src/backend/local/node.rs
This (tiny) PR updates Forge to allow nodes to write to logs using [append mode](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.append). This is useful for when a node is restarted during a run (e.g., a smoke test), allowing it to append to the previous log (as opposed to writing over the old content -- something that had me super confused until I realized what was happening 😃).
Yes.
Verified this using a local smoke test run.
None.
> [Forge] Use append mode for node logs

- Cargo.lock
- execution/executor-benchmark/Cargo.toml
- execution/executor-benchmark/src/db_generator.rs
- execution/executor-benchmark/src/lib.rs
- execution/executor-benchmark/src/transaction_generator.rs
- storage/diemdb/src/lib.rs
- storage/schemadb/src/lib.rs
- storage/schemadb/src/metrics.rs
- storage/scratchpad/src/sparse_merkle/metrics.rs
- storage/scratchpad/src/sparse_merkle/mod.rs
1. create-db pipelines execution and commission
2. up to 1M accounts involved in p2p test
3. shorten commit queue length, 50->3, to save some memory and make it more realistic (less SMT nodes cached in mem); for db-create, also shorten the execution queue 50->3, there's no point buffering too much and it makes the progress bar I'll introduce later too not accurate.
also,
add a few progress bars for db-create, so we have a idea how far we've gone when generating a large db.
add a few timers for analysis
Y
local runs
```
cargo run -p executor-benchmark -- --block-size 1000 create-db --data-dir ~/work/data/tmp/10k --num-accounts 10000 --prune-window 20000
```
```
time cargo run -p executor-benchmark -- --block-size 1000 run-executor --data-dir ~/work/data/tmp/10k --checkpoint-dir /tmp/t
```
> [executor-benchmark] ajustments

- language/move-model/src/ast.rs
- language/move-model/src/builder/model_builder.rs
- language/move-model/src/builder/module_builder.rs
- language/move-model/src/lib.rs
- language/move-model/src/model.rs
Attributes weren't yet represented in the move-model. This PR adds a representation and extends the model builder to translate them from the expansion AST.
Attributes in the model are needed for playing with EVM code generation, and possibly also Jazz.
Yes
NA
NA
> [move-model] Represent Move attributes in the move-model.

- config/src/config/state_sync_config.rs
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/utils.rs
- state-sync/storage-service/server/src/tests.rs
This PR offers some small optimizations to increase the syncing throughput of the state sync driver. As measured in forge, we now see:
- Transaction execution syncing: ~3.6k tx/s (max observed)
- Transaction output syncing: ~8.8k tx/s (max observed) 🚀 
1. Make the storage synchronizer clone-able and remove the shared lock. We can do this because the synchronizer is now just a struct containing channel senders.
2. Add support for checking if there is data pending in the execute/apply or commit pipelines. If so, the driver will wait for those pipelines to flush before attempting to make further progress (reducing CPU contention).
3. Make the interval checks more aggressive and support larger chunk sizes.
4. Reduce contention around storage when syncing. …
> [State Sync] Further optimizations for transaction and output syncing.

- .github/workflows/daily.yml
Move and Move Prover have moved to their own repository. `move-prover` is not available in the Diem repository any longer. 
This PR temporarily disables the daily test for Prover in order to suppress the recent [test failures](https://github.com/diem/diem/runs/4854448001?check_suite_focus=true#step:6:28).
TODO:
- Fix this daily test. The Prover inconsistency (daily) test is specially important not only for Prover but also for the Diem Framework. So, this daily test should be fixed rather than removed from the Diem repo.
To disable the daily test for Prover which is no longer available in the Diem repo
Yes
> [move-prover] Disable the daily test for Prover

- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs
- state-sync/state-sync-v2/state-sync-driver/src/notification_handlers.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
This PR updates the state sync driver to handle storage synchronizer failures (e.g., if the node receives bad data from a peer). In this case, the driver will: (i) terminate the currently active data stream; (ii) penalize the peer who sent the data notification containing the invalid data; (iii) wait for the storage synchronizer pipeline to drain; and (iv) start fetching a new data stream to make progress.
Yes.
The smoke tests only cover very basic functionality. As such, this new behavior will need to be verified when we add a more complex test framework (coming soon!).
> [State Sync] Support failure handling for the storage synchronizer.

- testsuite/forge/src/runner.rs
My IDE insists to add these options while start debugging tests, so I'm adding these much like the existing NO-OP options, like test_threads, to the forge runner option.
Y
My IDE now works.
> [forge] accept and ignore "-Z unstable-options" and "--show-output"

- diem-move/diem-validator-interface/src/lib.rs
- diem-move/transaction-replay/src/lib.rs
- diem-move/writeset-transaction-generator/src/release_flow/create.rs
- diem-move/writeset-transaction-generator/src/release_flow/verify.rs
It's weird and confusing that DebuggerStateView queries at self.version - 1.
Made self.version an Option<Version>.
On the callsites (mainly the transaction replay tool):
* annotate_x_at_version annotates the *result* state of the version
* execute_x_at_version and run_x_at_version runs things based on the previous version state.
* create_release_from_artifact runs on top of artifact.version state
Y
> DiemValidatorInterface: DebuggerStateView::version usage clean up
